#!/usr/bin/env python3
# Gen prompt ảnh Video #3 "Why Are You Still Afraid of the Dark?" — style KHOÁ y V2.
# Chạy: python3 gen_prompts.py  → PROMPTS_FULL.txt (số. + prompt) + SHOTLINES_FULL.txt (TTS)
import re
# Lọc mô tả nhân vật THỪA trong action (vài shot subagent tả lại nhân vật — token đã chèn mô tả rồi)
_STRIP = [
 r"a person with a shaved head and short clothes",
 r"a bald stick figure in short sleeves",
 r"a bald stick figure in short clothes",
 r"an ancestor with messy brown hair and fur clothes",
]
def clean_act(act):
    a = act
    for p in _STRIP:
        a = re.sub(p, "", a, flags=re.I)
    a = re.sub(r"^\s*(a|an|the)\b[^,]*?\b(stick ancestor|ancestors?|stick figure|figure|person)\b\s*", "", a, flags=re.I)
    a = re.sub(r"^[\s,]+", "", a)
    a = re.sub(r"\s{2,}", " ", a).strip()
    return a

STYLE = "Flat 2D digital doodle cartoon drawn with clean BOLD SOLID BLACK ink outlines of even, consistent line weight (smooth confident strokes like a clean black felt-tip pen), in a simple minimalist educational style,"

MODERN = ("the recurring modern guy, the same bald black-outline STICK FIGURE kept EXACTLY identical in every image — a plain round BALD white head with NO hair and a simple face, a bare white stick-line torso with NO shirt, wearing ONLY a small pair of simple flat blue shorts at the hips, thin bold noodle arms and legs, simple rounded mitten hands and small oval feet,")

CAVE = ("the recurring caveman STICK FIGURE kept EXACTLY identical in every image — a round white head framed by a BIG MESSY LONG SHAGGY mane of messy hair coloured EXACTLY hex #7C5D39 (a warm medium brown), unkempt hanging down the sides of the head in scraggly tousled locks (competitor caveman style) with thick expressive eyebrows, wearing a rough brown animal-hide fur garment over the torso (a flat brown shape with a jagged fur bottom edge), bare thin bold black stick-line legs, simple rounded mitten hands, barefoot with small oval feet,")

CONSIST = ("The people are TRUE STICK-FIGURE doodles: a large round white head with just a face (two dot eyes, clear thick expressive eyebrows, a tiny mouth, no nose) on a THIN body made of BOLD SOLID BLACK LINES (a single bold line torso plus thin bold noodle arms and legs) — NOT a filled or solid body shape, just clean bold black ink stick lines, with simple rounded mitten hands and small oval feet, ALWAYS drawn as the SAME stickman, kept identical in every image. The modern man is BALD (round white head, NO hair) with a bare torso and small blue shorts; the caveman has a BIG MESSY LONG SHAGGY mane of warm brown hair (hex #7C5D39) hanging down the sides and a brown fur/hide garment. Any animals and props are simple and cute in flat SOLID COLOUR (never black-and-white), each animal a simple cute character with a little face. Clean BOLD SOLID BLACK ink outlines of even weight (confident smooth strokes, filled solid black, NOT pencil, NOT sketchy, NOT thin, NOT grey); flat colours, NO gradient shading.")

SCENE = ("ONE single scene showing ONLY ONE instance of the character; no model sheet, no multiple poses, no grid, no panels, no split frames; keep it minimal on a plain white background, the whole background one single flat colour, with lots of clean empty background space and a soft light-grey shadow under the character on the ground; draw ONLY the character plus the exact props/animals named in this scene description, each at a clear readable size (a decent portion of the frame, NOT tiny) — do NOT invent or add ANY extra objects, toys, toy blocks, furniture, plants or background clutter; keep most of the frame clean and empty (never a full-colour background fill); RED is the accent colour used for labels, tags, warning signs and small danger marks; keep the people as simple bold black stick-figure doodles with colour only on the named garment, animals, props and tags,")

NEG = ("Family-friendly, wholesome, cute, gentle, non-violent, no blood, no gore, no injury. Keep the character identical every time; the modern man is bald with no hair, the caveman has a big messy long shaggy warm brown (#7C5D39) mane of hair; no shirt and no long trousers on the modern man (bare torso + blue shorts only), no hoodie, no jacket, no full outfit; NO PENCIL, no graphite, no pencil sketch, no crosshatching, no faint or grey lines, no rough sketch shading (solid black ink lines only); no gradients, no textures, no photorealism, no 3D, no glossy render, no solid filled body, no extra limbs or fingers, no random extra objects, no toys, no toy blocks, no clutter, no unrequested props, no watermark, no logo, no frame borders, no duplicate characters, no collage, no picture-in-picture, 16:9, clean educational YouTube explainer doodle style.")

F = {
 "med": "a medium shot, the subject drawn big and centered with clean breathing space around it.",
 "wide": "a WIDE establishing shot, the subject fairly small inside a large scene with lots of environment around it.",
 "close": "a tight CLOSE-UP on the character's face and shoulders, the expressive face filling most of the frame.",
 "high": "a HIGH-ANGLE shot looking DOWN from above, making the subject look small and vulnerable.",
 "low": "a LOW-ANGLE shot looking UP from below, making the subject look big, powerful and looming.",
}
def tag(t): return f'a small "{t}" in bold white ALL-CAPS letters on a little red tag or sign.'
NT = "no text or letters."

# (shot line, character | None(=cảnh), hành động+biểu cảm, framing, text)
SHOTS = [
 ("You're lying in bed.", MODERN, "lying in bed in a pitch-black room, eyes wide open, nervous wavy mouth", "med", NT),
 ("The room is pitch black.", MODERN, "small in bed surrounded by solid black darkness, only the white head showing, scared", "wide", NT),
 ("You know nothing is there.", MODERN, "sitting up in bed, deadpan flat mouth, trying to reassure himself", "med", NT),
 ("You checked.", MODERN, "peeking under the bed with a flashlight, curious tilted head", "med", NT),
 ("The door's locked.", None, "a simple closed door with a big locked padlock icon on it", "close", NT),
 ("You're an adult.", MODERN, "standing tall with arms crossed, deadpan proud straight mouth", "med", NT),
 ("You pay taxes.", MODERN, "holding a small tax form paper, deadpan flat mouth", "close", NT),
 ("And yet some animal part of you is dead certain", MODERN, "back in bed, one eyebrow raised, uneasy sweat drop", "close", NT),
 ("that if you let one foot hang off the edge of the bed,", MODERN, "one leg dangling off the edge of the bed, nervous", "med", NT),
 ("something is going to grab it.", None, "a scary dark clawed shadow-hand reaching up from under a bed", "low", tag("GRAB")),
 ("So you pull it back under the covers, fast,", MODERN, "yanking his leg back under the blanket fast, motion lines, wide eyes", "med", NT),
 ("like the floor just turned to lava.", None, "a bedroom floor drawn as bright orange-red bubbling lava beside a bed", "wide", tag("LAVA")),
 ("You. A grown human.", MODERN, "standing centered, deadpan flat straight mouth, arms at sides", "close", NT),
 ("Terrified of a room you've walked through a thousand times.", MODERN, "cowering in the doorway of an ordinary room, nervous wavy mouth, sweat drop", "wide", NT),
 ("Just because someone turned off the light.", None, "a simple wall light switch flipped to OFF", "close", NT),
 ("Here's the strange part.", None, "big bold black uppercase marker card on white", "med", tag("WAIT")),
 ("The dark can't actually hurt you.", MODERN, "poking a floating black blob of darkness, curious unbothered face", "med", NT),
 ("Darkness is just what's left when the light leaves the room.", None, "a lightbulb walking out a door leaving a plain dark patch behind", "wide", NT),
 ("It has no teeth.", None, "a soft black darkness blob with a friendly harmless little face", "close", tag("NO TEETH")),
 ("So why does your body react like it does?", MODERN, "clutching his chest, surprised wide round eyes, question mark above head", "close", NT),
 ("Why the racing heart?", None, "a cute red heart with speed motion lines beating fast", "close", NT),
 ("Why the held breath?", MODERN, "cheeks puffed holding his breath, tense wide eyes", "close", NT),
 ("Because your body knows something your calendar forgot.", None, "a simple wall calendar with a small question mark, one flat colour", "med", NT),
 ("For almost the entire story of being human,", None, "a long horizontal timeline line with tiny plain white stickmen along it", "wide", NT),
 ("the dark was the most dangerous thing in the world.", None, "a big dark night sky patch with faint yellow predator eyes, warning feel", "wide", tag("DANGER")),
 ("Night was when you died.", None, "big bold red uppercase text card on white", "med", tag("NIGHT = DEATH")),
 ("And that fear didn't leave", None, "a small black fear blob with a nervous little face hiding in a corner", "med", NT),
 ("when we invented the lightbulb.", None, "a single glowing yellow lightbulb switched on, bright", "close", NT),
 ("It just went quiet.", None, "the small black fear blob sitting quietly with a finger-to-mouth shhh face", "med", NT),
 ("It's still in there. Right now. Tonight.", MODERN, "standing calm but the small dark fear blob lurking inside a thought bubble", "med", NT),
 ("And the deepest reason of all is so old", None, "an ancient cracked stone tablet with dust, one flat grey colour", "med", tag("ANCIENT")),
 ("it's baked into three things you can't control.", None, "three small numbered red cards 1 2 3 lined up on white", "wide", NT),
 ("How you sleep.", MODERN, "sleeping curled up with tiny z z z above the head, peaceful", "med", NT),
 ("How your kids act the moment the lights go out.", None, "a small caveman child with a tiny tuft of dark hair, scared wide eyes in the dark", "med", NT),
 ("And a little alarm deep in your skull", None, "a small side-view head outline with a tiny red alarm bell inside the skull", "close", NT),
 ("that never, ever switches off.", None, "a little red alarm bell ringing with motion lines, permanently on", "close", tag("ALWAYS ON")),
 ("Stick around for that one.", MODERN, "pointing forward at the viewer, one eyebrow up, sly half-lidded eyes", "close", NT),
 ("We saved it for the end.", None, "a small red bookmark or END tag pinned on the right side", "med", NT),
 ("But first, let's clear one thing up,", MODERN, "wiping a small chalkboard clean, focused deadpan face", "med", NT),
 ("because it changes everything.", None, "big bold black uppercase marker text card on white", "med", tag("EVERYTHING")),
 ("You are not actually afraid of the dark.", MODERN, "next to a black darkness blob with a red X over the fear, deadpan face", "med", NT),
 ("Think about it.", MODERN, "one finger tapping his temple, curious tilted head", "close", NT),
 ("Nobody's scared of a dark closet in the middle of the day,", MODERN, "casually opening a slightly dark closet in bright daylight, totally relaxed", "med", NT),
 ("with the door wide open.", None, "a simple open closet door with a bright sunny room around it", "wide", NT),
 ("You're not afraid of the darkness itself.", None, "a plain harmless black darkness blob with a red X mark over it", "med", NT),
 ("You're afraid of what the darkness hides.", None, "a black darkness blob with two faint glowing yellow eyes hidden inside", "close", tag("HIDES")),
 ("The dark isn't a thing.", None, "a black darkness blob with a red X, one flat colour", "med", NT),
 ("It's a hiding place.", None, "a black darkness patch with a sneaky predator shape crouched inside", "med", NT),
 ("So here's a better way to see it.", MODERN, "holding up a lightbulb idea, one eyebrow raised, thoughtful", "med", NT),
 ("The dark is the moment your single best survival tool,", None, "a single cartoon eye icon drawn as a tool, flat colour", "close", NT),
 ("your eyes, gets switched off.", None, "a cartoon eye icon with a big OFF switch, closed dark eye", "close", tag("OFF")),
 ("And you're left standing there, exposed,", MODERN, "standing alone in a dark void, arms slightly out, nervous vulnerable face", "high", NT),
 ("in a world that didn't switch off with it.", None, "faint yellow predator eyes and shapes still awake in the surrounding dark", "wide", NT),
 ("And this fear isn't one clean thing.", None, "a messy tangled black scribble ball, one flat shape", "med", NT),
 ("It got pressed into us in layers,", None, "three stacked flat-colour layers pressed together like a sandwich cross-section", "med", NT),
 ("one bad night stacked on the last,", None, "many small dark night patches stacked into a tall pile", "med", NT),
 ("for millions of years.", None, "a long horizontal timeline line stretching far with small marks", "wide", tag("MILLIONS")),
 ("One layer is your eyes.", None, "a single cartoon eye icon, flat colour, labelled layer one", "close", NT),
 ("One is what was hunting them in the dark.", None, "a pair of glowing yellow predator eyes in a black patch", "close", NT),
 ("And the deepest one is still running", None, "a small red alarm bell ringing deep inside a faint head outline", "close", NT),
 ("behind your face, tonight.", MODERN, "close on his face at night with a tiny red alarm glowing behind the eyes", "close", NT),
 ("So let's turn the lights off,", None, "a wall light switch being flipped to OFF, the frame going darker", "close", NT),
 ("and go back.", None, "a big black backward-pointing arrow on white, time-travel feel", "med", NT),
 ("Way back.", None, "a long timeline arrow sweeping far to the left into the past", "wide", NT),
 ("To the first night that ever scared us.", CAVE, "a lone caveman crouched by a tiny fire under a huge dark night sky, scared", "wide", NT),
 ("Here's the first thing you need to understand about yourself.", MODERN, "pointing at himself with both thumbs, curious tilted head", "med", NT),
 ("You are a day creature.", MODERN, "standing happily under a bright yellow sun, cheerful face", "med", tag("DAY CREATURE")),
 ("Full stop.", None, "a single big bold black full-stop dot on white", "close", NT),
 ("Every part of you, your eyes, your body clock,", None, "a cartoon eye icon beside a small clock icon, flat colours", "med", NT),
 ("your color vision,", None, "a bright rainbow colour swatch or palette icon, flat colours", "close", NT),
 ("was built to run in daylight.", MODERN, "standing under a big bright yellow sun, arms open, confident face", "wide", NT),
 ("Your eyes are built for color, for detail,", None, "a big cartoon eye icon with tiny colourful dots and fine lines inside", "close", NT),
 ("for reading a face across a room.", MODERN, "squinting to read another small stickman's face across empty space", "wide", NT),
 ("In bright light, you're one of the best-seeing animals alive.", MODERN, "standing proud in bright light with a gold star, smug half-lidded eyes", "med", tag("BEST")),
 ("But the sun goes down,", None, "a yellow sun setting low with the sky patch turning dark", "wide", NT),
 ("and all of that just quietly stops working.", MODERN, "standing in the dark blinking uselessly, deadpan flat mouth, small OFF sign", "med", NT),
 ("Look at a nocturnal hunter's eyes.", None, "a big glowing pair of yellow predator eyes centered in the dark", "close", NT),
 ("A cat, a leopard, an owl.", None, "a cute flat grey cat, a cute flat brown leopard, and a brown owl side by side", "wide", NT),
 ("They have a mirror at the back of the eye", None, "a simple side-view eye diagram with a little mirror at the back, black arrow", "close", NT),
 ("that bounces light back through,", None, "an eye diagram with a light ray bouncing off a mirror back out, arrows", "close", NT),
 ("so they squeeze twice the vision out of almost nothing.", None, "a cute flat leopard with bright glowing yellow eyes seeing clearly in the dark", "med", tag("2X")),
 ("That's why their eyes glow", None, "a cute flat cat face with two bright glowing yellow eyes in the dark", "close", NT),
 ("when a light hits them in the dark.", None, "glowing yellow cat eyes lit up by a small beam of light in darkness", "close", NT),
 ("You don't have that mirror.", MODERN, "pointing at his own plain dark eye, a small mirror icon with a red X", "close", NT),
 ("Nothing behind your eyes glows.", MODERN, "close on his face in the dark, plain dull eyes, no glow, deadpan", "close", NT),
 ("So when the light drops,", None, "a wall light switch flipping OFF, the surroundings darkening", "med", NT),
 ("you don't get a night-vision upgrade.", MODERN, "standing in the dark, a night-vision upgrade icon with a red X above him", "med", NT),
 ("You get to squint, panic,", MODERN, "squinting hard with a panicked wavy mouth and sweat drop in the dark", "close", NT),
 ("and stub your toe on the same chair you've owned for six years.", MODERN, "stubbing his toe on a small chair, jumping in pain, X eyes", "med", NT),
 ("You just go half blind", MODERN, "arms stretched out feeling blindly in the dark, half-closed eyes", "med", NT),
 ("and start bumping into furniture.", MODERN, "bumping face-first into a table in the dark, surprised wide eyes", "med", NT),
 ("A hundred thousand years of evolution,", None, "a long timeline arrow from a caveman on the left to a modern stickman on the right", "wide", tag("100,000 YRS")),
 ("and you still can't find the bathroom at three in the morning.", MODERN, "fumbling in a dark hallway toward a small bathroom door sign, nervous", "wide", NT),
 ("And your brain hates this.", None, "a cute pink cartoon brain with an angry grumpy little face", "close", NT),
 ("Because your brain runs almost entirely on your eyes.", None, "a cute pink brain plugged by a cord into a big cartoon eye icon", "med", NT),
 ("Take away sight, and it's suddenly flying blind,", MODERN, "stumbling with hands out, eyes shut, lost in the dark", "med", NT),
 ("in a body that can't run fast,", CAVE, "trying to run, clumsy and slow", "wide", NT),
 ("can't smell well, and can't hear a predator hold its breath.", CAVE, "covering nose and ears, looking helpless", "med", tag("PREDATOR")),
 ("So what does a nervous brain do", None, "a cute flat-colour brain with a little worried face and wide eyes", "close", NT),
 ("when it loses its main sense?", None, "a cute flat-colour brain with a little face, an eye icon crossed out beside it", "close", NT),
 ("It doesn't relax.", None, "a cute flat-colour brain with a little tense face, sweating", "close", NT),
 ("It assumes the worst.", None, "a cute flat-colour brain with a little panicked face imagining a monster", "med", tag("WORST")),
 ("Every creak becomes a footstep.", CAVE, "flinching, ear turned to a sound", "med", NT),
 ("Every shadow becomes a shape.", None, "a dark menacing shadow shape looming on a wall", "low", NT),
 ("It would rather scare you a hundred times for nothing", None, "a cute flat-colour brain with a little face sounding a tiny alarm bell", "med", NT),
 ("than miss the one time it's real.", None, "a cute flat-colour leopard with a little face hidden in dark shadows, yellow eyes", "low", tag("REAL")),
 ("And here's the thing.", MODERN, "leaning in, one finger raised", "close", NT),
 ("That is not a bug. That's the whole point.", None, "a cute flat-colour bug with a little face crossed out, a check mark beside it", "med", tag("THE POINT")),
 ("Because for millions of years,", None, "a simple calendar icon with many pages flying off, an arrow of time", "wide", NT),
 ("the one time it was real,", None, "a cute flat-colour leopard with a little face lunging out of dark shadows", "low", NT),
 ("was the only time that mattered.", CAVE, "frozen in fear in the dark", "high", NT),
 ("Now let's talk about who you were sharing that darkness with.", MODERN, "peering nervously into pitch black", "med", NT),
 ("Because you weren't alone out there. Not even close.", None, "many pairs of glowing yellow eyes floating in the dark", "wide", tag("NOT ALONE")),
 ("Think about the animals that hunted our ancestors.", None, "a cute flat-colour leopard with a little face prowling in dark shadows", "low", NT),
 ("Leopards. Lions. Hyenas.", None, "a cute flat-colour lion and hyena with little faces standing side by side in shadow", "low", tag("PREDATORS")),
 ("Almost all of them do their best work at night.", None, "a cute flat-colour leopard with a little face under a crescent moon", "low", NT),
 ("And it's not a coincidence.", None, "a cute flat-colour leopard with a little confident face, moon behind it", "med", NT),
 ("The dark isn't just something they tolerate.", None, "a cute flat-colour hyena with a little face relaxed in deep shadow", "low", NT),
 ("The dark is their weapon.", None, "a cute flat-colour leopard with a little face, darkness wrapping around it like a cloak", "low", tag("WEAPON")),
 ("A leopard can see you in near-total darkness.", None, "a cute flat-colour leopard with a little face, bright yellow glowing eyes in black", "close", NT),
 ("It can move without a sound.", None, "a cute flat-colour leopard with a little face padding silently, tiny shh icon", "low", NT),
 ("It doesn't need the lights on. It doesn't need to find the switch.", None, "a cute flat-colour leopard with a little face beside a light switch that is off", "med", NT),
 ("It just needs you to close your eyes.", CAVE, "asleep, eyes closed, unaware", "high", NT),
 ("It can wait, perfectly still, for an hour,", None, "a cute flat-colour leopard with a little patient face crouched motionless in shadow", "low", NT),
 ("watching a sleeping camp.", None, "a cute flat-colour leopard with a little face watching a small camp in the dark", "high", tag("WATCHING")),
 ("And you, the daytime animal, cannot see it at all.", CAVE, "squinting into black, seeing nothing", "med", NT),
 ("Picture that for a second.", MODERN, "framing a scene with fingers", "close", NT),
 ("There is an animal twenty feet away", None, "a cute flat-colour leopard with a little face in the dark, a distance marker of six metres", "wide", NT),
 ("that can see you perfectly.", None, "a cute flat-colour leopard with a little face, sharp glowing yellow eyes fixed forward", "close", NT),
 ("And you're staring into the same darkness", CAVE, "staring blankly into black", "med", NT),
 ("and seeing nothing but black.", None, "a plain solid black field, nothing visible", "close", tag("NOTHING")),
 ("Nature never dealt a worse hand than that.", None, "a hand of playing cards, all blank and grim, a tiny sad face", "med", NT),
 ("One of you is hunting. One of you is blind.", None, "a cute flat-colour leopard with a little face on one side, a blindfolded stickman on the other", "wide", tag("BLIND")),
 ("It's the worst game of hide-and-seek ever invented,", None, "a cute flat-colour leopard with a little face hiding, a blindfold icon nearby", "med", NT),
 ('and you\'re "it" every single night.', CAVE, "blindfolded, arms out under a moon", "high", NT),
 ("So for your ancestors, sundown wasn't cozy.", CAVE, "watching the sun sink, looking worried", "med", NT),
 ("Sundown was the start of the most dangerous twelve hours of the day.", None, "a clock icon shaded dark, a small warning symbol on the night hours", "wide", tag("DANGEROUS")),
 ("And they knew it.", CAVE, "nodding grimly, eyes on the horizon", "close", NT),
 ("Every night, the math was brutally simple.", None, "a simple chalk equation with a tiny grim face", "med", NT),
 ("The light is gone. Our eyes are useless. Theirs are perfect.", None, "an eye icon crossed out beside a bright glowing leopard eye", "med", NT),
 ("So we get small, we get quiet,", CAVE, "curled up low, finger to lips", "high", NT),
 ("and we pray the dark stays empty.", CAVE, "hands clasped, eyes shut in the dark", "high", tag("PRAY")),
 ("And most nights, it did.", None, "a calm empty dark landscape under a quiet moon", "wide", NT),
 ("But not every night.", None, "a cute flat-colour leopard with a little face emerging from the dark edge", "low", tag("NOT EVERY NIGHT")),
 ("And your brain is descended from the ones", None, "a cute flat-colour brain with a little alert face, a family-tree line below it", "med", NT),
 ("who never, ever assumed it would.", CAVE, "wide awake, watchful in the dark", "med", NT),
 ("But here's where it gets worse,", MODERN, "wincing, hand raised", "close", NT),
 ("and this is a detail most people never hear.", MODERN, "leaning in, hand cupped to mouth", "close", tag("NEVER HEAR")),
 ("We didn't just live in a dangerous world at night.", CAVE, "small in a dark threatening landscape", "high", NT),
 ("We voluntarily made ourselves easier to eat.", CAVE, "shrugging on open ground, exposed", "med", tag("EASIER TO EAT")),
 ("Look at our closest relatives.", None, "a cute flat-colour chimp with a little face sitting in a tree", "med", NT),
 ("A chimp, an orangutan, a gorilla.", None, "a cute flat-colour chimp, orangutan and gorilla with little faces in a row", "wide", NT),
 ("Every single night, they build a fresh nest to sleep in.", None, "a cute flat-colour ape with a little face nestled in a leafy nest up a tree", "med", NT),
 ("Usually up in the trees. Off the ground. Out of reach.", None, "a cute flat-colour ape with a little face high in a tree, safe above the ground", "low", tag("OUT OF REACH")),
 ("It's the oldest safety rule there is:", None, "a simple rule icon, a tree with a check mark", "med", NT),
 ("sleep where the big cats can't easily follow.", None, "a cute flat-colour leopard with a little face looking up at an ape safe in a tree", "low", NT),
 ("But somewhere along the way,", CAVE, "pausing at the base of a tree", "med", NT),
 ("our ancestors did something strange.", CAVE, "looking down at the ground, thoughtful", "med", tag("STRANGE")),
 ("We came down.", CAVE, "climbing down from a tree to the ground", "high", NT),
 ("We started sleeping on the ground.", CAVE, "lying asleep on the open ground", "high", NT),
 ("Out in the open. On the exact level where every ground predator hunts.", CAVE, "lying asleep on flat open ground, a cute flat-colour leopard with a little face nearby", "wide", tag("EXPOSED")),
 ("On paper, that is a catastrophically bad idea.", None, "a sheet of paper with a big red cross and a tiny alarmed face", "med", NT),
 ("It's like deciding to take a nap in the middle of a highway.", CAVE, "asleep on the centre line of a highway", "high", tag("HIGHWAY")),
 ("So why on earth would we do that?", MODERN, "shrugging with palms up, puzzled", "med", NT),
 ("Part of the answer is that we got taller and heavier,", CAVE, "standing taller, broader than before", "med", NT),
 ("and flimsy tree nests stopped working.", None, "a flimsy tree nest cracking under weight, a tiny worried face", "med", NT),
 ("But the bigger answer is the one thing", MODERN, "raising one finger, eyebrows up", "close", NT),
 ("that finally made sleeping on the ground survivable.", CAVE, "resting on the ground, calmer now", "med", tag("SURVIVABLE")),
 ("We found a way to make the ground safe.", CAVE, "standing confidently on open ground", "med", NT),
 ("We found a way to push the dark back.", None, "a warm glow of firelight pushing shadows away in the dark", "wide", tag("PUSH THE DARK BACK")),
 ("That one move, learning to hold the dark back,", CAVE, "holding up a small flame against the black", "med", NT),
 ("is why you're the kind of animal that builds cities instead of nests.", None, "a simple city skyline glowing, contrasted with a small empty tree nest", "wide", tag("CITIES")),
 ("Because the moment we could defend the night,", CAVE, "standing guard with a flame, firm stance", "low", NT),
 ("we didn't just survive it.", CAVE, "standing tall by firelight, unafraid", "low", NT),
 ("We started to own it.", MODERN, "standing confidently under the night sky", "low", tag("OWN IT")),
 ("Here's where the story turns.", None, "a bright orange campfire flickering in the dark, hopeful", "wide", NT),
 ("At a place called Wonderwerk Cave in South Africa,", None, "a deep cave mouth in a rocky cliff, mysterious", "wide", tag("WONDERWERK")),
 ("there's evidence of controlled fire from around a million years ago.", None, "an ancient hearth with glowing embers inside a cave", "med", tag("1 MILLION YEARS")),
 ("And fire did something no claw, no muscle, no scream ever could.", CAVE, "standing tall beside a fire, awed and lit orange", "med", NT),
 ("It pushed the dark back.", None, "a ring of warm firelight shoving black shadows outward", "wide", NT),
 ("Think about what a fire actually is", CAVE, "crouching close to the flames, curious face", "close", NT),
 ("to a small, blind, ground-sleeping ape.", CAVE, "sitting on the ground squinting into the dark, uneasy", "med", NT),
 ("It's a bubble of daylight you can carry into the night.", None, "a glowing dome of light like a portable sun in darkness", "wide", NT),
 ("Inside that ring of light, your eyes work again.", CAVE, "wide open eyes reflecting the fire, relieved", "close", NT),
 ("You can see the shapes.", CAVE, "peering at dim silhouettes beyond the fire, alert", "med", NT),
 ("You can see the eyes at the edge.", None, "two glowing predator eyes at the rim of the firelight", "med", NT),
 ("And just as important, the predator can see the fire.", None, "a cute flat-colour leopard with a little face staring at flames", "med", NT),
 ("And most of them want nothing to do with it.", None, "a cute flat-colour leopard with a little face backing away, wary", "wide", NT),
 ("So for the first time in the whole story,", CAVE, "standing confidently by the fire, chin up", "med", NT),
 ("the thing in the dark was the one that had to be nervous.", None, "a cute flat-colour leopard with a little face shrinking into shadow, nervous", "high", NT),
 ("The leopard still owned the shadows.", None, "a cute flat-colour leopard with a little face prowling in darkness", "wide", NT),
 ("But it didn't own the fire.", CAVE, "holding a burning torch aloft, defiant", "med", NT),
 ("And around that fire, something happened", CAVE, "several ancestors gathered in a circle around flames", "wide", NT),
 ("that had nothing to do with staying alive.", CAVE, "leaning back relaxed by the fire, gesturing while talking", "med", NT),
 ("An anthropologist named Polly Wiessner", MODERN, "holding a notebook taking notes, attentive", "med", tag("WIESSNER")),
 ("spent decades with the Ju'hoansi people in the Kalahari,", None, "a warm campfire under a starry Kalahari sky with seated figures", "wide", tag("JU'HOANSI")),
 ("recording how they actually talk.", MODERN, "holding a small recorder, listening closely", "close", NT),
 ("And she found something strange.", MODERN, "raising an eyebrow, intrigued", "close", NT),
 ("In the daytime, people talked about ordinary things.", CAVE, "chatting under bright daylight, casual", "med", NT),
 ("Work. Food. Who's annoying who.", None, "simple icons of a tool, a fish, and two arguing faces", "med", NT),
 ("But at night, around the fire, the talk completely changed.", CAVE, "faces lit orange leaning in around the flames, engaged", "med", NT),
 ("At night, they told stories.", CAVE, "one ancestor gesturing dramatically, others listening rapt", "med", NT),
 ("They talked about people who weren't there,", None, "faint ghostly figures drawn above the firelight", "wide", NT),
 ("about spirits, about the past, about the imagination.", None, "swirling dreamlike shapes and stars rising from the fire", "wide", NT),
 ("The daylight was for surviving.", CAVE, "working hard under the sun, sweating, busy", "med", NT),
 ("But the firelight was for becoming human.", CAVE, "a circle of ancestors glowing around the fire, warm", "wide", NT),
 ("So the fire didn't just guard us from the dark.", None, "a protective ring of firelight around sleeping figures", "wide", NT),
 ("It turned the most dangerous hours of the day", None, "a clock face with the night hours glowing ominous", "med", NT),
 ("into the hours where we invented stories, gods, and each other.", CAVE, "ancestors laughing and gesturing together around flames", "wide", NT),
 ("Those late-night stories were the first hard drive humanity ever had.", None, "a glowing campfire morphing into a hard-drive icon", "med", tag("HARD DRIVE")),
 ("But there was still a stretch of the night", None, "a dark timeline bar with one shadowed gap remaining", "wide", NT),
 ("the fire couldn't cover.", None, "a dying campfire with encroaching darkness at the edges", "med", NT),
 ("The hours when everyone was supposed to be asleep.", CAVE, "a whole tribe curled up asleep around dim embers", "high", NT),
 ("And evolution had a fix for that too.", None, "a lightbulb icon over a sleeping camp, clever", "med", NT),
 ("So here's a question you've probably never asked.", MODERN, "scratching head, thinking, curious", "close", NT),
 ("When your whole family is asleep in the dark,", CAVE, "a family of ancestors sleeping in a dark shelter", "wide", NT),
 ("who's watching the door?", None, "a dark doorway with a question mark hovering over it", "med", NT),
 ("For most of history, the answer could not be nobody.", CAVE, "one ancestor sitting up awake while others sleep", "med", NT),
 ("A group of humans all sleeping deeply at the same time, in the open,", CAVE, "a whole tribe fast asleep exposed under open sky", "high", NT),
 ("is just a buffet that hasn't been served yet.", None, "sleeping figures drawn like dishes on a dinner table", "wide", NT),
 ("So researchers had a theory.", MODERN, "holding a clipboard with a lightbulb, thoughtful", "med", NT),
 ("What if we were never all supposed to be asleep at once?", None, "a diagram of figures with some awake and some asleep", "med", NT),
 ("It's called the sentinel hypothesis.", None, "a lone silhouette standing guard over sleeping figures", "wide", tag("SENTINEL")),
 ("And in 2017, a team led by David Samson", MODERN, "a researcher holding a tablet, focused", "med", tag("2017")),
 ("decided to actually test it.", MODERN, "rolling up sleeves, determined", "med", NT),
 ("They went to the Hadza, hunter-gatherers in Tanzania,", None, "a savanna camp with grass huts at dusk", "wide", tag("HADZA")),
 ("and put sleep trackers on a whole camp.", None, "small wrist tracker devices glowing on sleeping figures", "med", NT),
 ("Then they watched twenty nights of real human sleep.", None, "a calendar of twenty crescent-moon nights", "med", tag("20 NIGHTS")),
 ("And what they found is hard to believe.", MODERN, "eyes wide, jaw dropped, astonished", "close", NT),
 ("Across those twenty nights, the number of minutes when every single person was asleep at the same time", None, "twenty overlapping sleep bars with a tiny overlap", "wide", NT),
 ("was about eighteen.", None, "a stopwatch reading 18 glowing bright", "close", tag("18 MINUTES")),
 ("Not eighteen hours. Eighteen minutes. Total.", None, "a huge 18 with MINUTES underlined next to a crossed-out clock", "med", tag("18 MINUTES")),
 ("For basically the entire night, every night,", None, "a full night sky arc from dusk to dawn", "wide", NT),
 ("somebody was awake.", CAVE, "one figure sitting upright awake among sleepers, alert", "med", NT),
 ("And it wasn't a guard duty roster.", None, "a crossed-out schedule chart with a red X", "med", NT),
 ("Nobody was assigned anything.", CAVE, "shrugging beside sleeping tribe members", "med", NT),
 ("It happened naturally,", None, "a smooth flowing curve of sleep and wake times", "med", NT),
 ("because people fall asleep and wake up on different schedules.", None, "a staggered chart of figures dozing off at different times", "wide", NT),
 ("The teenagers stayed up late,", CAVE, "a young ancestor wide awake poking the fire at night", "med", NT),
 ("because teenagers always have.", MODERN, "slouched, yawning but wide awake, unbothered", "med", NT),
 ("The older adults woke up in the small hours", CAVE, "an elder ancestor sitting up in the dark, awake", "med", NT),
 ("and couldn't get back to sleep,", CAVE, "an elder rubbing tired eyes by dim embers", "close", NT),
 ("because that's what older bodies do.", None, "an icon of an elder figure with a moon overhead", "med", NT),
 ("And between the night owls and the early risers,", None, "a timeline with an owl at one end and a sunrise at the other", "wide", NT),
 ("the camp was almost never fully undefended.", CAVE, "a sleeping camp with one alert figure always on watch", "high", NT),
 ("Now sit with what that means for you.", MODERN, "sitting down, pointing at the viewer, earnest", "med", NT),
 ("That grandparent who's up at four a.m. making tea.", MODERN, "an elderly figure pouring tea in a dim kitchen at dawn", "med", tag("4 A.M.")),
 ("That teenager who won't go to sleep before one.", MODERN, "a teen glued to a glowing phone in bed, wide awake", "med", tag("1 A.M.")),
 ("Your own three a.m. wake-up", MODERN, "lying in bed suddenly wide awake, eyes open", "close", tag("3 A.M.")),
 ("where you just lie there, alert, for no reason.", MODERN, "lying awake staring at the ceiling, alert", "med", NT),
 ("Your family isn't dysfunctional.", MODERN, "standing calm and reassured, small smile", "med", NT),
 ("It's a security roster nobody remembers signing up for.", None, "a duty-roster chart with faded unsigned names", "wide", NT),
 ("You've been calling that a sleep problem.", MODERN, "frowning at an alarm clock, frustrated", "close", NT),
 ("It might be a two-million-year-old security system.", None, "an ancient stone shield icon glowing with a moon", "med", tag("2 MILLION YEARS")),
 ("Your insomnia isn't broken. It's ancient.", MODERN, "sitting up in bed looking calm and understood", "med", NT),
 ("So the next time you're staring at the ceiling", MODERN, "lying in bed staring straight up at the ceiling", "high", NT),
 ("at three in the morning for absolutely no reason, relax.", MODERN, "lying back on the pillow, relieved, letting go", "close", tag("3 A.M.")),
 ("You just got promoted to night watch.", MODERN, "standing proud wearing an imaginary sentry badge", "med", tag("NIGHT WATCH")),
 ("There's no pay, and nobody is going to thank you.", MODERN, "holding an empty wallet, shrugging with a wry smile", "med", NT),
 ("And it's still standing guard against a leopard", None, "a cute flat-colour leopard with a little face lurking in shadow", "wide", NT),
 ("that stopped coming for us a hundred thousand years ago.", None, "a faded ghostly leopard walking away into the dark", "wide", tag("100,000 YEARS")),
 ("Which brings us to the last layer.", None, "an abstract stack of thin flat layers, top layer glowing softly, gentle reveal", "wide", NT),
 ("The one we saved for the end.", None, "a single layer peeled aside to reveal a dark doorway beyond, quiet", "med", NT),
 ("Because here's the twist that ties all of this together.", MODERN, "holding up a single tangled thread, curious look", "med", NT),
 ("The predators are gone.", None, "a faded grey outline of a big cat walking away off-frame, empty space left behind", "wide", NT),
 ("The fire is electric now.", None, "a small campfire icon morphing into a glowing lightbulb, tidy transition", "med", tag("ELECTRIC")),
 ("The camp is a locked apartment.", None, "a simple apartment door with a bold padlock, clean flat shapes", "med", NT),
 ("But the fear never got the memo.", MODERN, "flinching, wide startled eyes, unread note falling", "close", NT),
 ("Deep in your brain there's a small, ancient alarm", None, "a transparent stick-figure head with a small red alarm glowing deep inside", "close", tag("AMYGDALA")),
 ("called the amygdala.", None, "the tiny red alarm bell labelled inside the glass head, ringing faintly", "close", tag("AMYGDALA")),
 ("Its entire job is to spot a threat and hit the panic button", None, "a big red panic button being slammed, sharp motion lines", "med", tag("PANIC")),
 ("before the thinking part of you even knows what's happening.", None, "a transparent head with a slow calm brain still asleep while the red alarm blares", "close", NT),
 ("It's a piece of survival software written two million years ago,", None, "an ancient stone tablet showing lines of glowing code, weathered", "med", tag("2,000,000 YRS")),
 ("and nobody ever pushed an update.", None, "a dusty update button with a cobweb, greyed out and ignored", "med", NT),
 ("It's fast, it's old, and it does not wait for proof.", None, "the red alarm bell rocketing off with speed lines, no time to check", "wide", NT),
 ("And it is especially tuned to the dark.", None, "the red alarm glowing brighter as a black shadow creeps over it", "close", NT),
 ("Watch a young child, somewhere between about six and twelve.", None, "a small stick child sitting up in bed, big worried eyes", "med", NT),
 ("Almost all of them go through a phase of being afraid of the dark.", None, "a small stick child hugging knees in a dark bedroom, trembling lines", "med", NT),
 ("Nobody teaches them this.", None, "an empty chalkboard with no lesson written, a small child glancing at it", "wide", NT),
 ("You don't sit a toddler down and explain leopards.", None, "an empty classroom pointer aimed at a blank spot where a leopard would be", "med", NT),
 ("The fear just arrives, on schedule, like it was installed.", None, "a small stick child with a tiny gear icon clicking into its head, on-time clock", "close", tag("INSTALLED")),
 ("Because it was.", None, "the tiny gear locking firmly into place inside a glass head, snug fit", "close", NT),
 ("And notice what we're afraid of, even in a modern bedroom.", MODERN, "peeking nervously around a tidy modern bedroom", "wide", NT),
 ("Not electrical outlets. Not cars. Not the actual things that hurt people today.", None, "an electrical outlet, a car, and a road sign each crossed out with a red line", "med", NT),
 ("We're afraid of shapes in the dark.", None, "a vague dark blob shape looming in a black doorway, faint outline", "med", NT),
 ("Of things under the bed.", None, "two glowing eyes peeking out from under a simple bed frame", "low", NT),
 ("Of something with eyes and teeth.", None, "a black shadow with two eyes and a jagged white grin, unsettling", "close", tag("EYES AND TEETH")),
 ("Your brain learns to fear snakes and darkness in a single bad moment,", None, "a coiled snake and a black patch, a lightning-fast red spark linking them to a brain", "med", NT),
 ("but it takes forever to learn to fear a power socket.", None, "a bored brain tapping its foot beside an unthreatening power socket, slow clock", "med", NT),
 ("Because one of those threats was stalking your ancestors for millions of years.", CAVE, "frozen still as a big cat's eyes glow in the brush behind", "wide", NT),
 ("And the other one is younger than your grandmother.", None, "a power socket next to a tiny new sparkle tag, comically recent", "med", NT),
 ("So this is the real answer to the whole question.", MODERN, "pointing at a big glowing question mark resolving", "med", NT),
 ("You're not afraid of the dark.", MODERN, "standing calmly in front of a plain black wall", "med", NT),
 ("You're afraid of what used to be in it.", None, "a black void with a faint ghostly predator silhouette fading inside it", "close", NT),
 ("The predators left.", None, "a grey big-cat outline stepping out of frame, leaving empty darkness", "wide", NT),
 ("But the fear was too useful to delete.", None, "a trash bin with a red alarm bell refusing to go in, keep glow", "med", NT),
 ("So it stayed.", None, "the red alarm bell settling firmly onto a shelf inside a glass head", "close", NT),
 ("It moved off the savanna, and it moved into your head.", None, "a small red alarm travelling from a grassy plain into a transparent stick-figure head", "wide", NT),
 ("And every time you feel it, you're not being childish.", MODERN, "nodding gently, reassured expression", "close", NT),
 ("You're running a program that kept every single one of your ancestors alive", None, "a long line of stick ancestors linked by a glowing thread, all standing alert", "wide", NT),
 ("long enough to make you.", MODERN, "at the end of a glowing ancestral line", "med", NT),
 ("Now, let's be honest for a second, because it matters.", MODERN, "holding up an open honest palm, sincere", "close", NT),
 ("Statistically, the dark is safe for you now.", None, "a calm dark room with a small green safe checkmark floating in it", "med", tag("SAFE")),
 ("The hallway at night is not going to eat you.", MODERN, "standing relaxed in a plain dark hallway", "wide", NT),
 ("Nothing is under the bed.", None, "a simple bed lifted to show only dust and empty floor beneath", "low", NT),
 ("Your fear, most of the time, is a smoke alarm going off because you made toast.", None, "a ceiling smoke alarm blaring over a pop-up toaster with a harmless slice of toast", "med", tag("JUST TOAST")),
 ("But here's the thing about a smoke alarm.", None, "a round white smoke alarm on a ceiling, single spotlight on it", "close", NT),
 ("You don't rip it off the wall because it's usually wrong.", MODERN, "pausing, hand near the alarm but choosing not to pull", "med", NT),
 ("You keep it, because of the one time it isn't.", None, "a smoke alarm glowing red as real flames flicker just below it, vital moment", "close", NT),
 ("For two million years, that alarm was right often enough to be worth every false alarm.", None, "a long timeline of tally marks with one bold red right mark standing out", "wide", tag("2,000,000 YRS")),
 ("And that is why you still have it.", None, "the red alarm bell resting safely inside a transparent stick-figure head, kept", "close", NT),
 ("The people who felt nothing in the dark,", CAVE, "strolling casually into pitch black, unbothered", "wide", NT),
 ("who strolled out into the black without a care,", CAVE, "whistling into the darkness, arms swinging loosely", "med", NT),
 ("they were statistically less likely to become someone's ancestor.", None, "a faint stick figure fading away with a broken family-line thread", "med", NT),
 ("The nervous ones lived.", CAVE, "crouched safely behind a rock, wide-eyed and alert, surviving", "close", tag("THEY LIVED")),
 ("You are the descendant of the ones who were afraid.", MODERN, "at the end of a proud line of alert ancestors", "med", NT),
 ("So the next time you're lying in bed, and the room is pitch black,", MODERN, "lying flat in bed inside a fully black room", "wide", NT),
 ("and you get that urge to pull your foot back under the covers.", MODERN, "quickly tucking a foot back under the blanket", "close", NT),
 ("Don't laugh at it.", MODERN, "with a serious, respectful expression", "close", NT),
 ("That flinch is older than your language.", None, "a tiny flinch spark next to an ancient scroll of faded letters", "med", tag("OLDER")),
 ("It's older than your country.", None, "the flinch spark beside a crumbling old map with fading borders", "med", NT),
 ("It's older than farming, or writing, or the wheel.", None, "simple icons of a wheat sprout, a quill, and a wheel, all greyed as ancient", "wide", NT),
 ("It's a message, passed down an unbroken line of survivors,", None, "a glowing thread linking many small stick figures hand to hand, unbroken", "wide", NT),
 ("every one of whom made it through the night.", None, "a row of stick ancestors each stepping from dark night into soft dawn light", "med", NT),
 ("And the message is simple.", None, "a small folded note with a soft glow, waiting to be read", "close", NT),
 ("Stay alert. Stay alive. See you in the morning.", None, "a sunrise over a plain horizon with three clean words of light", "wide", tag("STAY ALIVE")),
 ("That fear in the dark isn't a weakness in you.", MODERN, "standing straight, no shame, calm eyes", "med", NT),
 ("It's the oldest, most loyal bodyguard you will ever have.", None, "a sturdy stick bodyguard in shades standing guard beside a glass head, arms crossed", "med", tag("BODYGUARD")),
 ("It has never once taken a night off.", None, "a bodyguard stick figure alert under a moon, an untouched day-off calendar nearby", "med", NT),
 ("And it's still standing watch over you, right now, tonight.", MODERN, "asleep in bed while a loyal stick bodyguard stands watch beside him", "wide", NT),
 ("So the next time you walk into a dark room", MODERN, "stepping through a doorway into darkness", "med", NT),
 ("and feel the hair rise on the back of your neck,", MODERN, "with tiny raised lines along the neck, alert", "close", NT),
 ("remember what it is.", MODERN, "pausing thoughtfully in the dark, steady gaze", "close", NT),
 ("That's not fear making you weak.", MODERN, "standing firm, shoulders squared in the dark", "med", NT),
 ("That's two million years of survivors, still whispering the same thing.", None, "a long faint line of ancestor silhouettes leaning in as if whispering together", "wide", tag("2,000,000 YRS")),
 ("Something's out there. Be ready.", None, "two alert eyes in the dark and a small ready-stance figure facing them", "close", NT),
 ("That's you.", MODERN, "standing tall and calm, quietly powerful, that's-you moment", "low", tag("THAT'S YOU")),
 ("That's what you are.", MODERN, "standing proud in the dark, unshaken", "close", tag("THAT'S WHAT YOU ARE")),
 ("The most dangerous thing in the dark,", MODERN, "standing boldly in pitch black, faint glow around", "med", NT),
 ("that never stopped listening for something more dangerous.", MODERN, "head tilted, one ear alert, still listening", "close", NT),
 ("If you made it to the end, tell me one thing in the comments.", MODERN, "pointing warmly toward the viewer beside a comment icon", "med", NT),
 ("What's the first thing you check when you walk into a dark room?", MODERN, "pointing directly at the viewer, inviting question look", "close", tag("YOUR TURN")),
]

def build(shot, ch, act, fr, txt):
    subj = f"{ch} {clean_act(act)}" if ch else act
    return " ".join(f"{STYLE} {subj}. Framing: {F[fr]} {CONSIST} {SCENE} {txt} {NEG}".split())

if __name__ == "__main__":
    with open("PROMPTS_FULL.txt", "w") as pf:
        for i, s in enumerate(SHOTS, 1):
            pf.write(f"{i:03d}.\n{build(*s)}\n\n")
    with open("SHOTLINES_FULL.txt", "w") as sf:
        for i, s in enumerate(SHOTS, 1):
            sf.write(f"{s[0]}\n")
    print(f"✅ {len(SHOTS)} prompt → PROMPTS_FULL.txt · {len(SHOTS)} shot-line → SHOTLINES_FULL.txt")
