# -*- coding: utf-8 -*-
"""V20 COLD — "How Did Ancient Humans Sleep Through Freezing Nights?"

(line, kind, subj, text, bg, face)

kind : SCENE_A ancient | SCENE_W woman | GROUP nhom | SCENE_N khong nguoi | CARD
bg   : cold_night night_dark night_open fire_ring fire_edge dusk_grey dry_plain
       cave_warm dark_card white
face : flat shock tired worry scared happy asleep dumb curious sad

2.111 tu / ~10:30 -> nhip ~2,2 giay/shot -> ~286 shot.

LUAT HINH RIENG CUA V20
───────────────────────
1. KHONG CO NHAN VAT HIEN DAI. Lane "ve BAN" da bo 10/08.
2. Khoi nhan vat ep MOI nguoi trong MOI kind deu la nguoi co dai mac ao da.
   -> Doan KHOA HOC HIEN DAI (Basel 2000, buong nhiet 1981) ve DO VAT, khong ve nguoi:
      giuong, num chinh nhiet, nhiet ke, bieu do. Ngu phap: qua khu co NGUOI, khoa hoc co VAT.
3. Co che sinh ly ve TREN THAN NGUOI CO DAI (tay am, tay lanh, hoi nong bay len),
   KHONG ve thanh so do. V19 hong vi 62% khung la the; doi thu 36-41%.
"""

SHOTS = [

# ═════════════════ HOOK — 21 shot ═════════════════
("Sixteen hours.","CARD","the words filling the frame, nothing else drawn","large bold headline text \"SIXTEEN HOURS\"","dark_card","flat"),
("That is how long the dark lasts","SCENE_N","a wide flat block of almost-black night sky over one thin strip of frosted pale ground, nothing else in the frame","no text","cold_night","flat"),
("on a winter night in northern Europe,","SCENE_N","a plain outline map of Europe with the northern half filled solid dark navy","a label \"NORTHERN EUROPE\"","white","flat"),
("twenty thousand years back.","CARD","a single long horizontal line with one small mark near the left end and a small mark at the far right","a label \"20,000 YEARS\" under the left mark and \"NOW\" under the right","white","flat"),
("Sixteen hours is not a figure of speech here.","SCENE_N","a wide frozen plain under a black sky with one thin pale band of light along the very bottom of the horizon and nothing else","a label \"LIGHT\" on the pale band","cold_night","flat"),
("At that latitude the shortest day of the year","SCENE_N","a very low pale sun sitting just above a flat frozen horizon, casting a long thin shadow across the ground","no text","cold_night","flat"),
("holds under eight hours of light.","SCENE_N","a low pale sun over a frozen plain with a short dotted arc drawn across the sky showing the whole path it will take","a label \"8 HOURS\" along the dotted arc","cold_night","flat"),
("Everything else is night.","SCENE_N","a completely dark frame with one faint pale line where the ground meets the sky","no text","night_dark","flat"),
("The temperature drops past freezing","SCENE_N","a simple upright thermometer drawn on flat dark ground, the column low and small frost marks along the glass","a label \"0\" beside the middle of the thermometer","cold_night","flat"),
("and keeps going.","SCENE_N","the same upright thermometer with the column lower still and a small black arrow beside it pointing down","no text","cold_night","flat"),
("And somewhere in that dark,","SCENE_N","a very wide empty view of frozen ground under a black sky, with one tiny dot of orange firelight far away","no text","cold_night","flat"),
("a person has to lie down on the ground","SCENE_A","he lowers himself onto flat frozen ground, one hand down, knees bent, seen from the side","no text","cold_night","tired"),
("and lose consciousness.","SCENE_A","he lies flat on his back on frozen ground, eyes closed, arms at his sides","no text","cold_night","asleep"),
("Almost every account of this asks the same question.","CARD","a row of three identical plain closed books standing side by side","no text","white","flat"),
("How did they stay warm.","CARD","the question filling the frame in plain black lettering","large bold headline text \"HOW DID THEY STAY WARM?\"","white","flat"),
("That is the wrong question.","CARD","the same words with one thick red diagonal stroke drawn across them","large bold headline text \"HOW DID THEY STAY WARM?\" with a red line through it","white","flat"),
("Staying warm has obvious answers,","SCENE_N","a small fire on dark ground with a thick folded animal hide lying beside it and a bundle of sticks behind it","no text","fire_ring","flat"),
("and they are the ones everybody already knows.","SCENE_N","the same small fire with the folded hide beside it, and a small green check mark drawn over each of the two objects","no text","fire_ring","flat"),
("Fire.","SCENE_N","one small fire drawn as a wobbly orange and yellow shape on flat dark ground, alone in the frame","a label \"FIRE\"","fire_ring","flat"),
("Hides.","SCENE_N","one thick animal hide with fur along one edge, folded once, lying alone on frozen ground beside a low fire","a label \"HIDES\"","fire_edge","flat"),
("Other bodies pressed close.","GROUP","three of them lying tight together in a row on frozen ground, shoulders touching, all asleep","no text","cold_night","asleep"),

# ═════════════════ CH1 — CAU HOI THAT — 18 shot ═════════════════
("Falling asleep is the part with no obvious answer,","CARD","one plain question mark drawn large and alone","large bold headline text \"FALLING ASLEEP\"","white","flat"),
("because of something about sleep","SCENE_A","he lies on his side on frozen ground with his eyes wide open, plainly not asleep","no text","cold_night","worry"),
("that almost nobody has been told.","SCENE_A","close on his face, eyes open in the dark, eyebrows raised at the inner ends","no text","night_dark","tired"),
("A human being cannot fall asleep","SCENE_A","he lies flat on his back with eyes wide open and both arms straight at his sides","no text","cold_night","worry"),
("without giving heat away.","SCENE_A","he lies on his back with small wavy orange heat lines rising off his hands and feet into the dark air","no text","cold_night","asleep"),
("Not lying still.","CARD","one plain figure lying flat and straight with a small red cross beside it","no text","white","flat"),
("Not being tired enough.","CARD","one plain figure lying flat with a small tired face and a small red cross beside it","no text","white","flat"),
("Giving heat away, through the skin, on purpose.","SCENE_A","he lies flat on frozen ground with many small wavy orange lines lifting off the skin of his hands and feet","a label \"HEAT OUT\"","cold_night","asleep"),
("And the first thing a freezing night does","SCENE_N","flat frozen ground under a black sky, small white frost marks scattered across the surface","no text","cold_night","flat"),
("to a human body is shut down exactly that.","SCENE_A","he lies curled on frozen ground with both hands pulled in tight against his chest, no heat lines anywhere","no text","cold_night","worry"),
("Which gives the fire in the middle of that camp","SCENE_N","a small fire burning alone in the middle of flat dark ground, seen from slightly above","no text","fire_ring","flat"),
("a different job from the obvious one.","SCENE_N","one small fire burning alone on dark ground with a large plain question mark drawn in the black air above it","no text","fire_ring","flat"),
("Not comfort.","CARD","the word alone in the frame with a thin red line through it","large bold headline text \"COMFORT\" with a red line through it","dark_card","flat"),
("Permission.","CARD","the word alone in the frame, nothing else drawn","large bold headline text \"PERMISSION\"","dark_card","flat"),
("The claim is a strong one,","CARD","one plain speech bubble drawn large and empty","no text","white","flat"),
("and it does not come out of the ground.","SCENE_N","a shallow pit dug into frozen ground with a small pile of earth beside it and nothing at all inside the pit","no text","cold_night","flat"),
("It comes out of sleep laboratories,","CARD","one plain empty bed with a small bedside instrument box beside it, thin wires running from the box to the pillow","no text","white","flat"),
("from people wired to sensors in the last fifty years.","CARD","a close view of a small instrument box with three thin wires leaving it and a single line traced across a paper strip","no text","white","flat"),

# ═════════════════ CH2 — DEM DAI BAO NHIEU — 30 shot ═════════════════
("So here is where it comes from,","CARD","one thin black arrow pointing from a small instrument box toward an empty space","no text","white","flat"),
("and here is where it runs out.","CARD","the same thin black arrow stopping at a solid black wall","no text","white","flat"),
("Start with the night itself,","SCENE_N","a wide flat block of black night sky over a pale frozen plain, no fire and nobody in it","no text","cold_night","flat"),
("because the number is larger than people expect.","SCENE_N","a very tall block of solid black sky filling almost the whole frame over one narrow pale strip of ground at the very bottom","no text","cold_night","flat"),
("At fifty degrees north,","CARD","a plain outline of the globe with one horizontal line drawn across the upper part of it","a label \"50 N\" at the end of the line","white","flat"),
("the line that runs through the Ukrainian plain","CARD","the same globe outline with a small solid dot marked on the line","a label \"50 N\" at the end of the line","white","flat"),
("where the mammoth bone houses stood,","SCENE_N","one low round shelter built from long curved bones and tusks, standing alone on flat frozen ground","no text","cold_night","flat"),
("the shortest day of the year gives","SCENE_N","a small pale sun very low over a flat frozen horizon","no text","cold_night","flat"),
("about seven and a half hours of daylight.","SCENE_N","a pale sun sitting low over a flat frozen plain with a short dotted arc across the sky above it","a label \"7.5 HOURS\" along the arc","cold_night","flat"),
("That leaves sixteen hours of dark.","SCENE_N","the same frozen plain with the sun gone and a long dotted arc running right across the black sky from one side to the other","a label \"16 HOURS\" along the long arc","night_dark","flat"),
("Go further north, to sixty degrees,","CARD","the globe outline with a second horizontal line drawn higher than the first","a label \"60 N\" at the end of the upper line","white","flat"),
("and daylight falls to five and a half hours.","SCENE_N","a smaller paler sun barely clearing a frozen horizon with a very short dotted arc above it","a label \"5.5 HOURS\" along the short arc","cold_night","flat"),
("Eighteen and a half hours of night.","CARD","the same bar almost entirely solid dark","large bold headline text \"18.5 HOURS\"","dark_card","flat"),
("Not once.","CARD","one small square drawn alone on empty white","no text","white","flat"),
("Every night, for months,","SCENE_N","a line of many small identical fires stretching away across a frozen plain into the dark distance, getting smaller toward the horizon","no text","cold_night","flat"),
("with the worst of it in the middle.","CARD","the same rows of small dark squares with the squares in the centre drawn solid black and circled","no text","white","flat"),
("None of that is reconstruction,","CARD","a plain drawn sketch of a scene on paper with a red cross through it","no text","white","flat"),
("and none of it is an estimate.","CARD","a plain question mark with a red cross drawn through it","no text","white","flat"),
("The tilt of the planet has not moved,","CARD","a plain circle for the planet with a straight axis line through it leaning to one side, and a small sun to the left","a label \"TILT\" beside the axis line","white","flat"),
("and this is the one part of the story","CARD","a row of several plain shapes with only one of them drawn solid and the rest left as thin outlines","no text","white","flat"),
("that is simply settled.","CARD","one plain shape drawn solid black with a small green check mark beside it","large bold headline text \"SETTLED\"","white","flat"),
("Now put a human body next to it.","SCENE_A","he stands alone on a wide flat frozen plain under a black sky, small in the frame","no text","cold_night","flat"),
("Nobody sleeps sixteen hours.","SCENE_A","he lies flat on frozen ground with his eyes wide open, a long dotted arc drawn across the black sky above him","a label \"16 HOURS\" along the arc","cold_night","worry"),
("So for a large part of every winter night,","SCENE_N","flat frozen ground under a black sky with one small dying fire and a long stretch of empty dark around it","no text","cold_night","flat"),
("people were lying in the dark, awake,","GROUP","three of them lying on their backs on frozen ground, all with their eyes open, none touching","no text","cold_night","worry"),
("in the cold, waiting.","SCENE_A","he lies on his back with his eyes open, breath drawn as a small pale cloud above his mouth","no text","cold_night","tired"),
("What they did with those waiting hours","GROUP","two of them sitting up together beside a low fire in the dark, one turned toward the other","no text","fire_ring","flat"),
("is a story of its own.","CARD","a plain closed book lying alone with a thin arrow pointing away from the frame","no text","dark_card","flat"),
("This one is about the other end of it.","SCENE_A","he lies flat on frozen ground with his eyes closed, seen from directly above","no text","cold_night","asleep"),
("How anybody stopped waiting, and went under.","CARD","a plain figure lying flat, drawn half in light and half sinking into a solid dark block","large bold headline text \"WENT UNDER\"","dark_card","flat"),


# ═════════════════ CH3 — NGU DUOC LA NHU THE NAO — 34 shot ═════════════════
("Falling asleep does not feel like a process.","SCENE_A","he lies on his back on frozen ground with his eyes closed and his face completely still","no text","cold_night","asleep"),
("It feels like an absence.","SCENE_N","an empty patch of flat frozen ground with a shallow body shaped dent pressed into the frost and nobody in it","no text","cold_night","flat"),
("One moment there is a person lying there,","SCENE_A","he lies flat on frozen ground, drawn small in a wide empty frame, eyes open","no text","cold_night","flat"),
("and then there is not.","SCENE_A","the same wide frame and the same position, but his eyes are closed and his mouth has gone slack","no text","cold_night","asleep"),
("But it is a process,","CARD","three plain squares in a row joined by two short black arrows","no text","white","flat"),
("and it has a first step,","CARD","the same three squares with only the first one filled solid black","no text","white","flat"),
("and the first step is not in the brain.","CARD","a plain round head in profile with a small red cross drawn over the top of it","no text","white","flat"),
("It is in the hands and the feet.","SCENE_A","close on one of his open hands and one bare foot resting on frozen ground, both drawn solid white","a label \"HANDS\" and \"FEET\"","cold_night","flat"),
("In the hour before sleep,","SCENE_A","he sits on frozen ground beside a low fire with his hands held out toward the flames","no text","fire_edge","tired"),
("the small blood vessels in the fingers and the toes open up.","SCENE_A","very close on his open hand in the firelight, thin branching lines inside the fingers drawn wide and warm orange","no text","fire_edge","flat"),
("Warm blood from the middle of the body runs out to the surface,","SCENE_A","he lies flat beside a low fire with thin orange lines running outward from his chest along both arms and both legs","no text","fire_edge","asleep"),
("and heat leaves through the skin.","SCENE_A","he lies on his back with small wavy orange lines lifting off his open hands into the black air","no text","cold_night","asleep"),
("The hands get warmer.","SCENE_A","close on both of his open hands lying on the ground, filled warm orange","a label \"WARMER\"","fire_edge","flat"),
("The core gets cooler.","SCENE_A","he lies flat with his chest and stomach drawn pale cold blue and his hands left warm orange","a label \"COOLER\"","fire_edge","asleep"),
("That is what a body does","SCENE_A","he lies flat with orange hands and a pale blue chest, eyes half closed","no text","cold_night","tired"),
("when it is about to go under.","SCENE_A","close on his face with the eyelids sliding down","no text","cold_night","asleep"),
("In 2000 a team in Basel measured this on people in a sleep laboratory,","CARD","one plain bed with a small instrument box beside it and three thin wires running to the pillow","a label \"BASEL, 2000\"","white","flat"),
("and asked one plain question.","CARD","one plain question mark drawn large and alone","no text","white","flat"),
("Of everything that can be recorded about a person lying in the dark,","CARD","a paper strip with four separate wavy lines traced along it, one under the other","no text","white","flat"),
("what actually predicts how fast they fall asleep.","CARD","a small clock face with a thin arrow curving away from it toward an empty bed","no text","white","flat"),
("They had all the obvious candidates on the list.","CARD","a plain vertical list of four empty boxes drawn one under the other","no text","white","flat"),
("Core body temperature.","CARD","one plain thermometer standing alone in the first box of the list","a label \"CORE TEMPERATURE\"","white","flat"),
("Melatonin.","CARD","one small round drop shape drawn alone in the second box of the list","a label \"MELATONIN\"","white","flat"),
("Heart rate.","CARD","one plain jagged heartbeat line drawn in the third box of the list","a label \"HEART RATE\"","white","flat"),
("And how sleepy the person said they felt.","CARD","one plain speech bubble in the fourth box of the list with three small z shapes inside it","a label \"FEELING SLEEPY\"","white","flat"),
("The winner was none of them.","CARD","the vertical list of four boxes with a red cross drawn through every one of them","no text","white","flat"),
("The best predictor was the gap between the temperature of the hands and feet","CARD","one plain open hand filled warm orange on one side of the frame and a plain torso filled pale blue on the other, with a thin double headed arrow between them","no text","white","flat"),
("and the temperature of the trunk.","CARD","the same hand and torso with the double headed arrow drawn thicker and darker","a label \"THE GAP\" on the arrow","white","flat"),
("The wider that gap, the faster sleep arrived.","CARD","two pairs of hand and torso side by side, the pair with the wider arrow marked with a small green check","no text","white","flat"),
("Their conclusion is worth saying in their own words.","CARD","one plain open paper page with a few lines of handwriting drawn as thin marks","no text","white","flat"),
("Sleepiness is associated with heat loss,","CARD","one plain figure lying flat with many small wavy orange lines lifting off it, and a small green check beside","a label \"HEAT LOSS\"","white","flat"),
("and not with a drop in core temperature.","CARD","one plain thermometer with the column low, and a red cross drawn beside it","no text","white","flat"),
("Which turns around the thing almost everyone assumes.","CARD","one plain curved arrow bending right back on itself","no text","white","flat"),
("The body does not cool down because it fell asleep.","CARD","two plain boxes joined by an arrow, with a red cross drawn over the arrow","a label \"SLEEP\" in the first box and \"COOL\" in the second","white","flat"),

# ═════════════════ CH4 — CAI LANH LAM GI TRUOC — 26 shot ═════════════════
("It falls asleep because it is already cooling,","CARD","the same two boxes with the arrow now running the other way and a small green check over it","a label \"COOL\" in the first box and \"SLEEP\" in the second","white","flat"),
("and it cools by opening the hands.","SCENE_A","close on his hand opening flat on the ground, the fingers spread and warm orange lines lifting off every fingertip","no text","fire_edge","flat"),
("Now take that body outside,","SCENE_A","he steps out of a low shelter onto frozen ground under a black sky","no text","cold_night","flat"),
("on a night well below freezing.","SCENE_N","a wide frozen plain under a black sky with heavy white frost across the whole ground","no text","cold_night","flat"),
("The cold reaches the skin,","SCENE_A","close on his forearm and hand with small pale frost marks settling on the skin","no text","cold_night","worry"),
("and the body does the oldest thing it knows how to do.","SCENE_A","he pulls both hands in and pushes them under his arms, shoulders lifted","no text","cold_night","worry"),
("It closes the hands.","SCENE_A","close on his hand curling into a tight fist on frozen ground, the thin lines inside the fingers narrow and pale blue","no text","cold_night","flat"),
("Blood is pulled back out of the fingers and the toes","SCENE_A","close on his hand with the orange lines retreating from the fingertips back toward the wrist","no text","cold_night","flat"),
("and held in the middle,","SCENE_A","he lies curled on frozen ground with his chest drawn solid warm orange and his arms and legs left plain white","no text","cold_night","worry"),
("around the organs that are not allowed to cool.","CARD","the same figure with a heavy black ring drawn around the chest area","a label \"KEEP WARM\" beside the ring","white","flat"),
("This is why fingers go white and clumsy in the cold,","SCENE_A","close on his hand trying and failing to close around a small stick, the fingers stiff and pale","no text","cold_night","worry"),
("and why they hurt on the way back.","SCENE_A","close on his hand held near a fire, the fingers drawn with small sharp red marks around the tips","no text","fire_edge","worry"),
("It is not a fault.","CARD","one plain hand curled into a fist with a red cross beside it, and the cross itself crossed out","no text","white","flat"),
("It is heat conservation, and it works.","CARD","the same closed fist with a small green check mark beside it","a label \"IT WORKS\"","white","flat"),
("But look at what it does to the other system.","CARD","two plain boxes side by side, the left one with a closed fist and the right one with an open hand","no text","white","flat"),
("The vessels that have to open before sleep can start","SCENE_A","close on his open hand with wide warm orange lines inside the fingers, lying in firelight","a label \"SLEEP NEEDS THIS\"","fire_edge","flat"),
("are the exact vessels the cold has just shut.","SCENE_A","the same hand now clenched shut on frozen ground with the lines inside it narrow and pale blue","a label \"COLD DOES THIS\"","cold_night","flat"),
("Two survival programs, in the same body, on the same night,","SCENE_A","he lies on frozen ground with one hand drawn open and warm orange and the other drawn clenched and pale blue","no text","cold_night","worry"),
("each one cancelling the other's first move.","CARD","two thin black arrows pointing straight at each other and meeting head on","no text","white","flat"),
("Staying warm wins, because it has to.","CARD","the two arrows again, with the one coming from the closed fist drawn much thicker and pushing the other back","no text","white","flat"),
("Which leaves a person who is not going to freeze","SCENE_A","he lies curled tight on frozen ground with both hands tucked in, alive and still","no text","cold_night","tired"),
("and is not going to sleep either.","SCENE_A","the same curled position, eyes wide open, staring into the black air","no text","cold_night","worry"),
("A claim like that ought to be testable,","CARD","one plain empty box with a thin question mark drawn inside it","no text","white","flat"),
("and it has been tested.","CARD","the same box with a small green check mark drawn inside it","no text","white","flat"),
("In 1981 researchers put six men to bed in a chamber","CARD","six identical plain empty beds in two rows inside one drawn rectangular room","a label \"1981\"","white","flat"),
("where the temperature could be set.","CARD","one large round dial with a pointer and small marks around the edge, mounted on a plain wall","a label \"SET\" beside the dial","white","flat"),

# ═════════════════ CH5 — SAU NGUOI VA MOT NUM VAN — 30 shot ═════════════════
("They wore nothing but shorts, on a bed made of nylon webbing,","CARD","one plain bed drawn as an open lattice of criss crossed straps with no mattress on it","no text","white","flat"),
("so air could reach them from every side.","CARD","the same lattice bed with small thin arrows passing through the gaps from below and above","no text","white","flat"),
("Five settings.","CARD","five identical plain dials in a row, each with its pointer at a different angle","no text","white","flat"),
("Twenty one degrees Celsius, twenty four, twenty nine, thirty four, thirty seven.","CARD","the same five dials with a number written under each one","a label \"21\" \"24\" \"29\" \"34\" \"37\" under the five dials","white","flat"),
("Twenty nine was the neutral point,","CARD","the middle dial of the five drawn larger than the rest with a heavy black ring around it","a label \"29\"","white","flat"),
("where a bare body is neither working to warm itself nor working to cool.","CARD","one plain figure lying flat with no orange lines and no blue shading anywhere on it","no text","white","flat"),
("Then they read the sleep.","CARD","one long paper strip with a single continuous wavy line traced along it","no text","white","flat"),
("Heat broke it up.","CARD","the same paper strip with the wavy line interrupted by several short flat gaps","a label \"37\"","white","flat"),
("Cold broke it up worse.","CARD","the same paper strip with the wavy line broken into many more short pieces with wide flat gaps between them","a label \"21\"","white","flat"),
("And the single most disruptive setting in the whole study","CARD","the five dials in a row again, all drawn as plain outlines","no text","white","flat"),
("was not the coldest thing a person can survive.","CARD","a plain thermometer with its column at the very bottom and a red cross drawn beside it","no text","white","flat"),
("It was twenty one degrees.","CARD","one of the five dials filled solid and circled heavily in black marker","large bold headline text \"21\"","white","flat"),
("Room temperature.","CARD","one plain round wall dial hanging alone on an empty wall","large bold headline text \"ROOM TEMPERATURE\"","white","flat"),
("The number on an office thermostat,","CARD","one plain round wall dial with a small pointer, drawn alone","no text","white","flat"),
("in the middle of an argument about the office thermostat.","CARD","the same wall dial with two plain empty speech bubbles pointing at it from opposite sides","no text","white","flat"),
("An uncovered human body is already losing sleep","CARD","one plain figure lying flat on an open lattice bed with nothing over it","no text","white","flat"),
("at a temperature nobody would call cold.","CARD","one plain thermometer with the column at a comfortable middle height and a plain question mark beside it","a label \"21\"","white","flat"),
("And that was a room with a door on it.","CARD","one plain rectangular room outline with a closed door drawn in one wall and a round dial on another","no text","white","flat"),
("The cold has a cruder move than any of that.","SCENE_N","flat frozen ground under a black sky with thick white frost drawn across the whole surface","no text","cold_night","flat"),
("Shivering.","SCENE_A","he lies on the frozen ground with short repeated motion marks drawn along both arms and both shoulders","large bold headline text \"SHIVERING\"","cold_night","worry"),
("When the closed hands are not enough,","SCENE_A","close on his two clenched fists held tight against his chest, pale and stiff","no text","cold_night","worry"),
("the muscles start working,","SCENE_A","close on his upper arm and shoulder with several short repeated motion marks along the edge","no text","cold_night","worry"),
("and the body makes heat by moving.","SCENE_A","he lies curled with motion marks along his back and a few small wavy orange lines lifting off him","no text","cold_night","worry"),
("It is effective, it is expensive,","CARD","one plain figure with motion marks along it, and beside it a small pile of food drawn with a thin arrow pointing away","no text","white","flat"),
("and it has one obvious problem.","CARD","one plain figure lying flat with motion marks along it and three small z shapes above it, the z shapes crossed out in red","no text","white","flat"),
("A body busy shivering","SCENE_A","he lies on frozen ground shaking, motion marks along both arms, eyes wide open","no text","cold_night","worry"),
("is not a body on its way to sleep.","SCENE_A","close on his face, eyes wide open, jaw tight, motion marks at the edge of the frame","no text","cold_night","worry"),
("A person cold enough to shiver","SCENE_A","he sits upright on frozen ground with his arms wrapped around his knees, motion marks along his back","no text","cold_night","worry"),
("is a person who is not getting to sleep.","SCENE_A","he sits in the same position under a black sky, awake, drawn small in a wide empty frame","no text","cold_night","tired"),


# ═════════════════ CH6 — VIEC THAT CUA NGON LUA — 32 shot ═════════════════
("And a person who is not shivering, on a night that cold,","SCENE_A","he lies completely still on frozen ground with no motion marks anywhere on him","no text","cold_night","asleep"),
("is either warm enough,","SCENE_A","he lies still on the ground close beside a burning fire, one side of him lit warm orange","no text","fire_edge","asleep"),
("or is already in trouble.","SCENE_A","he lies still on bare frozen ground with no fire anywhere in the frame and frost on the ground around him","no text","cold_night","flat"),
("The fire in the middle of that camp","SCENE_N","a small fire burning in the middle of flat dark ground, seen from slightly above, with an empty ring of ground around it","no text","fire_ring","flat"),
("is doing something other than what it looks like it is doing.","SCENE_N","the same fire with a plain question mark drawn in the dark air above the flames","no text","fire_ring","flat"),
("A fire does not warm the air around it very much.","SCENE_N","a small fire on dark ground with the air around it drawn as plain flat cold navy right up to the flames","no text","fire_ring","flat"),
("Air moves, and on open ground it takes the heat with it.","SCENE_N","a small fire with several thin curved lines sweeping sideways away from it across the dark ground","no text","fire_ring","flat"),
("What a fire warms is surfaces,","SCENE_N","a small fire beside a large flat stone, the face of the stone turned to the fire lit warm orange and the far face left dark","no text","fire_edge","flat"),
("and the surface in question is skin.","SCENE_A","close on his bare forearm held near a fire, the side facing the flames lit warm orange and the other side dark","no text","fire_edge","flat"),
("A person lying with one side turned to the flames","SCENE_A","he lies on his side on the ground facing a low fire, the whole front of him lit warm orange","no text","fire_edge","asleep"),
("has that side held above the temperature where the vessels shut.","SCENE_A","the same position with the lit side of his body drawn warm orange and the shaded side drawn pale cold blue","no text","fire_edge","asleep"),
("That last step is inference, not measurement.","CARD","two plain boxes joined by a thin arrow, the arrow drawn as a dashed line instead of a solid one","a label \"INFERENCE\" on the dashed arrow","white","flat"),
("Nobody has ever wired a person up beside a campfire.","CARD","one small instrument box with thin wires drawn beside a small fire, with a red cross between them","no text","white","flat"),
("But it is the same skin and the same vessels, and warm skin is exactly what the laboratory was measuring.","SCENE_A","close on his bare forearm in the firelight with thin warm orange lines showing inside the skin","no text","fire_edge","flat"),
("Which is the one condition the sleep system was waiting on.","SCENE_A","close on his open hand lying on the ground in the firelight, small wavy orange lines lifting off the fingers","no text","fire_edge","asleep"),
("So the fire is not making the night warm.","SCENE_N","a wide view of a small fire on a huge dark frozen plain, the darkness reaching right up to the edge of the light","no text","fire_ring","flat"),
("Nothing was going to make that night warm.","SCENE_N","the same wide dark plain with the fire drawn very small near the bottom of the frame","no text","fire_ring","flat"),
("It is making a strip of skin warm enough","SCENE_A","close on his shoulder and upper arm with one narrow band across the skin lit warm orange and everything else dark","no text","fire_edge","asleep"),
("that the body will agree to let heat go.","SCENE_A","he lies asleep facing the fire with small wavy orange lines lifting off his open hand","no text","fire_edge","asleep"),
("Heat on the outside, permission on the inside.","CARD","one plain figure lying on its side with a small fire beside it, warm orange marks on the outer skin and small wavy lines rising from the hand","a label \"HEAT\" beside the fire and \"PERMISSION\" beside the hand","dark_card","flat"),
("That is a small thing to ask of a fire,","SCENE_N","one very small fire drawn alone on dark ground, low and quiet","no text","fire_ring","flat"),
("and it is not a small thing to be given.","SCENE_A","he lies asleep on the ground beside that same small fire, completely still","no text","fire_edge","asleep"),
("Now, if any of that is right,","CARD","one plain empty box with a thin question mark inside it","no text","white","flat"),
("it has to show up somewhere other than in an argument.","CARD","a plain speech bubble on one side and a small hand trowel on the other, with a thin arrow running from the bubble to the trowel","no text","white","flat"),
("A body that needs one warm side","CARD","one plain figure lying on its side with one half drawn warm orange and the other half pale blue","no text","white","flat"),
("would not lie down just anywhere in a camp.","SCENE_N","a wide patch of dark ground with a small fire at one edge and several scattered empty sleeping spots far from it, each marked with a red cross","no text","fire_ring","flat"),
("It would lie in a ring, close in,","SCENE_N","seen from directly above, a small fire in the centre with several empty body shaped patches arranged evenly around it","no text","fire_ring","flat"),
("with one side turned to the fire,","SCENE_A","seen from above, he lies on his side with his front toward the central fire","no text","fire_ring","asleep"),
("and it would turn over in the night.","SCENE_A","seen from above, the same person now lying the other way round with his back to the fire","no text","fire_ring","asleep"),
("That is a prediction.","CARD","the word alone in the frame, nothing else drawn","large bold headline text \"A PREDICTION\"","dark_card","flat"),
("And it is the kind of prediction the ground can be asked about.","CARD","a simple cross-section of layered soil with a small hand trowel resting on the top layer","no text","white","flat"),
("Everything to this point has been measured on living people","CARD","one plain bed with a small instrument box beside it and thin wires running to the pillow","no text","white","flat"),
("in rooms with thermostats.","CARD","one plain round wall dial hanging on an otherwise empty wall","no text","white","flat"),
("There is one place where the ring turns up in the ground.","SCENE_N","a shallow excavated pit seen from above with a faint round pattern pressed into the soil at the bottom","no text","dry_plain","flat"),
("A camp on the shore of the Sea of Galilee,","SCENE_N","a low reed shelter standing on a flat lake shore with still water behind it and low hills beyond","no text","dry_plain","flat"),

# ═════════════════ CH7 — SAN LEU O OHALO — 26 shot ═════════════════
("twenty three thousand years old,","CARD","one long horizontal line with a single small mark near the left end","a label \"23,000 YEARS\"","white","flat"),
("spent most of the time since then underwater.","SCENE_N","a flat sheet of still water with the faint outline of a small round shelter visible under the surface","no text","dry_plain","flat"),
("It is the only reason anything soft survived,","SCENE_N","a small bundle of green stems lying under shallow still water, whole and undamaged","no text","dry_plain","flat"),
("because plants normally do not.","CARD","one plain stem with leaves drawn beside a small pile of dust, with a thin arrow running from one to the other","no text","white","flat"),
("When it was excavated,","SCENE_N","a shallow rectangular pit dug into pale dry soil with a small hand trowel and a brush lying at its edge","no text","dry_plain","flat"),
("the floor of one brush hut still had the bedding lying on it.","SCENE_N","the flat floor of a small round shelter seen from above, with pale dried grass spread across it in a clear pattern","no text","dry_plain","flat"),
("Not a stain in the soil.","SCENE_N","a plain pale patch on flat dry soil with a red cross drawn through it","no text","dry_plain","flat"),
("Not a dark shadow where something used to be.","SCENE_N","a dark body shaped outline on flat dry soil with a red cross drawn through it","no text","dry_plain","flat"),
("The actual grass.","SCENE_N","a close view of real dried grass stems lying flat on a soil floor, every stem drawn separately","large bold headline text \"THE ACTUAL GRASS\"","dry_plain","flat"),
("Bunches of stems and leaves from a marsh grass,","SCENE_N","several tied bundles of long thin grass stems lying side by side on a soil floor","no text","dry_plain","flat"),
("partly charred, pressed flat under a thin layer of clay.","SCENE_N","the same grass bundles with their ends blackened, pressed under a thin pale layer of dried clay","no text","dry_plain","flat"),
("And the excavators wrote down how it was laid out.","SCENE_N","a plain open notebook lying on dry soil beside the edge of the excavated floor","no text","dry_plain","flat"),
("Arranged in a repeated pattern, on the floor, around a central hearth.","SCENE_N","seen from directly above, a round hut floor with a dark burnt circle at the centre and pale grass bedding laid evenly around it","a label \"HEARTH\" on the burnt circle","dry_plain","flat"),
("It is the oldest bedding anybody has found,","CARD","one long horizontal line with a single mark at the far left end and nothing before it","a label \"OLDEST\"","white","flat"),
("and the shape of it is a ring with a fire at the centre.","SCENE_N","seen from directly above, a ring of pale grass laid around a small dark burnt circle on a hut floor","no text","dry_plain","flat"),
("So one third of the prediction is sitting there in the clay.","CARD","three small boxes in a row with only the first one filled solid and marked with a green check","a label \"THE RING\" under the first box","white","flat"),
("The other two thirds are not,","CARD","the same three boxes with the second and third left empty and marked with question marks","a label \"FACING\" under the second box and \"TURNING\" under the third","white","flat"),
("and no amount of staring at it will produce them.","SCENE_N","the excavated round floor seen from above again, plain and unchanged, with nothing added to it","no text","dry_plain","flat"),
("Grass does not record which way a person was facing,","SCENE_N","a close view of flat dried grass on a soil floor with a small curved arrow drawn over it and crossed out in red","no text","dry_plain","flat"),
("and it does not record anybody turning over.","SCENE_N","the same flat grass with a second curved arrow drawn over it and also crossed out in red","no text","dry_plain","flat"),
("Nor does the layout prove anything about blood vessels.","CARD","one plain open hand drawn beside a small round hut floor plan, with a red cross between the two","no text","white","flat"),
("A hearth in the centre of a room is useful for a list of reasons,","SCENE_N","a dark burnt circle on a hut floor seen from above with four short arrows pointing outward from it","no text","dry_plain","flat"),
("and warmth is only one of them.","SCENE_N","the same burnt circle with only one of the four arrows drawn warm orange and the rest plain black","a label \"WARMTH\"","dry_plain","flat"),
("But if a body needs a warm surface on one side before it will agree to shed heat,","SCENE_A","he lies on his side facing a low fire, the near half of him warm orange and small wavy lines lifting off his hand","no text","fire_edge","asleep"),
("then bedding laid in a ring around a fire is what that requirement looks like from above.","SCENE_N","seen from directly above, a round hut floor with a burnt circle at the centre and grass bedding laid evenly all the way around it","no text","dry_plain","flat"),
("And the shore of the Sea of Galilee is not a cold place.","SCENE_N","a warm flat lake shore under a plain pale sky, still water and low dry hills, no frost anywhere","no text","dry_plain","flat"),
("Whatever pulled those people into that ring, it was not a winter on the Ukrainian plain.","CARD","two small round hut floor plans side by side, one drawn on a warm pale ground and the other on a frosted grey ground","no text","white","flat"),


# ═════════════════ CH8 — KHUC THANH THAT — 32 shot ═════════════════
("The base under all of this is narrower than it sounds,","SCENE_N","a very wide flat stone slab balanced on one small narrow block underneath it","no text","white","flat"),
("and it should be named out loud.","CARD","one plain speech bubble drawn large and empty","no text","white","flat"),
("Nobody has ever measured a night of sleep","SCENE_A","he lies asleep on frozen ground beside a small fire, drawn very small in a wide empty frame","no text","cold_night","asleep"),
("from twenty thousand years ago.","CARD","one small instrument box with wires, drawn beside a long horizontal line, with a red cross over the box","a label \"20,000 YEARS\"","white","flat"),
("Nobody is going to.","CARD","the same instrument box with the red cross drawn heavier and thicker","no text","white","flat"),
("There are no sensors in the archaeological record,","SCENE_N","a shallow excavated pit with bones and stone tools laid out at the bottom, and no wires or instruments anywhere","no text","dry_plain","flat"),
("and there is no way to get one onto a body","CARD","one small sensor with a thin wire, drawn beside a plain outline of a skeleton, with a red cross between them","no text","white","flat"),
("that has been gone that long.","SCENE_N","a few pale bones lying half buried in dry soil, seen from above","no text","dry_plain","flat"),
("Nearly every number in this comes from living people,","CARD","one plain bed with a small instrument box and thin wires running to the pillow","no text","white","flat"),
("indoors, wired up, in the last fifty years.","CARD","the same bed drawn inside a plain rectangular room outline with a round wall dial on the wall","a label \"50 YEARS\"","white","flat"),
("And the study that produced the sharpest number in it,","CARD","six identical plain empty beds in two rows inside one drawn rectangular room","no text","white","flat"),
("the one about room temperature, ran on six men.","CARD","the same six beds with a heavy black ring drawn around all of them together","large bold headline text \"SIX\"","white","flat"),
("Six.","CARD","six small identical plain figures standing in a row on empty white, nothing else drawn","large bold headline text \"SIX\"","white","flat"),
("The people who ran it said plainly","CARD","one plain open paper page with a few thin handwritten lines on it","no text","white","flat"),
("that the differences between one man and the next were large.","CARD","six plain vertical bars of very different heights standing side by side","no text","white","flat"),
("Some of them handled the cold setting nearly as well as the neutral one,","CARD","two plain figures lying flat side by side, both with a small green check mark above them","no text","white","flat"),
("and some of them barely slept.","CARD","one plain figure lying flat with its eyes open and a paper strip beside it broken into many short pieces","no text","white","flat"),
("So the honest shape of this is not a discovery about the past.","CARD","a small hand trowel drawn beside a shallow soil layer, with a red cross over the trowel","no text","white","flat"),
("It is a set of constraints that a human body carries now,","SCENE_A","he stands upright in the middle of an empty white frame with one hand open and warm orange and the chest pale blue","no text","white","flat"),
("and that a human body almost certainly carried then,","SCENE_A","the same standing figure, now on frozen ground under a black sky, drawn exactly the same way","no text","cold_night","flat"),
("because the parts involved are old.","CARD","one plain open hand with thin branching lines inside the fingers, drawn beside a long horizontal line marked far to the left","no text","white","flat"),
("Blood vessels that narrow in the cold are not a modern feature.","SCENE_A","close on his clenched fist on frozen ground with narrow pale blue lines inside the fingers","no text","cold_night","flat"),
("Neither is the shivering,","SCENE_A","he lies on frozen ground with short repeated motion marks along both arms","no text","cold_night","worry"),
("and neither is the need to shed heat before sleep begins.","SCENE_A","he lies asleep with small wavy orange lines lifting off his open hands and bare feet","no text","fire_edge","asleep"),
("What cannot be recovered is the part everybody would most like to have.","CARD","one plain empty box drawn large with a question mark inside it","no text","white","flat"),
("Whether a specific person, on a specific night,","SCENE_A","he lies on frozen ground beside a low fire, drawn small in a wide dark frame","no text","fire_edge","flat"),
("on frozen ground in what is now Ukraine,","SCENE_N","a plain outline map of Europe with one small area filled solid dark near the centre east","a label \"UKRAINE\"","white","flat"),
("actually slept.","SCENE_A","close on his face lying on the ground, the eyes drawn as two plain question marks instead of eyes","no text","cold_night","flat"),
("The record does not keep that.","SCENE_N","a shallow excavated pit seen from above with bones, stones and a burnt circle laid out, and one empty space in the middle","no text","dry_plain","flat"),
("It keeps the houses, the hearths,","SCENE_N","one low round shelter built from long curved bones standing on frozen ground, with a dark burnt circle in front of it","no text","cold_night","flat"),
("the bones and the tools,","SCENE_N","a few pale bones and two shaped stone tools laid out side by side on dry soil","no text","dry_plain","flat"),
("and none of those can say whether anyone in them rested.","SCENE_N","the same bones and stone tools with one plain question mark drawn in the empty space beside them","no text","dry_plain","flat"),

# ═════════════════ KET — 30 shot ═════════════════
("So the answer is smaller than the question sounds, and stranger.","SCENE_N","a wide dark frozen plain with one small fire burning near the centre and nothing else","no text","fire_ring","flat"),
("Nobody slept through those nights,","SCENE_A","he lies on the ground beside a low fire with his eyes open, a long dotted arc drawn right across the black sky above him","no text","fire_edge","tired"),
("because no sleep is sixteen hours long.","CARD","one long horizontal bar with only a short section near one end filled in","a label \"16 HOURS\" over the whole bar","dark_card","flat"),
("What the evidence will carry is this.","CARD","one plain open hand held out flat and empty","no text","white","flat"),
("A body has to give heat away before it will sleep,","SCENE_A","he lies on his back with small wavy orange lines lifting off his open hands","no text","cold_night","asleep"),
("a freezing night takes that option off the table,","SCENE_A","the same position with his hands now clenched tight and no orange lines anywhere","no text","cold_night","worry"),
("and something warm on one side puts it back.","SCENE_A","he lies on his side facing a low fire, the near side of him lit warm orange and small wavy lines lifting off his open hand","no text","fire_edge","asleep"),
("On that landscape there was one thing warm enough to do that,","SCENE_N","a wide frozen plain at night with a single small fire burning in the middle of it","no text","fire_ring","flat"),
("and somebody had to keep it alight.","SCENE_A","he crouches beside the fire feeding one stick into it, everything around him dark","no text","fire_edge","tired"),
("Every other animal there answered the cold with its own body.","SCENE_N","a thick coated mammoth standing alone on a frozen plain under a black sky","no text","cold_night","flat"),
("Fur.","SCENE_N","one heavily furred animal standing alone on frozen ground, the coat drawn with many separate strands","a label \"FUR\"","cold_night","flat"),
("Fat.","SCENE_N","one round heavy bodied animal lying alone on frozen ground, the body drawn thick and solid","a label \"FAT\"","cold_night","flat"),
("A burrow.","SCENE_N","a cross-section of frozen ground with a small round chamber dug beneath the surface and a small animal curled inside it","a label \"BURROW\"","cold_night","flat"),
("A season spent unconscious.","SCENE_N","the same underground chamber with the animal asleep and a long dotted line running across the frame above the ground","a label \"ONE SEASON\"","cold_night","flat"),
("No other animal there answered it","SCENE_N","several different animals standing apart on a frozen plain, none of them near any fire","no text","cold_night","flat"),
("by building the heat source outside the body,","SCENE_A","he kneels on frozen ground stacking small sticks into a low pile in front of him","no text","cold_night","flat"),
("and then lying down around it.","GROUP","seen from directly above, three of them lying evenly spaced around a small fire in the centre, each turned toward it","no text","fire_ring","asleep"),
("A bedroom is the same arrangement","SCENE_N","a plain empty modern bedroom drawn from above, one bed in the middle of a rectangular room","no text","modern_night","flat"),
("with the fire moved inside the walls.","SCENE_N","the same empty bedroom with a small warm orange glow drawn inside the wall beside the bed","no text","modern_night","flat"),
("What that leaves is a picture nobody dug up,","CARD","one plain empty picture frame drawn hanging alone","no text","dark_card","flat"),
("and it is a very small one.","CARD","the same picture frame drawn very small in the middle of a large empty dark frame","no text","dark_card","flat"),
("A person turns over.","SCENE_A","seen from above, he rolls from one side onto the other beside a low fire","no text","fire_ring","asleep"),
("The cold side goes to the flames,","SCENE_A","he lies on his side facing the fire, the near half of him lit warm orange","no text","fire_edge","asleep"),
("the warm side goes to the dark,","SCENE_A","the same person with his back to the fire, the near half of him drawn pale cold blue","no text","fire_edge","asleep"),
("and the vessels in the hands open again","SCENE_A","close on his open hand lying on the ground in the firelight, the thin lines inside the fingers drawn warm orange","no text","fire_edge","asleep"),
("by a fraction of a degree.","SCENE_A","the same open hand with small wavy orange lines lifting off the fingertips into the dark","no text","fire_edge","asleep"),
("And for a few hours, in the middle of a sixteen hour night,","SCENE_N","a long dotted arc across a black sky with one short section of it marked off between two small marks","a label \"A FEW HOURS\" on the short section","night_dark","flat"),
("the body stops arguing with itself,","CARD","two thin black arrows that had been pointing at each other now drawn lying flat and still","no text","dark_card","flat"),
("and gives away the heat it has to lose","SCENE_A","he lies asleep beside the fire with small wavy orange lines lifting off his open hand into the black air","no text","fire_edge","asleep"),
("in order to sleep at all.","SCENE_A","he lies still and asleep beside a small fire on a dark frozen plain, drawn small in a very wide quiet frame","no text","fire_ring","asleep"),

]
