#!/usr/bin/env python3
# Gen prompt ảnh cho Video #2 — chỉnh style ở khối trên rồi chạy: python3 gen_prompts.py
# Nhân vật KHOÁ CỐ ĐỊNH (đè điểm yếu drift của đối thủ): hiện đại = đầu trọc + trần trên + short; cổ đại = có tóc + khố.

STYLE = "Flat 2D digital doodle cartoon drawn with clean BOLD SOLID BLACK ink outlines of even, consistent line weight (smooth confident strokes like a clean black felt-tip pen), in a simple minimalist educational style,"

MODERN = ("the recurring modern guy, the same bald black-outline STICK FIGURE kept EXACTLY identical in every image — a plain round BALD white head with NO hair and a simple face, a bare white stick-line torso with NO shirt, wearing ONLY a small pair of simple flat blue shorts at the hips, thin bold noodle arms and legs, simple rounded mitten hands and small oval feet,")

CAVE = ("the recurring caveman STICK FIGURE kept EXACTLY identical in every image — a round white head framed by a BIG MESSY LONG SHAGGY mane of messy hair coloured EXACTLY hex #7C5D39 (a warm medium brown), unkempt hanging down the sides of the head in scraggly tousled locks (competitor caveman style) with thick expressive eyebrows, wearing a rough brown animal-hide fur garment over the torso (a flat brown shape with a jagged fur bottom edge), bare thin bold black stick-line legs, simple rounded mitten hands, barefoot with small oval feet,")

CONSIST = ("The people are TRUE STICK-FIGURE doodles: a large round white head with just a face (two dot eyes, clear thick expressive eyebrows, a tiny mouth, no nose) on a THIN body made of BOLD SOLID BLACK LINES (a single bold line torso plus thin bold noodle arms and legs) — NOT a filled or solid body shape, just clean bold black ink stick lines, with simple rounded mitten hands and small oval feet, ALWAYS drawn as the SAME stickman, kept identical in every image. The modern man is BALD (round white head, NO hair) with a bare torso and small blue shorts; the caveman has a BIG MESSY LONG SHAGGY mane of warm brown hair (hex #7C5D39) hanging down the sides and a brown fur/hide garment. Any animals and props are simple and cute in flat SOLID COLOUR (never black-and-white), each animal a simple cute character with a little face. Clean BOLD SOLID BLACK ink outlines of even weight (confident smooth strokes, filled solid black, NOT pencil, NOT sketchy, NOT thin, NOT grey); flat colours, NO gradient shading.")

SCENE = ("ONE single scene showing ONLY ONE instance of the character; no model sheet, no multiple poses, no grid, no panels, no split frames; keep it minimal on a plain white background, the whole background one single flat colour, with lots of clean empty background space and a soft light-grey shadow under the character on the ground; draw ONLY the character plus the exact props/animals named in this scene description, each at a clear readable size (a decent portion of the frame, NOT tiny) — do NOT invent or add ANY extra objects, toys, toy blocks, furniture, plants or background clutter; keep most of the frame clean and empty (never a full-colour background fill); RED is the accent colour used for labels, tags, warning signs and small danger marks; keep the people as simple bold black stick-figure doodles with colour only on the named garment, animals, props and tags,")

NEG = ("Family-friendly, wholesome, cute, gentle, non-violent, no blood, no gore, no injury. Keep the character identical every time; the modern man is bald with no hair, the caveman has a big messy long shaggy warm brown (#7C5D39) mane of hair; no shirt and no long trousers on the modern man (bare torso + blue shorts only), no hoodie, no jacket, no full outfit; NO PENCIL, no graphite, no pencil sketch, no crosshatching, no faint or grey lines, no rough sketch shading (solid black ink lines only); no gradients, no textures, no photorealism, no 3D, no glossy render, no solid filled body, no extra limbs or fingers, no random extra objects, no toys, no toy blocks, no clutter, no unrequested props, no watermark, no logo, no frame borders, no duplicate characters, no collage, no picture-in-picture, 16:9, clean educational YouTube explainer doodle style.")

F = {
 "med": "a medium shot, the subject drawn big and centered with clean breathing space around it.",
 "wide": "a WIDE establishing shot, the subject fairly small inside a large scene with lots of environment around it.",
 "close": "a tight CLOSE-UP on the character's face and shoulders, the expressive face filling most of the frame.",
 "high": "a HIGH-ANGLE shot looking DOWN from above, making the subject look small and vulnerable.",
 "low": "a LOW-ANGLE shot looking UP from below, making the subject look big, powerful and looming.",
}
def tag(t): return f'a small "{t}" in bold white ALL-CAPS letters on a little red tag or sign.'
NT = "no text or letters."

# (shot line, character | None(=cảnh), hành động+biểu cảm, framing, text)
SHOTS = [
 ("Right now, you think you're the most dangerous thing in the room.", MODERN, "strutting proudly with chest out and hands on hips like he owns the place, chin up, smug half-lidded eyes", "med", NT),
 ("You walk into a forest like you own it.", MODERN, "strolling casually with hands behind his back among a few simple flat green trees, calm smug face", "wide", NT),
 ("You. A soft, slow, mostly hairless ape", MODERN, "standing plainly with a big black arrow pointing down at him, dumb clueless expression", "med", tag("YOU")),
 ("who gets winded climbing two flights of stairs", MODERN, "puffing and out of breath climbing a simple black staircase, hunched, nervous wavy mouth and a sweat drop", "med", NT),
 ("and screams at a spider in the bathroom.", MODERN, "shrieking at a tiny cute spider on a thread, surprised with wide round eyes and open O mouth, arms up", "close", NT),
 ("No claws. No fangs. No fur.", MODERN, "shrugging and showing his empty mitten hands, with three tiny red X marks floating beside him, deadpan flat mouth", "med", NT),
 ("A top speed a house cat finds adorable.", MODERN, "running hard with effort and little motion-puff clouds, while a small smug cute cat sits watching unimpressed", "med", tag("ADORABLE")),
 ("But somehow you strut around this planet like the landlord.", MODERN, "strutting proudly on top of a simple flat round globe with pale green land shapes, tiny confident smile", "med", NT),
 ("Here's the part that should keep you up at night.", MODERN, "lying awake in a simple bed with eyes wide open, a flat dark night shape behind, worried face", "med", NT),
 ("For almost the entire story of being human,", None, "a long horizontal black timeline line with a few tiny bold stick figures spaced along it from left to right", "wide", NT),
 ("you were not the one doing the hunting.", CAVE, "holding a wooden spear with a big red X over him, dumb expression", "med", NT),
 ("You were the meal.", CAVE, "a nervous caveman sitting on a simple flat plate, surprised wide eyes", "med", tag("YOU WERE THE MEAL")),
 ("Something was always watching you from the dark,", CAVE, "a nervous caveman crouching, with many pairs of glowing yellow eyes peering from a flat black bush behind him", "high", NT),
 ("and it was hungry.", None, "a big flat black bush shape with several pairs of glowing yellow eyes and one hungry licking mouth", "close", tag("HUNGRY")),
 ("So here's the question this whole video is going to answer.", CAVE, "a caveman looking up at a HUGE bold black question mark towering over him, curious tilted head", "med", NT),
 ("Out of everything that ever stalked, ambushed, and ate our ancestors,", None, "a row of simple cute flat-colour predators facing forward - a brown leopard with black rosettes, a green crocodile, and a brown eagle, each with a little face", "wide", NT),
 ("what hunted us the most?", None, "a police-lineup row of cute flat-colour predators (leopard, crocodile, eagle) with a big bold black question mark above them", "wide", NT),
 ("And let's be honest up front.", MODERN, "shrugging with both mitten hands up in an honest gesture, calm sincere face", "med", NT),
 ("It's not lions.", None, "a single cute flat golden-yellow lion with a mane and a little face, with a big red X crossing it out", "med", NT),
 ("Everyone guesses lions.", None, "three bold black stick figures each with a thought bubble containing a small cute yellow lion", "wide", NT),
 ("The real answer is stranger,", MODERN, "with one thick eyebrow raised, intrigued curious face, one mitten hand on his chin", "close", NT),
 ("there's more than one suspect,", None, "three blank suspect cards standing in a row, each showing a bold black question mark", "med", NT),
 ("and the case is still open.", None, "a simple flat manila case folder lying open with a few papers and a bold black question mark on top", "med", tag("CASE OPEN")),
 ("Because the animal that hunted us the most", None, "a single bold cute flat brown leopard with black rosettes and a little face, prowling, centered", "med", NT),
 ("might not be the animal that changed us the most.", CAVE, "standing in the middle with a black arrow pointing left to a cute leopard face and a black arrow pointing right to a big eye-and-brain icon, two different ideas", "med", NT),
 ("Stick around till the end,", MODERN, "pointing forward straight at the viewer with a slight friendly grin", "med", NT),
 ("because the last suspect on this list is still hiding inside your head right now,", None, "a bold stick-figure BALD head shown in side profile, with a small dark mysterious question-mark shape hidden inside the head", "close", NT),
 ("and you still flinch at it without knowing why.", MODERN, "flinching and jumping backward, startled, wide round eyes and a sweat drop", "close", NT),
 ("Let's open the file.", None, "a single mitten hand opening a simple flat case folder marked with a question mark", "med", NT),
 ("First, the uncomfortable truth.", CAVE, "a caveman standing looking uneasy and awkward, nervous wavy mouth", "med", tag("THE UNCOMFORTABLE TRUTH")),
 ("For most of our history, humans were not predators.", CAVE, "holding a spear that has a small red X over it, deadpan", "med", tag("PREDATOR?")),
 ("We were prey.", CAVE, "a lone vulnerable caveman standing small and alone in a big empty white frame, looking up nervously", "high", tag("PREY")),
 ("Not the scary kind of animal.", CAVE, "puffing up his chest and baring teeth trying to look fierce and scary but failing, a big red X over the idea", "med", NT),
 ("The snack kind.", CAVE, "a caveman sitting on a simple flat plate like a snack, dumb clueless expression", "med", tag("SNACK")),
 ("Picture what we actually were two million years ago.", None, "a horizontal timeline with a black arrow pointing far to the left toward a small primitive caveman", "wide", tag("2 MILLION YEARS AGO")),
 ("Small. Slow on the ground.", CAVE, "a caveman standing next to a simple cute flat snail, shrugging to show he is slow", "med", tag("SLOW")),
 ("No armor, no natural weapons.", CAVE, "shrugging beside two crossed-out icons, a shield and a claw, each with a small red X", "med", NT),
 ("Basically a walking lunchbox that could scream.", CAVE, "holding a simple flat lunchbox, mouth open screaming with wide round eyes", "med", tag("LUNCHBOX")),
 ("And we lived in a world crawling with things that wanted to eat us.", CAVE, "a nervous ancestor surrounded by many glowing eyes in the dark", "high", NT),
 ("This was never one villain.", None, "a single red WANTED poster crossed out with a red X, breaking apart into several smaller wanted posters", "med", NT),
 ("It was a whole menu,", None, "a folded restaurant menu card with cute predator icons listed", "med", tag("THE MENU")),
 ("and we were on it.", CAVE, "a worried caveman drawn as a menu item with a price tag", "close", NT),
 ("So we're going to do this like detectives.", MODERN, "in a detective hat holding a magnifying glass", "med", NT),
 ("We line up the suspects,", None, "a police line-up of cute flat-colour predators each with a little face", "wide", tag("SUSPECTS")),
 ("we look at the real evidence,", None, "a magnifying glass hovering over a white skull on a table", "close", NT),
 ("actual fossils with actual bite marks,", None, "a cute flat-colour fossil bone with two little tooth dents", "close", NT),
 ("and we work out who did the most damage.", MODERN, "pinning photos on a red-string detective board", "med", NT),
 ("Some of these you will expect.", MODERN, "nodding with a knowing half-smile", "close", NT),
 ("One of them comes from the sky.", None, "a cute flat-colour eagle with a little face, wings spread, seen from below", "low", NT),
 ("One of them is basically a log with teeth.", None, "a cute flat-colour crocodile with a little face, looking like a floating log", "med", NT),
 ("And one of them is so small and so old", None, "a small mysterious dark coiled shape hinting at a hidden snake, tucked behind a giant black question mark", "med", NT),
 ("it may have shaped the way you literally see the world.", MODERN, "staring at his own reflection with wide worried eyes", "close", NT),
 ("Suspect number one is the one we have the clearest evidence for.", None, "a red case file folder, a leopard photo peeking out", "med", tag("SUSPECT #1")),
 ("And that evidence is a skull with two neat holes punched in the top.", None, "a white skull with two round holes in the top, sitting on a table", "close", NT),
 ("Let's start with the suspect the evidence points to hardest.", None, "a magnifying glass focused on a cute flat-colour spotted leopard face", "med", NT),
 ("South Africa.", None, "a simple flat map of Africa with a red location pin on the south", "wide", tag("SOUTH AFRICA")),
 ("A cave called Swartkrans.", None, "a dark cave mouth in a rocky hillside, flat-colour", "wide", tag("SWARTKRANS")),
 ("Scientists dig up an ancient skull,", None, "a hand brushing dirt off a white skull in the ground", "close", NT),
 ("an early human relative,", CAVE, "a gentle ancestor portrait framed like a museum card", "med", NT),
 ("over a million years old.", None, "a long dusty timeline arrow stretching far back, flat-colour", "wide", tag("1,000,000+ YRS")),
 ("On the back of that skull are two small round holes.", None, "a white skull, two round holes highlighted in red", "close", NT),
 ("For a long time, nobody was sure what made them.", None, "the two-hole skull surrounded by floating question marks", "med", NT),
 ("Then someone had an unsettling idea.", MODERN, "with a lightbulb and a slightly uneasy face", "close", NT),
 ("They took the lower jaw of a leopard and turned it over.", None, "a cute flat-colour leopard jawbone being flipped, two fangs showing", "med", NT),
 ("The two fangs on that jaw lined up with the two holes.", None, "leopard fangs descending toward the two holes in the skull", "close", NT),
 ("Perfectly.", None, "the two fangs slotting exactly into the two holes, tiny sparkle", "close", tag("PERFECT MATCH")),
 ("Like a key sliding into a lock.", None, "a cute key sliding into a lock, flat-colour", "med", NT),
 ("That's not a coincidence.", MODERN, "shaking his head, arms crossed, certain", "close", NT),
 ("That's a leopard grabbing a human by the head.", None, "a cute flat-colour leopard gently biting a skull by the top", "low", NT),
 ("And here's what nobody tells you about leopards.", None, "a cute flat-colour spotted leopard with a little face, sly look", "med", NT),
 ("They don't just kill you.", None, "a cute leopard with a little face licking its paw, calm", "med", NT),
 ("They carry you up a tree.", None, "a leopard climbing a tree trunk carrying a bundle in its mouth", "low", NT),
 ("A leopard will haul something its own body weight straight up into the branches,", None, "a cute leopard hauling a heavy load up a tall tree, seen from below", "low", NT),
 ("to eat in peace,", None, "a leopard resting on a high branch with its meal, content face", "med", NT),
 ("safe from lions and hyenas.", None, "a cute flat-colour lion and hyena looking up hungry from the ground", "high", NT),
 ("So picture it.", MODERN, "framing a scene with his hands like a director", "med", NT),
 ("Your ancestor climbs a tree,", CAVE, "climbing up a tree trunk, hopeful face", "wide", NT),
 ("because a tree used to feel safe.", CAVE, "sitting on a branch with a relieved little smile", "med", NT),
 ("But the leopard is already up there.", None, "a cute flat-colour leopard crouched on a higher branch, eyes down", "low", NT),
 ("Waiting.", None, "leopard eyes glowing in the tree leaves, still and silent", "close", tag("WAITING")),
 ("For our ancestors,", CAVE, "at the base of a huge tree looking up nervous", "high", NT),
 ("the leopard turned the one safe place into its own pantry.", None, "a tree with bones tucked in the branches, a leopard beside them", "wide", tag("PANTRY")),
 ("And the fossils agree.", None, "a cute flat-colour fossil bone with a little face nodding", "close", NT),
 ("In some caves, that pile of old bones isn't a graveyard.", None, "a cave floor with a neat pile of white bones, flat-colour", "wide", NT),
 ("It's the bottom of a leopard's lunch tray.", None, "the bone pile framed like food scraps on a plate", "med", tag("LEFTOVERS")),
 ("So the leopard is suspect number one,", None, "a cute leopard mugshot on a red WANTED card", "med", tag("SUSPECT #1")),
 ("the clearest case on the whole board.", MODERN, "tapping the leopard photo on his detective board", "med", NT),
 ("But the next attacker didn't come from the trees.", None, "a leafy tree with a red cross over it, flat-colour", "med", NT),
 ("It came from a direction your ancestors never thought to guard.", CAVE, "looking left and right on the ground, oblivious", "med", NT),
 ("Straight down.", None, "a cute flat-colour eagle diving straight down, seen from below", "low", tag("STRAIGHT DOWN")),
 ("In 1924, in a limestone quarry in South Africa,", None, "a flat-colour rocky quarry scene with pickaxes", "wide", tag("1924")),
 ("workers found a small skull.", None, "a hand lifting a small white skull from pale rock", "close", NT),
 ("It belonged to a child.", CAVE, "a gentle ancestor child portrait, soft expression", "med", NT),
 ("A very old child.", None, "a small skull resting on a dusty timeline arrow", "med", NT),
 ("About three years old, and about two and a half million years old.", None, "a skull between a number 3 icon and a huge year number", "med", tag("2.5 MILLION YRS")),
 ("We call it the Taung Child.", None, "a small skull on a museum plaque, framed nicely", "close", tag("TAUNG CHILD")),
 ("For decades it was famous for one thing.", None, "the Taung skull under a single bright spotlight", "med", NT),
 ("It helped prove that we evolved in Africa.", None, "a flat map of Africa with the skull and a rising family-tree icon", "wide", tag("AFRICA")),
 ("But a detail hid in plain sight for seventy years.", None, "a magnifying glass sweeping over the small skull, one spot glowing", "close", tag("70 YEARS")),
 ("The damage on that little skull.", None, "the small skull with faint scratch marks near the eyes", "close", NT),
 ("In the two thousands, researchers looked closely,", None, "a scientist magnifying glass hovering over an old skull on a table", "med", tag("2000s")),
 ("at the marks around the eye sockets.", None, "a close view of a skull's eye sockets with tiny scratch marks", "close", NT),
 ("And they matched something specific.", None, "two claw-mark shapes lining up on an evidence card", "med", NT),
 ("The talons of a large bird of prey.", None, "a close view of sharp curved eagle talons", "close", tag("TALONS")),
 ("The Taung Child wasn't killed", None, "a small ancient child skull sitting alone", "med", tag("TAUNG CHILD")),
 ("by a cat on the ground.", None, "a cute flat-colour cat with a little face, crossed out with a red X", "low", NT),
 ("It was taken by an eagle.", None, "a cute flat-colour brown eagle with a little face swooping down", "low", tag("EAGLE")),
 ("From the sky.", None, "a small eagle silhouette high against an empty pale sky", "high", NT),
 ("Modern crowned eagles in Africa", None, "a cute flat-colour brown crowned eagle with a little face perched", "med", tag("CROWNED EAGLE")),
 ("still hunt monkeys in exactly this way.", None, "a cute flat-colour little monkey with a face, an eagle looming above", "high", NT),
 ("They drop out of the canopy at highway speed,", None, "a cute flat-colour eagle diving fast down out of tree branches", "low", NT),
 ("and strike straight through the skull.", None, "an eagle talon hitting a small skull, motion lines", "close", NT),
 ("To a small ancient human, an eagle wasn't a bird.", CAVE, "looking up at the sky, mouth open in fear", "high", NT),
 ("It was a silent death that fell out of the sun.", None, "a cute flat-colour eagle diving straight out of a bright sun", "low", NT),
 ("And think about what that does to a mind", MODERN, "tapping his temple, uneasy thinking face", "close", NT),
 ("over millions of years.", None, "a long horizontal timeline arrow stretching across", "wide", NT),
 ("You can watch the ground.", MODERN, "looking down carefully at the ground", "high", NT),
 ("You can climb away from the ground.", CAVE, "climbing up a bare tree trunk", "low", NT),
 ("But how do you defend against a place you can't even see?", MODERN, "shrugging helplessly while glancing up at the sky", "med", NT),
 ("You don't.", MODERN, "standing with a blank flat expression", "close", NT),
 ("You just get unlucky.", CAVE, "frozen under a spreading eagle-shaped shadow", "high", NT),
 ("So that's two suspects.", None, "an evidence board pinned with two mugshot cards", "med", tag("2 SUSPECTS")),
 ("The trees, and the sky.", None, "a split scene, a single tree on one side and open sky on the other", "wide", NT),
 ("Which only leaves the ground, the water, and the dark.", None, "three simple icons in a row, a patch of grass, a blue water drop, and a dark night crescent moon with a pair of glowing yellow eyes", "med", NT),
 ("And the next one has been eating people", None, "a still dark water surface with two eyes just breaking it", "close", NT),
 ("for two million years without changing a single thing.", None, "a long flat timeline with the same shape at both ends", "wide", tag("2 MILLION YEARS")),
 ("Meet the suspect that never had to evolve,", None, "two crocodile eyes and nostrils poking above the waterline", "close", tag("SUSPECT")),
 ("because it was already perfect.", None, "a cute flat-colour green crocodile with a little face, calm grin", "med", NT),
 ("At Olduvai Gorge in Tanzania,", None, "a simple map of Africa with a pin marking a gorge", "wide", tag("OLDUVAI")),
 ("one of the most famous fossil sites on Earth,", None, "a dusty dig site with small flags and a brush", "med", NT),
 ("researchers found ancient human bones covered in bite marks.", None, "a long bone with rows of tiny bite dents", "close", NT),
 ("Not cat marks. Not hyena marks.", None, "a cat icon and a hyena icon both crossed out with red X's", "med", NT),
 ("Crocodile marks.", None, "a bone with a wide crocodile bite pattern circled in red", "close", tag("CROCODILE")),
 ("And they named the animal that most likely made them.", None, "a name plate card beside a crocodile silhouette", "med", NT),
 ("Crocodylus anthropophagus.", None, "a cute flat-colour green crocodile with a little face and tiny horns", "med", tag("CROCODYLUS")),
 ("The name literally means the man-eating crocodile.", None, "a cute flat-colour crocodile licking its lips next to a small caveman", "wide", NT),
 ("It had strange little horns on the back of its head,", None, "a crocodile head with two small bumpy horns", "close", NT),
 ("and it shared the water with our ancestors", CAVE, "crouched at a riverbank while a crocodile floats nearby", "wide", NT),
 ("nearly two million years ago.", None, "a simple calendar page curling and yellowing with age", "med", NT),
 ("Here's why the crocodile is such a nasty suspect.", None, "a cute flat-colour crocodile with a little face grinning slyly", "close", NT),
 ("It never had to chase us.", None, "a cute flat-colour crocodile lying completely still and lazy", "med", NT),
 ("It just needed us to be thirsty.", CAVE, "with a dry mouth eyeing the water longingly", "med", NT),
 ("Every single day, our ancestors had to walk to the water", CAVE, "walking a worn path toward a river", "wide", NT),
 ("and drink.", CAVE, "kneeling and cupping water to drink", "close", NT),
 ("There's no skipping that.", MODERN, "shrugging with palms up, no way around it", "med", NT),
 ("No cleverness, no fire, no spear changes the fact that", CAVE, "holding a spear and a torch, looking useless", "med", NT),
 ("a body needs water.", None, "a single blue water drop glowing in the center", "close", NT),
 ("So the crocodile ran the perfect business. Zero overhead, zero effort.", None, "a cute flat-colour crocodile with a little face looking smug", "med", NT),
 ("Stay still. Wait at the one place your food can't avoid.", None, "a crocodile lurking motionless at a water's edge", "wide", NT),
 ("Let lunch walk right to you.", CAVE, "strolling unaware toward the waiting crocodile", "wide", NT),
 ("A lion has to clock in for every single meal.", None, "a cute flat-colour lion with a little face running and panting", "med", NT),
 ("A crocodile just needs patience, a good spot, and no commute.", None, "a relaxed crocodile resting at a prime shady riverbank", "med", NT),
 ("And here's the part that should give you chills.", MODERN, "hugging himself with a shivering nervous face", "close", NT),
 ("That prehistoric crocodile, ambushing humans at the water,", None, "a crocodile lunging up out of the water in ambush", "low", NT),
 ("two million years ago,", None, "a long timeline arrow pointing far into the past", "wide", tag("2 MILLION YEARS")),
 ("is doing the exact same thing today.", None, "the same crocodile in the same ambush pose, unchanged", "low", NT),
 ("The animal never got a software update. Same predator, version 1.0, still running two million years later.", None, "a cute flat-colour crocodile with a little face, identical twin beside it", "med", NT),
 ("We're still the ones walking up to the edge.", MODERN, "stepping toward a water's edge from above", "high", NT),
 ("So the trees, the sky, and the water", None, "three threat icons in a row, a tree, a cloud, and a wave", "med", NT),
 ("were all trying to kill you.", CAVE, "cowering as arrows point at him from all sides", "high", NT),
 ("You'd think that's a full lineup of predators already.", None, "a police lineup of cute flat-colour animals against a height chart", "wide", NT),
 ("But we've barely opened the file.", None, "a thick case file folder only just cracked open", "med", NT),
 ("Because ancient Africa wasn't just more dangerous than today.", None, "a simple map of Africa with warning marks scattered on it", "wide", NT),
 ("It was crowded.", None, "a savanna packed shoulder to shoulder with cute flat-colour predators", "wide", tag("CROWDED")),
 ("Try to picture the actual neighborhood our ancestors lived in.", MODERN, "closing his eyes with a thought bubble forming", "med", NT),
 ("Today, on a safari, you might see a few big predators,", None, "a safari jeep with just two distant animals on the plain", "wide", NT),
 ("spread thin across a huge landscape.", None, "a vast empty landscape with one small animal far away", "wide", NT),
 ("Back then, that same landscape was stacked with them.", None, "the same plain now crowded with many cute flat-colour predators", "wide", NT),
 ("And several were bigger than anything alive now.", None, "a huge animal silhouette towering over a small modern one", "low", NT),
 ("Take the hyena.", None, "a cute flat-colour spotted hyena with a little face", "med", tag("HYENA")),
 ("You're picturing that hunched little scavenger giggling in a nature documentary.", None, "a small cute hyena giggling with its tongue out", "close", NT),
 ("Forget that one.", MODERN, "waving a hand dismissively, brushing it away", "med", NT),
 ("There was a giant hyena, Pachycrocuta,", None, "a huge cute flat-colour hyena with a little face standing tall", "low", tag("PACHYCROCUTA")),
 ("roughly the size of a lioness.", None, "the giant hyena standing next to a lioness for scale", "wide", NT),
 ("Its jaws could crush solid bone,", None, "hyena jaws clamping down on a thick bone", "close", NT),
 ("the way you crush a breadstick.", MODERN, "snapping a breadstick in half with one hand", "close", NT),
 ("It didn't leave leftovers.", None, "a hyena beside a completely empty licked-clean plate", "med", NT),
 ("It ate the leftovers, bones included.", None, "a cute flat-colour hyena chewing on a pile of bones", "med", NT),
 ("Which is kind of rude, because it means it destroyed the evidence.", None, "a hyena beside an empty magnifying glass, no clues left", "med", NT),
 ("Some of our ancestors never got a fossil.", CAVE, "standing on bare empty ground, no fossil outline", "high", NT),
 ("They got digested.", None, "a round-bellied cute flat-colour hyena patting its full stomach", "close", NT),
 ("And it did not hunt alone.", None, "a pack of cute flat-colour hyenas standing together", "wide", NT),
 ("It shared the map with several kinds of saber-toothed cats.", None, "a cute flat-colour saber-toothed cat with a little face and long fangs", "med", tag("SABER-TOOTH")),
 ("Not one. Several.", None, "three saber-toothed cats lined up side by side", "wide", NT),
 ("At the same time, in the same place.", None, "a savanna map dotted with many predator markers", "wide", NT),
 ("So an ancient human crossing the savanna,", CAVE, "walking across a wide open grassland", "wide", NT),
 ("wasn't dodging a predator,", CAVE, "glancing around with a nervous face", "med", NT),
 ("they were walking through a room full of them.", CAVE, "surrounded on all sides by cute flat-colour predators", "high", NT),
 ("Now, so far, all of our suspects are big, obvious, and terrifying.", None, "three cute flat-colour predators, a leopard, an eagle and a crocodile, lined up", "wide", NT),
 ("But the case file has a twist.", None, "a flat manila case file folder with a big red question mark on it", "med", tag("TWIST")),
 ("Because one of the scariest names on this whole list might actually be innocent.", None, "a cute flat-colour saber-toothed cat with two fangs and a little worried face", "close", tag("INNOCENT?")),
 ("For years, there was a famous theory about a specific saber-toothed cat", None, "a cute flat-colour saber-toothed cat with two long fangs and a little face", "med", NT),
 ("called Dinofelis.", None, "a cute flat-colour saber-toothed cat with two fangs, a red name card beside it", "close", tag("DINOFELIS")),
 ("The idea was chilling.", None, "a cute flat-colour saber-toothed cat with a little face, cold blue tint around it", "med", NT),
 ("Some researchers suggested Dinofelis might have been a specialist.", None, "a cute flat-colour saber-toothed cat with a little face, a small red target icon", "med", NT),
 ("A cat that actually preferred hunting us.", CAVE, "looking scared as a saber-tooth cat eyes him", "wide", NT),
 ("A predator that looked at early humans and thought, that.", None, "a cute flat-colour saber-toothed cat with a little face, eyes locked forward", "close", NT),
 ("That's my food.", CAVE, "gulping nervously, a red arrow pointing at him", "med", NT),
 ("It's a fantastic villain.", None, "a cute flat-colour saber-toothed cat with two fangs and a tiny villain cape", "med", NT),
 ("It shows up in books and documentaries everywhere.", None, "a cute flat-colour saber-toothed cat printed on a little open book and a TV screen", "wide", NT),
 ("But here's where being honest matters more than being scary.", None, "a flat balance scale, one side a heart, one side a scary mask", "med", NT),
 ("When scientists studied the chemistry locked inside Dinofelis fossils,", None, "a flat fossil skull of a saber-tooth cat with a magnifying glass over it", "close", NT),
 ("the chemistry that reveals what an animal actually ate,", None, "a flat lab flask with tiny bubbles and a little food icon inside", "med", NT),
 ("the specialist story started to fall apart.", None, "a flat paper labelled with a cracked red line splitting it in two", "med", NT),
 ("The evidence suggests it mostly ate grazing animals, like antelope,", None, "a cute flat-colour antelope with little horns and a little face grazing on flat grass", "wide", tag("ANTELOPE")),
 ("not a steady diet of us.", CAVE, "with a little face, a big red X crossing him out", "med", NT),
 ("So Dinofelis probably wasn't a human-hunting supervillain.", None, "a cute flat-colour saber-toothed cat with a little face, a tiny villain cape falling off", "med", tag("DINOFELIS")),
 ("It was more like a big cat that would happily eat you if you were convenient,", None, "a cute flat-colour saber-toothed cat with a little face licking its lips lazily", "med", NT),
 ("but wasn't building its whole life around it.", None, "a cute flat-colour saber-toothed cat with a little face lounging, eyes half-closed", "low", NT),
 ("Which, honestly, is not that comforting either.", CAVE, "with a flat unimpressed face and a small sweat drop", "close", NT),
 ("And this is the thing about the entire case.", None, "a flat manila case file folder stuffed with little papers", "med", NT),
 ("It keeps changing.", None, "a flat case file with little papers swirling and swapping around it", "med", NT),
 ("Every few years, a new fossil or a new method rewrites who the real culprit was.", None, "a flat fossil bone and a little pencil rewriting a red suspect card", "wide", NT),
 ("The leopard is still the clearest.", None, "a cute flat-colour leopard with spots and a little face, a small check mark", "med", NT),
 ("The eagle is still the biggest surprise.", None, "a cute flat-colour eagle with big wings and a little face, a small exclamation", "high", NT),
 ("But the exact ranking keeps shifting.", None, "a flat ranking list with little arrows moving items up and down", "med", NT),
 ("Now step back and look at all of it at once.", CAVE, "from behind facing a wall of little predator icons", "wide", NT),
 ("Leopards in the trees.", None, "a cute flat-colour leopard with a little face crouched on a flat tree branch", "high", NT),
 ("Eagles in the sky.", None, "a cute flat-colour eagle with a little face soaring in an empty sky", "wide", NT),
 ("Crocodiles in the water.", None, "a cute flat-colour crocodile with a little face, only eyes above flat water", "low", NT),
 ("Giant hyenas and saber-tooths on the open ground.", None, "a cute flat-colour hyena and a saber-tooth cat with little faces on flat ground", "wide", NT),
 ("That's not bad luck.", CAVE, "shrugging, a broken dice nearby", "med", NT),
 ("That's a species that spent a very long time as food.", CAVE, "with a little face, a small red dinner-plate label on him", "med", NT),
 ("Which raises a genuinely uncomfortable question.", None, "a big flat red question mark casting a little shadow", "med", NT),
 ("If everything out there was hunting us, how are you here, watching this,", MODERN, "sitting relaxed on a flat couch looking at us", "med", NT),
 ("holding a snack, completely relaxed?", MODERN, "holding a little snack bowl with a calm face", "close", NT),
 ("Hold that thought.", MODERN, "raising one finger with a little thoughtful face", "med", NT),
 ("Because first, there's the suspect promised at the very start.", None, "a flat red suspect card with a big question mark still hidden", "med", NT),
 ("The small one. The old one.", None, "a small flat silhouette card with a little ancient dusty label", "close", NT),
 ("The one still hiding inside your head.", MODERN, "side view, a little glow inside his head outline", "close", NT),
 ("Rewind. Way back.", None, "a flat rewind arrow icon spinning backward over a little timeline", "med", tag("REWIND")),
 ("Long before leopards and eagles were the main problem.", None, "a faded flat leopard and eagle icon shrinking into the distance", "wide", NT),
 ("Before we were anything close to human,", None, "a flat empty evolution line with the human end faded out", "wide", NT),
 ("our tiny ancestors were small mammals living in the trees.", None, "a cute flat-colour small mammal ancestor with big eyes and a little face on a branch", "high", NT),
 ("And the deadliest thing in their world wasn't big at all.", None, "a cute flat-colour small mammal ancestor with a little face peering down nervously", "close", NT),
 ("It was the snake.", None, "a cute green coiled snake with a little face resting in flat grass", "med", tag("SNAKE")),
 ("In 2006, an anthropologist named Lynne Isbell proposed something wild.", None, "a flat portrait card of a scientist with glasses and a red name label", "med", tag("ISBELL")),
 ("She argued that snakes were the first serious predator of our primate ancestors,", None, "a cute green coiled snake with a little face facing a small primate ancestor", "med", NT),
 ("tens of millions of years ago.", None, "a flat dusty timeline arrow stretching far back, a small year label", "wide", NT),
 ("The very first thing that hunted our line wasn't a lion or a bear.", None, "a flat faded lion and bear icon with a big red X over both", "med", NT),
 ("It was a thing with no legs that you could step on in the dark.", None, "a cute green snake with a little face half-hidden in flat dark grass", "low", NT),
 ("But her idea goes much further than danger.", None, "a flat idea lightbulb with a little snake curled inside it", "med", NT),
 ("Isbell suggested that the constant threat of snakes actually shaped our eyes and our brains.", None, "a flat big eye icon and a little brain linked by a curling green snake", "med", tag("ISBELL")),
 ("The primates who survived were the ones who could spot a snake,", None, "a cute flat-colour small primate ancestor with big alert eyes and a little face", "close", NT),
 ("frozen and hidden, a split second faster than the rest.", None, "a cute green snake with a little face frozen still in flat grass, a small clock", "med", NT),
 ("So over millions of years, evolution turned the dial on our vision all the way up.", None, "a flat dial knob turned to max beside a big bright eye icon", "med", NT),
 ("That sharp, forward-facing, detail-obsessed eyesight.", None, "a big flat forward-facing eye with sharp little detail lines around it", "close", NT),
 ("The visual brain that lets you read these words.", None, "a flat little brain with a small glowing eye linked to tiny text lines", "med", NT),
 ("Part of the reason it's so good might be snakes.", None, "a big bright eye icon with a small green snake reflected in it", "close", tag("SNAKE")),
 ("Think about that for a second.", MODERN, "with a little thoughtful face, hand on chin", "med", NT),
 ("You may be able to see the world this clearly", MODERN, "with wide clear eyes looking around brightly", "close", NT),
 ("because a hundred million years of your ancestors were terrified of stepping on a noodle.", None, "a cute green wavy snake with a little face looking exactly like a noodle", "med", NT),
 ("And there's a strange clue that backs this up.", None, "a flat magnifying glass over a little green snake clue card", "med", NT),
 ("There's a kind of lemur on Madagascar", None, "a cute flat-colour lemur with big round eyes, a striped tail and a little face", "med", tag("LEMUR")),
 ("that evolved on an island with almost no dangerous snakes.", None, "a flat little island shape with a green snake crossed out by a red X", "wide", NT),
 ("And compared to other primates, its snake-detection wiring is weaker.", None, "a cute flat-colour lemur with a little face beside a dim, faint brain icon", "med", NT),
 ("Different threat, different brain.", None, "two flat little brain icons side by side, one bright one dim", "med", NT),
 ("Now here's how you can feel this theory in your own body, right now.", MODERN, "with a little curious face, hand on his chest", "med", NT),
 ("Have you ever jumped at a garden hose?", MODERN, "leaping back from a flat coiled garden hose", "wide", NT),
 ("A curved stick? A crack in the pavement?", MODERN, "flinching at a flat curved stick on the ground", "med", NT),
 ("That jolt of fear, before you even finished looking, that's not silly.", MODERN, "with a startled face and little shock lines", "close", NT),
 ("That's a survival system older than the human face,", None, "a flat dusty ancient gear icon labelled with a tiny old timeline", "med", NT),
 ("still firing inside you today.", MODERN, "side view, a little spark glowing inside his head", "close", NT),
 ("The snake never went extinct.", None, "a cute flat-colour snake with a little face coiling quietly", "med", tag("SNAKE")),
 ("It just moved into your nervous system and stayed.", MODERN, "touching the back of his neck, uneasy", "close", NT),
 ("So which one wins?", MODERN, "shrugging, asking who won", "med", NT),
 ("Which animal hunted us the most?", None, "a row of little animal faces lined up like suspects", "wide", NT),
 ("We're almost ready to give a verdict.", MODERN, "holding up a hand, almost there", "med", NT),
 ("But there's one honest thing we have to say first.", MODERN, "leaning in, serious honest look", "close", NT),
 ("Because none of this is safely in the past.", None, "a red warning card glowing in the dark", "med", NT),
 ("Here's the uncomfortable footnote.", None, "a small red index card that reads FOOTNOTE", "close", tag("FOOTNOTE")),
 ("You're not actually off the menu.", MODERN, "glancing over his shoulder, nervous", "med", NT),
 ("Not completely.", MODERN, "giving a tight worried shake of the head", "close", NT),
 ("In parts of the world today, crocodiles still kill", None, "a cute flat-colour crocodile with a little face lurking in water", "wide", NT),
 ("hundreds of people every year.", None, "a cute flat-colour crocodile with a little face, eyes just above the water", "low", tag("CROCODILE")),
 ("Leopards and tigers still take the occasional person", None, "a cute flat-colour leopard with a little face creeping low", "med", NT),
 ("who wanders too far, alone.", MODERN, "walking off alone into the shadows", "wide", NT),
 ("There were the Tsavo lions in Kenya,", None, "two cute flat-colour lions with little faces prowling together", "wide", tag("TSAVO")),
 ("a pair that famously hunted workers", None, "two cute flat-colour lions with little faces near a small railway camp", "med", NT),
 ("at a railway camp in the eighteen nineties.", None, "a simple old railway tent camp under a dark sky", "wide", NT),
 ("There was a single tiger in India,", None, "a cute flat-colour tiger with a little face standing alone", "med", NT),
 ("the Champawat tiger, blamed for a staggering number", None, "a cute flat-colour tiger with a little face, red card behind it", "close", tag("CHAMPAWAT")),
 ("of human deaths before it was finally stopped.", None, "a cute flat-colour tiger with a little face lowering its head", "med", NT),
 ("So when we say we became the apex predator,", MODERN, "standing tall, cautious pride", "med", NT),
 ("we don't mean we became untouchable.", MODERN, "waving off the idea, humble", "close", NT),
 ("We mean something changed so completely", CAVE, "looking up, dawning realisation", "med", NT),
 ("that a single human, alone and unarmed,", CAVE, "standing alone with empty hands", "wide", NT),
 ("went from ordinary prey to a rare exception.", CAVE, "straightening up, from scared to standing firm", "close", NT),
 ("So what changed?", MODERN, "spreading his hands, asking", "med", NT),
 ("How does a walking lunchbox that could scream", MODERN, "pointing at himself, sheepish grin", "med", NT),
 ("end up sitting on top of the food chain?", None, "a simple food-chain PYRAMID with a stickman standing proudly on the very top", "high", NT),
 ("The answer isn't fangs.", MODERN, "baring his flat harmless teeth", "close", NT),
 ("We never grew any.", MODERN, "shrugging with a small smile", "med", NT),
 ("It's not claws or speed.", MODERN, "looking at his soft empty hands", "close", NT),
 ("You're still slower than almost everything that ever wanted to eat you.", MODERN, "jogging slowly, out of breath", "wide", NT),
 ("We won with three things.", CAVE, "holding up three fingers, proud", "med", tag("THREE THINGS")),
 ("And you still carry all three.", MODERN, "nodding, hand on chest", "close", NT),
 ("First. Fire.", None, "a bright cute orange campfire pushing back the dark", "med", tag("FIRE")),
 ("At a site called Wonderwerk Cave in South Africa,", None, "a simple cave mouth with a small warm fire inside", "wide", tag("WONDERWERK")),
 ("there's evidence of controlled fire around a million years ago.", CAVE, "kneeling and feeding a small campfire, careful", "med", NT),
 ("Fire did something no claw ever could.", None, "a bright orange campfire glowing warmly", "close", NT),
 ("It pushed the dark back.", None, "a ring of orange firelight shoving the black night outward", "wide", NT),
 ("A leopard hunts by night, in the shadows.", None, "a cute flat-colour leopard with a little face hidden in dark shadows", "low", NT),
 ("But a ring of fire took the night,", CAVE, "gathered inside a bright ring of firelight", "wide", NT),
 ("the predator's home turf, and made it ours.", CAVE, "standing confident inside the fire ring at night", "med", NT),
 ("For the first time, the thing in the dark", None, "a cute flat-colour leopard with a little face shrinking from the light", "med", NT),
 ("was the one that had to be nervous.", None, "a cute flat-colour leopard with a little face, wide worried eyes", "close", NT),
 ("Second. Weapons that kill from a distance.", None, "a simple wooden throwing spear flying through the air", "med", tag("SPEARS")),
 ("In a coal mine in Germany, at a place called Schoningen,", None, "a dark mine shaft with a spear resting in the dirt", "wide", tag("SCHONINGEN")),
 ("archaeologists found wooden throwing spears", None, "several polished wooden spears laid out in a row", "med", NT),
 ("about three hundred thousand years old.", None, "an old wooden spear with a small age tag on it", "close", NT),
 ("Beautifully made. Balanced. Built to be thrown.", CAVE, "balancing a spear on one finger, admiring it", "med", NT),
 ("That was the moment the rules broke.", None, "a wooden spear snapping an invisible line, dramatic", "close", NT),
 ("Now the small, slow ape could hurt you", CAVE, "drawing back a spear, determined", "med", NT),
 ("without ever letting you get close.", CAVE, "hurling a spear across a wide gap", "wide", NT),
 ("Third, and biggest of all. Each other.", CAVE, "a group of ancestors standing shoulder to shoulder together, brave", "wide", tag("THE GROUP")),
 ("One human is a snack.", CAVE, "one lone ancestor looking worried", "med", NT),
 ("But thirty humans, standing together,", CAVE, "a tight group of ancestors standing shoulder to shoulder", "wide", NT),
 ("with fire and spears and a habit", CAVE, "a group of ancestors holding fire and spears in a ring", "med", NT),
 ("of guarding each other's backs,", CAVE, "a group of ancestors standing back to back, watchful and united", "med", NT),
 ("is not a meal anymore.", None, "a red card that reads NOT A MEAL", "close", NT),
 ("It's the single scariest thing on the savanna.", CAVE, "a united group of ancestors looming confident on the plain", "wide", NT),
 ("Fire. Distance. The group.", None, "three small icons, a flame, a spear, a group of figures", "med", NT),
 ("Not strength. Cooperation.", CAVE, "a group of ancestors clasping hands together, teamwork", "close", NT),
 ("And that's what finally lets us answer the question.", MODERN, "nodding, ready to give the verdict", "med", NT),
 ("So, what animal hunted ancient humans the most?", None, "a lineup of little animal faces, a verdict card above", "wide", NT),
 ("If you want the honest answer,", MODERN, "holding up a finger, honest look", "med", NT),
 ("it depends on what you mean by most.", None, "a red card that reads MOST with a question mark", "close", NT),
 ("For the clearest evidence, the leopard wins.", None, "a cute flat-colour leopard with a little face, winner ribbon", "med", tag("LEOPARD")),
 ("It left our skulls with fang marks", None, "a simple skull with two neat fang holes in it", "close", NT),
 ("that fit like a key in a lock.", None, "two fang holes lining up with a leopard's teeth like a key", "close", NT),
 ("For the biggest shock, it's the eagle.", None, "a cute flat-colour eagle with a little face swooping down", "high", tag("EAGLE")),
 ("Death that fell out of the sky onto a child.", None, "a cute flat-colour eagle with a little face diving from above", "low", NT),
 ("For sheer patience, the crocodile.", None, "a cute flat-colour crocodile with a little face waiting still in water", "med", tag("CROCODILE")),
 ("Two million years of the same trap, still set today.", None, "a cute flat-colour crocodile with a little face, eyes above calm water", "wide", NT),
 ("But for the one that changed us the most,", MODERN, "pausing, thoughtful", "close", NT),
 ("it was never the biggest suspect on the board.", None, "a suspect board with the smallest silhouette circled", "med", NT),
 ("It was the snake.", None, "a cute flat-colour snake with a little face raising its head", "close", tag("SNAKE")),
 ("It didn't just hunt our bodies.", None, "a cute flat-colour snake with a little face coiling slowly", "med", NT),
 ("It shaped our eyes, our fear,", MODERN, "his wide eyes reflecting a snake shape", "close", NT),
 ("and the way you see the world in this exact moment.", MODERN, "staring straight ahead, quietly stunned", "close", NT),
 ("And here's the part worth sitting with.", MODERN, "sitting down calmly to reflect", "med", NT),
 ("Every one of those predators lost.", None, "a row of little animal faces with soft X marks", "wide", NT),
 ("Not because we were stronger.", CAVE, "flexing a thin arm, sheepish", "close", NT),
 ("We weren't.", CAVE, "shrugging, arms limp", "med", NT),
 ("But because a frightened, hairless, snack-sized ape", CAVE, "hugging himself in the dark, worried", "med", NT),
 ("learned to make fire, to throw,", CAVE, "lighting fire and throwing a spear, growing bold", "med", NT),
 ("and to stand shoulder to shoulder with others.", CAVE, "a group of ancestors standing shoulder to shoulder together, brave", "wide", tag("THE GROUP")),
 ("You come from an unbroken line of survivors.", MODERN, "at the front of a long line of ancestors", "wide", NT),
 ("Every single one of your ancestors lived long enough,", CAVE, "a chain of ancestors passing a small flame down the line", "wide", NT),
 ("in a world full of teeth, to pass you on.", MODERN, "receiving the little flame, moved", "close", NT),
 ("So that fear in the dark,", MODERN, "his eyes darting in darkness", "close", NT),
 ("that flinch at a shape in the grass,", MODERN, "flinching at a shadow in tall grass", "med", NT),
 ("that urge to check the corner of the room,", MODERN, "glancing warily at a dark corner", "med", NT),
 ("that's not weakness.", MODERN, "shaking his head, firm", "close", NT),
 ("That's the survival system that got you here.", MODERN, "with a soft glowing outline of instinct", "close", NT),
 ("It's still running.", MODERN, "alert, a faint pulse around him", "med", NT),
 ("And it's yours.", MODERN, "placing a hand on his own chest", "close", NT),
 ("So the next time you walk into a dark forest", MODERN, "stepping into a dark forest", "wide", NT),
 ("and feel the hair rise on the back of your neck,", MODERN, "touching his neck as hair rises", "close", NT),
 ("don't laugh it off.", MODERN, "stopping, taking it seriously", "med", NT),
 ("Something in you remembers being the meal.", CAVE, "a faint scared ancestor shape", "med", NT),
 ("And something in you remembers winning anyway.", CAVE, "a faint proud ancestor shape standing tall", "close", NT),
 ("That's you. That's what you are.", MODERN, "standing proud, that's-you moment, slight smile", "close", NT),
 ("The most dangerous thing in the room,", MODERN, "standing calm and quietly powerful", "low", NT),
 ("standing on the shoulders of everything that was ever afraid.", MODERN, "standing proudly on top of a broad low mound made of many faded overlapping ancestor silhouettes fading down into the ground", "wide", NT),
 ("If you made it all the way to the end,", MODERN, "smiling warmly at the viewer", "close", NT),
 ("tell me one thing in the comments.", MODERN, "pointing down at a comment box, inviting", "med", tag("COMMENT")),
 ("What still makes you flinch,", MODERN, "tilting his head, asking the viewer", "close", NT),
 ("even though you know you're safe?", MODERN, "pointing at the viewer with a knowing smile", "med", NT),
]

def build(shot, ch, act, fr, txt):
    subj = f"{ch} {act}" if ch else act
    return " ".join(f"{STYLE} {subj}. Framing: {F[fr]} {CONSIST} {SCENE} {txt} {NEG}".split())

if __name__ == "__main__":
    # File 1: CHỈ prompt (số + prompt) — copy dán thẳng vào gen ảnh, KHÔNG dính lời thoại
    with open("PROMPTS_FULL.txt", "w") as pf:
        for i, s in enumerate(SHOTS, 1):
            pf.write(f"{i:03d}.\n{build(*s)}\n\n")
    # File 2: shot-lines (số + câu narration) — để nạp TTS / sync, KHÔNG dùng để gen ảnh
    with open("SHOTLINES_FULL.txt", "w") as sf:
        for i, s in enumerate(SHOTS, 1):
            sf.write(f"{s[0]}\n")
    print(f"✅ {len(SHOTS)} prompt → PROMPTS_FULL.txt (sạch, không lời thoại)")
    print(f"✅ {len(SHOTS)} shot-line → SHOTLINES_FULL.txt (cho TTS)")
