# -*- coding: utf-8 -*-
"""V19 MOON — "Why Were Some Nights Deadlier for Ancient Humans?"

(line, kind, subj, text, bg, face)

kind : SCENE_A ancient | SCENE_W woman | GROUP nhom | SCENE_N khong nguoi | CARD
bg   : dusk_grey dusk_water moonlit night_open night_dark cold_night fire_ring fire_edge
       savanna_day dry_plain cave_warm rain_day dark_card white
face : flat shock tired worry scared happy asleep dumb curious sad

1.686 tu / ~9:30 -> nhip 2,0-2,5 giay/shot -> ~230-250 shot.
CASTING: KHONG CO NHAN VAT HIEN DAI. Lane "ve BAN" da bo 10/08.
"""

SHOTS = [

# ═════════════════ HOOK — 14 shot ═════════════════
("You are walking down to the water","SCENE_A","he walks away from the viewer down a slope toward a strip of dark water, seen from behind","no text","dusk_water","flat"),
("and the sun has just gone.","SCENE_N","a flat colourless grey sky over a solid black treeline, the last pale light along the horizon","no text","dusk_grey","flat"),
("It is that flat grey half hour","SCENE_N","flat open ground under a colourless grey sky just after sunset, the ground still readable and the treeline already one solid black shape","a label \"HALF AN HOUR\"","dusk_grey","flat"),
("where the ground is still visible","SCENE_N","a patch of dim olive ground with two or three small stones clearly drawn on it","no text","dusk_grey","flat"),
("and the treeline is not.","SCENE_N","a wide view of flat grey dusk over still water, the whole treeline now one unbroken solid black shape with no branches and no gaps inside it, the pale ground still faintly visible in front of it","no text","dusk_grey","flat"),
("The camp is forty steps behind you.","SCENE_N","seen from above, a small ring of stones with a low fire, and a thin dotted line leading away from it","a label \"40 STEPS\"","dry_plain","flat"),
("You have made this walk a thousand times.","SCENE_A","he walks along a worn narrow dirt path through low grass, relaxed, one hand loose at his side","no text","dusk_grey","flat"),
("You made it ten nights ago","SCENE_A","he walks along a worn narrow dirt path under a bright full white moon, the ground clearly lit, a sharp black shadow behind him","no text","moonlit","flat"),
("and thought nothing of it.","SCENE_A","close on his face under the full moon, eyelids half down, completely unbothered","no text","moonlit","flat"),
("Tonight the moon will not come up for another four hours.","SCENE_N","an empty dark sky with a thin dotted circle low near the horizon showing where the moon is not yet","a label \"4 HOURS\"","night_dark","flat"),
("That is the only thing about this evening that has changed.","CARD","two identical small framed drawings side by side, each showing one narrow winding dirt path between low grass, the left drawing with a plain white moon in the sky above it, the right drawing with an empty sky and no moon","no text","white","flat"),
("And in a place with lions in it,","SCENE_N","one lion drawn in flat solid tawny colour lying low in dim grass, only the head and shoulders visible","no text","dusk_grey","flat"),
("people get killed on that walk","SCENE_A","he pauses mid step and looks back over his shoulder toward the line of trees","no text","dusk_grey","shock"),
("at several times the rate they do when the moon is up.","CARD","two simple vertical bars of different heights, the taller one much taller, no numbers","a label \"MOON UP\" under the short bar and \"NO MOON\" under the tall one","white","flat"),

# ═════════════════ CH1 — SO GHI 21 NAM — 26 shot ═════════════════
("That number is not a guess about the past.","CARD","a plain drawn scroll with a big red X through it","no text","white","flat"),
("It comes out of twenty one years of paperwork.","CARD","a tall stack of plain paper files drawn in flat grey","a label \"21 YEARS\"","white","flat"),
("In southeastern Tanzania,","SCENE_N","a plain outline map of the African continent with one small area near the southeast of Tanzania filled solid","a label \"TANZANIA\"","white","flat"),
("more than a thousand people were attacked by lions.","GROUP","a large loose crowd of small plain white stick figures filling the frame","a label \"1,000+\"","white","flat"),
("Four hundred and fifty of those attacks","CARD","a large crowd of many small identical figures drawn in rows, with one smaller block of them circled in a heavy black marker ring","a label \"450 ATTACKS\"","white","flat"),
("were recorded in enough detail to study.","CARD","one open paper file with neat handwritten rows drawn as plain lines","no text","white","flat"),
("And when the times were laid out,","CARD","a plain horizontal clock line running from a small sun symbol to a small moon symbol","no text","white","flat"),
("they did not spread evenly across the night.","CARD","one long horizontal line with many short vertical tally marks along it, the marks packed densely at the left end and thinning to almost none at the right end","no text","white","flat"),
("Nearly sixty percent of the victims were attacked","CARD","a simple bar sitting over one narrow section of that clock line, much taller than everything else","a label \"60%\"","white","flat"),
("between six in the evening and quarter to ten.","CARD","one long horizontal line with two vertical marks standing on it and the section between those two marks filled solid black","a label \"6:00 PM\" and \"9:45 PM\"","white","flat"),
("Not at midnight.","SCENE_N","empty open ground under a deep black sky with one small plain moon high overhead and nothing moving anywhere","no text","night_dark","flat"),
("Not at three in the morning.","SCENE_N","empty flat ground under a black sky, the faintest pale band along the very bottom of the horizon, nothing else","no text","night_dark","flat"),
("During dinner.","GROUP","three people sitting close together around a low fire, one holding food toward the flames","no text","fire_ring","flat"),
("Over two thirds of those attacks were fatal,","CARD","a row of small identical marks with two out of every three shaded solid black","a label \"2 IN 3\"","white","flat"),
("and the victims were eaten.","SCENE_N","one lion drawn in flat tawny colour walking away from the viewer into flat blackness","no text","night_dark","flat"),
("Now, those are lions in living memory,","SCENE_N","one lion standing in dim grass beside a plain wooden fence post","no text","dusk_grey","flat"),
("in villages with roads and clinics.","SCENE_N","two very simple square huts made of plain black lines on flat tan ground, and one straight dirt track running past them","no text","dry_plain","flat"),
("They are not the animals that hunted people a hundred thousand years ago.","SCENE_N","one lion standing on dry open plain in plain daylight, drawn large and calm","a label \"100,000 YEARS\"","dry_plain","flat"),
("But the shape of an evening has not moved.","SCENE_N","a low sun sitting right on the horizon over flat ground, the light going flat and grey","no text","dusk_grey","flat"),
("The light still goes in the same order it always went.","SCENE_N","the same flat ground with the sun now gone and only a pale strip left along the horizon","no text","dusk_grey","flat"),
("And wherever people camp,","SCENE_N","seen from above, a small ring of stones on open ground","no text","dry_plain","flat"),
("something outside the camp is still worth walking to before sleeping.","SCENE_N","seen from directly above: a small ring of stones on flat tan ground, and one thin dotted line running from it out to a narrow strip of dark water","no text","dry_plain","flat"),
("And the thing waiting past the treeline","SCENE_N","two small yellow eyes low inside the solid black treeline, nothing else visible","no text","dusk_grey","flat"),
("has always seen better in the dark than the people have.","SCENE_N","two small bright yellow eyes low inside a solid black treeline, everything else unreadable","no text","night_dark","flat"),
("So the danger was never the night.","SCENE_N","calm open ground under a deep blue night sky full of small white stars, nothing threatening in the frame","no text","night_open","flat"),
("It was one particular slice of it.","CARD","a plain circle divided into segments with one narrow segment shaded solid","no text","white","flat"),

# ═════════════════ CH2 — LOAI THU HAI, CUNG KHUNG GIO — 30 shot ═════════════════
("Further south, in Eswatini,","SCENE_N","a plain outline map of southern Africa with one very small country filled solid","a label \"ESWATINI\"","white","flat"),
("a different team spent two years counting something else.","CARD","two tall stacks of plain paper sheets standing side by side on a plain background, with one simple bracket drawn underneath both","a label \"2 YEARS\"","white","flat"),
("Not lions.","SCENE_N","one lion lying down in dim grass with its head turned away from the frame","no text","dusk_grey","flat"),
("Snakes.","SCENE_N","one snake in flat olive green coiled low on flat tan ground, small simple face, drawn in far more detail than a person would be","no text","dry_plain","flat"),
("They recorded where people were bitten, and when.","CARD","a plain outline of a standing human body with four small dots marked on the lower legs and feet","no text","white","flat"),
("Thirty percent of the patients were bitten","CARD","a row of ten small stick figures with three of them shaded solid","a label \"30%\"","white","flat"),
("between six in the evening and ten at night.","CARD","a horizontal clock line with the section between two marks shaded solid","a label \"6:00 PM\" and \"10:00 PM\"","white","flat"),
("Six to ten.","CARD","one short thick solid black horizontal bar alone in the middle of a plain background, nothing else drawn","a label \"6 TO 10\"","white","flat"),
("The same four hours,","CARD","two identical long horizontal clock lines stacked one above the other, each with its middle section filled solid black","no text","white","flat"),
("in a different country,","CARD","two small country outlines side by side with a plain arrow between them","no text","white","flat"),
("by an animal that hunts nothing like a lion does.","SCENE_N","one olive snake coiled low in dry pale grass, almost hidden by it","no text","dry_plain","flat"),
("Sixty percent of all the bites","CARD","a plain outline of a human body with the lower legs and feet shaded solid","a label \"60%\"","white","flat"),
("were to the foot, the ankle, the heel or the toe.","SCENE_A","he steps forward barefoot through low dark grass, the frame low near the ground so his feet are the largest thing in it","no text","night_dark","flat"),
("Not a hand reaching into somewhere it should not.","SCENE_A","he stands upright with both hands held plainly at his sides, touching nothing","no text","night_dark","flat"),
("A foot, going somewhere.","SCENE_A","close on his bare white foot mid stride just above dim ground, the rest of him out of frame above","no text","dusk_grey","flat"),
("Twenty seven percent of the people bitten","CARD","a row of ten small stick figures with just under three of them shaded solid","a label \"27%\"","white","flat"),
("were walking when it happened.","SCENE_A","he walks steadily across dim ground, mid stride, looking ahead and not down","no text","dusk_grey","flat"),
("A lion and a snake have close to nothing in common.","SCENE_N","one tawny lion on one side of dry open plain and one olive snake coiled on the other, far apart, both drawn plainly","no text","dry_plain","flat"),
("They hunt differently,","SCENE_N","a lion crouched flat and low behind a small bush","no text","dusk_grey","flat"),
("they sense the world differently,","SCENE_N","a snake with its tongue out, three small curved lines drawn in the air in front of it","no text","dry_plain","flat"),
("and they want completely different things from a person.","CARD","a lion head and a snake head with one plain arrow from each, pointing to two different small symbols","no text","white","flat"),
("Two research teams, two countries,","CARD","two separate small stacks of paper files with a wide gap between them","no text","white","flat"),
("more than ten years apart,","CARD","a plain timeline with two marks and a measured gap drawn between them","a label \"10+ YEARS\"","white","flat"),
("both landed on the same four hours.","CARD","two arrows coming in from opposite sides and meeting on one shaded section of a clock line","no text","white","flat"),
("Which means those four hours were never really about the animal.","SCENE_N","empty dry plain in the last of the light, no animal anywhere in the frame, only grass and one low bush","no text","dusk_grey","flat"),
("The animal is whatever happens to live nearby.","SCENE_N","one crocodile resting at the edge of still water in flat daylight","no text","savanna_day","flat"),
("The constant is a person on foot, outside,","SCENE_A","he walks alone across empty dim ground, small in a wide frame","no text","dusk_grey","flat"),
("in the stretch of evening where the light has gone and the day's work has not.","SCENE_A","he walks carrying a simple water vessel, the sky behind him almost fully grey","no text","dusk_grey","tired"),
("Which still leaves the part that has not been explained.","SCENE_A","he stands still in flat grey dusk, one hand half raised, looking off toward the treeline","no text","dusk_grey","curious"),
("Every evening has those four hours in it.","CARD","a row of seven identical long horizontal clock lines, each with its middle section filled solid black","no text","white","flat"),
("They are not all equally lethal, and the difference is not small.","CARD","a row of seven identical clock lines with one plain vertical bar rising above each line, the seven bars at very different heights","no text","white","flat"),
("Nothing on the ground changes between one evening and the next.","SCENE_N","one flat patch of dim olive ground with three small grey stones on it, drawn plainly, nothing else in the frame","no text","dusk_grey","flat"),
("Something overhead does.","SCENE_N","an empty dark sky with one thin pale crescent low in it","no text","night_dark","flat"),

# ═════════════════ CH3 — MAT TRANG — 30 shot ═════════════════
("Here is what a full moon actually does.","SCENE_N","one plain white circle for a full moon on a flat deep blue sky, nothing else in frame","no text","moonlit","flat"),
("It comes up as the sun goes down.","SCENE_N","one low sun sitting on the horizon on one side of the frame and one plain white moon rising on the other side, both at the same height","no text","dusk_grey","flat"),
("It is overhead and bright","SCENE_N","the full moon high in the frame with pale grey-blue ground clearly visible below it","no text","moonlit","flat"),
("through exactly the hours when people are still outside finishing things.","GROUP","three people moving about on ground that is clearly lit, one carrying a bundle, one bending down","no text","moonlit","flat"),
("Then every night after that it rises later.","CARD","five small horizon lines stacked, with a moon symbol slightly further to the right on each one","no text","white","flat"),
("By a good chunk of an hour, every single night, without fail.","CARD","a vertical stack of moon symbols drawn one under the other, with a thin measuring bracket down the side running from the top moon to the bottom moon","no text","white","flat"),
("By the tenth night","CARD","a plain row of ten small marks with the tenth one circled","a label \"10\"","white","flat"),
("it does not clear the horizon until the evening is long over.","SCENE_N","a completely dark sky with a thin dotted circle drawn well below the horizon line","no text","night_dark","flat"),
("And the gap between those two nights is larger than it sounds.","SCENE_N","open ground under a bright full moon, every stone and tuft of grass clearly readable","no text","moonlit","flat"),
("A clear night under a full moon","SCENE_N","open ground under a full moon, the stones and grass tufts all clearly visible","no text","moonlit","flat"),
("and a clear night with no moon","SCENE_N","flat open ground under an empty black night sky, almost nothing visible, only the faintest pale edge of one small stone","no text","night_dark","flat"),
("are not two shades of the same thing.","CARD","two plain squares side by side, the left one pale grey and the right one solid black, with an equals sign between them and a red X drawn through the equals sign","no text","white","flat"),
("There is roughly a hundred times less light in the second one.","CARD","one very large plain circle beside one very small plain circle","a label \"100x\"","white","flat"),
("On the first, a person can walk down to the water without putting a hand out.","SCENE_A","he walks under the full moon with both arms relaxed at his sides","no text","moonlit","flat"),
("On the second, the ground has to be found with a foot.","SCENE_A","he stands almost invisible in near black, one foot lifted and reaching forward, both hands out to the sides","no text","night_dark","worry"),
("Which is where the second number in that Tanzania study sits.","CARD","an open paper file with one row of it circled in black marker","no text","white","flat"),
("Hourly attack rates ran two to four times higher","CARD","two vertical bars, one clearly two to four times the height of the other","a label \"2-4x\"","white","flat"),
("in the ten days after a full moon","CARD","a row of moon phase circles with the ten after the full one shaded under a bracket","a label \"AFTER\"","white","flat"),
("than in the ten days before it.","CARD","a long row of small moon phase symbols ending in one large full moon, with a bracket drawn under the ten symbols that come before the full one","a label \"BEFORE\"","white","flat"),
("Same lions.","SCENE_N","two identical lions drawn side by side in flat tawny colour","no text","white","flat"),
("Same villages.","SCENE_N","two identical simple square buildings side by side","no text","white","flat"),
("Same hour of the evening.","CARD","two identical clock lines stacked one above the other, the same narrow section filled solid black on both, with a thin straight line joining the two black sections","no text","white","flat"),
("The only thing that moved","CARD","two rows of moon phase symbols stacked one above the other, with one long plain arrow running horizontally along them from left to right","no text","white","flat"),
("was whether anything was lit while people were still out in it.","SCENE_A","he walks down a worn path toward water under a bright full moon, the ground clearly lit ahead of him","no text","moonlit","flat"),
("So the question was never which animals were out there.","SCENE_N","dry open plain in daylight with one lion far off in the grass, small and unbothered","no text","savanna_day","flat"),
("They were always out there.","SCENE_N","several pairs of small yellow eyes at different heights inside flat blackness","no text","night_dark","flat"),
("The question was whether the walk down to the water","SCENE_A","he walks toward the strip of dark water, seen from behind","no text","dusk_water","flat"),
("happened in light,","SCENE_A","he walks along a worn dirt path under a bright full moon, the ground and the path clearly visible","no text","moonlit","flat"),
("or happened in nothing.","SCENE_A","he walks forward with almost the entire frame solid black, only the white of his head and one hand faintly visible","no text","night_dark","scared"),

# ═════════════════ CH4 — TRANG BO DOI CON SU TU TRUOC — 26 shot ═════════════════
("There is one more turn in this, and it runs the other way.","SCENE_A","he stops mid stride and turns his head back over one shoulder","no text","moonlit","curious"),
("The moon does not only take the light away from the people.","SCENE_N","one lion standing exposed on open ground under a bright full moon, its whole body plainly lit","no text","moonlit","flat"),
("It takes it away from the lion first.","SCENE_N","a lion drawn in flat tawny colour standing under a bright full moon, fully exposed and clearly visible","no text","moonlit","flat"),
("Lions hunt by ambush.","SCENE_N","a lion crouched flat and low in grass, only the top of its head showing","no text","savanna_day","flat"),
("Getting close without being seen is the whole method.","SCENE_N","one lion crouched very low in tall dry grass with only its head and shoulders showing","no text","dry_plain","flat"),
("And a week of bright nights is very bad for that.","SCENE_N","one lion crouched low on open ground under a bright full moon, its whole body and its shadow clearly visible","no text","moonlit","flat"),
("The researchers put it plainly.","CARD","an open paper file with one line of it circled in black marker","no text","white","flat"),
("Lions are hungriest just after the full moon,","SCENE_N","a lion standing with its head low and its ribs showing as simple curved lines","no text","dusk_grey","flat"),
("because the abundance of light just before and during the full moon","SCENE_N","the full moon at its brightest over ground that is fully lit","no text","moonlit","flat"),
("limits their ability to hunt successfully.","SCENE_N","one lion standing plainly visible on open moonlit ground with a small deer far away on the other side of the frame","no text","moonlit","flat"),
("So the bright half of the month is not a gift.","SCENE_N","bright moonlit open ground, calm and empty, one lion sitting still in the distance doing nothing","no text","moonlit","flat"),
("It is a delay.","SCENE_N","one lion lying flat on moonlit ground with its head down on its paws","no text","moonlit","flat"),
("People are safer while the moon is up,","GROUP","three people walking together on clearly lit ground under a full moon","no text","moonlit","flat"),
("and the animal waiting past the treeline","SCENE_N","two yellow eyes low inside a solid black treeline","no text","dusk_grey","flat"),
("is getting steadily emptier the whole time.","SCENE_N","one thin lion standing on open ground under a bright moon, its ribs drawn as a few plain lines","no text","moonlit","flat"),
("Then the moon starts rising late.","SCENE_N","flat dark ground under an empty black sky with one thin pale moon only just clearing the horizon line","no text","night_dark","flat"),
("The early evening goes dark.","SCENE_N","the treeline and ground almost entirely swallowed in flat black","no text","night_dark","flat"),
("And a hungry ambush hunter gets its hours back.","SCENE_N","a lion moving low through near darkness, only its outline and two yellow eyes visible","no text","night_dark","flat"),
("The safest nights and the deadliest nights are the same two weeks, in order.","CARD","a row of moon phase circles with the first half bracketed one way and the second half bracketed the other","no text","white","flat"),
("One pays for the other.","CARD","a plain balance scale with one side down, drawn in simple lines","a label \"BRIGHT HALF\" on the raised side and \"DARK HALF\" on the low side","white","flat"),
("None of this required anyone back then to understand it.","SCENE_A","he sits by a low fire looking into it, not looking up at all","no text","fire_ring","flat"),
("A pattern can kill people for a hundred thousand years","CARD","a very long horizontal line with small identical marks repeating along its whole length","no text","white","flat"),
("without anybody working out that it is a pattern.","SCENE_A","he walks past the treeline without looking at it, plainly unaware","no text","dusk_grey","flat"),
("But there is something in the modern numbers that resists that.","CARD","a plain sheet of graph paper with one wavy line drawn across it and a row of moon phase circles along the top edge","a label \"TODAY\"","white","flat"),

# ═════════════════ CH5 — NO VAN DANG CHAY — 28 shot ═════════════════
("In 2021 researchers put sleep monitors on three communities in Argentina.","CARD","a plain wristband with a small square device on it, drawn large","a label \"2021\"","white","flat"),
("All three were Toba and Qom people.","CARD","three small identical house shapes in a row","no text","white","flat"),
("One had electricity around the clock.","CARD","the first house with a small lit bulb above it and a plain clock beside it","no text","white","flat"),
("One had power inside the houses and nothing past the doorway.","CARD","the second house with a lit bulb inside it and flat black outside the door","no text","white","flat"),
("One had none at all.","CARD","the third house with no bulb and a red X where the bulb would be","no text","white","flat"),
("The monitors tracked when people fell asleep,","SCENE_A","he lies asleep on his side on a simple mat, one plain wristband visible on his wrist","no text","night_open","asleep"),
("night after night, across the whole lunar month.","CARD","a row of moon phase circles running the full width of the frame","no text","white","flat"),
("And the sleep moved with the moon.","CARD","a wavy line drawn directly beneath the row of moon phases, rising and falling with them","no text","white","flat"),
("On the nights before a full moon,","CARD","the row of moon phases with the ones before the full moon bracketed","no text","white","flat"),
("when there is moonlight in the hours right after dark,","SCENE_N","the moon fairly low over lit ground just after sunset","no text","moonlit","flat"),
("people went to sleep later","SCENE_A","he sits up on his mat with his eyes open while everything around him is dark","no text","night_open","flat"),
("and slept less.","CARD","two horizontal bars of different lengths, the second clearly shorter","no text","white","flat"),
("The effect peaked three to five days before the full moon itself.","CARD","the row of moon phases with three of the circles before the full one circled","a label \"3-5 DAYS\"","white","flat"),
("The community with no electricity showed it most strongly,","CARD","three wavy horizontal lines stacked one under the other, the top two with small shallow peaks and the bottom one with much larger peaks","no text","white","flat"),
("which is roughly what anyone would guess.","CARD","a plain tick mark drawn alone","no text","white","flat"),
("Then the same analysis was run","CARD","a plain rectangular sheet of graph paper with one wavy line drawn across it from left to right","a label \"SAME METHOD\"","white","flat"),
("on four hundred and sixty four university students in Seattle.","CARD","a dense grid of small identical marks with two simple tall building shapes behind it","a label \"464\"","white","flat"),
("It was still there.","CARD","four wavy horizontal lines stacked one under the other, all four drawn with the same shape and the same size peaks","no text","white","flat"),
("Nobody in Seattle is waiting on moonlight to finish anything.","CARD","a plain street lamp drawn with light coming off it","no text","white","flat"),
("The streets are lit, the blinds are shut,","CARD","a simple window with the blinds drawn closed across it","no text","white","flat"),
("and the moon does not enter a single decision any of them make.","CARD","a plain moon symbol with a red X through it","no text","white","flat"),
("Their sleep moved with it anyway.","CARD","a row of eight moon phase circles across the top of the frame, and directly beneath it one wavy line rising and falling in step with them, joined by two thin vertical arrows","no text","white","flat"),
("Now hold that next to the lions.","CARD","the wavy sleep line on one side and a simple lion head on the other, with a plain vertical line between","no text","white","flat"),
("In the run up to a full moon the early night is lit, and people stay out in it longer.","GROUP","three people still moving about outside on clearly lit ground under a nearly full moon","no text","moonlit","flat"),
("In the ten nights after, the early night is black, and that is when the killing happens.","SCENE_N","flat blackness with two yellow eyes low in it and nothing else","no text","night_dark","flat"),
("Two teams who never worked together.","CARD","two separate stacks of paper files with a wide empty gap between them","no text","white","flat"),
("Two different things measured, on two different continents.","CARD","two small separate continent outlines side by side","no text","white","flat"),
("They are two halves of the same month.","CARD","one plain circle divided cleanly down the middle into a pale half and a black half","a label \"ONE MONTH\"","white","flat"),
("Whether the two are connected, nobody has shown,","CARD","two separate stacks of paper files with a dotted line between them and a question mark sitting on the line","no text","white","flat"),
("and nothing here shows it either.","CARD","one long horizontal dotted line with a large red X drawn through the middle of it","no text","white","flat"),
("So it is worth being exact","SCENE_A","he stands with one hand raised, counting something off on his fingers","no text","white","curious"),
("about what is settled here and what is not.","CARD","two columns drawn side by side, the left column headed with a green tick and the right column headed with a plain question mark","no text","white","flat"),
("The killing hours are settled.","CARD","one long horizontal clock line with its middle section filled solid black and a green tick beside it","no text","white","flat"),
("Twenty one years of records.","CARD","a tall stack of paper files with a green tick drawn beside it","a label \"21 YEARS\"","white","flat"),
("The moon's schedule is settled.","CARD","a row of small moon phase symbols with a green tick drawn beside the row","no text","white","flat"),
("That one is just astronomy.","SCENE_N","one plain white full moon high on a flat deep blue night sky above a solid black treeline","no text","moonlit","flat"),
("What people made of it","SCENE_A","he stands looking up at a bright moon, one hand half raised","no text","moonlit","curious"),
("is the part nobody can hand you.","SCENE_A","he stands with both empty white hands open in front of him, holding nothing","no text","white","flat"),
("Which is the obvious thing left to ask.","SCENE_A","he tips his head all the way back to look straight up at a sky with one plain moon in it","no text","night_open","curious"),

# ═════════════════ CH6 — HO CO BIET KHONG — 26 shot ═════════════════
("Did anyone back then actually read the cycle.","SCENE_A","he stands looking up at a sky with a crescent in it, head tilted back","no text","night_open","curious"),
("One famous attempt is the reason people assume they did.","CARD","a single old book drawn plainly, closed","no text","white","flat"),
("In the nineteen seventies a researcher named Alexander Marshack","CARD","a plain magnifying glass held over a small object","a label \"1970s\"","white","flat"),
("looked at scratch marks on Ice Age bone and antler.","SCENE_N","one piece of pale bone lying flat, drawn large, with a row of eleven short straight scratch marks cut across it, the bone rendered with fine texture while everything else stays plain","no text","white","flat"),
("He read them as notation systems,","CARD","a row of short scratch marks in a line with small faint numbers drawn above each mark","no text","white","flat"),
("specifically lunar calendars, notating the passage of time.","CARD","the row of scratches with a row of moon phase circles drawn directly above it, one moon per scratch","no text","white","flat"),
("Individual lines and dots as days.","CARD","three short scratch marks with a small sun symbol above each","no text","white","flat"),
("Sequences of them as months.","CARD","a long run of scratch marks with one large bracket over the whole run","no text","white","flat"),
("It is a beautiful idea and it has never gone away.","SCENE_N","one piece of pale bone lying flat with a row of short scratch marks cut across it, alone on an empty white background","no text","white","flat"),
("It has also never been proven.","CARD","one long pale bone lying flat with a row of small scratch marks cut across it, and a plain question mark beside it","no text","white","flat"),
("In 1989 another researcher published a reply in Current Anthropology.","CARD","a plain rectangular sheet of paper with one bold horizontal line across the top and eight thin ruled lines below it, nothing written","a label \"1989\"","white","flat"),
("The title of it was Palaeolithic Lunar Calendars, a Case of Wishful Thinking.","CARD","a plain rectangular sheet of paper with one bold hand-lettered headline across the top and thin ruled lines below it","the headline \"A CASE OF WISHFUL THINKING?\"","white","flat"),
("That is the whole argument, in five words, before the paper even starts.","CARD","a plain rectangular sheet of paper where the top headline line is drawn solid black and every line below it is drawn in pale grey","no text","white","flat"),
("The broader criticism is that the work over-interpreted many artifacts,","CARD","three plain small objects in a row on a white background: a stone blade, a piece of bone and a clay pot, each with one small moon symbol drawn above it","no text","white","flat"),
("finding numerical and calendrical patterns where none exist.","CARD","three plain small objects in a row on a white background: a stone blade, a piece of bone and a clay pot, each with a small moon symbol above it crossed out in red","no text","white","flat"),
("Which is the polite way of saying that if a person wants to find a moon in a row of scratches,","CARD","a random uneven row of scratch marks with a moon symbol being drawn onto it by a hand","no text","white","flat"),
("a row of scratches will usually oblige.","CARD","an uneven row of short scratch marks drawn on a white background, with one moon symbol drawn over the middle of the row","no text","white","flat"),
("So the marks are real.","SCENE_N","one piece of pale bone lying flat with a row of short scratch marks cut across it, drawn plainly with no symbols and no labels anywhere","no text","white","flat"),
("Somebody made them on purpose, and that much nobody argues with.","SCENE_A","close on his hands holding a small sharp stone against a piece of bone","no text","fire_ring","flat"),
("Whether they were cut one at a time over many nights,","CARD","one scratch mark with a moon symbol beside it, then a gap, then another scratch and another moon","no text","white","flat"),
("or in a single sitting, is part of what is in dispute.","CARD","a full row of scratch marks with one single moon symbol above the whole row","no text","white","flat"),
("And it matters, because a tally kept across a month","CARD","a row of scratch marks spread out with small gaps between each","no text","white","flat"),
("and a pattern carved in an afternoon are not the same object.","CARD","a row of short scratch marks packed tightly together with no gaps between them","no text","white","flat"),
("What they were counting, if they were counting, is not recoverable.","SCENE_N","one pale marked bone lying alone on flat dark ground under a plain moon","no text","night_dark","flat"),
("It may have been nights.","SCENE_N","one plain white moon alone high on a flat night sky, nothing else in the frame","no text","night_open","flat"),
("It may have been kills, or debts, or nothing at all.","CARD","three plain small drawings in a row on a white background: a flat tawny animal outline, a simple clay pot, and one empty dotted square","no text","white","flat"),

# ═════════════════ KET — 16 shot ═════════════════
("The moon is doing all of it right now.","SCENE_N","one plain white full moon high on a flat deep blue sky, nothing else in frame","no text","moonlit","flat"),
("It comes up as the sun goes down, once a month,","SCENE_N","one low sun dropping below the horizon on one side of the frame and one plain full moon standing clear of it on the other","no text","dusk_grey","flat"),
("and then loses the better part of an hour every night after that.","CARD","five stacked horizon lines with the moon symbol slightly further right on each","no text","white","flat"),
("The dark stretch arrives on time.","SCENE_N","flat open ground under a completely black empty sky with no moon anywhere in it","no text","night_dark","flat"),
("None of that has ever needed a person to notice it.","SCENE_N","the full moon alone over completely empty ground with no figure anywhere in frame","no text","moonlit","flat"),
("Which brings it back to the walk down to the water,","SCENE_A","he walks away from the viewer toward the strip of dark water, seen from behind","no text","dusk_water","flat"),
("forty steps from camp, in the grey half hour.","SCENE_N","seen from above, the ring of stones and the thin dotted line running out from it","a label \"40 STEPS\"","dry_plain","flat"),
("Whoever made that walk did not know they were standing inside a cycle.","SCENE_A","he stands still on the path with the empty grey sky above him","no text","dusk_grey","flat"),
("They may have known that some evenings felt worse than others,","SCENE_A","close on his face, eyelids low, looking off to one side toward the treeline","no text","dusk_grey","worry"),
("and stayed in.","SCENE_A","he sits down beside the low fire with his back to the dark, knees pulled up","no text","fire_ring","flat"),
("They may have gone anyway, because water does not fetch itself.","SCENE_A","he walks out toward the water carrying an empty vessel, head down","no text","dusk_water","flat"),
("The marks on the bone do not say.","SCENE_N","the marked bone lying alone on plain ground","no text","white","flat"),
("What is certain is narrower, and much older than any of the counting.","SCENE_N","one worn narrow dirt path running from the bottom of the frame down toward still water, in flat grey dusk, with no person on it","no text","dusk_grey","flat"),
("For a very long stretch of human history, whether a person came back from that walk","SCENE_A","he walks back up the slope toward the small distant fire, carrying a full vessel","no text","dusk_grey","flat"),
("was decided by something nobody could reach, nobody could argue with, and everybody could see.","SCENE_N","the moon alone, high and plain, above a solid black treeline","no text","night_dark","flat"),
("And it is up there tonight, on exactly the same schedule, over a world where nobody times the walk to the water by it any more.","SCENE_N","one plain white full moon high on a flat deep blue night sky, above a solid black treeline and one narrow strip of dark water along the bottom, with no person and no animal anywhere in the frame","no text","moonlit","flat"),
]
