# -*- coding: utf-8 -*-
"""V19 MOON — "Why Were Some Nights Deadlier for Ancient Humans?"

(line, kind, subj, text, bg, face)

kind : SCENE_A ancient | SCENE_W woman | GROUP nhom | SCENE_N khong nguoi | CARD
bg   : dusk_grey dusk_water moonlit night_open night_dark cold_night fire_ring fire_edge
       savanna_day dry_plain cave_warm rain_day dark_card white
face : flat shock tired worry scared happy asleep dumb curious sad

1.686 tu / ~9:30 -> nhip 2,0-2,5 giay/shot -> ~230-250 shot.
CASTING: KHONG CO NHAN VAT HIEN DAI. Lane "ve BAN" da bo 10/08.
"""

SHOTS = [

# ═════════════════ HOOK — 14 shot ═════════════════
("You are walking down to the water","SCENE_A","he walks away from the viewer down a slope toward a strip of dark water, seen from behind","no text","dusk_water","flat"),
("and the sun has just gone.","SCENE_N","a flat colourless grey sky over a solid black treeline, the last pale light along the horizon","no text","dusk_grey","flat"),
("It is that flat grey half hour","CARD","a wide flat band of colourless grey filling the frame, with one small plain circle for the sun resting exactly on a single horizontal line","a label \"HALF AN HOUR\"","white","flat"),
("where the ground is still visible","SCENE_N","a patch of dim olive ground with two or three small stones clearly drawn on it","no text","dusk_grey","flat"),
("and the treeline is not.","SCENE_N","the same view further out, the trees now one solid black shape with nothing inside it","no text","dusk_grey","flat"),
("The camp is forty steps behind you.","SCENE_N","seen from above, a small ring of stones with a low fire, and a thin dotted line leading away from it","a label \"40 STEPS\"","dry_plain","flat"),
("You have made this walk a thousand times.","SCENE_A","he walks the same path, relaxed, one hand loose at his side","no text","dusk_grey","flat"),
("You made it ten nights ago","SCENE_A","the same walk under a bright full moon, the ground clearly lit, his shadow sharp behind him","no text","moonlit","flat"),
("and thought nothing of it.","SCENE_A","close on his face under the full moon, eyelids half down, completely unbothered","no text","moonlit","flat"),
("Tonight the moon will not come up for another four hours.","SCENE_N","an empty dark sky with a thin dotted circle low near the horizon showing where the moon is not yet","a label \"4 HOURS\"","night_dark","flat"),
("That is the only thing about this evening that has changed.","CARD","two identical small drawings of the same path side by side, one with a moon above it and one with an empty sky","no text","white","flat"),
("And in a place with lions in it,","SCENE_N","one lion drawn in flat solid tawny colour lying low in dim grass, only the head and shoulders visible","no text","dusk_grey","flat"),
("people get killed on that walk","SCENE_A","he pauses mid step and looks back over his shoulder toward the line of trees","no text","dusk_grey","shock"),
("at several times the rate they do when the moon is up.","CARD","two simple vertical bars of different heights, the taller one much taller, no numbers","a label \"MOON UP\" under the short bar and \"NO MOON\" under the tall one","white","flat"),

# ═════════════════ CH1 — SO GHI 21 NAM — 26 shot ═════════════════
("That number is not a guess about the past.","CARD","a plain drawn scroll with a big red X through it","no text","white","flat"),
("It comes out of twenty one years of paperwork.","CARD","a tall stack of plain paper files drawn in flat grey","a label \"21 YEARS\"","white","flat"),
("Between 1988 and 2009,","CARD","a long horizontal line with two short marks on it and nothing between them","a label \"1988\" at the left mark and \"2009\" at the right","white","flat"),
("in southeastern Tanzania,","SCENE_N","a plain outline map of the African continent with one small area near the southeast of Tanzania filled solid","a label \"TANZANIA\"","white","flat"),
("more than a thousand people were attacked by lions.","GROUP","a large loose crowd of small plain white stick figures filling the frame","a label \"1,000+\"","white","flat"),
("Four hundred and fifty of those attacks","CARD","the same crowd with a smaller block of the figures circled in black marker","a label \"450 ATTACKS\"","white","flat"),
("were recorded in enough detail to study.","CARD","one open paper file with neat handwritten rows drawn as plain lines","no text","white","flat"),
("Four hundred and seventy four victims.","CARD","a dense grid of small identical marks","a label \"474\"","white","flat"),
("And when the times were laid out,","CARD","a plain horizontal clock line running from a small sun symbol to a small moon symbol","no text","white","flat"),
("they did not spread evenly across the night.","CARD","the same line with small marks clustered heavily at one end and almost none at the other","no text","white","flat"),
("Nearly sixty percent of the victims were attacked","CARD","a simple bar sitting over one narrow section of that clock line, much taller than everything else","a label \"60%\"","white","flat"),
("between six in the evening and quarter to ten.","CARD","the same line with the section between two marks shaded solid","a label \"6:00 PM\" and \"9:45 PM\"","white","flat"),
("Not at midnight.","CARD","a plain moon high in the middle of a dark square with a red X through it","no text","dark_card","flat"),
("Not at three in the morning.","CARD","the same dark square with a red X and nothing else in it","no text","dark_card","flat"),
("During dinner.","GROUP","three people sitting close together around a low fire, one holding food toward the flames","no text","fire_ring","flat"),
("Over two thirds of those attacks were fatal,","CARD","a row of small identical marks with two out of every three shaded solid black","a label \"2 IN 3\"","white","flat"),
("and the victims were eaten.","SCENE_N","one lion drawn in flat tawny colour walking away from the viewer into flat blackness","no text","night_dark","flat"),
("Now, those are lions in living memory,","SCENE_N","the same lion standing in dim grass beside a plain drawn fence post","no text","dusk_grey","flat"),
("in villages with roads and clinics.","SCENE_N","two very simple square huts made of plain black lines on flat tan ground, and one straight dirt track running past them","no text","dry_plain","flat"),
("They are not the animals that hunted people a hundred thousand years ago.","CARD","a plain long timeline with one mark far to the left and one far to the right","a label \"100,000 YEARS\"","white","flat"),
("But the shape of an evening has not moved.","CARD","three small squares in a row showing the same horizon getting darker from left to right","no text","white","flat"),
("The light still goes in the same order it always went.","CARD","a horizon line with a sun symbol above it, then on it, then below it, drawn three times in sequence","no text","white","flat"),
("And wherever people camp,","SCENE_N","seen from above, a small ring of stones on open ground","no text","dry_plain","flat"),
("something outside the camp is still worth walking to before sleeping.","SCENE_N","seen from directly above: a small ring of stones on flat tan ground, and one thin dotted line running from it out to a narrow strip of dark water","no text","dry_plain","flat"),
("And the thing waiting past the treeline","SCENE_N","two small yellow eyes low inside the solid black treeline, nothing else visible","no text","dusk_grey","flat"),
("has always seen better in the dark than the people have.","CARD","two simple eye shapes side by side, one drawn with a bright ring around it and one plain","no text","white","flat"),
("So the danger was never the night.","CARD","a plain dark square with a red X through it","no text","dark_card","flat"),
("It was one particular slice of it.","CARD","a plain circle divided into segments with one narrow segment shaded solid","no text","white","flat"),

# ═════════════════ CH2 — LOAI THU HAI, CUNG KHUNG GIO — 30 shot ═════════════════
("Further south, in Eswatini,","SCENE_N","a plain outline map of southern Africa with one very small country filled solid","a label \"ESWATINI\"","white","flat"),
("a different team spent two years counting something else.","CARD","two tall stacks of plain paper sheets standing side by side on a plain background, with one simple bracket drawn underneath both","a label \"2 YEARS\"","white","flat"),
("Not lions.","CARD","a simple lion head drawn in flat tawny colour with a red X through it","no text","white","flat"),
("Snakes.","SCENE_N","one snake in flat olive green coiled low on flat tan ground, small simple face, drawn in far more detail than a person would be","no text","dry_plain","flat"),
("They recorded where people were bitten, and when.","CARD","a plain outline of a standing human body with four small dots marked on the lower legs and feet","no text","white","flat"),
("Thirty percent of the patients were bitten","CARD","a row of ten small stick figures with three of them shaded solid","a label \"30%\"","white","flat"),
("between six in the evening and ten at night.","CARD","a horizontal clock line with the section between two marks shaded solid","a label \"6:00 PM\" and \"10:00 PM\"","white","flat"),
("Six to ten.","CARD","the same shaded section alone on a plain background, nothing else drawn","a label \"6 TO 10\"","white","flat"),
("The same four hours,","CARD","two clock lines stacked one above the other, the same section shaded on both","no text","white","flat"),
("in a different country,","CARD","two small country outlines side by side with a plain arrow between them","no text","white","flat"),
("by an animal that hunts nothing like a lion does.","CARD","a lion head and a snake head side by side with a plain vertical line between them","no text","white","flat"),
("Sixty percent of all the bites","CARD","a plain outline of a human body with the lower legs and feet shaded solid","a label \"60%\"","white","flat"),
("were to the foot, the ankle, the heel or the toe.","CARD","one bare foot drawn large and plain, with four thin arrows pointing at four places on it","no text","white","flat"),
("Not a hand reaching into somewhere it should not.","CARD","a hand reaching into a dark hollow, with a red X through the whole drawing","no text","white","flat"),
("A foot, going somewhere.","SCENE_A","close on his bare white foot mid stride just above dim ground, the rest of him out of frame above","no text","dusk_grey","flat"),
("Twenty seven percent of the people bitten","CARD","a row of ten small stick figures with just under three of them shaded solid","a label \"27%\"","white","flat"),
("were walking when it happened.","SCENE_A","he walks steadily across dim ground, mid stride, looking ahead and not down","no text","dusk_grey","flat"),
("A lion and a snake have close to nothing in common.","CARD","a lion and a snake drawn on opposite sides of the frame with a wide empty gap between them","no text","white","flat"),
("They hunt differently,","SCENE_N","a lion crouched flat and low behind a small bush","no text","dusk_grey","flat"),
("they sense the world differently,","SCENE_N","a snake with its tongue out, three small curved lines drawn in the air in front of it","no text","dry_plain","flat"),
("and they want completely different things from a person.","CARD","a lion head and a snake head with one plain arrow from each, pointing to two different small symbols","no text","white","flat"),
("Two research teams, two countries,","CARD","two separate small stacks of paper files with a wide gap between them","no text","white","flat"),
("more than ten years apart,","CARD","a plain timeline with two marks and a measured gap drawn between them","a label \"10+ YEARS\"","white","flat"),
("both landed on the same four hours.","CARD","two arrows coming in from opposite sides and meeting on one shaded section of a clock line","no text","white","flat"),
("Which means those four hours were never really about the animal.","CARD","one flat tawny lion and one flat olive snake side by side, each with a large red X drawn over it, and below them a plain horizontal line with one section shaded solid black","no text","white","flat"),
("The animal is whatever happens to live nearby.","CARD","three small different animals drawn in flat solid colour in a row, all the same size, none emphasised","no text","white","flat"),
("The constant is a person on foot, outside,","SCENE_A","he walks alone across empty dim ground, small in a wide frame","no text","dusk_grey","flat"),
("in the stretch of evening where the light has gone and the day's work has not.","SCENE_A","he walks carrying a simple water vessel, the sky behind him almost fully grey","no text","dusk_grey","tired"),
("Which still leaves the part that has not been explained.","CARD","a plain question mark alone on an empty background","no text","white","flat"),
("Every evening has those four hours in it.","CARD","a row of seven identical clock lines, the same section shaded on every one","no text","white","flat"),
("They are not all equally lethal, and the difference is not small.","CARD","the same row of seven clock lines, now with bars of very different heights above them","no text","white","flat"),
("Nothing on the ground changes between one evening and the next.","SCENE_N","one flat patch of dim olive ground with three small grey stones on it, drawn plainly, nothing else in the frame","no text","dusk_grey","flat"),
("Something overhead does.","SCENE_N","an empty dark sky with one thin pale crescent low in it","no text","night_dark","flat"),

# ═════════════════ CH3 — MAT TRANG — 30 shot ═════════════════
("Here is what a full moon actually does.","SCENE_N","one plain white circle for a full moon on a flat deep blue sky, nothing else in frame","no text","moonlit","flat"),
("It comes up as the sun goes down.","CARD","a horizon line with a sun symbol dropping below it on one side and a moon rising above it on the other","no text","white","flat"),
("It is overhead and bright","SCENE_N","the full moon high in the frame with pale grey-blue ground clearly visible below it","no text","moonlit","flat"),
("through exactly the hours when people are still outside finishing things.","GROUP","three people moving about on ground that is clearly lit, one carrying a bundle, one bending down","no text","moonlit","flat"),
("Then every night after that it rises later.","CARD","five small horizon lines stacked, with a moon symbol slightly further to the right on each one","no text","white","flat"),
("By a good chunk of an hour, every single night, without fail.","CARD","the same stack with a thin measuring bracket drawn between the first and last moon symbol","no text","white","flat"),
("By the tenth night","CARD","a plain row of ten small marks with the tenth one circled","a label \"10\"","white","flat"),
("it does not clear the horizon until the evening is long over.","SCENE_N","a completely dark sky with a thin dotted circle drawn well below the horizon line","no text","night_dark","flat"),
("And the gap between those two nights is larger than it sounds.","CARD","two plain squares side by side, one pale grey and one solid black, nothing drawn inside either","no text","white","flat"),
("A clear night under a full moon","SCENE_N","open ground under a full moon, the stones and grass tufts all clearly visible","no text","moonlit","flat"),
("and a clear night with no moon","SCENE_N","the same open ground with almost nothing visible, only the faintest edge of one stone","no text","night_dark","flat"),
("are not two shades of the same thing.","CARD","the two squares again with a plain equals sign between them and a red X through the equals sign","no text","white","flat"),
("There is roughly a hundred times less light in the second one.","CARD","one very large plain circle beside one very small plain circle","a label \"100x\"","white","flat"),
("On the first, a person can walk down to the water without putting a hand out.","SCENE_A","he walks under the full moon with both arms relaxed at his sides","no text","moonlit","flat"),
("On the second, the ground has to be found with a foot.","SCENE_A","he stands almost invisible in near black, one foot lifted and reaching forward, both hands out to the sides","no text","night_dark","worry"),
("Which is where the second number in that Tanzania study sits.","CARD","an open paper file with one row of it circled in black marker","no text","white","flat"),
("Hourly attack rates ran two to four times higher","CARD","two vertical bars, one clearly two to four times the height of the other","a label \"2-4x\"","white","flat"),
("in the ten days after a full moon","CARD","a row of moon phase circles with the ten after the full one shaded under a bracket","a label \"AFTER\"","white","flat"),
("than in the ten days before it.","CARD","the same row with the ten before the full one bracketed instead","a label \"BEFORE\"","white","flat"),
("Same lions.","SCENE_N","two identical lions drawn side by side in flat tawny colour","no text","white","flat"),
("Same villages.","SCENE_N","two identical simple square buildings side by side","no text","white","flat"),
("Same hour of the evening.","CARD","two identical clock lines with the same section shaded on both","no text","white","flat"),
("The only thing that moved","CARD","the two rows of moon phases again, with one plain arrow running along them","no text","white","flat"),
("was whether anything was lit while people were still out in it.","CARD","two identical drawings of a person on a path, one with a moon overhead and one with an empty sky","no text","white","flat"),
("So the question was never which animals were out there.","CARD","one flat tawny lion, one flat olive snake and one flat grey wolf in a row, each with a large red X drawn over it","no text","white","flat"),
("They were always out there.","SCENE_N","several pairs of small yellow eyes at different heights inside flat blackness","no text","night_dark","flat"),
("The question was whether the walk down to the water","SCENE_A","he walks toward the strip of dark water, seen from behind","no text","dusk_water","flat"),
("happened in light,","SCENE_A","the same walk with the full moon above, ground and path clearly visible","no text","moonlit","flat"),
("or happened in nothing.","SCENE_A","the same walk with almost the entire frame solid black, only the white of his head faintly visible","no text","night_dark","scared"),

# ═════════════════ CH4 — TRANG BO DOI CON SU TU TRUOC — 26 shot ═════════════════
("There is one more turn in this, and it runs the other way.","CARD","a plain arrow that loops back on itself and points the opposite direction","no text","white","flat"),
("The moon does not only take the light away from the people.","CARD","a small stick figure with a plain arrow pointing away from it","no text","white","flat"),
("It takes it away from the lion first.","SCENE_N","a lion drawn in flat tawny colour standing under a bright full moon, fully exposed and clearly visible","no text","moonlit","flat"),
("Lions hunt by ambush.","SCENE_N","a lion crouched flat and low in grass, only the top of its head showing","no text","savanna_day","flat"),
("Getting close without being seen is the whole method.","CARD","a flat tawny lion with a dotted line curving from it to a small prey animal","no text","white","flat"),
("And a week of bright nights is very bad for that.","SCENE_N","the same crouched lion under a full moon, its whole body and its shadow clearly visible on open ground","no text","moonlit","flat"),
("The researchers put it plainly.","CARD","an open paper file with one line of it circled in black marker","no text","white","flat"),
("Lions are hungriest just after the full moon,","SCENE_N","a lion standing with its head low and its ribs showing as simple curved lines","no text","dusk_grey","flat"),
("because the abundance of light just before and during the full moon","SCENE_N","the full moon at its brightest over ground that is fully lit","no text","moonlit","flat"),
("limits their ability to hunt successfully.","CARD","a flat tawny lion with a dotted line curving toward a small prey animal, and a red X across the dotted line","no text","white","flat"),
("So the bright half of the month is not a gift.","CARD","a plain wrapped gift box with a red X through it","no text","white","flat"),
("It is a delay.","CARD","a plain hourglass drawn alone","no text","white","flat"),
("People are safer while the moon is up,","GROUP","three people walking together on clearly lit ground under a full moon","no text","moonlit","flat"),
("and the animal waiting past the treeline","SCENE_N","two yellow eyes low inside a solid black treeline","no text","dusk_grey","flat"),
("is getting steadily emptier the whole time.","CARD","four small lion outlines in a row, each one drawn slightly thinner than the last","no text","white","flat"),
("Then the moon starts rising late.","CARD","a horizon line with a moon symbol sitting well below it","no text","white","flat"),
("The early evening goes dark.","SCENE_N","the treeline and ground almost entirely swallowed in flat black","no text","night_dark","flat"),
("And a hungry ambush hunter gets its hours back.","SCENE_N","a lion moving low through near darkness, only its outline and two yellow eyes visible","no text","night_dark","flat"),
("The safest nights and the deadliest nights are the same two weeks, in order.","CARD","a row of moon phase circles with the first half bracketed one way and the second half bracketed the other","no text","white","flat"),
("One pays for the other.","CARD","a plain balance scale with one side down, drawn in simple lines","a label \"BRIGHT HALF\" on the raised side and \"DARK HALF\" on the low side","white","flat"),
("None of this required anyone back then to understand it.","SCENE_A","he sits by a low fire looking into it, not looking up at all","no text","fire_ring","flat"),
("A pattern can kill people for a hundred thousand years","CARD","a very long horizontal line with small identical marks repeating along its whole length","no text","white","flat"),
("without anybody working out that it is a pattern.","CARD","the same long line of marks with a question mark hovering above it","no text","white","flat"),
("But there is something in the modern numbers that resists that.","CARD","a plain sheet of graph paper with one wavy line drawn across it and a row of moon phase circles along the top edge","a label \"TODAY\"","white","flat"),

# ═════════════════ CH5 — NO VAN DANG CHAY — 28 shot ═════════════════
("In 2021 researchers put sleep monitors on three communities in Argentina.","CARD","a plain wristband with a small square device on it, drawn large","a label \"2021\"","white","flat"),
("All three were Toba and Qom people.","CARD","three small identical house shapes in a row","no text","white","flat"),
("One had electricity around the clock.","CARD","the first house with a small lit bulb above it and a plain clock beside it","no text","white","flat"),
("One had power inside the houses and nothing past the doorway.","CARD","the second house with a lit bulb inside it and flat black outside the door","no text","white","flat"),
("One had none at all.","CARD","the third house with no bulb and a red X where the bulb would be","no text","white","flat"),
("The monitors tracked when people fell asleep,","SCENE_A","he lies asleep on his side on a simple mat, one plain wristband visible on his wrist","no text","night_open","asleep"),
("night after night, across the whole lunar month.","CARD","a row of moon phase circles running the full width of the frame","no text","white","flat"),
("And the sleep moved with the moon.","CARD","a wavy line drawn directly beneath the row of moon phases, rising and falling with them","no text","white","flat"),
("On the nights before a full moon,","CARD","the row of moon phases with the ones before the full moon bracketed","no text","white","flat"),
("when there is moonlight in the hours right after dark,","SCENE_N","the moon fairly low over lit ground just after sunset","no text","moonlit","flat"),
("people went to sleep later","SCENE_A","he sits up on his mat with his eyes open while everything around him is dark","no text","night_open","flat"),
("and slept less.","CARD","two horizontal bars of different lengths, the second clearly shorter","no text","white","flat"),
("The effect peaked three to five days before the full moon itself.","CARD","the row of moon phases with three of the circles before the full one circled","a label \"3-5 DAYS\"","white","flat"),
("The community with no electricity showed it most strongly,","CARD","three wavy lines stacked, the bottom one with much bigger peaks than the other two","no text","white","flat"),
("which is roughly what anyone would guess.","CARD","a plain tick mark drawn alone","no text","white","flat"),
("Then the same analysis was run","CARD","a plain rectangular sheet of graph paper with one wavy line drawn across it from left to right","a label \"SAME METHOD\"","white","flat"),
("on four hundred and sixty four university students in Seattle.","CARD","a dense grid of small identical marks with two simple tall building shapes behind it","a label \"464\"","white","flat"),
("It was still there.","CARD","a fourth wavy line appearing under the other three, with the same shape","no text","white","flat"),
("Nobody in Seattle is waiting on moonlight to finish anything.","CARD","a plain street lamp drawn with light coming off it","no text","white","flat"),
("The streets are lit, the blinds are shut,","CARD","a simple window with the blinds drawn closed across it","no text","white","flat"),
("and the moon does not enter a single decision any of them make.","CARD","a plain moon symbol with a red X through it","no text","white","flat"),
("Their sleep moved with it anyway.","CARD","a row of eight moon phase circles across the top of the frame, and directly beneath it one wavy line rising and falling in step with them, joined by two thin vertical arrows","no text","white","flat"),
("Now hold that next to the lions.","CARD","the wavy sleep line on one side and a simple lion head on the other, with a plain vertical line between","no text","white","flat"),
("In the run up to a full moon the early night is lit, and people stay out in it longer.","GROUP","three people still moving about outside on clearly lit ground under a nearly full moon","no text","moonlit","flat"),
("In the ten nights after, the early night is black, and that is when the killing happens.","SCENE_N","flat blackness with two yellow eyes low in it and nothing else","no text","night_dark","flat"),
("Two teams who never worked together.","CARD","two separate stacks of paper files with a wide empty gap between them","no text","white","flat"),
("Two different things measured, on two different continents.","CARD","two small separate continent outlines side by side","no text","white","flat"),
("Nobody has shown the two are connected.","CARD","the two file stacks with a dotted line between them and a question mark on the line","no text","white","flat"),
("Nothing here shows it either.","CARD","the same dotted line with a red X through it","no text","white","flat"),
("But they are two halves of the same month.","CARD","one plain circle divided cleanly down the middle into a pale half and a black half","no text","white","flat"),
("There is one obvious thing left to ask, and the evidence handles it badly.","CARD","a plain question mark with a thin crack drawn through it","no text","white","flat"),

# ═════════════════ CH6 — HO CO BIET KHONG — 26 shot ═════════════════
("Did anyone back then actually read the cycle.","SCENE_A","he stands looking up at a sky with a crescent in it, head tilted back","no text","night_open","curious"),
("Nobody has been able to show it,","CARD","a plain empty rectangular frame drawn in black line on a white background, with nothing at all inside it","no text","white","flat"),
("and one famous attempt is the reason people assume otherwise.","CARD","a single old book drawn plainly, closed","no text","white","flat"),
("In the nineteen seventies a researcher named Alexander Marshack","CARD","a plain magnifying glass held over a small object","a label \"1970s\"","white","flat"),
("looked at scratch marks on Ice Age bone and antler.","SCENE_N","one piece of pale bone lying flat, drawn large, with a row of eleven short straight scratch marks cut across it, the bone rendered with fine texture while everything else stays plain","no text","white","flat"),
("He read them as notation systems,","CARD","the same row of scratches with small numbers drawn faintly above each one","no text","white","flat"),
("specifically lunar calendars, notating the passage of time.","CARD","the row of scratches with a row of moon phase circles drawn directly above it, one moon per scratch","no text","white","flat"),
("Individual lines and dots as days.","CARD","three short scratch marks with a small sun symbol above each","no text","white","flat"),
("Sequences of them as months.","CARD","a long run of scratch marks with one large bracket over the whole run","no text","white","flat"),
("It is a beautiful idea and it has never gone away.","SCENE_N","one piece of pale bone lying flat with a row of short scratch marks cut across it, alone on an empty white background","no text","white","flat"),
("It has also never been proven.","CARD","the same bone with a plain question mark beside it","no text","white","flat"),
("In 1989 another researcher published a reply in Current Anthropology.","CARD","a plain rectangular sheet of paper with one bold horizontal line across the top and eight thin ruled lines below it, nothing written","a label \"1989\"","white","flat"),
("The title of it was Palaeolithic Lunar Calendars, a Case of Wishful Thinking.","CARD","a plain rectangular sheet of paper with one bold hand-lettered headline across the top and thin ruled lines below it","the headline \"A CASE OF WISHFUL THINKING?\"","white","flat"),
("That is the whole argument, in five words, before the paper even starts.","CARD","a plain rectangular sheet of paper where the top headline line is drawn solid black and every line below it is drawn in pale grey","no text","white","flat"),
("The broader criticism is that the work over-interpreted many artifacts,","CARD","three plain small objects in a row on a white background: a stone blade, a piece of bone and a clay pot, each with one small moon symbol drawn above it","no text","white","flat"),
("finding numerical and calendrical patterns where none exist.","CARD","three plain small objects in a row on a white background: a stone blade, a piece of bone and a clay pot, each with a small moon symbol above it crossed out in red","no text","white","flat"),
("Which is the polite way of saying that if a person wants to find a moon in a row of scratches,","CARD","a random uneven row of scratch marks with a moon symbol being drawn onto it by a hand","no text","white","flat"),
("a row of scratches will usually oblige.","CARD","an uneven row of short scratch marks drawn on a white background, with one moon symbol drawn over the middle of the row","no text","white","flat"),
("So the marks are real.","SCENE_N","one piece of pale bone lying flat with a row of short scratch marks cut across it, drawn plainly with no symbols and no labels anywhere","no text","white","flat"),
("Somebody made them on purpose, and that much nobody argues with.","SCENE_A","close on his hands holding a small sharp stone against a piece of bone","no text","fire_ring","flat"),
("Whether they were cut one at a time over many nights,","CARD","one scratch mark with a moon symbol beside it, then a gap, then another scratch and another moon","no text","white","flat"),
("or in a single sitting, is part of what is in dispute.","CARD","a full row of scratch marks with one single moon symbol above the whole row","no text","white","flat"),
("And it matters, because a tally kept across a month","CARD","a row of scratch marks spread out with small gaps between each","no text","white","flat"),
("and a pattern carved in an afternoon are not the same object.","CARD","the same number of scratch marks packed tightly together with no gaps","no text","white","flat"),
("What they were counting, if they were counting, is not recoverable.","CARD","the marked bone with a plain question mark over it","no text","white","flat"),
("It may have been nights.","CARD","a small row of moon symbols","no text","white","flat"),
("It may have been kills, or debts, or nothing at all.","CARD","three plain small drawings in a row on a white background: a flat tawny animal outline, a simple clay pot, and one empty dotted square","no text","white","flat"),

# ═════════════════ KET — 16 shot ═════════════════
("The moon is doing all of it right now.","SCENE_N","one plain white full moon high on a flat deep blue sky, nothing else in frame","no text","moonlit","flat"),
("It comes up as the sun goes down, once a month,","CARD","a horizon line with a sun dropping on one side and a moon rising on the other","no text","white","flat"),
("and then loses the better part of an hour every night after that.","CARD","five stacked horizon lines with the moon symbol slightly further right on each","no text","white","flat"),
("The dark stretch arrives on time.","CARD","a row of moon phase circles with the dark ones bracketed","no text","white","flat"),
("None of that has ever needed a person to notice it.","SCENE_N","the full moon alone over completely empty ground with no figure anywhere in frame","no text","moonlit","flat"),
("Which brings it back to the walk down to the water,","SCENE_A","he walks away from the viewer toward the strip of dark water, seen from behind","no text","dusk_water","flat"),
("forty steps from camp, in the grey half hour.","SCENE_N","seen from above, the ring of stones and the thin dotted line running out from it","a label \"40 STEPS\"","dry_plain","flat"),
("Whoever made that walk did not know they were standing inside a cycle.","SCENE_A","he stands still on the path with the empty grey sky above him","no text","dusk_grey","flat"),
("They may have known that some evenings felt worse than others,","SCENE_A","close on his face, eyelids low, looking off to one side toward the treeline","no text","dusk_grey","worry"),
("and stayed in.","SCENE_A","he sits down beside the low fire with his back to the dark, knees pulled up","no text","fire_ring","flat"),
("They may have gone anyway, because water does not fetch itself.","SCENE_A","he walks out toward the water carrying an empty vessel, head down","no text","dusk_water","flat"),
("The marks on the bone do not say.","SCENE_N","the marked bone lying alone on plain ground","no text","white","flat"),
("What is certain is narrower, and much older than any of the counting.","CARD","one very long horizontal black line running the full width of the frame, with a small bracket drawn under the far left end of it","no text","white","flat"),
("For a very long stretch of human history, whether a person came back from that walk","SCENE_A","he walks back up the slope toward the small distant fire, carrying a full vessel","no text","dusk_grey","flat"),
("was decided by something nobody could reach, nobody could argue with, and everybody could see.","SCENE_N","the moon alone, high and plain, above a solid black treeline","no text","night_dark","flat"),
("And it is up there tonight, on exactly the same schedule, over a world where nobody times the walk to the water by it any more.","SCENE_N","one plain white full moon high on a flat deep blue night sky, above a solid black treeline and one narrow strip of dark water along the bottom, with no person and no animal anywhere in the frame","no text","moonlit","flat"),
]
