# -*- coding: utf-8 -*-
"""V19 NightWalk — shot data.  (line, kind, subj, text, bg, face)

kind : SCENE_A ancient | SCENE_M modern | SCENE_W woman | GROUP nhom | SCENE_N khong nguoi | CARD
bg   : fire_ring fire_edge night_open night_dark cold_night village_night modern_night modern_hall white
face : flat shock tired worry scared happy asleep dumb curious sad

Nhip muc tieu 2,8-3,0 giay/shot (do tren 3 video doi thu: 2,90 / 3,03 / 3,11).
1.491 tu / 8:20 -> ~172 shot.
Casting: NGUOI CO DAI la nhan vat chinh ~85-90%. Nguoi hien dai CHI o hook va ket.
"""

SHOTS = [

# ═══════════════════════ HOOK — 17 shot ═══════════════════════
("It is the middle of the night, fifty thousand years ago,","SCENE_A","he lies curled on his side on bare ground beside a small fire, fast asleep","no text","fire_ring","asleep"),
("and you need to pee.","SCENE_A","his eyes snap open in the dark, wide awake, one hand pressed to his stomach","no text","fire_ring","shock"),
("There is no bathroom","CARD","a plain drawn toilet with a big red X through it","no text","white","flat"),
("and no door.","CARD","a plain drawn door with a big red X through it","no text","white","flat"),
("Just a ring of orange light,","SCENE_N","seen from directly above, a small fire in the centre of one round patch of warm orange light on brown ground","no text","fire_ring","flat"),
("twenty steps across.","CARD","the same round patch of light seen from above with a thin measuring line drawn across it","a label \"20 STEPS\"","white","flat"),
("Past its edge you see nothing.","SCENE_A","he stands at the very edge of the orange light and stares out into flat blackness","a small label \"NOTHING\"","fire_edge","scared"),
("Everything out there sees you.","SCENE_N","four pairs of small yellow eyes floating in flat blackness, all pointing the same way","a small label \"EVERYTHING\"","night_dark","flat"),
("So the sensible thing is to wait.","SCENE_A","he sits back down beside the fire with his knees pulled up and his arms wrapped around them","a small label \"WAIT\"","fire_ring","worry"),
("You hold it until sunrise","SCENE_A","he sits by the dying fire with his jaw set, waiting, while the sky behind turns from navy to orange","no text","night_open","tired"),
("and walk out in daylight.","SCENE_A","he walks away across open ground under a plain pale sky, relaxed","no text","night_open","happy"),
("That is what your own body arranges for you every night of your life.","SCENE_M","the modern man lies asleep in a simple bed, completely still","no text","modern_night","asleep"),
("You sleep eight hours and it does not wake you once.","CARD","a plain clock face with a large eight-hour slice shaded in dark navy","a label \"8 HOURS\"","white","flat"),
("So why couldn't they?","SCENE_A","close on his face lit from below by firelight, looking straight out","no text","fire_ring","curious"),
("Not because they were soft, or slow, or hairless, or close to blind after sunset.","CARD","four small stick figures in a row, each with a red X beside it","no text","white","flat"),
("All of that is true. None of it is the answer.","CARD","the same four figures with one big red X drawn across the whole group","a label \"NOT IT\"","white","flat"),
("The answer is that the system fails.","CARD","a simple drawn machine outline with one crack running through the middle of it","a small label \"IT FAILS\"","white","flat"),
("It fails hardest on the coldest nights.","SCENE_A","he sits hunched beside a small fire under a cold grey-blue sky, shoulders drawn in tight","a small label \"COLDEST\"","cold_night","tired"),
("And it fails worst in the people least able to survive what was waiting outside.","GROUP","a small caveman child, a pregnant caveman woman and an old bent caveman stand in a row on dark ground","no text","fire_edge","worry"),

# ═══════════════════════ CHƯƠNG 1 — CA ĐÊM — 38 shot ═══════════════════════
("Start with the system that works,","CARD","a large hand-drawn heading band across the top of a plain frame","large text \"THE NIGHT SHIFT\"","white","flat"),
("because you are running it right now.","SCENE_M","the modern man stands plainly facing forward with one hand on his own stomach","no text","white","flat"),
("After sunset two things climb together in your blood.","CARD","two simple line graphs side by side, both curving upward from left to right","no text","dark_card","flat"),
("One is melatonin, which everybody has heard of.","CARD","one of the two rising curves circled, with a plain arrow pointing at it","a label \"MELATONIN\"","dark_card","flat"),
("The other is vasopressin, which almost nobody has.","CARD","the second rising curve circled in red with a plain arrow pointing at it","a label \"VASOPRESSIN\"","dark_card","flat"),
("Vasopressin tells your kidneys to make less urine.","CARD","two simple bean-shaped kidneys drawn in flat red-brown with a short arrow pointing at them","a label \"MAKE LESS\"","dark_card","flat"),
("Your bladder is working the same shift.","CARD","one plain rounded bladder shape drawn in flat pale yellow with a black outline","a label \"BLADDER\"","dark_card","flat"),
("It clocks on at sunset","CARD","the same bladder shape wearing a tiny drawn cap, standing beside a small punch clock","no text","dark_card","flat"),
("and has never once called in sick.","SCENE_A","he sits awake beside the small fire keeping watch while the others sleep, calm and steady","no text","fire_ring","flat"),
("Overnight it turns down the signal it sends your brain,","SCENE_A","he sleeps deeply beside the fire, one hand resting on his stomach, undisturbed","no text","fire_ring","flat"),
("so it can hold more before it says anything.","SCENE_A","he sleeps on, completely still, while the fire beside him burns low","no text","fire_ring","flat"),
("Your phone does something similar at eleven at night.","SCENE_M","the modern man lies in bed at night holding a plain rectangle phone that glows faintly","no text","modern_night","flat"),
("Do Not Disturb does not stop the messages arriving.","CARD","a plain phone rectangle with three small envelope shapes dropping into it","no text","dark_card","flat"),
("It stops the phone telling you about them.","CARD","the same phone with a plain crescent-moon icon on it and a red X over a small bell","no text","dark_card","flat"),
("That is roughly your bladder after dark.","SCENE_M","the modern man sleeps in bed with the phone lying face down on the floor beside him","no text","modern_night","flat"),
("Filling, and saying nothing.","SCENE_M","the modern man sleeps peacefully, the room quiet and dark around him","no text","modern_night","flat"),
("Now, here is the part most people get backwards.","SCENE_A","he sits up beside the fire and turns to look back over his own shoulder","no text","fire_ring","flat"),
("The reason this system exists is not predators.","CARD","a cute flat golden-yellow lion with a mane, with a big red X drawn across it","a small label \"NOT THIS\"","white","flat"),
("It exists because you cannot drink while you are asleep,","SCENE_A","he lies asleep on the ground with a simple water gourd sitting just out of reach beside him","a small label \"CANNOT DRINK\"","night_open","asleep"),
("so the body stops spending water it has no way to replace.","SCENE_A","he sleeps beside the fire with an empty water gourd lying on its side near his hand","a label \"NO REFILL\"","fire_ring","flat"),
("Nocturnal animals run the same rhythm with the hours reversed.","SCENE_N","a cute flat brown owl with a little face sitting on a branch under a night sky, wide awake","no text","night_open","flat"),
("Water was the reason it evolved.","CARD","a plain water drop drawn large in the centre with a green check mark beside it","a label \"THE REASON\"","white","flat"),
("Staying inside all night was a side effect.","SCENE_A","he lies asleep well inside the round patch of orange light, nowhere near its edge","a label \"SIDE EFFECT\"","fire_ring","flat"),
("But the side effect is the one that mattered.","SCENE_A","he sleeps inside the light while flat blackness presses right up against the edge of it","no text","fire_edge","flat"),
("So what was it worth?","SCENE_A","he sleeps beside the fire while one pair of small yellow eyes watches from the blackness beyond","a small label \"WORTH?\"","fire_edge","flat"),
("Look at the people whose bodies do not do it.","SCENE_M","the modern man sits on the edge of a bed at night with both feet on the floor, awake","no text","modern_night","tired"),
("When the vasopressin rhythm goes flat,","CARD","the rising vasopressin curve from earlier redrawn as one flat horizontal line","no text","dark_card","flat"),
("urine production does not drop after dark.","CARD","a simple bar chart with the night bar exactly as tall as the day bar","no text","dark_card","flat"),
("Those people are up three and four times a night, every night.","SCENE_M","the modern man walks across a dark bedroom floor towards a doorway, drawn mid-stride","a small label \"3-4x\"","modern_hall","tired"),
("The condition has a name.","CARD","a plain empty label plate drawn in the centre of the frame","no text","dark_card","flat"),
("Nocturnal polyuria.","CARD","the same label plate now filled with hand-lettered writing","large text \"NOCTURNAL POLYURIA\"","dark_card","flat"),
("So sleeping through the night is not something you do.","CARD","a stick figure lying asleep with a red X drawn beside its own hands","no text","white","flat"),
("It is something that gets done for you.","CARD","the same sleeping stick figure with a plain arrow coming in from outside the body","a label \"FOR YOU\"","dark_card","flat"),
("And fifty thousand years ago it was doing something more than letting you rest.","SCENE_A","he lies asleep beside the small fire inside the round patch of orange light","no text","fire_ring","asleep"),
("It was keeping a soft, slow, hairless animal","SCENE_A","he stands plainly on brown ground with nothing in his hands, looking small","no text","fire_ring","dumb"),
("with no night vision","SCENE_A","close on his face as he squints out into flat blackness and sees nothing","a small label \"NO NIGHT VISION\"","fire_edge","worry"),
("on the safe side of the firelight.","SCENE_A","he sits well inside the round orange patch, with the black beyond drawn as a hard edge","a small label \"SAFE SIDE\"","fire_ring","flat"),
("Eight hours at a stretch,","CARD","a plain horizontal bar divided into eight equal segments","a label \"8 HOURS\"","dark_card","flat"),
("and nobody had to decide anything.","SCENE_A","he lies asleep with a plain empty thought bubble above his head","a small label \"NO DECISION\"","fire_ring","asleep"),
# ═══════════════════════ CHƯƠNG 2 — CÁI LẠNH PHÁ CA TRỰC — 34 shot ═══════════════════════
("That system was working fifty thousand years ago too.","SCENE_A","he lies asleep beside the fire, still and undisturbed","no text","fire_ring","asleep"),
("So what overrode it?","CARD","a large hand-drawn question mark standing alone","no text","dark_card","flat"),
("The cold did.","CARD","one word filling the whole frame","large text \"THE COLD\"","dark_card","flat"),
("When you get cold,","SCENE_A","he stands hunched with both arms wrapped tight around himself, shivering","no text","cold_night","tired"),
("your body does something sensible that backfires here.","SCENE_A","he pulls his arms in tight against his chest against the cold, teeth set","no text","cold_night","flat"),
("To protect your heart and your brain","CARD","a simple heart shape and a simple brain shape side by side with a protective bracket drawn around both","a label \"PROTECT\"","dark_card","flat"),
("it clamps down the blood vessels near the skin.","CARD","a cross-section strip of skin with thin vessel lines in it, pinched narrow by two small arrows","a label \"CLAMP\"","dark_card","flat"),
("That is why your hands go pale","SCENE_A","he holds up both hands and stares at them, fingers drawn stiff and straight","no text","cold_night","worry"),
("and your feet go numb.","SCENE_A","he sits on cold pale ground rubbing his own bare foot with both hands","a label \"NUMB\"","cold_night","flat"),
("All that blood has to go somewhere,","SCENE_A","he stands rigid in the cold with both fists clenched at his sides","no text","cold_night","flat"),
("so it gets pushed inward.","CARD","the same body outline with the centre area filled in flat red","a label \"INWARD\"","dark_card","flat"),
("Suddenly your core is carrying more fluid than it usually does.","CARD","two body outlines side by side, the second with a much larger red centre than the first","no text","dark_card","flat"),
("Your kidneys read that as a surplus","CARD","the two bean-shaped kidneys again with a small overflow line drawn above them","a label \"SURPLUS\"","dark_card","flat"),
("and start getting rid of it.","SCENE_A","he shifts uncomfortably where he sits, one hand pressed low on his stomach","no text","cold_night","flat"),
("The name for this is cold induced diuresis.","CARD","a plain label plate filled with hand-lettered writing","large text \"COLD DIURESIS\"","dark_card","flat"),
("You have felt it every time standing outside in winter","SCENE_M","the modern man stands outside in the cold with his shoulders up and his hands in front of him","no text","cold_night","tired"),
("sent you looking for a toilet.","SCENE_M","the modern man walks quickly toward a plain doorway rectangle","no text","modern_hall","worry"),
("What took researchers a while was not whether it happens.","CARD","a green check mark beside a small drawing of the falling drops","a label \"IT HAPPENS\"","white","flat"),
("It was why.","CARD","a large hand-drawn question mark standing alone beside a small drawing of the kidneys","large text \"WHY\"","dark_card","flat"),
("For a long time the assumption was that cold simply switched the vasopressin off.","CARD","a plain toggle switch drawn in the OFF position with a thin line running to a small labelled bottle","a label \"OFF?\"","dark_card","flat"),
("The more recent work says something different, and worse.","CARD","the same toggle switch with a big red X drawn across it","no text","dark_card","flat"),
("The vasopressin is still being sent.","CARD","a small labelled bottle with three arrows still streaming out of it","a label \"STILL SENT\"","dark_card","flat"),
("The kidneys stop responding to it.","CARD","the arrows arriving at the two kidneys and bouncing off a plain wall drawn in front of them","a label \"NO ANSWER\"","dark_card","flat"),
("Researchers are still arguing about the exact mechanism,","CARD","two plain speech bubbles pointing at each other with a small question mark between them","no text","white","flat"),
("and it would be wrong to say it is settled.","CARD","a plain gavel shape with a red X drawn across it","a small label \"NOT SETTLED\"","white","flat"),
("But that it happens is not in doubt.","SCENE_A","he stands up abruptly from beside the fire, one hand on his stomach, decision made","no text","cold_night","flat"),
("And it happens at the worst possible time.","SCENE_A","he stands at the edge of the firelight on the coldest night, looking out into blackness","no text","fire_edge","flat"),
("Cold means night.","SCENE_N","a small fire burning alone on cold pale frosted ground under a deep blue-grey sky","no text","cold_night","flat"),
("Cold means the fire is the only warm thing within reach.","SCENE_A","he sits pressed close to a small fire on cold pale ground with flat blackness all around","no text","cold_night","tired"),
("So on the coldest nights,","SCENE_A","he sits hunched by a small fire, drawn small inside a very wide cold empty frame","no text","cold_night","tired"),
("the system holding a person beside that fire is the least reliable it ever gets.","CARD","a plain rope drawn with one strand visibly frayed near the middle","a small label \"WEAKEST\"","dark_card","flat"),
("Now put those two facts next to each other.","CARD","two plain empty boxes drawn side by side","no text","white","flat"),
("The cold decides whether you have to go outside.","CARD","the left box now holding a plain snowflake with a small arrow pointing out of it","a label \"COLD DECIDES\"","dark_card","flat"),
("It has no say in what is waiting when you do.","CARD","the right box holding a pair of small yellow eyes, with a red X over a small snowflake beside it","a label \"NO SAY\"","dark_card","flat"),
("That was true for everyone who ever slept beside a fire.","GROUP","five cavemen of different sizes lie asleep in a rough ring around one small fire","no text","fire_ring","asleep"),
("But some people had far less say in it than others.","GROUP","the same ring of sleepers, with three of the five figures drawn with a thin circle around them","no text","fire_ring","worry"),

# ═══════════════════════ CHƯƠNG 3 — AI KHÔNG NHỊN ĐƯỢC — 30 shot ═══════════════════════
("Start with the people that system never fully covered.","CARD","a large hand-drawn heading band across the top of a plain frame","large text \"WHO CANNOT WAIT\"","dark_card","flat"),
("A child's control over this arrives late,","CARD","a plain horizontal timeline with a small marker set far along toward the right end","a label \"LATE\"","dark_card","flat"),
("and it arrives slowly.","CARD","the same timeline with a long slow gradient arrow creeping along it","a label \"SLOWLY\"","dark_card","flat"),
("In a study of six and a half thousand children in Xi'an,","CARD","a plain map outline of China with one small pin dropped on it","a label \"XI'AN\"","white","flat"),
("nine percent of five-year-old boys","CARD","a grid of one hundred tiny stick figures with nine of them filled in flat blue","large text \"9%\"","white","flat"),
("and six percent of the girls","CARD","a second grid of one hundred tiny stick figures with six filled in flat red","large text \"6%\"","white","flat"),
("were still wetting the bed.","CARD","a plain small bed drawn with one soft irregular shape on it","no text","dark_card","flat"),
("Not occasionally.","SCENE_A","a small caveman child lies asleep on a fur mat beside the fire","no text","fire_ring","flat"),
("As a pattern.","GROUP","three small caveman children lie asleep in a row on fur mats beside the fire","a small label \"PATTERN\"","fire_ring","flat"),
("That is a modern number, from a modern city, with heating and indoor plumbing.","SCENE_M","the modern man sleeps in a warm bed with a plain radiator drawn on the wall behind him","no text","modern_night","flat"),
("A five-year-old bladder does not know about heating or plumbing.","CARD","a small bladder shape drawn beside a radiator and a tap, both crossed out with red X marks","no text","dark_card","flat"),
("It is small,","CARD","a large bladder shape and a much smaller one drawn side by side for comparison","a label \"SMALL\"","dark_card","flat"),
("and the signal telling the brain about it is not finished yet.","CARD","a thin line running from the small bladder toward a simple brain shape, the line broken partway with a gap","a label \"UNFINISHED\"","dark_card","flat"),
("It is not only children.","GROUP","a small caveman child and a pregnant caveman woman stand together on dark ground","no text","fire_edge","flat"),
("In a study of two hundred and seventy pregnant women,","SCENE_W","she stands plainly in profile with a rounded belly, one hand resting on it","no text","white","flat"),
("three out of four were getting up at night.","CARD","four small figures in a row with three of them filled in flat colour","large text \"3 IN 4\"","white","flat"),
("Under a third in the first trimester.","CARD","a simple bar chart with one short bar drawn on the left","a label \"1ST\"","dark_card","flat"),
("Three quarters by the last.","CARD","the same bar chart with a much taller bar added on the right","a label \"3RD\"","dark_card","flat"),
("A full-term uterus sits directly on the bladder.","CARD","a simple cross-section with a large rounded shape resting directly on a smaller rounded shape below it","a label \"DIRECTLY ON\"","dark_card","flat"),
("That does not wait politely until morning.","SCENE_W","she pushes herself up from lying on the ground beside a small fire, one hand on her belly","no text","fire_ring","tired"),
("Past sixty-five,","CARD","a plain number drawn large in the centre of the frame","large text \"65+\"","dark_card","flat"),
("about half of people get up at least once a night,","CARD","a grid of ten small figures with five of them filled in","large text \"HALF\"","white","flat"),
("and about a quarter get up twice or more.","CARD","the same grid with two and a half figures marked in a darker fill","large text \"A QUARTER\"","white","flat"),
("The same rhythm from earlier, flattening out with age.","CARD","the rising vasopressin curve from the first chapter redrawn beside a much flatter version of itself","no text","dark_card","flat"),
("So line those three up.","CARD","three plain empty boxes drawn in a row","no text","white","flat"),
("Small children.","GROUP","a small caveman child stands alone on dark ground","no text","fire_edge","worry"),
("Women late in pregnancy.","SCENE_W","she stands alone on dark ground with a rounded belly, one hand supporting her back","no text","fire_edge","tired"),
("The old.","SCENE_A","an old bent caveman with grey hair and a grey beard stands alone on dark ground leaning on a stick","no text","fire_edge","tired"),
("Which of those three gets back to the fire fastest?","GROUP","the child, the pregnant woman and the old man stand in a row facing the same direction, with a small fire drawn far away behind them","a label \"FASTEST?\"","fire_edge","worry"),
# ═══════════════════════ CHƯƠNG 4 — HARAMAYA — 45 shot ═══════════════════════
("Twenty steps does not sound far.","CARD","a short measuring line drawn across a plain frame with a small tick at each end","a label \"20 STEPS\"","white","flat"),
("That is because you have never been that blind.","SCENE_M","the modern man stands with both hands held out in front of him in flat blackness","no text","night_dark","scared"),
("A hyena has a mirror behind its retina.","CARD","a simple cross-section of an animal eye with a small flat silver band drawn behind it","a label \"MIRROR\"","dark_card","flat"),
("It sends the light back through a second time.","CARD","the same eye cross-section with an arrow entering, bouncing off the silver band, and leaving again","a label \"TWICE\"","dark_card","flat"),
("That is why its eyes flash in your headlights.","SCENE_N","a cute flat brown spotted hyena with a little face standing in flat blackness, its two eyes drawn as bright yellow discs","no text","night_dark","flat"),
("Yours never do.","SCENE_M","close on the modern man's face in flat blackness, his eyes drawn as two plain dark dots","no text","night_dark","flat"),
("You never grew the mirror.","CARD","a simple cross-section of a human eye with an empty space where the silver band would be, marked with a red X","no text","dark_card","flat"),
("Nothing in your eye gives you a second try at the same light.","CARD","the human eye cross-section with a single arrow entering and stopping dead","a label \"ONE TRY\"","dark_card","flat"),
("So the edge of the firelight was not the place where seeing got harder.","SCENE_A","he stands at the very edge of the round orange patch with a red X drawn over a small gradient strip beside him","no text","fire_edge","flat"),
("It was the place where seeing stopped.","SCENE_A","he stands at a hard straight line where the orange light ends and flat blackness begins","a small label \"STOPPED\"","fire_edge","scared"),
("There is one thing in this story nobody can measure,","CARD","a plain measuring ruler with a red X drawn across it","no text","white","flat"),
("and it is worth saying out loud.","CARD","a plain open speech bubble drawn large and empty","no text","white","flat"),
("Nobody knows how well a fire actually worked.","SCENE_N","a small fire drawn alone on brown ground with a large question mark standing beside it","no text","fire_ring","flat"),
("There is no study of Paleolithic campfires","SCENE_N","a small fire burning alone on brown ground with nobody near it","no text","night_open","flat"),
("and how many predators they turned back.","CARD","a cute flat golden-yellow lion with a mane beside a small fire, with a question mark between them","no text","white","flat"),
("There never will be.","SCENE_N","the same fire burned down to a few grey ashes on empty ground","no text","night_open","flat"),
("You cannot rerun the Stone Age.","CARD","a plain rewind arrow with a red X drawn through it","a small label \"NO REWIND\"","dark_card","flat"),
("But there are places where people still walk out into the dark at night,","SCENE_N","a plain dirt path leading away from two simple square houses into flat blackness","no text","village_night","flat"),
("and somebody counted.","SCENE_M","the modern man stands beside a plain dirt path at night holding an open notebook","no text","village_night","flat"),
("In the Haramaya district of eastern Ethiopia,","CARD","a plain map outline of the African continent with one small pin dropped on the eastern side","a label \"ETHIOPIA\"","white","flat"),
("three researchers spent two years recording hyena attacks on people.","CARD","three plain stick figures standing beside a large open notebook","a label \"2 YEARS\"","white","flat"),
("They finished in 2013.","CARD","nothing but the year drawn large in the centre","large text \"2013\"","dark_card","flat"),
("They recorded twenty four attacks.","CARD","a grid of twenty four small identical marks","large text \"24\"","dark_card","flat"),
("Half of those attacks happened while the person was going to the toilet in the evening.","CARD","the same grid of twenty four marks with exactly half of them filled in flat red","large text \"HALF\"","dark_card","flat"),
("The rest happened to people sleeping outdoors,","SCENE_A","he lies asleep on bare ground outside a simple square house","no text","village_night","asleep"),
("or walking between villages after dark.","SCENE_A","he walks alone along a plain dirt path with flat blackness on both sides","no text","village_night","worry"),
("Between 2010 and 2012,","CARD","a short plain timeline with two ticks and the span between them shaded","a label \"2010-2012\"","dark_card","flat"),
("twelve people in that district were killed.","CARD","a row of twelve small plain stick figures, all filled in flat dark grey","large text \"12\"","dark_card","flat"),
("Seven of them were children under the age of twelve.","CARD","the same row of twelve with seven of the figures drawn noticeably smaller","large text \"7 CHILDREN\"","dark_card","flat"),
("Seven out of twelve.","CARD","seven small figures separated out from five larger ones by a plain dividing line","large text \"7 OF 12\"","dark_card","flat"),
("The paper does not say what those seven were doing when it happened.","CARD","a plain open notebook page with an empty box on it and a question mark inside the box","no text","white","flat"),
("What it does say is that half the attacks it recorded came during an evening toilet trip.","CARD","the notebook page with one line of the tally circled and an arrow leading out of it","a label \"HALF\"","white","flat"),
("Those two facts sit next to each other.","CARD","two plain boxes drawn side by side with a clear gap between them","no text","white","flat"),
("Nobody has joined them up.","CARD","the same two boxes with a dotted line between them that stops halfway","a small label \"NOT JOINED\"","white","flat"),
("There is a second number in the same paper.","CARD","the open notebook page with a second figure written below the first","no text","white","flat"),
("Of the twenty four people attacked, eighteen were men.","CARD","a row of twenty four small figures with eighteen of them drawn taller and filled in","large text \"18 MEN\"","dark_card","flat"),
("The researchers read that as men going out to help once something had already started.","GROUP","three grown cavemen run out from beside a small fire toward flat blackness","no text","fire_edge","scared"),
("On their reading, the danger did not stop with whoever left the shelter.","CARD","a plain circle drawn around one small figure, then a second larger circle drawn around three more","no text","dark_card","flat"),
("And nobody wrote down what those households actually do about it.","CARD","a plain open notebook page left completely blank","no text","white","flat"),
("Not whether they wait for company,","GROUP","two cavemen walk out along a dirt path together, side by side","no text","village_night","flat"),
("or carry a light,","SCENE_A","he walks along a dirt path at night holding a small burning torch out in front of him","no text","village_night","flat"),
("or simply hold on.","SCENE_A","he lies awake on the ground inside a simple square house, eyes open, not moving","no text","village_night","flat"),
("A team spent two years in that district and counted the attacks, not the arrangements.","CARD","a full tally of marks on one side and a completely empty box on the other, with a plain line between them","a label \"COUNTED / NOT\"","dark_card","flat"),
("That district has roads, a hospital, and electricity in some houses and not others.","SCENE_N","two simple square houses, one with a small yellow window square lit and one dark, a plain road line running past them","no text","village_night","flat"),
("The list it shares with fifty thousand years ago is much shorter.","GROUP","a caveman beside a fire on one side and a modern villager beside a house on the other, both facing the same dark path","no text","village_night","flat"),
("An animal that hunts at dusk,","SCENE_N","a cute flat brown spotted hyena with a little face standing on dry tan ground under a dim sky","no text","village_night","flat"),
("a shelter you have to leave,","SCENE_N","one simple square house with a plain open doorway and an arrow leading out of it","no text","village_night","flat"),
("and no light on the path.","SCENE_N","a plain dirt path running straight into flat blackness with nothing on it","no text","night_dark","flat"),

# ═══════════════════════ KẾT — 18 shot ═══════════════════════
("So that is the answer.","CARD","a large hand-drawn heading band across the top of a plain frame","large text \"THE ANSWER\"","dark_card","flat"),
("They could not hold it until morning because on cold nights the body would not let them.","SCENE_A","he stands up from beside a small fire on cold pale ground, one hand on his stomach","no text","cold_night","tired"),
("And the ones who could hold it least were small, or pregnant, or old.","GROUP","the child, the pregnant woman and the old man stand together on cold pale ground","no text","cold_night","worry"),
("That is not a story about bravery.","SCENE_A","he walks out into the dark with his shoulders hunched, plainly not brave","no text","fire_edge","flat"),
("Nobody chose any of it.","SCENE_A","he stands at the edge of the light with both empty hands open at his sides","a small label \"NO CHOICE\"","fire_edge","flat"),
("You will never take that walk,","SCENE_M","the modern man stands in a plain lit bedroom doorway, relaxed","no text","modern_night","flat"),
("because there is nothing outside your bedroom.","SCENE_M","the modern man looks out of a plain doorway into an ordinary empty hallway","no text","modern_hall","flat"),
("But tonight you will get up in the dark","SCENE_M","the modern man sits up on the edge of a bed in a dark room, both feet finding the floor","no text","modern_night","tired"),
("and go to the bathroom.","SCENE_M","the modern man walks across a dark floor toward a plain doorway rectangle","no text","modern_hall","tired"),
("Thirty seconds,","CARD","a plain clock face with one small thirty-second slice shaded","a label \"30 SECONDS\"","dark_card","flat"),
("on a floor you have crossed ten thousand times.","CARD","a plain strip of floor with a long trail of small footprint shapes running along it","large text \"10,000\"","dark_card","flat"),
("Watch what your legs do on the way back.","SCENE_M","close on the modern man's legs mid-stride on a dark floor","no text","modern_hall","flat"),
("They speed up.","SCENE_M","the same legs drawn mid-stride with three short motion lines behind them","a small label \"FASTER\"","modern_hall","flat"),
("You will not decide to do that,","SCENE_M","the modern man walking quickly with a plain empty thought bubble above his head","no text","modern_hall","flat"),
("and nothing in that house has ever chased anyone.","SCENE_M","the modern man stands in an ordinary empty hallway with nothing else in the frame","no text","modern_hall","flat"),
("Nobody can prove where the hurry came from.","SCENE_M","the modern man stands still in the hallway looking down at his own feet","no text","modern_hall","flat"),
("Hurrying does not fossilise.","CARD","a plain fossil shape in stone with a red X drawn across it","a small label \"NO FOSSIL\"","dark_card","flat"),
("But somebody made that walk before you, on a cold night,","SCENE_A","he walks away from a small fire into flat blackness on cold pale ground","no text","cold_night","worry"),
("and did not always come back.","SCENE_N","one small fire burning alone on cold pale ground with an empty patch of flattened ground beside it","no text","cold_night","flat"),
("And you are still walking a little faster, on a cold floor, on the way to bed.","SCENE_M","the modern man walks back toward a bed across a dark floor, drawn mid-stride with two short motion lines","no text","modern_hall","flat"),
]
