# -*- coding: utf-8 -*-
"""BẢN SẮC HÌNH ẢNH CỦA KÊNH — MỘT nguồn duy nhất cho MỌI video.

VÌ SAO CÓ FILE NÀY
──────────────────
Trước 08/08/2026, các khối STYLE / CONSIST / NEG nằm trong `build_prompts.py` của
TỪNG video. Đo ngày 08/08: chúng đã trôi thành BA bản khác nhau —

    STYLE_CARD    V17  9.563 ký tự  ·  V18 12.232  ·  V19 12.644
    STYLE_SCENE   V17 10.326        ·  V18 12.922  ·  V19 13.334
    NEG_CARD      V17  5.140        ·  V18  5.944  ·  V19  6.356

Tức ba video được gen bằng BA định nghĩa style khác nhau, và không ai quyết định
điều đó — nó xảy ra vì chép file rồi sửa dần. Với kênh faceless thì NHẤT QUÁN HÌNH
ẢNH là tài sản lớn nhất.

⛔ SỬA FILE NÀY LÀ ĐỔI BẢN SẮC CỦA CẢ KÊNH. Không sửa cho riêng một video.
   Muốn một video khác đi thì đổi `subj`/`text` trong shot_data.py của video đó.

SỬA 10/08/2026 — sau khi mổ 102 thumbnail của 13 kênh cùng ngách:
  · TÓC MỞ KHOÁ  → hằng số `HAIR` + `HAIR_NEG`, đổi MỘT LẦN mỗi video rồi để yên.
    Lý do: tóc có mặt ở CẢ hai phía thắng-chìm nên không đo được gì; Axen KHÔNG TÓC
    được 32.481 view/ngày, cao nhất trong bộ.
  · KHUÔN MẶT   → `FACE_BUILD`, trường phái Mack · Stickly · Neon Rush do chủ chọn.
    Đầu MÉO (không tròn compa) · mắt BẦU DỤC ĐỨNG · có MÍ TRÊN · con ngươi LỆCH TÂM
    nhìn vào cảnh chứ không nhìn ống kính · miệng LỆCH một bên · nét viền dày mảnh
    không đều · tư thế bất đối xứng.
  · ⚠️ SỬA MỘT LỖI CŨ: dict `FACE` ghi "two dot eyes" ở 8/10 mục, tức mỗi shot đều
    dán một câu ĐÈ NGƯỢC lại CHARACTER LOCK ("never tiny dots"). Nay cả 10 mục nói
    bằng ngôn ngữ mí mắt + hướng con ngươi, khớp với khối nhân vật.
  · KHÔNG đụng tới STYLE_SCENE / STYLE_CARD / BG / framing — đó là cách vẽ CẢNH,
    thuộc quyết định khác.

Bản này lấy từ V19 (mới nhất, đã qua các sửa 30/07 và 07-08/08).
V17 và V18 giữ bản riêng của chúng làm HIỆN VẬT — prompt phải khớp thứ đã thật sự
dùng để gen ảnh, không được sửa lại lịch sử.
"""

# ⚠️ CHỈ DÙNG CHO THUMBNAIL. Đo 10/08 trên khung video thật của Mack và Stickly:
#    bão hoà trung vị VIDEO 30,2% (90% dưới 53-71%) — CAO HƠN thumbnail (23-27%).
#    Khung video CẦN màu rực để làm ký hiệu: dấu ✗ ĐỎ, dấu ✓ XANH, lửa cam.
#    Áp trần này cho video là bóp chết chính bộ ký hiệu đó.
# 🔴 BÁC 12/08/2026 — đo 23 QUẢ NỔ THẬT của ngách (250K-7,8 triệu view, tải bản 1280px):
#    bão hoà trung vị **36,1%**, dải 0-64%. Tức quả nổ KHÔNG hề nhạt màu.
#    Con số "thumbnail 23-27%" của bản 10/08 đo trên tập gồm cả kênh trung vị 1 vpd,
#    nên nó đo "màu của kênh yếu", không phải "màu của quả nổ".
#    Và thumbnail của ta đo được **38,6%** — tức đang ngang quả nổ, KHÔNG cần hạ.
#    ⛔ Ép desaturate là kéo ngược. Giữ tên hằng số cho khỏi vỡ chỗ gọi, đổi nội dung.
SAT_CEILING = ("Colours are rich and saturated like poster paint straight from the pot, warm and "
               "earthy rather than neon: firelight orange, clay brown, dry-grass tan, deep night "
               "blue. Nothing is washed out or greyed down, and nothing is candy pink or pure cyan. ")

# ── STYLE LOCK — 🔴 THÊM 11/08/2026 ──────────────────────────────────────
# Vì sao: quy trình cũ neo nét vẽ bằng ẢNH THAM CHIẾU trong Google Flow
# (videos/Video18_Sleep/_cu/PROMPT_NGAN_dung_kem_anh_ref.txt: "để Flow học nét vẽ từ
# ẢNH, không phải từ chữ"). Chủ đã bỏ phần đó trong Flow, nên thứ ảnh ref từng gánh
# nay phải nằm trong chữ, nếu không model rơi về mặc định của nó: vector sạch, tô
# đều tăm tắp, bóng số.
# ⚠️ KHỐI NÀY CHỈ NÓI CÁCH VẼ. Không thêm một luật nội dung nào — bài học V18: hai
#    lỗi nặng nhất đều là luật tự thêm. Và tuyệt đối không dùng ba chữ cartoon /
#    clean / smooth: khung 4K của đối thủ cho thấy nét RUN TAY, không phải nét sạch.
# Đặt ở ĐẦU prompt (trọng số cao nhất), trước cả khối nhân vật.
STYLE_LOCK = (
    "ART STYLE - this is the single most important instruction and it overrides any default look: "
    "the whole picture is a rough hand-drawn doodle, made by ONE person with ONE black marker in a "
    "few quick strokes, the way a teacher sketches on a whiteboard. "
    "Every line is drawn freehand and shows it: the stroke WOBBLES, its thickness varies along its "
    "own length, circles are visibly out of round, straight lines drift, and some strokes overshoot "
    "slightly at the corners where two lines meet. Nothing is measured, traced or mechanically even. "
    "Colour is laid down like a child colouring with a marker: FLAT SOLID patches, put down in one "
    "pass, and the fill does not line up perfectly with the outline - here and there it stops a "
    "little short of the line or runs a little past it. "
    "Low finish on purpose. No vector art, no digital gradients, no airbrushing, no glow, no texture "
    "overlay, no soft blur, no glossy or plastic surfaces, no 3D shading, no rendered lighting on "
    "the drawing itself. It must look drawn by a human hand in a hurry, never generated by a "
    "computer. ")

STYLE_SCENE = (
    "A hand-drawn 2D explainer frame that looks drawn with a digital felt-tip marker: every outline "
    "is solid BLACK with slightly WOBBLY, uneven thickness, never the smooth uniform look of vector "
    "art. The environment is built from FLAT BLOCKS OF COLOUR with extremely low detail: only what "
    "the scene line below names and nothing more, nothing layered, no "
    "depth, no texture. Stars are plain white dots. Fire is a wobbly orange shape with a yellow "
    "centre. A tree is one brown line for a trunk with a green cloud on top. Flat solid fills, no "
    "gradients, no shadows. 16:9. ")

# Thẻ: phẳng, trắng, chữ tay. Đây là chỗ DUY NHẤT được phẳng.
STYLE_CARD = (
    "A hand-drawn explainer CARD on a plain WHITE background, drawn with the same confident "
    "medium-bold black ink outline as the rest of the series. Simple flat hand-drawn shapes, "
    "hand-lettered marker text, generous empty white space, nothing photographic. 16:9. ")

# ── TÓC — 🔓 MỞ KHOÁ 10/08/2026 (chủ chốt: "tóc có thể tự do sáng tạo") ────
# Bằng chứng: mổ 102 thumbnail/13 kênh — tóc xuất hiện ở CẢ hai phía thắng-chìm
# nên không đo được gì. Bờm viền (Mack) thắng · mảng trùm (NeonRush) thắng ·
# sợi rủ trước mặt (Stickly) thắng · KHÔNG TÓC (Axen) thắng cao nhất 32.481 vpd.
#
# ⚠️ TỰ DO GIỮA CÁC VIDEO — KHOÁ TRONG CÙNG MỘT VIDEO.
#    Đổi HAIR + HAIR_NEG ở đây một lần cho mỗi video, rồi để yên.
#    Đổi giữa chừng = drift = đúng lỗi file này sinh ra để chặn.
# 🔴 HẠ VỀ LANE KHUNG VIDEO 11/08/2026 — chủ bắt được: bản trước là khối đúc cho
#    THUMBNAIL (bờm nhiều sợi trùm hai bên mặt như mũ trùm) mà lại chạy cho cả 202
#    khung video. Khung video của Mack · Stickly là NGƯỜI QUE ĐƠN GIẢN; chi tiết cao
#    chỉ dành cho thumbnail, và chỗ để đổ chi tiết là VẬT KỂ CHUYỆN, không phải người.
HAIR = ("MEDIUM BROWN, a SMALL messy tuft of a few separate wavy strands sitting ON TOP of "
        "the head with ragged pointed ends; it does NOT hang down over the sides of the face "
        "and does NOT frame the face like a hood; the white circle of the face stays fully "
        "visible and mostly bare")
HAIR_NEG = ("no hedgehog hair, no spiky hair ball on top of the head, no fine radiating hair needles, "
            "no smooth bob, no long hair hanging past the jaw, no mane framing the face, "
            "no hair covering both sides of the head, ")

# Tóc LUÔN vẽ theo cách này, dù chọn kiểu gì — đây là kỹ thuật, không phải kiểu.
HAIR_HOW = ("The hair is always drawn as SEPARATE LOOSE STRANDS rather than one solid block, and it "
            "REACTS to the weather in this shot instead of sitting still. ")

# ── KHUÔN MẶT — trường phái MACK · STICKLY · NEON RUSH (chốt 10/08/2026) ───
# Chín đặc điểm mổ ở 1280px. Thứ đắt nhất là (3): con ngươi LỆCH TÂM.
# 🔴 HẠ VỀ LANE KHUNG VIDEO 11/08/2026 — cùng lý do với HAIR ở trên. Bản trước tả mặt
#    ở độ chi tiết của một khung CẬN thumbnail (oval lệch, cằm thon, viền dày mỏng đổi
#    theo chỗ, mắt oval TO). Giữ lại đúng ba thứ đã kiểm chứng: con ngươi LỆCH TÂM,
#    mắt KHÔNG nhìn ống kính, biểu cảm nằm ở LÔNG MÀY chứ không ở miệng.
FACE_BUILD = (
    "the head is ONE LARGE ROUND white circle with a slightly wobbly hand-drawn outline, "
    "never a compass-perfect circle; NO neck; "
    "eyes = two SMALL oval white eyes set well apart, each with a small black pupil sitting "
    "OFF-CENTRE so the character is clearly LOOKING AT SOMETHING IN THE SCENE and NEVER at the "
    "viewer; a short curved upper eyelid line over each eye; "
    "two thin curved eyebrows, INNER ends raised, carrying the emotion; one short mouth line OFF "
    "TO ONE SIDE, never centred; no nose, no ears; the whole face is made of FEW simple marks and "
    "is never rendered, shaded or detailed; ASYMMETRIC pose with one readable hand gesture. ")

# ── NHÂN VẬT (lặp Y NGUYÊN mọi lần xuất hiện) ─────────────────────────────
ANCIENT = (
    "EXACTLY ONE PERSON: one head, one body, two arms, two legs. Never two heads, never a second "
    "figure. CHARACTER LOCK - fixed in every image, only pose and expression change: "
    "(1) the face is filled SOLID WHITE; " + FACE_BUILD +
    "(2) hair = " + HAIR + "; " + HAIR_HOW +

    "(7) ONE garment only: a ragged brown animal-hide tunic over the torso with a torn jagged hem, "
    "a strap over one shoulder; "
    "(8) arms and legs = THIN single black lines, slightly crooked, no joints; "
    "(9) small white mitten hands and small white oval feet, filled the SAME SOLID WHITE as the "
    "head, never skin-coloured, never peach or tan, always barefoot; "
    "(10) never add a beard, necklace, headband, boots or shirt. "
    "Every line is drawn by hand with a slightly wobbly, uneven stroke, never a computer-perfect "
    "shape. "
    "This is the recurring caveman of the series. ")

MODERN = (
    "EXACTLY ONE PERSON: one head, one body, two arms, two legs. Never two heads, never a second "
    "figure. CHARACTER LOCK - fixed in every image, only pose and expression change: one LARGE round "
    "hand-drawn circle for a head, filled SOLID WHITE with a slightly wobbly uneven outline, "
    "completely BALD with NO hair; NO neck; face = two "
    "small black dot eyes placed OFF-CENTRE so he is looking at something in the scene and not at "
    "the viewer, thin eyebrows with the inner ends raised, one small mouth set off to one side; a BARE thin black stick-line body with "
    "NO clothes unless this shot names one; thin single-line arms and legs, no joints; small "
    "mitten hands, small oval feet. This is the recurring modern guy of the series. ")

WOMAN = (
    "EXACTLY ONE PERSON: one head, one body, two arms, two legs. Never two heads, never a second "
    "figure. CHARACTER LOCK - a caveman woman built to the same fixed rules as the recurring "
    "caveman: the face is filled SOLID WHITE; " + FACE_BUILD +
    "her hair = " + HAIR + ", and it falls PAST THE SHOULDERS; " + HAIR_HOW +
    "ONE garment only, a ragged brown hide wrap with a torn jagged hem; "
    "arms and legs = THIN single black lines, no joints; small white mitten hands and small white "
    "oval feet, filled the SAME SOLID WHITE as the head, never skin-coloured; always barefoot. "
    "This is the recurring caveman woman of the series. ")

GROUP = (
    "EXACTLY ONE HEAD PER PERSON. Every figure has one head, one body, two arms, two legs. No two "
    "heads on one body, no conjoined figures. CHARACTER LOCK - EVERY caveman built to the same "
    "fixed rules: the face is filled SOLID WHITE; " + FACE_BUILD +
    "hair = " + HAIR + "; " + HAIR_HOW +
    "ONE garment only, a ragged brown hide tunic with a torn jagged hem; arms and "
    "legs THIN single black lines, slightly crooked, no joints; small white mitten hands and small "
    "white oval feet filled the SAME SOLID WHITE as the head, never skin-coloured, barefoot; never "
    "add beards, necklaces, headbands or boots. Give EVERY face in the group a DIFFERENT expression "
    "so the group reads as real people, not copies. Tell them apart by height, hair length and hair "
    "colour: grey strands for the old ones, longer strands for the women, smaller bodies for the "
    "children. ")


# ── NGƯỜI TRONG KHUNG THẺ — 🔴 VÁ 11/08/2026 ──────────────────────────────
# Trước: 126/202 khung CARD của V19 chỉ nhận câu mơ hồ "Any person shown is the same
# stickman with a LARGE round white head" — KHÔNG tóc, KHÔNG khố, KHÔNG quy cách mặt.
# Hậu quả: khung cảnh ra người cổ đại tóc nâu mặc khố, khung thẻ ra người que trắng
# trọc đầu. Hai nhân vật khác nhau đổi qua đổi lại suốt bài.
# Nay khung thẻ dùng ĐÚNG khối nhân vật, nhưng nói CÓ ĐIỀU KIỆN để không ép vẽ người
# vào những thẻ vốn chỉ có sơ đồ.
PERSON_IN_CARD = (
    "IF the card needs no person, draw none. IF any person appears anywhere in this card, "
    "that person is drawn to these exact fixed rules and no others: " + FACE_BUILD +
    "hair = " + HAIR + "; ONE garment only, a ragged brown animal-hide tunic over the torso "
    "with a torn jagged hem, a strap over one shoulder; arms and legs = THIN single black "
    "lines, slightly crooked, no joints; small white mitten hands and small white oval feet, "
    "filled the SAME SOLID WHITE as the head, never skin-coloured, never peach or tan, always "
    "barefoot; never add a beard, necklace, headband, boots or shirt. "
    "Never a bald plain stick figure, never a person without hair, never a person without the "
    "hide tunic. Every line is drawn by hand with a slightly wobbly, uneven stroke, never a "
    "computer-perfect shape. This is the recurring caveman of the series. ")

# ── NEG ───────────────────────────────────────────────────────────────────
# Đã BỎ 'no country borders' và 'no inset panel': đo được là đối thủ CÓ dùng.
NEG_SCENE = ("NEG: NO TWO HEADS ON ONE BODY, no conjoined figures, no duplicate character, no "
             "mirrored copy, no split-screen, no collage, no photorealism, no 3D, no anime, no "
             "Disney or Pixar style, no glossy render, no stock clipart, no solid black pictogram "
             "people, no sepia, no brown monochrome, no pencil "
             "sketch, no charcoal, no cross-hatching, no watercolour, no aged paper, no vintage "
             "engraving, no skin-coloured hands or feet, no peach or tan skin anywhere, NO MODERN PERSON OF ANY KIND, no bald smooth head, no person without hair, no sweater, no hoodie, no t-shirt, no jumper, no trousers, no jeans, no shoes, no naked pink body, no realistic human face, no blank featureless face, NO ANIMAL OF ANY KIND unless this shot names one, no fox, no bear, no cat, no dog, no bird, no elephant, no pet, " + HAIR_NEG + "no large round white eyes, no eyes looking straight at the viewer, no symmetrical centred mouth, no extra limbs or fingers, no blood, no gore, no watermark, no logo, no "
             "frame border, no subtitle bar, 16:9. ")

NEG_CARD = ("NEG: no photograph, no photorealism, no 3D render, no stock clipart, no icon-pack art, "
            "no corporate infographic style, no glossy icons, no solid black pictogram people, "
            "no gradient background, no computer font for the headline, no watermark, no logo, "
            "no subtitle bar, NO MODERN PERSON, no bald smooth head, no person without hair, "
            "no sweater, no hoodie, no t-shirt, no trousers, no shoes, no peach or tan skin, "
            "no realistic human face, "
            # 🔴 khung 173 lô 2 in NGUYÊN chữ hướng dẫn lên hình: "HAND-DRAWN EXPLAINER CARD /
            # CONFIDENT BLACK INK OUTLINE / HEADLINE LINE / PALE GREY LINES". Model đọc phần
            # mô tả STYLE thành nội dung phải vẽ. Chặn thẳng bằng tên các cụm đó.
            "never write the words HAND-DRAWN, EXPLAINER, CARD, OUTLINE, HEADLINE, STYLE, "
            "PROMPT, LINES or any instruction word anywhere in the picture, "
            "the only words allowed are the ones named in TEXT, 16:9. ")

# ── BẢNG MÀU — đo thật trên 12 quả thắng của Mack · Stickly · Neon Rush ───
# (chủ chốt 10/08: "màu bg phải giống 3 kênh đó")
#
#   BÃO HOÀ TRUNG VỊ   Mack 23% · Stickly 27% · Neon Rush 27%
#                      SKETCHAPIENS 37%, và 10% số điểm ảnh vượt 86%  ← chỗ lệch
#   SÁNG TRUNG VỊ      42-55%, cả bốn kênh bằng nhau → sáng KHÔNG phải chỗ lệch
#
# Nghĩa là: ta không sai ở độ sáng, ta sai ở CHỖ MÀU QUÁ RỰC. Vài quả có mảng
# cyan/đỏ gần bão hoà tối đa; ba kênh kia không có điểm nào như thế.
# ⚠️ ĐÂY LÀ HỌ MÀU + TRẦN BÃO HOÀ, KHÔNG PHẢI MÀU MẶC ĐỊNH CỦA VIDEO.
#    Không video nào "mặc định nâu" hay "mặc định đêm". CẢNH TRONG KỊCH BẢN quyết
#    dùng mã nào: mưa → rain_blue · đêm → night_blue · hang → brown · đồng cỏ → tan.
#    Thứ duy nhất áp cho MỌI video là SAT_CEILING ở trên.
# Màu xương sống, đo được (chiếm 15-29% khung ở quả thắng):
PALETTE = {
 "tan":        "#C4A870",   # đất khô, cỏ cháy — màu hay gặp nhất của cả ba kênh
 "brown":      "#8C7054",   # đất ẩm, da thú, thân cây
 "brown_dark": "#705438",   # bóng đổ, trong hang
 "olive":      "#707054",   # bụi cây, cỏ già
 "olive_dark": "#545438",   # tán lá tối
 "straw":      "#C4C470",   # cỏ vàng — chữ ký của Neon Rush
 "sky_pale":   "#C4E0FC",   # trời nhạt, chỉ dùng làm dải mỏng phía trên
 "rain_blue":  "#54708C",   # trời mưa (Mack RAIN AGAIN)
 "night_blue": "#54548C",   # đêm — vẫn XỈN, không phải navy rực
 "green_mute": "#70A854",   # cây cỏ, đã giảm bão hoà
}

# ── NỀN CẢNH ──────────────────────────────────────────────────────────────
# ⚠️ BẢNG MÀU là hằng số của kênh (học được). CHỌN entry nào cho shot nào thì
#    KỊCH BẢN quyết — không có tỉ lệ chuẩn, không có mặc định. Xem
#    kho/3_bangchung/THUMB_TEARDOWN_2026-08-10/KETLUAN.md và skill thumbnail
#    (bảng "cái gì học được / cái gì kịch bản quyết").
BG = {
 # ── NGÀY, ĐẤT KHÔ (thêm 10/08 — đúng bảng màu ba kênh) ──
  # ── CHẠNG VẠNG (mạch chính của V19-Moon) ──
 "dusk_grey":  ("one flat band of colourless pale grey sky low across the top, over a wide flat block of "
               "dim olive-brown ground " + PALETTE["olive"] + ", with a solid dark treeline as one flat "
               "shape along the horizon and no detail inside it"),
 "dusk_water": ("a flat strip of still dark water " + PALETTE["rain_blue"] + " along the bottom, a flat "
               "band of dim grey sky above, and a solid black treeline between them"),
 "moonlit":    ("a flat block of deep blue night sky with one plain white circle for a full moon, over "
               "flat pale grey-blue ground bright enough to see the shapes on it"),
 "savanna_day": ("one flat band of pale sky " + PALETTE["sky_pale"] + " across the top third, over a wide "
               "flat block of dry tan ground " + PALETTE["tan"] + ", with two or three muted olive "
               + PALETTE["olive"] + " shrubs and one distant hill in " + PALETTE["brown"]),
 "dry_plain":  ("a wide flat block of dry tan ground " + PALETTE["tan"] + " meeting a low horizon, with "
               "straw-yellow " + PALETTE["straw"] + " grass tufts drawn as a few loose V strokes"),
 "cave_warm":  ("flat blocks of warm brown " + PALETTE["brown"] + " cave wall with deeper "
               + PALETTE["brown_dark"] + " in the recesses, and one darker opening at one side"),
 "rain_day":   ("a flat block of grey-blue rain sky " + PALETTE["rain_blue"] + " over wet olive-brown "
               + PALETTE["olive"] + " ground with a few pale puddles"),
 # ── ĐÊM & LỬA (mạch chính của V19) ──
 "fire_ring":  ("one flat block of very dark navy filling most of the frame, and in the middle a small "
               "fire drawn as a wobbly orange shape with a yellow centre on a few grey stones, casting "
               "a soft round patch of warm orange on a flat strip of medium-brown ground"),
 "fire_edge":  ("a warm orange patch of firelight on flat brown ground on one side, and on the other "
               "side a flat block of almost-black navy with nothing drawn in it at all"),
 "night_open": ("a flat block of midnight-blue night sky with plain white dots for stars and a small "
               "white crescent moon, over one flat strip of medium-brown ground, and one tree drawn as "
               "a brown line with a dark green cloud on top"),
 "night_dark": "a flat block of almost-black dark navy filling the whole frame, with nothing else drawn in it",
 "cold_night": ("a flat block of cold blue-grey night sky with a few white star dots, over one flat "
               "strip of pale frosted grey-brown ground, and one bare tree drawn as a brown line with "
               "a few bare twigs"),
 # ── HARAMAYA (huyện hiện đại, ban đêm) ──
 "village_night": ("a flat block of dark navy night sky over one flat strip of dry tan ground, with two "
               "very simple square houses drawn in plain black lines, one small yellow window square, "
               "and a plain dirt path leading away into the dark"),
 # ── HIỆN ĐẠI (khách mời — chỉ hook và kết) ──
 "modern_night": ("a flat block of dark blue-grey bedroom wall, a simple bed drawn in a few black lines, "
               "and one plain rectangle for a doorway with a darker rectangle inside it"),
 "modern_hall": ("a flat block of dark blue-grey wall, one flat strip of pale grey floor, and a plain "
               "open doorway rectangle at one end"),
 # ── CƠ THỂ / KHÁI NIỆM ──
 "dark_card":  ("a flat block of very dark navy filling the entire frame with generous empty space; "
               "every line, shape and letter in this image is drawn in WHITE or pale cream marker on "
               "top of that dark navy, not in black"),
 "white":      "a plain WHITE background with generous empty space",
}

# ── THUMBNAIL — KHỐI RIÊNG, CỐ Ý KHÁC STYLE_SCENE ────────────────────────
# ⛔ ĐỪNG HỢP NHẤT VỚI STYLE_SCENE. Trích khung video thật của Mack và Stickly
#    ngày 10/08 cho thấy CÙNG MỘT KÊNH dùng HAI ngữ pháp hình khác hẳn nhau:
#
#      KHUNG VIDEO  →  nền TRẮNG hoặc MỘT mảng phẳng tuyệt đối · không chiều sâu ·
#                      không bóng đổ · không nguồn sáng · đầy đồ hoạ dạy học
#                      (bản đồ, mũi tên, thẻ chữ, timeline, dấu ✗ đỏ) · chữ khắp nơi
#      THUMBNAIL    →  có LỚP · có NGUỒN SÁNG thật · có bóng đổ · có vignette ·
#                      chi tiết KHÔNG ĐỀU (một vật vẽ kỹ, người vẽ trơn)
#
#    Nên STYLE_SCENE giữ nguyên "flat, no depth, no shadows" — nó ĐÚNG, và nó
#    khớp đúng thứ Mack/Stickly làm trong video. Chỉ thumbnail mới được dựng lớp.
STYLE_THUMB = (
    "A hand-drawn 2D thumbnail illustration in the same black marker line as the series, but "
    "rendered with DEPTH, unlike the flat frames inside the video: build the scene in three "
    "layers (a dark foreground edge, the subject in the middle, a lighter distance behind), "
    "lit by ONE visible light source inside the frame (a campfire, a low sun) so surfaces "
    "facing it are warm and bright and everything turned away falls into cooler shade, with "
    "soft cast shadows on the ground and a slight darkening at the four corners. "
    "ONE object in the frame is drawn with FAR more detail than everything else — fine texture, "
    "individual hairs or grain, its own highlight — while the people stay plain and untextured, "
    "so the eye lands on that object first. "
    "Put a cool blue-grey area (rain, night sky, a cave mouth) somewhere in the SAME scene so "
    "warm and cold sit side by side; this is NOT a split screen, it is one continuous place. "
    "Small storytelling props scattered along the bottom edge. " + SAT_CEILING + "16:9. ")

THUMB_TEXT = (
    "Large hand-lettered ALL-CAPS marker text across the TOP of the frame, filling most of the "
    "width and about a fifth of the height, with a thick black outline: BRIGHT YELLOW when the "
    "area behind it is warm, WHITE when the area behind it is sky or grey. ")

THUMB_NEG = ("NEG: no modern people, no modern objects of any kind (no bed, no phone, no shoes, "
             "no toothbrush, no glasses, no camera, no cup), no split screen, no side-by-side "
             "comparison, no before-and-after layout, no photographic elements, no real photos, "
             "no animal alone without a person, no Roman or Greek or gunpowder-era setting, "
             "no skulls, no gore. ")

# ── KHUNG HÌNH ────────────────────────────────────────────────────────────
def framing(kind, subj, thuan=False):
    s = subj.lower()
    # 🔴 VÁ 12/08/2026 — ĐỌC prompt 002 mới thấy: khung cảnh thuần vừa ghi "THIS FRAME HAS
    # NO PEOPLE IN IT" thì ngay sau đó framing lại bảo "the figure large and roughly centred
    # ... around HIM". Prompt TỰ CÃI NHAU, và model có cớ để vẽ người ra.
    # grep không bao giờ bắt được lỗi này vì cả hai vế đều "đúng" khi đứng riêng.
    if thuan:
        if any(k in s for k in ("wide","landscape","open ground","empty")):
            return ("Framing: a WIDE establishing shot of the empty place itself, plenty of open "
                    "ground and sky, no figure anywhere in it. ")
        if any(k in s for k in ("close","large","drawn large")):
            return ("Framing: a tight CLOSE-UP on the object named above, filling most of the "
                    "frame, no figure anywhere in it. ")
        return ("Framing: a MEDIUM WIDE shot of the place itself with the horizon low in the "
                "frame, the scene readable and empty of people. ")
    if kind.startswith("SCENE") or kind == "GROUP":
        if any(k in s for k in ("wide","camp","seen small","at a distance","whole band","landscape")):
            return ("Framing: a WIDE establishing shot, the figures fairly small inside a large "
                    "environment, plenty of world visible around them. ")
        if any(k in s for k in ("close","his own hand","holding one hand","face fills")):
            return "Framing: a tight CLOSE-UP, the subject filling most of the frame. "
        if any(k in s for k in ("sitting","kneeling","lying","crouch","seated")):
            return ("Framing: a MEDIUM shot from slightly above, the figure large in frame with the "
                    "ground and surroundings clearly visible. ")
        return ("Framing: a MEDIUM shot, the figure large and roughly centred, with the environment "
                "readable behind and around him. ")
    if "map" in s:
        return "Framing: the map centred and LARGE, filling most of the frame. "
    if any(k in s for k in ("cross-section","timeline","chart","diagram")):
        return "Framing: the diagram centred and LARGE, drawn nearly edge to edge. "
    if "row of" in s or "in a row" in s:
        return "Framing: the items in ONE straight horizontal row across the middle, evenly spaced. "
    if "title card" in s or "text filling" in s or "headline" in s:
        return "Framing: the lettering fills most of the frame. "
    return "Framing: one subject centred and drawn LARGE, generous empty white space around it. "

LETTER = ("All lettering is IRREGULAR HAND-LETTERED marker writing, each letter drawn by hand and "
          "slightly uneven, NOT a computer font. Spell it EXACTLY as written above, no extra words, "
          "no gibberish letters. ")

SAME_HAND = ("Every object, icon and diagram shape is drawn BY HAND in the same style and the same "
             "black ink outline as the characters in this series. Any person shown is the same "
             "stickman with a LARGE round white head and thin stick limbs, NEVER a solid black "
             "pictogram figure. ")

# ── BIEU CAM (deadpan la mac dinh; suc bieu cam nam o MAT) ───────────────
# Moi shot PHAI chon mot cai. Khong co "trung tinh".
FACE = {
 "flat":   "FACE: eyelids level across the top of the eyes, pupils looking slightly to one side, eyebrows level, mouth one short straight line set off to one side. ",
 "shock":  "FACE: eyelids lifted clear of the eyes so both eyes are wide, pupils small and pushed to one side, eyebrows shot up, mouth a small open circle off centre. ",
 "tired":  "FACE: heavy upper eyelids covering nearly HALF of each eye, pupils looking DOWN, a faint pink smudge under each eye, eyebrows sloping down, mouth one short straight line. ",
 "worry":  "FACE: upper eyelids covering the top third of the eyes, pupils looking off to one side, eyebrows tilted up at the INNER ends, mouth a small downward curve set off to one side. ",
 "scared": "FACE: eyelids lifted so both eyes are wide, pupils tiny and pushed to one side away from the danger, eyebrows high and tilted up at the inner ends, mouth a small open circle, one short sweat line beside the head. ",
 "happy":  "FACE: eyes closed as two upward curved lines, eyebrows relaxed, mouth an upward curve set off to one side. ",
 "asleep": "FACE: eyes closed as two short downward curved lines, eyebrows relaxed, mouth one small line off centre. ",
 "dumb":   "FACE: upper eyelids half closed, pupils drifting apart to opposite sides, eyebrows level, mouth one flat line, head tilted slightly. ",
 "curious":"FACE: eyelids level, pupils pushed hard to ONE side as if glancing at something off to the edge, one eyebrow higher than the other, mouth a small circle off centre. ",
 "sad":    "FACE: upper eyelids drooping, pupils looking DOWN, eyebrows tilted up at the INNER ends, mouth a downward curve set off to one side. ",
}

ANIMAL = ("Any animal in this shot is drawn with MORE detail and body volume than the simple "
          "stick people, filled with FLAT SOLID colour and a black outline, with a small simple "
          "face. The animal is the colour accent of the frame. ")
SCENE_N = ANIMAL   # canh khong co nhan vat nguoi
WHO = {"SCENE_A": ANCIENT, "SCENE_M": MODERN, "SCENE_W": WOMAN, "GROUP": GROUP, "SCENE_N": SCENE_N}

# 🔴 THÊM 11/08/2026 — khối cho SCENE_N THUẦN CẢNH (không con vật, không người).
# Bản vá sáng 11/08 bỏ hẳn khối WHO cho loại khung này, tưởng là "sạch". Hoá ra
# prompt KHÔNG CÒN MỘT DÒNG LUẬT NÀO VỀ NGƯỜI, và model lấp chỗ trống bằng thứ
# nó quen tay nhất: một anh hiện đại đầu trọc mặc áo len. 28/46 khung SCENE_N của
# lô 2 hỏng đúng vì thế, gồm CẢ HAI KHUNG CUỐI VIDEO.
# Luật: khoảng trống trong prompt không bao giờ là khoảng trống trên hình.
NO_PERSON = (
    "THIS FRAME HAS NO PEOPLE IN IT. Draw the landscape and the objects only. "
    "There is NO person, NO human figure, NO face, NO silhouette of a body, NO hands, "
    "NO one standing in the distance, NO one at the edge of the frame. "
    "Absolutely never a modern man, never a bald round-headed man, never anyone in a "
    "sweater, hoodie, t-shirt, trousers or shoes, never peach or tan skin. "
    "If the shot names an object, that object is the only subject. ")


