# -*- coding: utf-8 -*-
# V17 — (dòng-shot, kiểu, subject, text, nền)
# kiểu: SCENE_A cổ đại · SCENE_M hiện đại · SCENE_W nữ · GROUP cả nhóm · CARD thẻ
# 31/07: shot 145 sửa lại — bản cũ để muỗi đè lên chữ R, đọc thành "THE WATE".
NT = "no text or letters"
SHOTS = [
# ── HOOK ─────────────────────
("Rain starts.","SCENE_M","standing still on the pavement, looking up as the first few drops land, calm face","small hand-lettered rain sounds \"tap. tap.\" floating in the air beside his head","street"),
("You pull a hood up,","SCENE_M","pulling a plain grey hood up over the bald head with one hand, completely unbothered",NT,"street"),
("or you take six steps to a door,","SCENE_M","walking briskly toward a plain brown door, six small footprints on the wet pavement behind him",NT,"street"),
("and it's finished.","SCENE_M","standing just inside, the brown door shut behind him, dry, the rain only visible through the window",NT,"modern"),
("You're dry again inside a minute,","SCENE_M","lying back on a grey sofa under a yellow blanket, a steaming mug on the side table, a TV glowing, heavy half-lidded eyes",NT,"modern"),
("and you don't think about it once.","SCENE_M","the same sofa, now looking at a small phone, flat straight mouth, totally bored","small hand-lettered \"tap tap\" beside the rain on the window","modern"),
("Now take the hood away.","SCENE_M","standing bare-headed in the rain, the grey hood drawn floating away out of frame with a thick RED X over it, water running down his bald head",NT,"street"),
("Take the door away, and the roof.","SCENE_M","standing in the same spot where the building was, the door and the roof now drawn only as thin BLACK DASHED outlines, rain falling straight through them onto him",NT,"street"),
("Take away every dry thing you can think of.","CARD","a horizontal row of five hand-drawn objects, evenly spaced and drawn large: a grey hood, a brown door, a brown pitched roof, a blue towel, a small heater, each with a thick RED X across it","a hand-lettered headline across the top reading \"EVERY DRY THING\"","white"),
("It's fifty thousand years ago,","CARD","a very large hand-lettered number filling the middle of the frame, with a small hand-drawn stone hand-axe beneath it","the words \"50,000 YEARS AGO.\" very large and bold","white"),
("and it has been raining for nine weeks.","CARD","a row of nine small hand-drawn rain clouds, the ninth circled in red, a hand-lettered headline above","the headline \"NINE WEEKS.\" large and bold above the row, and a small label \"WEEK 9\" under the circled cloud","white"),
("You are a soft, mostly hairless ape","SCENE_A","standing in the open, the same spiky brown mop now soaked and heavy with water, arms hanging, heavy half-lidded eyes, water running off the hide","small hand-lettered rain sound \"SHHHHHHH...\" curving across the upper part of the frame","rain_out"),
("sitting in a puddle","SCENE_A","sitting down heavily in a shallow puddle, knees up, resigned flat mouth, water splashed around him",NT,"rain_out"),
("that used to be where you slept.","SCENE_A","the same seated pose, and beside him a thin BLACK DASHED outline on the flooded ground showing the shape of a sleeping spot","a small hand-lettered label with a thin arrow pointing at the dashed shape, reading \"YOUR BED\"","rain_out"),
("And you have another two months of this.","SCENE_A","seen very small at a distance, one lone figure in the middle of a vast flooded plain that runs to the horizon in every direction",NT,"rain_out"),
("So here's the question.","SCENE_A","standing at the mouth of the cave looking out at the rain, arms loose, deadpan",NT,"cave_mouth"),
("What happens to a human body","SCENE_A","standing in the rain looking down at his own body, both arms held slightly out from his sides",NT,"rain_out"),
("that never, ever gets dry?","CARD","large hand-lettered text filling the frame with a scattering of small blue raindrops drawn around it","the words \"NEVER DRY?\" very large and bold","white"),
("And what did people actually do about it?","SCENE_A","sitting inside the cave, head tilted, one hand slightly raised, curious",NT,"cave"),
("Because they did do something.","SCENE_A","sitting beside the small fire, giving a small nod, the firelight warm on his face",NT,"cave_fire"),
("Four things,","CARD","a very large hand-lettered numeral 4 on the left and four empty hand-drawn boxes numbered 1 2 3 4 in a row on the right","the numeral \"4\" very large, and small numbers 1 2 3 4 inside the boxes","white"),
("and each one is stranger than the last.","CARD","the same four hand-drawn boxes in a row, each drawn noticeably larger than the one before, the fourth clearly the biggest","small numbers 1 2 3 4 inside the boxes","white"),
("The last one could be lost","CARD","the same row of four boxes, the fourth box wrapped in a soft YELLOW GLOW while the first three are drawn pale and faded",NT,"white"),
("in a single night, and not got back.","CARD","the same row of four boxes, the fourth box now empty and dark with a thin wisp of grey smoke rising out of it, and a curved return arrow crossed out with a red X",NT,"white"),
("I saved that one for the end.","SCENE_A","sitting by the fire, raising one finger, heavy half-lidded eyes, flat mouth",NT,"cave_fire"),
("People were living in West African rainforest","CARD","a hand-drawn map of Africa in flat sand-tan sitting on a pale blue sea, the West African rainforest belt filled flat forest-green, one bold red map pin on the Ivory Coast with a thin leader line","a hand-lettered label beside the pin reading \"WEST AFRICAN RAINFOREST\"","white"),
("a hundred and fifty thousand years ago.","CARD","the same hand-drawn map of Africa with the same red pin","the same label, and beneath the map a large hand-lettered line reading \"150,000 YEARS AGO\"","white"),
("Researchers only worked that out in 2026.","CARD","the same hand-drawn map of Africa with the same red pin and a small hand-drawn magnifying glass resting beside it","a small hand-lettered note under the map reading \"FOUND IN 2026\"","white"),
("Not passing through it.","SCENE_A","a line of small footprints running straight through the frame and out the far side with nobody in it, a thick RED X drawn over the line of prints",NT,"forest"),
("Living in it.","SCENE_A","a small camp of two simple hide shelters with a low orange fire between them, seen from a little way off","a small hand-lettered label box in the top corner reading \"EVERY YEAR\"","forest"),
("Through every wet season.","GROUP","five or six of them sitting close together under a dripping canopy, water running off the leaves onto their shoulders","small hand-lettered water sounds \"DRIP DRIP\" and \"PATTER-PATTER...\" floating among the leaves","forest"),
("So let's start where the rain starts.","SCENE_A","a tight close-up as one single fat raindrop lands on his bare shoulder and bursts",NT,"rain_out"),
("On your skin.","CARD","a chapter title card, very large hand-lettered text with one large hand-drawn blue water droplet beside it","the words \"1. YOUR SKIN\" very large and bold in black","white"),
# ── CHƯƠNG 1 — DA ────────────
("You've met the beginning of this,","SCENE_M","standing in a bathroom doorway looking down at his own hand, mild curiosity",NT,"modern"),
("and you thought it was funny.","SCENE_M","holding one hand up close to his face, small amused smile",NT,"modern"),
("You stay in the bath too long,","SCENE_M","sitting in a white bathtub full of pale blue water, only head and shoulders showing, relaxed","a small hand-lettered \"...\" and a few bubbles beside him","modern"),
("your fingertips go wrinkly,","SCENE_M","a tight close-up of his hand lifted out of the water, the fingertips drawn with fine wrinkle lines","a small hand-lettered label with a thin arrow pointing at the fingertips reading \"PRUNE FINGERS\"","modern"),
("and you get out.","SCENE_M","stepping out of the bathtub onto the floor, water dripping off him",NT,"modern"),
("Now don't get out.","SCENE_M","sitting back down in the bathtub, arms folded, completely deadpan, staring straight ahead",NT,"modern"),
("For nine weeks.","CARD","large hand-lettered text with a small hand-drawn bathtub beneath it","the words \"NINE WEEKS.\" very large and bold","white"),
("Skin is waterproof,","CARD","one hand-drawn human hand held palm-up and drawn large, with small blue water beads sitting on the skin and rolling off","a hand-lettered label under the hand reading \"WATERPROOF\"","white"),
("which is true for about a day.","CARD","the same hand-drawn hand, the water beads now soaking in instead of beading","a two-part hand-lettered line, the first part thin reading \"WATERPROOF\" and the second part large and bold reading \"FOR ABOUT A DAY.\"","white"),
("The outer layer is a wall of dead cells packed flat,","CARD","a hand-drawn cross-section of skin drawn large, the outer layer shown as flat dead cells packed together like thin bricks in a wall","small hand-lettered labels with thin arrows reading \"DEAD CELLS\" and \"THE WALL\"","white"),
("and it works right up until it gets waterlogged.","CARD","the same skin cross-section with small blue arrows pushing down into the brick-like layer from above",NT,"white"),
("Then the wall drinks.","CARD","the same cross-section, the flat cells now visibly swollen and rounded and full of blue","a hand-lettered label reading \"IT DRINKS\"","white"),
("It swells, it softens,","CARD","the same cross-section, the swollen cells pushing apart with pale gaps opening between them",NT,"white"),
("and it stops holding together.","CARD","the same cross-section, the wall now broken into loose pieces with wide gaps",NT,"white"),
("Doctors have a name for this,","CARD","one hand-drawn bare foot drawn large in the centre, pale and slightly swollen","a hand-lettered line above it, thin, reading \"DOCTORS HAVE A NAME FOR IT.\"","white"),
("because soldiers kept turning up with it.","CARD","a row of three hand-drawn heavy boots standing in a strip of brown mud","a small hand-lettered label under the mud reading \"1914\"","white"),
("In the cold they called it trench foot.","CARD","one hand-drawn bare foot drawn very large in the centre, the skin pale and soft-looking","very large bold hand-lettered text above reading \"TRENCH FOOT.\"","white"),
("It can wreck a foot in twelve hours.","CARD","a large hand-drawn clock face, the twelve-hour sweep marked in red","a hand-lettered label beside the clock reading \"12 HOURS\"","white"),
("In the warm, wet version,","CARD","the same hand-drawn clock face with small heat lines rising off it",NT,"white"),
("it takes two or three days.","CARD","a comparison card split by a vertical dashed line, a hand-drawn clock on the left and a hand-drawn sun over three small day-marks on the right","hand-lettered labels, on the left \"COLD - 12 HOURS\" and on the right \"WARM - 2-3 DAYS\"","white"),
("That's the whole timer.","CARD","a small hand-drawn hourglass drawn centred with sand nearly run through","a two-part hand-lettered line, thin reading \"THAT'S THE WHOLE\" then large and bold reading \"TIMER.\"","white"),
("The skin goes pale and soft,","SCENE_A","sitting on a wet rock lifting one foot up to look at it, the sole drawn pale","a small hand-lettered label with a thin arrow reading \"PALE\"","rain_out"),
("then it blisters,","SCENE_A","a tight close-up of the same foot held up, small round blisters drawn on the sole",NT,"rain_out"),
("and the blisters open,","SCENE_A","the same close-up, his face above it wincing, eyes squeezed shut",NT,"rain_out"),
("and it peels away in strips.","SCENE_A","the same close-up, thin pale strips of skin lifting away from the sole","a small hand-lettered label with a thin arrow reading \"PEELING\"","rain_out"),
("Your feet were never built for this.","SCENE_A","walking easily across warm dry ground, feet fine, small dust puffs behind him",NT,"dry_plain"),
("Your feet were built for a long walk across dry ground,","SCENE_A","seen small at a distance walking steadily across a wide dry landscape, a long line of footprints stretching behind him",NT,"dry_plain"),
("and then a sit down.","SCENE_A","sitting on a warm flat rock with his legs stretched out, content, deadpan",NT,"dry_plain"),
("Armies still lose men to it,","SCENE_A","walking with a limp across muddy ground, a line of his own prints behind him, rain falling",NT,"rain_out"),
("and they've had a hundred years to work it out.","CARD","a long horizontal hand-drawn timeline with a mark at each end and a small boot drawn above the left end","hand-lettered labels at the two ends reading \"1914\" and \"TODAY\", and \"100 YEARS\" above the line","white"),
("So how does a barefoot person","SCENE_A","standing in soft mud, looking down at his own feet, rain falling",NT,"rain_out"),
("get through nine weeks of that?","SCENE_A","the same pose seen a little wider, the ground around him all mud and standing water",NT,"rain_out"),
("Barefoot is the answer.","CARD","one hand-drawn bare foot drawn very large in the centre, wrapped in a soft YELLOW GLOW","large bold hand-lettered text beneath reading \"BAREFOOT.\"","white"),
("Trench foot isn't really a water problem.","SCENE_A","standing in the rain with his arms out, and a thick RED X drawn over the falling rain beside him",NT,"rain_out"),
("It's a footwear problem.","CARD","a comparison card split by a vertical dashed line, a hand-drawn heavy boot on the left with a red X above it, a hand-drawn bare foot on the right with a green check above it",NT,"white"),
("The damage comes from wet socks and wet boots","CARD","a hand-drawn cutaway of a boot with a foot inside it, blue water drawn filling every gap around the foot","small hand-lettered labels with thin arrows reading \"WET SOCK\" and \"TRAPPED\"","white"),
("holding water against skin,","CARD","the same boot cutaway with small blue arrows pressing inward against the skin from every side",NT,"white"),
("with no dry air in between.","CARD","the same boot cutaway with a thick RED X drawn over a small gap of white air",NT,"white"),
("A bare foot gets soaked.","SCENE_A","a close-up of one bare foot standing in a puddle, water up over the ankle",NT,"rain_out"),
("A bare foot also dries.","SCENE_A","sitting by the fire with one bare foot held out toward the flames, small heat lines rising off it","a small hand-lettered label with a thin arrow reading \"DRIES\"","cave_fire"),
("You have no boots,","SCENE_A","sitting by the fire looking down at his own two bare feet, deadpan",NT,"cave_fire"),
("so you have no bucket strapped to your leg.","CARD","an equation card, a hand-drawn heavy boot on the left, a large hand-lettered equals sign, and a hand-drawn bucket brimming with water on the right",NT,"white"),
("That's a real advantage,","SCENE_A","sitting by the fire giving a small nod, a small green check mark floating beside his head",NT,"cave_fire"),
("and it's the only one you get.","SCENE_A","the same seated pose, deadpan, the rain still falling hard past the cave mouth behind him",NT,"cave_fire"),
("Because skin isn't a covering.","SCENE_A","standing in the rain pulling a loose hide up over his shoulders like a blanket, the water going straight through it",NT,"rain_out"),
("Skin is a wall.","CARD","a hand-drawn brick wall drawn large and solid across the middle of the frame","large bold hand-lettered text beneath reading \"A WALL.\"","white"),
("It stands between a warm wet body","CARD","the same hand-drawn wall seen from the side, a warm orange body shape standing close behind it",NT,"white"),
("and everything in the water that would like to get in.","CARD","the same wall, and on the other side a crowd of small hand-drawn microbes and bugs pressed up against it","a small hand-lettered label with a thin arrow reading \"EVERYTHING ELSE\"","white"),
("Nine weeks of rain doesn't just make you uncomfortable.","SCENE_A","standing hunched in the rain, arms wrapped around himself, miserable","small hand-lettered shiver marks drawn beside his arms","rain_out"),
("It takes the wall down.","CARD","the same hand-drawn brick wall now crumbling, whole sections fallen out and lying in pieces",NT,"white"),
("Every crack is a door.","CARD","a close-up of one crack in the wall with a thin arrow drawn passing straight through it","a small hand-lettered label beside the crack reading \"A DOOR\"","white"),
("And while your feet are busy falling apart,","SCENE_A","walking with a bad limp through the mud, one foot held oddly, face tight",NT,"rain_out"),
("you still have to walk.","SCENE_A","seen small at a distance still walking on across a wide wet landscape",NT,"rain_out"),
("Because out here, a person who can't walk","SCENE_A","sitting down alone in the mud with his legs out in front of him, rain falling, nobody else in frame",NT,"rain_out"),
("is a person who can't eat.","SCENE_A","the same seated figure holding an empty wooden bowl, looking into it",NT,"rain_out"),
# ── CHƯƠNG 2 — THỨC ĂN ───────
("Now, the food.","CARD","a chapter title card, very large hand-lettered ALL-CAPS text with one large hand-drawn empty wooden bowl beside it","the words \"2. THE FOOD\" very large and bold in black","white"),
("And this is where most people","SCENE_M","standing on the wet street pointing confidently off to one side, sure of himself",NT,"street"),
("get the wet season backwards.","CARD","a hand-drawn arrow curving confidently one way, with a second arrow drawn beneath it pointing the opposite way in red","a hand-lettered line above reading \"BACKWARDS.\"","white"),
("Rain sounds like abundance.","SCENE_A","standing among thick wet green growth with leaves and fruit all around him, looking around, faint smile",NT,"forest"),
("Everything is green. Everything is growing.","SCENE_A","seen small inside a wide lush green rainforest, plants towering over him on every side",NT,"forest"),
("It looks like the richest time of the year.","SCENE_A","reaching up toward a cluster of fruit hanging above him",NT,"forest"),
("It was the hungriest.","CARD","a hand-drawn empty wooden bowl drawn large in the centre, tipped slightly so it clearly holds nothing","a two-part hand-lettered line, thin reading \"IT WAS THE\" then very large and bold reading \"HUNGRIEST.\"","white"),
("The forest is full of food","SCENE_A","standing under heavy wet green growth, fruit and pods hanging all around him, looking up at them",NT,"forest"),
("you can't eat yet.","SCENE_A","the same pose, now holding one hard green unripe fruit in his hand and staring at it, flat mouth","a small hand-lettered label with a thin arrow pointing at the fruit reading \"NOT YET\"","forest"),
("There's a number from the Mbuti,","CARD","a hand-drawn map of Africa in flat sand-tan on a pale blue sea, the eastern Congo basin filled flat forest-green, one bold red map pin on it with a thin leader line","a hand-lettered label beside the pin reading \"MBUTI - EASTERN CONGO\"","white"),
("in the rainforest of the eastern Congo,","CARD","the same hand-drawn map of Africa with the same red pin, thin rain lines falling across the green area",NT,"white"),
("that should stop you.","CARD","a very large hand-lettered number filling the frame with a small hand-drawn cluster of fruit beneath it","the words \"FIVE MONTHS.\" very large and bold","white"),
("For five months of the year,","CARD","a hand-drawn ring of twelve month blocks arranged in a circle, five of them filled solid grey","a small hand-lettered label in the middle of the ring reading \"5 OF 12\"","white"),
("the fruits and seeds that actually carry calories","CARD","a horizontal row of three hand-drawn objects drawn large and evenly spaced: a cluster of fruit, a handful of seeds, a piece of honeycomb","small hand-lettered labels under each reading \"FRUIT\", \"SEEDS\", \"HONEY\"","white"),
("are gone.","CARD","the same row of three hand-drawn objects, all three now drawn faded and pale with a thick RED X across each","the same three labels, and a large bold hand-lettered word above reading \"GONE.\"","white"),
("Not scarce. Not harder to find.","SCENE_A","standing among the wet trees with both empty hands held open in front of him, looking around",NT,"forest"),
("Gone.","SCENE_A","the same figure seen small inside a wide empty stretch of dripping forest with nothing hanging anywhere",NT,"forest"),
("And the honey goes with them.","SCENE_A","looking up at an empty hollow in a tree trunk, one hand reaching into it, finding nothing","small hand-lettered \"...\" floating beside his head","forest"),
("So why doesn't the forest just feed you?","SCENE_A","standing with his arms out in a shrug, looking straight at the viewer, deadpan",NT,"forest"),
("A tree fruits when it suits the tree.","CARD","one hand-drawn tree drawn large and centred with a small hand-drawn calendar leaf beside it, and a thin arrow curving from the calendar to the tree",NT,"white"),
("It has never once checked whether you're hungry.","CARD","a comparison card split by a vertical dashed line, the same hand-drawn tree on the left, and on the right the caveman stickman holding his stomach","hand-lettered labels above, on the left \"THE TREE\" and on the right \"YOU\", and a small red X drawn over a thin arrow running between them","white"),
("You hunt instead,","SCENE_A","crouched low with a wooden spear held ready, moving through wet grass, eyes fixed ahead",NT,"rain_out"),
("except the rain took that too.","SCENE_A","the same crouched pose, now with rain hammering down, the spear lowered, shoulders dropped",NT,"rain_out"),
("Tracks wash out in minutes.","SCENE_A","kneeling and looking down at a set of animal tracks in mud that are visibly filling with water and dissolving","small hand-lettered water sound \"plink\" beside the tracks","rain_out"),
("You can't hear anything over the water.","SCENE_A","standing still with one hand cupped behind his ear, head turned, listening, rain everywhere","hand-lettered rain noise \"SHHHHHHHHH\" filling the air all around his head","rain_out"),
("So you stop looking up,","SCENE_A","looking up into the empty dripping canopy above him, then nothing there",NT,"forest"),
("and you start digging.","SCENE_A","kneeling and driving a sharpened digging stick into the wet earth, dirt flying",NT,"forest"),
("Foragers across tropical Africa, Asia and South America","CARD","a hand-drawn world map, land in flat sand-tan on a pale blue sea, three regions filled flat forest-green: west and central Africa, southeast Asia, and the Amazon, each with a small red pin",NT,"white"),
("all fall back on the same thing when the fruit fails.","CARD","the same world map with three thin lines running from the three pins down to one hand-drawn root vegetable at the bottom of the frame","a hand-lettered label under the root reading \"THE SAME THING\"","white"),
("Roots. Tubers. Rhizomes.","CARD","three hand-drawn root vegetables drawn large in a row, each a different shape, drawn with soil still clinging to them","small hand-lettered labels under each reading \"ROOT\", \"TUBER\", \"RHIZOME\"","white"),
("Some buried deep, some weighing three kilos.","CARD","a hand-drawn cross-section of the ground, a small tuber near the surface and a very large one buried deep, a thin arrow marking the depth","small hand-lettered labels reading \"DEEP\" and \"3 KG\"","white"),
("Researchers call them fallback foods,","CARD","one hand-drawn tuber drawn very large in the centre, still dusted with soil","large bold hand-lettered text beneath reading \"FALLBACK FOOD.\"","white"),
("which is a very calm name","CARD","the same hand-drawn tuber, now wrapped in a soft YELLOW GLOW",NT,"white"),
("for the thing that keeps you alive.","CARD","the same hand-drawn tuber with a thin arrow running from it to a small drawing of the caveman stickman standing upright","a two-part hand-lettered line, thin reading \"THE THING THAT\" then very large and bold reading \"KEEPS YOU ALIVE.\"","white"),
("And here's why that matters","SCENE_A","kneeling in the mud holding a freshly pulled tuber up in one hand, looking at it",NT,"rain_out"),
("when it won't stop raining.","SCENE_A","the same kneeling figure seen a little wider, rain hammering down on him and on the open ground",NT,"rain_out"),
("Everything above the ground","CARD","a hand-drawn cross-section of a hillside, everything above the soil line drawn in: grass, a bush, a small tree, with rain and wind lines hitting them",NT,"white"),
("is at the mercy of the weather.","CARD","the same cross-section, the plants above the line now battered flat and stripped, with a thick RED X above them",NT,"white"),
("Everything under it is not.","SCENE_A","kneeling and pulling a fat tuber up out of wet ground with both hands, soil falling away",NT,"rain_out"),
("A tuber doesn't care","CARD","one hand-drawn tuber sitting alone in a pocket of dark soil, drawn large and calm",NT,"white"),
("that it has been raining for nine weeks.","CARD","the same buried tuber, and above the soil line thin rain lines hammering down, the soil line drawn thick between them","a small hand-lettered label above the soil reading \"WEEK 9\"","white"),
("It's been sitting there the whole time,","CARD","the same buried tuber with a small hand-drawn hourglass resting in the soil beside it",NT,"white"),
("waiting for somebody with a sharp stick.","SCENE_A","kneeling and pushing a sharpened digging stick down into the soil, the tip just reaching a tuber",NT,"rain_out"),
("But digging takes you out into the open,","SCENE_A","seen small at a distance, alone and kneeling in the middle of a wide flat open stretch of wet ground",NT,"rain_out"),
("on those feet, for hours.","SCENE_A","a close-up of his two bare feet planted in cold mud, water up over the ankles, the skin pale","a small hand-lettered label with a thin arrow reading \"HOURS\"","rain_out"),
("And while you're out there,","SCENE_A","the same figure digging, seen from behind, with the flooded ground stretching away behind him",NT,"rain_out"),
("the water sitting on the ground behind you","SCENE_A","a low close view of still standing water filling a hollow in the ground, absolutely flat and quiet",NT,"rain_out"),
("has been busy.","SCENE_A","the same still water, now with dozens of tiny dark wriggling shapes drawn just under the surface",NT,"rain_out"),
("Rain doesn't drain away. It sits.","SCENE_A","a wide low view of flooded ground where the water has nowhere to go, every dip and hollow holding still standing water right to the horizon",NT,"rain_out"),
("It sits in every hollow, every hoofprint,","SCENE_A","a wide low view of muddy ground covered in small water-filled hollows and animal hoofprints, each one holding still water",NT,"rain_out"),
("every dip in the ground you walked past without noticing.","SCENE_A","the same ground with a line of his own footprints running through it, each print holding water",NT,"rain_out"),
("Every footprint you left last week","SCENE_A","a tight close-up of one single footprint in the mud, filled to the brim with still water","a small hand-lettered label with a thin arrow reading \"LAST WEEK\"","rain_out"),
("is now full of mosquito larvae.","SCENE_A","the same footprint close-up, the water now thick with tiny wriggling larvae drawn in detail",NT,"rain_out"),
("After unusually heavy rain,","CARD","a hand-drawn bar chart with two bars, a short one and a very tall one, drawn by hand with a wobbly baseline","small hand-lettered labels under the bars reading \"NORMAL\" and \"AFTER RAIN\"","white"),
("the number of biting insects explodes.","CARD","the same hand-drawn bar chart, the tall bar now drawn in red and running off the top of the frame, with a swarm of small hand-drawn mosquitoes bursting out of it",NT,"white"),
("Not slightly more mosquitoes.","SCENE_A","standing in the rain waving one hand in front of his face, a thin scatter of mosquitoes around his head",NT,"rain_out"),
# ── CHƯƠNG 3 — TRONG NƯỚC ────
("A different order of magnitude.","CARD","a chapter title card. The hand-lettered text sits on the LEFT half of the frame. A single large hand-drawn mosquito sits alone on the RIGHT half, in its own clear empty space, well clear of the lettering. Nothing overlaps the text, nothing touches any letter","the words \"3. THE WATER\" very large and bold in dark red, on the left, complete and unobstructed","white"),
("And that isn't an itching problem.","SCENE_A","a close-up of one forearm with several small bites on it, his other hand scratching, face annoyed",NT,"rain_out"),
("That's how insect-borne disease travels.","CARD","a hand-drawn diagram, one mosquito on the left, a thin arrow to a small drawing of the caveman stickman in the middle, a second thin arrow to another stickman on the right","small hand-lettered labels under the two figures reading \"SICK\" and \"NEXT\"","white"),
("The wet season is the season","CARD","a hand-drawn ring of twelve month blocks, the wet-season months filled flat blue with small rain lines over them","a small hand-lettered label beside the blue months reading \"WET SEASON\"","white"),
("the sick season rides in on.","CARD","the same hand-drawn ring, a second thinner ring drawn in red overlapping exactly the same months","a small hand-lettered label in red reading \"SICK SEASON\"","white"),
("Now put that on top of chapter one.","CARD","a hand-drawn cross-section of skin drawn broken and open with wide gaps, and a mosquito drawn descending toward one of the gaps",NT,"white"),
("Your skin is soft. Your skin is open.","CARD","the same broken skin cross-section drawn larger, several thin arrows passing straight through the gaps","a small hand-lettered label with a thin arrow reading \"OPEN\"","white"),
("The wall came down two months ago.","CARD","a hand-drawn brick wall lying collapsed in pieces on the ground, with a small hand-drawn calendar leaf beside the rubble","a small hand-lettered label under the calendar reading \"2 MONTHS\"","white"),
("So here's where you'd expect the story to end,","SCENE_A","sitting alone and slumped in the mud with his head down, rain falling on him, nobody else in frame",NT,"rain_out"),
("with a lot of dead people and nothing anyone could do.","SCENE_A","the same figure seen small at a distance in a wide empty flooded landscape under a heavy sky",NT,"rain_out"),
("Except they did something,","SCENE_A","lifting his head and looking straight at the viewer, rain still falling, one eyebrow slightly up",NT,"rain_out"),
("and they did it a long time ago.","CARD","a long horizontal hand-drawn timeline running across the frame, a small glowing yellow dot marked far over at the left end","a hand-lettered label under the dot reading \"77,000 YEARS AGO\"","white"),
("At Sibudu, a rock shelter in South Africa,","CARD","a hand-drawn map of southern Africa in flat sand-tan on a pale blue sea, one bold red map pin on the east coast with a thin leader line, and a small hand-drawn rock shelter icon beside it","a hand-lettered label beside the pin reading \"SIBUDU - SOUTH AFRICA\"","white"),
("archaeologists dug through fifteen separate layers of bedding.","CARD","a hand-drawn stratigraphic cross-section, fifteen thin horizontal layers stacked one on another in alternating pale green and brown, a thin bracket down the left side","a hand-lettered label beside the bracket reading \"15 LAYERS\"","white"),
("Stems and rushes, packed down flat,","CARD","a close hand-drawn view of one bedding layer, dried stems and rushes pressed flat and interwoven","a small hand-lettered label with a thin arrow reading \"STEMS\"","white"),
("a few centimetres thick.","CARD","the same layer seen from the side with a small hand-drawn measuring mark against its thickness","a small hand-lettered label reading \"A FEW CM\"","white"),
("Big enough to lie on.","SCENE_A","lying flat on his back on a thick mat of packed stems inside the shelter, hands behind his head",NT,"cave"),
("A mattress.","CARD","one hand-drawn bedding mat drawn large and centred, seen from slightly above, its edges frayed","large bold hand-lettered text beneath reading \"A MATTRESS.\"","white"),
("Seventy seven thousand years old.","CARD","a very large hand-lettered number filling the frame with the small hand-drawn bedding mat beneath it","the words \"77,000 YEARS OLD.\" very large and bold","white"),
("But that isn't the clever part.","SCENE_A","sitting on the edge of the bedding mat inside the shelter, raising one finger, deadpan",NT,"cave"),
("On top of it, thinner than tissue paper,","CARD","a hand-drawn side view of the bedding mat with one extremely thin extra layer drawn on top of it, and a thin arrow pointing at that layer",NT,"white"),
("was a layer of leaves from one particular tree.","CARD","the same side view with the top layer now drawn as overlapping green leaves, wrapped in a soft YELLOW GLOW","a small hand-lettered label with a thin arrow reading \"LEAVES\"","white"),
("Cape laurel.","CARD","one hand-drawn sprig of cape laurel drawn very large and centred, three glossy pointed leaves","large bold hand-lettered text beneath reading \"CAPE LAUREL.\"","white"),
("The leaves are full of compounds that kill insects,","CARD","one hand-drawn leaf drawn large with a mosquito beside it and a thick RED X over the mosquito",NT,"white"),
("and kill the larvae too.","CARD","the same leaf with a small hand-drawn pool of water beneath it holding larvae, all crossed out in red","a small hand-lettered label with a thin arrow reading \"LARVAE TOO\"","white"),
("They were sleeping on an insecticide.","SCENE_A","lying asleep on the leaf-covered bedding inside the shelter, eyes closed, calm","small hand-lettered sleep marks \"zzZz\" floating above his head","cave"),
("And I want to be careful here,","SCENE_A","sitting up on the bedding with one hand raised flat, a cautious look",NT,"cave"),
("because this is the part that's easy to oversell.","CARD","a hand-drawn set of scales tipping too far to one side, a small leaf on the heavy pan","a small hand-lettered label under the heavy pan reading \"TOO FAR\"","white"),
("Nobody can prove those leaves","CARD","one hand-drawn leaf drawn large in the centre with a hand-drawn question mark beside it",NT,"white"),
("were a wet season measure specifically.","CARD","the same leaf with a thin dashed arrow running toward a small rain cloud, the arrow crossed out with a red X","a small hand-lettered label under the dashed arrow reading \"NOT PROVEN\"","white"),
("What it proves is that seventy seven thousand years ago,","CARD","a large hand-lettered number filling the upper frame with a thin line drawn under it","the words \"WHAT IT DOES PROVE\" in a smaller thin hand-lettered line above, and \"77,000 YEARS AGO\" large and bold below","white"),
("people knew some plants keep insects off you,","SCENE_A","kneeling and picking a specific sprig of leaves from a low bush, examining it closely, sure of himself",NT,"forest"),
("and they used that on purpose, fifteen times over.","SCENE_A","kneeling on the bedding inside the shelter, laying a fresh handful of leaves down across the top of it",NT,"cave"),
("There's also a reason we found it at Sibudu","CARD","a comparison card split by a vertical dashed line, a hand-drawn dry rock shelter on the left with a green check, a hand-drawn dripping wet forest floor on the right with a red X","hand-lettered labels above reading \"SURVIVES\" and \"GONE\"","white"),
("and not somewhere wetter.","CARD","a hand-drawn map of Africa in flat sand-tan, the Congo rainforest area shaded flat green with a thick RED X over it","a small hand-lettered label under the map reading \"NOTHING SURVIVES\"","white"),
("The wet that rotted their feet","SCENE_A","sitting on wet ground looking down at his own pale ruined foot",NT,"rain_out"),
("rotted nearly everything else they left behind.","CARD","a hand-drawn cross-section of dark wet soil with a bone, a stick and a scrap of hide inside it, all drawn crumbling into nothing","a small hand-lettered label with a thin arrow reading \"ACIDIC SOIL\"","white"),
("Dry caves survive. Wet seasons don't.","CARD","a comparison card split by a vertical dashed line, a hand-drawn dry cave interior on the left, a hand-drawn flooded forest floor on the right","hand-lettered labels above reading \"DRY\" and \"WET\"","white"),
("So how does anyone work out which leaf to sleep on,","SCENE_A","standing holding two different sprigs of leaves, one in each hand, looking from one to the other",NT,"forest"),
("with no writing and no way to test it?","CARD","a hand-drawn scroll and a hand-drawn glass vial side by side, each with a thick RED X across it","small hand-lettered labels under each reading \"NO WRITING\" and \"NO TESTING\"","white"),
("You don't.","SCENE_A","standing with both arms out in a shrug, deadpan, looking straight at the viewer",NT,"cave"),
("Somebody's grandmother does, and she tells you.","SCENE_W","an old woman sitting by the fire holding out a sprig of leaves toward a younger figure beside her, mouth open mid-sentence",NT,"cave_fire"),
("Nobody wrote it down. Nobody could.","CARD","a hand-drawn scroll and quill drawn large with a thick RED X across them","a hand-lettered line beneath reading \"NEVER WRITTEN.\"","white"),
("They just knew,","GROUP","five of them sitting close around the fire inside the cave, one talking, the others listening, firelight on all their faces",NT,"cave_fire"),
("and they kept knowing, for tens of thousands of years.","GROUP","a long line of them stretching across the frame from left to right, each one turned slightly toward the next, a thin arrow running along the whole line","a hand-lettered label under the line reading \"PASSED ON\"","white"),
("Now, let's be honest about something,","SCENE_A","sitting by the fire, leaning forward slightly, one hand open, a level look at the viewer",NT,"cave_fire"),
("because so far this has gone quite well for you.","SCENE_A","the same seated figure, a small green check mark floating beside his head",NT,"cave_fire"),
("Bare feet. Tubers under the ground. Leaves that keep the insects off.","CARD","a row of three hand-drawn objects drawn large and evenly spaced: a bare foot, a fat tuber, a sprig of leaves, each with a small green check above it",NT,"white"),
("Every one of those answers","CARD","the same three objects with three thin lines running down from them and meeting at one point below",NT,"white"),
("has the same thing underneath it.","CARD","the same three lines meeting at one small hand-drawn fire wrapped in a soft YELLOW GLOW","a hand-lettered label beneath the fire reading \"WARM ENOUGH.\"","white"),
("You have to be warm enough to move.","SCENE_A","standing up from beside the fire, stretching, moving off toward the cave mouth",NT,"cave_fire"),
("Somebody cold enough doesn't dig,","SCENE_A","sitting hunched and shivering in the rain, a digging stick lying unused on the ground beside him","small hand-lettered shiver marks beside his shoulders","rain_out"),
("doesn't gather leaves, doesn't walk anywhere.","SCENE_A","the same hunched figure, arms wrapped tight around his knees, not moving",NT,"rain_out"),
("They sit down.","SCENE_A","the same figure seen small at a distance, a single seated shape alone in a wide flooded landscape",NT,"rain_out"),
("And in a wet season, sitting down is how it ends.","SCENE_A","the same wide landscape at dusk, the seated shape now barely visible, the light almost gone",NT,"rain_night"),
# ── CHƯƠNG 4 — LỬA + KẾT ─────
("Which brings us to fire.","CARD","a chapter title card, very large hand-lettered ALL-CAPS text with one large hand-drawn fire on a ring of stones beside it, wrapped in a warm yellow glow","the words \"4. THE FIRE\" very large and bold in black","white"),
("Not fire as a nice thing to sit near.","SCENE_M","sitting comfortably in an armchair beside a small decorative fireplace holding a mug, blanket over his knees, half-lidded eyes",NT,"modern"),
("Fire as the only source of heat that existed.","CARD","the same hand-drawn fire drawn very large and wrapped in a strong warm YELLOW GLOW filling most of the frame","a two-part hand-lettered line, thin reading \"THE ONLY\" then very large and bold reading \"HEAT THAT EXISTED.\"","white"),
("Here's the number that makes rain lethal","SCENE_A","sitting close beside the fire with his arms out toward it, soaked through, firelight on his face",NT,"cave_fire"),
("instead of miserable.","SCENE_A","the same seated figure seen a little wider, the rain hammering past the cave mouth behind him",NT,"cave_fire"),
("A wet body loses heat","CARD","a comparison card split by a vertical dashed line, the caveman stickman drawn dry on the left with two small red heat arrows leaving him, and drawn soaked on the right with a dense burst of red heat arrows leaving him in every direction","hand-lettered labels under the two figures reading \"DRY\" and \"WET\"","white"),
("up to twenty five times faster than a dry one.","CARD","the same comparison card, the numbers now written large under each figure, the right-hand number drawn in RED","hand-lettered numbers under the two figures reading \"1x\" and \"25x\", the \"25x\" in red","white"),
("Not twenty five percent. Twenty five times.","CARD","a very large hand-lettered figure filling the frame, with a small percent sign drawn beside it crossed out in red","the words \"25 TIMES.\" very large and bold, and a small crossed-out \"25%\" beside them","white"),
("So the fire isn't comfort.","SCENE_A","sitting bolt upright right beside the fire, not relaxed at all, eyes open and watchful, hands ready",NT,"cave_fire"),
("The fire is the reason you wake up.","SCENE_A","lying asleep on his side close beside the fire inside the cave, calm, the firelight warm across him","small hand-lettered sleep marks \"zzZz\" above his head","cave_fire"),
("And rain is the single best thing in nature","SCENE_A","standing at the cave mouth looking out at a wall of hammering rain, spear in one hand",NT,"cave_mouth"),
("at putting fire out.","SCENE_A","crouched over a fire at the cave mouth as rain drives in onto it, the flames flattened, grey smoke and steam rising","small hand-lettered sounds \"HISSSS\" beside the steam","cave_mouth"),
("Now, you're probably picturing someone","SCENE_M","standing on the wet street holding two stones together, pretending to strike them, pleased with himself",NT,"street"),
("striking a stone to get it back.","CARD","two hand-drawn stones drawn large being struck together with a small bright spark and a soft yellow glow between them",NT,"white"),
("For most of human history,","CARD","the same two stones with a thick RED X drawn across them","a hand-lettered line beneath reading \"NOT AN OPTION.\"","white"),
("that was not an option.","SCENE_A","kneeling over a dead grey fire, striking two stones together, nothing happening, face set",NT,"cave"),
("The oldest fire sites, in Kenya and in South Africa,","CARD","a hand-drawn map of Africa in flat sand-tan on a pale blue sea with two bold red map pins, one in east Africa and one in the south, each with a thin leader line","hand-lettered labels beside the pins reading \"KENYA\" and \"SOUTH AFRICA\"","white"),
("go back one point six million years.","CARD","a very large hand-lettered number filling the frame with a small hand-drawn fire beneath it","the words \"1.6 MILLION YEARS.\" very large and bold","white"),
("And those people were not making fire.","SCENE_A","kneeling over a dead grey fire striking two stones together again and again, no spark, shoulders tight with effort",NT,"cave"),
("They were collecting it.","SCENE_A","crouching at the edge of a burnt patch of ground lifting one glowing ember into a folded piece of bark, warm light on his hands",NT,"dry_plain"),
("From lightning strikes.","SCENE_A","seen small at a distance watching from a rise as a fork of lightning strikes a lone tree across the valley and sets it alight",NT,"rain_night"),
("From wildfires.","SCENE_A","standing at a distance in front of a low line of grass fire burning across the plain, orange light on him, smoke drifting",NT,"dry_plain"),
("They took embers from something the sky had already set alight,","SCENE_A","crouching at the edge of a burnt patch, lifting a glowing ember into a cupped piece of bark with a stick",NT,"dry_plain"),
("and carried them home.","SCENE_A","walking carefully with both hands cupped around a small glowing ember, a warm yellow glow on his face and chest, dusk around him",NT,"rain_night"),
("So for over a million years,","CARD","a long horizontal hand-drawn timeline running the width of the frame with a small fire drawn above the left end and above the right end","a hand-lettered label above the line reading \"1,000,000 YEARS\"","white"),
("if your fire went out, you did not relight it.","SCENE_A","kneeling over a fire that has gone out, pushing the cold grey ash apart with one finger, nothing left glowing",NT,"cave"),
("You waited for the sky to strike something.","SCENE_A","sitting at the cave mouth looking up at a heavy dark sky, waiting, nothing happening",NT,"cave_mouth"),
("And in a wet season,","SCENE_A","the same seated figure with rain now driving in past him, the cave floor wet",NT,"cave_mouth"),
("the sky is busy doing the exact opposite.","SCENE_A","standing out in the open at night with rain driving down hard, no light anywhere, arms wrapped around himself",NT,"rain_night"),
("So somebody sat with it.","SCENE_A","sitting cross-legged directly beside the fire, feeding it one small stick, wide awake",NT,"cave_fire"),
("Not as a chore.","SCENE_A","the same seated figure, face serious and focused, eyes on the flames, not bored",NT,"cave_fire"),
("Somebody in that group did nothing else.","GROUP","the whole band inside the cave, most of them working at other things around the edges, one figure sitting alone right beside the fire doing only that","a small hand-lettered label box in the top corner reading \"FIRE KEEPER\"","cave_fire"),
("Not hunting. Not digging. Not gathering.","SCENE_A","sitting beside the fire watching the others walk away out of the cave mouth, one carrying a spear, one a digging stick, one a basket",NT,"cave_fire"),
("Just the fire.","CARD","one hand-drawn fire drawn very large and centred, wrapped in a warm YELLOW GLOW, nothing else in the frame",NT,"white"),
("In a group of thirty people who are already hungry,","GROUP","a wide view of about thirty of them spread across the cave floor, thin and hunched, some lying down, the fire small in the middle",NT,"cave_fire"),
("one of them is doing nothing but watching something burn.","GROUP","the same wide cave view, one single figure beside the fire wrapped in a soft YELLOW GLOW while everyone else is drawn plain",NT,"cave_fire"),
("That's what it was worth.","CARD","a hand-drawn set of scales, one pan holding a small fire and the other holding a full day's food, the fire pan sitting lower","a hand-lettered line beneath reading \"THAT'S THE PRICE.\"","white"),
("They paid it every wet season, for a million years.","GROUP","a long horizontal line of small seated figures stretching across the frame, each one beside a small fire, receding into the distance",NT,"white"),
("Eventually that changed,","SCENE_A","kneeling over a fresh fire, holding up a small dull yellow stone and looking at it closely",NT,"cave"),
("and it changed in the most ordinary way possible.","SCENE_A","the same kneeling figure knocking the yellow stone against a flint, a single spark jumping off",NT,"cave"),
("At a site called Barnham in Suffolk,","CARD","a hand-drawn map of Britain in flat sand-tan on a pale blue sea, one bold red map pin in the east of England with a thin leader line","a hand-lettered label beside the pin reading \"BARNHAM - SUFFOLK\"","white"),
("there's a hearth about four hundred thousand years old.","CARD","a hand-drawn overhead view of a ring of blackened hearth stones with dark ash inside it","a large hand-lettered line beneath reading \"400,000 YEARS OLD.\"","white"),
("Beside it, pieces of iron pyrite.","CARD","two hand-drawn lumps of iron pyrite drawn large and centred, dull brassy gold with rough faces","large bold hand-lettered text beneath reading \"IRON PYRITE.\"","white"),
("Stone that throws a spark.","SCENE_A","a tight close-up of his two hands striking flint against pyrite, one bright spark leaping off between them",NT,"cave"),
("Somebody had stopped waiting for the sky.","SCENE_A","standing at the cave mouth with his back to the dark sky outside, striking a spark in his own hands, warm light on his face",NT,"cave_mouth"),
("Five thousand years ago a man died in the Alps","SCENE_A","lying still on his side on a snowfield high in the mountains, the peaks drawn pale and cold behind him",NT,"dry_plain"),
("carrying a small kit.","SCENE_A","a close-up of the small leather pouch tied at his hip, his hand resting on it, the mountain light cold and pale",NT,"dry_plain"),
("Flint, pyrite, and a dried fungus","CARD","a hand-drawn kit layout, four objects arranged with space around them: a flint blade, a lump of pyrite, a dried bracket fungus, and a bundle of plant tinder","a hand-lettered heading above reading \"THE FIRE KIT\", and small labels under each item reading \"FLINT\", \"PYRITE\", \"FUNGUS\", \"TINDER\"","white"),
("that catches a spark and holds it.","CARD","a hand-drawn cutaway of the dried fungus with a small ember glowing deep inside it, wrapped in a soft yellow glow","a small hand-lettered label with a thin arrow reading \"HOLDS IT\"","white"),
("He carried it everywhere, because you would.","SCENE_A","walking a high mountain path with the small pouch tied at his hip, one hand resting on it",NT,"dry_plain"),
("Everybody in that line kept it burning","GROUP","a long horizontal line of them stretching across the frame, each one handing a small flame on to the next, a thin arrow running along the whole line",NT,"white"),
("long enough to hand it on.","GROUP","the same line, the flame now reaching the far right end where one figure holds it up, the whole line wrapped in a faint warm glow",NT,"white"),
("That isn't a nice thought.","SCENE_A","sitting alone by the fire looking straight at the viewer, flat mouth, not smiling",NT,"cave_fire"),
("It's just what had to happen for you to be here.","SCENE_A","the same seated figure, and behind him on the cave wall his shadow drawn long and steady",NT,"cave_fire"),
("Rain starts.","SCENE_M","standing still on the pavement looking up as the first drops land, exactly as at the very beginning","small hand-lettered rain sounds \"tap. tap.\" floating beside his head","street"),
("You pull a hood up, you take six steps to a door,","SCENE_M","pulling the grey hood up and walking toward the brown door, six footprints behind him on the wet pavement",NT,"street"),
("and behind that door there is heat","SCENE_M","standing inside with the door shut behind him, a warm glow filling the room around him",NT,"modern"),
("that nobody in your family has to sit up all night to protect.","GROUP","a comparison card drawn as two scenes side by side split by a vertical dashed line, the modern guy asleep on his sofa on the left, and on the right one caveman sitting up wide awake beside a fire","hand-lettered labels above the two halves reading \"YOU\" and \"THEM\"","white"),
("Somewhere in a kitchen drawer","SCENE_M","pulling open a kitchen drawer and looking down into it, the warm room around him",NT,"modern"),
("there is a small plastic thing","CARD","one hand-drawn plastic lighter drawn very large and centred, plain and cheap-looking",NT,"white"),
("that makes fire on the first try, in any weather,","SCENE_M","standing in the kitchen flicking the small plastic lighter, one small flame appearing at the top, warm light on his face",NT,"modern"),
("and it cost you almost nothing.","CARD","an equation card, the hand-drawn lighter on the left, a large hand-lettered equals sign, and a small coin on the right",NT,"white"),
("For a million years,","CARD","a long horizontal hand-drawn timeline running the width of the frame, one small glowing point marked at the far right end","a hand-lettered label above the line reading \"1,000,000 YEARS\"","white"),
("that was a person's entire life.","SCENE_A","a wide view at dawn, one figure standing alone at the mouth of the cave looking out over a valley, seen small against the opening light, a low fire still burning behind him",NT,"cave_mouth"),
]
