# -*- coding: utf-8 -*-
"""V18 — 224 shot.  (line, kind, subj, text, bg, face)

kind : SCENE_A ancient | SCENE_M modern | SCENE_W woman | GROUP nhom | SCENE_N khong nguoi | CARD
bg   : night_open night_fire cave_fire cave_mouth dry_plain dusk modern camp_wide white
face : flat shock tired worry scared happy asleep dumb curious sad
"""

SHOTS = [
# ══ HOOK ══
("Tonight you will go to bed behind a door that locks.","SCENE_M","he lies in a simple bed at night, a closed door on the wall behind him","no text","modern","asleep"),
("If something moves outside, a wall will be in the way.","SCENE_M","he sleeps in bed while a solid wall and a shut door stand between him and the dark outside","no text","modern","asleep"),
("For almost all of human history, none of that existed.","CARD","one long horizontal timeline line with tiny plain stick figures along it, and a very small bracket at the far right end","a small label \"US\" at the right end","white","flat"),
("No door.","CARD","a plain drawn door with a big red X through it","no text","white","flat"),
("No lock.","CARD","a simple padlock with a big red X through it","no text","white","flat"),
("No walls.","CARD","a short section of wall with a big red X through it","no text","white","flat"),
("Just a person on the ground in the open,","SCENE_A","he lies flat on his back on bare open ground with nothing around him at all","no text","night_open","worry"),
("with the sky on top of them.","SCENE_A","seen from far above, he is small on the ground under an enormous open night sky","no text","night_open","worry"),
("So why would anyone lie down like that and close their eyes?","SCENE_A","he lies on the ground and closes his eyes","no text","night_open","asleep"),
("How did anyone survive the night?","SCENE_A","he lies flat on the open ground at night with his eyes shut, completely defenceless","no text","night_open","asleep"),
("They had no claws, no night vision,","SCENE_A","he holds up both hands and stares at his own blunt fingertips, no claws at all","no text","dry_plain","dumb"),
("and a top speed that loses to a goose.","SCENE_A","he runs as hard as he can while a plain white goose strolls past him, easily faster","no text","dry_plain","dumb"),
("Everything out there that wanted to eat them could see in the dark.","SCENE_N","a pair of glowing yellow-green predator eyes floating in the dark just beyond the firelight","no text","night_fire","flat"),
("They could not.","SCENE_A","close-up of his face as he peers into the dark and sees nothing","no text","night_open","scared"),
("And we know exactly how that went for some of them.","SCENE_N","a broken piece of skull lying in the dirt, one corner catching the light","no text","cave_mouth","flat"),
("There is a piece of a skull from a South African cave called Swartkrans.","SCENE_N","a broken piece of a human skull lying half buried in the dirt on a cave floor","no text","cave_mouth","flat"),
("It is about 1.8 million years old,","CARD","the same skull fragment with an arrow and a written date beside it","a label \"1.8 MILLION YEARS\"","white","flat"),
("and it has two holes punched through the top of it,","SCENE_N","a broken skull fragment in the dirt, two clean round holes punched through the top of it","no text","cave_mouth","flat"),
("side by side.","CARD","the two round holes drawn large with a short measuring line between them","no text","white","flat"),
("The spacing matches the canine teeth of a leopard.","CARD","a leopard's jaw drawn in flat golden-brown with black rosettes, its two canine teeth lining up exactly with the two holes in the skull beside it","no text","white","flat"),
("So how do you lie down in that world and lose consciousness for six hours?","SCENE_A","he lies on the open ground with his eyes wide open, refusing to shut them","no text","night_open","scared"),
("The obvious answer is that somebody stayed awake and kept watch.","SCENE_A","he sits bolt upright with his back straight, staring out into the dark, keeping watch","no text","night_fire","tired"),
("Take shifts.","CARD","two stick figures with a curved arrow passing from one to the other","a label \"SHIFTS\"","white","flat"),
("Two hours each.","CARD","a plain clock face with a two-hour slice shaded in","no text","white","flat"),
("Wake the next person.","GROUP","one caveman leans over and shakes a sleeping caveman awake by the shoulder","no text","night_fire","tired"),
("That's what almost everyone assumes.","SCENE_M","he lies in bed with a thought bubble above him holding a small guard figure on watch","no text","modern","dumb"),
("It's also wrong.","CARD","that same thought bubble with a huge red X drawn straight through it","no text","white","flat"),
("In 2017,","CARD","nothing but the year","large hand-lettered text \"2017\"","white","flat"),
("researchers strapped activity trackers to an entire hunter-gatherer camp in Tanzania and watched them sleep for twenty nights.","GROUP","a whole camp of cavemen lying asleep on the ground, each one with a small dark band around one wrist","no text","camp_wide","asleep"),
("Across all twenty nights,","CARD","a grid of twenty small squares, each square a tiny crescent moon","no text","white","flat"),
("there were eighteen minutes when everybody was asleep at the same time.","CARD","one long horizontal bar filled almost completely, with a single tiny red sliver near one end","no text","white","flat"),
("Eighteen minutes.","CARD","nothing but the words","large hand-lettered text \"18 MINUTES\"","white","flat"),
("Nobody was assigned to keep watch.","GROUP","the whole camp lies asleep on the ground and not one figure is standing up","no text","camp_wide","asleep"),
("Nobody had to be.","SCENE_N","an empty stretch of ground at the edge of a sleeping camp, nobody standing there","no text","camp_wide","flat"),
("And whatever kept them alive is still happening in your house tonight.","SCENE_M","he lies awake in bed in the dark with his eyes open","no text","modern","tired"),
("There is no single answer to this.","CARD","one box on the page with a question mark inside it","no text","white","flat"),
("There never is.","CARD","that one box multiplying into three stacked boxes","no text","white","flat"),
("There are three layers,","CARD","three flat boxes stacked on top of each other, numbered 1, 2 and 3","no text","white","flat"),
("and the last one is why your grandfather wakes at five without an alarm.","SCENE_M","an older man sits on the edge of his bed in the dark, wide awake, an unused alarm clock on the table beside him","no text","modern","tired"),
("That one's at the end.","CARD","the same three stacked boxes with a black arrow pointing at the bottom one","no text","white","flat"),

# ══ CHUONG 1 — ho khong ngu luc troi toi ══
("Picture the night before electricity.","SCENE_A","he stands alone on open ground watching the last of the light go","no text","dusk","curious"),
("The sun goes down, the light goes away, everybody lies down.","GROUP","the sun has just dropped below the horizon and the whole group is lying down flat on the ground at once","no text","dusk","asleep"),
("That's the version everyone has in their head.","CARD","a stick figure with a thought bubble containing that exact picture of everyone lying down at sunset","no text","white","flat"),
("It's wrong, and it's wrong by about three hours.","SCENE_A","he is still sitting bolt upright by the fire long after dark, nowhere near sleep","no text","night_fire","flat"),
("In 2015 a team led by Jerome Siegel at UCLA put trackers on three groups who live without electric light.","CARD","a stick figure in a lab coat holding a clipboard, with the year written large beside him","large hand-lettered text \"2015\"","white","flat"),
("The Hadza in Tanzania.","CARD","a simple outline of the African continent with one dot marked on it","a label \"HADZA\"","white","flat"),
("The San in Namibia.","CARD","the same simple African outline with a different dot marked","a label \"SAN\"","white","flat"),
("The Tsimané in Bolivia.","CARD","a simple outline of South America with one dot marked","a label \"TSIMANE\"","white","flat"),
("Three groups on three continents who have never met and never heard of one another.","GROUP","three small separate groups of cavemen standing far apart from each other with wide empty ground between them","no text","dry_plain","flat"),
("Different languages, different ancestry, no shared history at all.","CARD","three speech bubbles side by side, each filled with a completely different pattern of squiggles","no text","white","flat"),
("So if all three do the same thing, that thing isn't culture.","GROUP","three separate groups of cavemen all doing exactly the same thing at the same moment","no text","dry_plain","flat"),
("All three went to sleep about three hours after sunset.","GROUP","the sun is long gone but the group is still sitting up around the fire, wide awake","no text","night_fire","flat"),
("Not at sunset.","SCENE_A","the sun is long gone and he is still sitting up wide awake, not lying down","no text","dusk","flat"),
("Three hours after.","SCENE_A","he sits wide awake by the fire long after the sun has gone","no text","night_fire","curious"),
("So what were they doing, in the dark, with nothing to do?","SCENE_A","he sits in the dark with nothing in his hands, looking around at nothing in particular","no text","night_fire","dumb"),
("Here's the part most people never think about.","SCENE_A","he sits by the fire in the dark, looking around at the others, thinking","no text","night_fire","curious"),
("What do you talk about when the work is done and there is nowhere to go?","GROUP","cavemen sitting close around the fire, several of them talking at once, hands moving","no text","night_fire","curious"),
("In 2014 the anthropologist Polly Wiessner published a study in the Proceedings of the National Academy of Sciences.","CARD","a stapled paper document lying flat with the year written large beside it","large hand-lettered text \"2014\"","white","flat"),
("She had spent years recording the actual conversations of the Ju/'hoansi in the Kalahari.","CARD","a small recording device with a wire, and an open notebook beside it","no text","white","flat"),
("Not what they told her they talked about.","CARD","a speech bubble with a big red X through it","no text","white","flat"),
("What they actually said.","GROUP","cavemen around the fire mid-conversation, several talking at once","no text","night_fire","happy"),
("In daylight, the talk was work.","GROUP","cavemen working in bright daylight, one carrying a bundle of wood, one digging at the ground","no text","dry_plain","tired"),
("Who is hunting where.","GROUP","two cavemen crouch over a patch of ground in daylight pointing out a route to each other","no text","dry_plain","curious"),
("Which plants are ready.","SCENE_W","she crouches beside a low plant in daylight, turning a leaf over to check it","no text","dry_plain","curious"),
("Who owes what.","GROUP","two cavemen stand facing each other in daylight, one holding out an open hand","no text","dry_plain","dumb"),
("After dark, around the fire, more than eighty percent of it was stories.","GROUP","cavemen packed close around the fire at night, all animated, arms up, mid-story","no text","night_fire","happy"),
("People in far-off places.","SCENE_N","a line of low distant hills at night with one tiny figure standing far away on them","no text","night_open","flat"),
("Journeys.","SCENE_A","he walks alone across wide open ground, seen small, a long way from anywhere","no text","dry_plain","curious"),
("The dead.","SCENE_N","a simple mound of earth with one upright stone standing beside it","no text","dry_plain","flat"),
("Jokes that got the whole camp laughing.","GROUP","the whole group around the fire doubled over laughing, heads back","no text","night_fire","happy"),
("Same people, same day,","GROUP","the same two cavemen standing together in daylight, exactly as they were","no text","dry_plain","flat"),
("and the talk changed completely once the sun went down.","GROUP","those same two cavemen now sitting by the fire at night, animated and mid-story","no text","night_fire","happy"),
("So those three hours were not people lying around waiting to fall asleep.","SCENE_A","he sits up by the fire, wide awake and animated, clearly not trying to sleep","no text","night_fire","happy"),
("They were the only hours nobody had a job to do.","SCENE_N","a stone tool and a wooden spear lying set down on the ground beside a burning fire","no text","night_fire","flat"),
("Fire did not just give us warmth and cooked meat.","SCENE_A","he holds both hands out to the fire to warm them while a piece of meat cooks on a stick","no text","night_fire","happy"),
("It gave us somewhere to be after the work was finished.","GROUP","cavemen simply sitting together around the fire, doing nothing in particular, comfortable","no text","night_fire","happy"),
("You have those three hours too.","SCENE_M","he lies in bed at night doing nothing","no text","modern","dumb"),
("You just call it being on your phone in bed.","SCENE_M","he lies in bed in the dark staring at a small glowing rectangle held above his face","no text","modern","dumb"),
("But here's the strange part.","CARD","a magnifying glass held over a small thermometer","no text","white","flat"),
("What put them to sleep wasn't the darkness.","CARD","a crescent moon with a big red X through it","no text","white","flat"),
("It was the temperature.","CARD","a plain thermometer drawn large, the level dropping","no text","white","flat"),
("They fell asleep as the air cooled, not as the light faded.","SCENE_A","he settles down to sleep on the cold ground, a small puff of breath visible in the air","no text","night_open","asleep"),
("Across all three groups, the sleep clock tracked the thermometer, not the sun.","CARD","a thermometer and a sun side by side, a black arrow pointing firmly at the thermometer and a red X over the sun","no text","white","flat"),
("Clouds hide the sun.","SCENE_N","a flat cloud drifting across and covering the sun over open ground","no text","dry_plain","flat"),
("Trees hide the sun.","SCENE_N","a single tree standing directly in front of the sun and blocking it","no text","dry_plain","flat"),
("Nothing hides the cold.","SCENE_A","he stands out in the open at night with his arms wrapped tightly around himself","no text","night_open","tired"),
("Not the dark.","CARD","a crescent moon with a red X through it","no text","white","flat"),
("The cold.","CARD","nothing but the words","large hand-lettered text \"THE COLD\"","white","flat"),
("Remember that.","CARD","a small thermometer with a circle drawn around it","no text","white","flat"),

# ══ CHUONG 2 — ho ngu IT hon ban ══
("So they went to bed three hours late.","SCENE_A","he finally lies down long after dark, the fire burned low beside him","no text","night_fire","asleep"),
("Which means they slept in.","SCENE_A","he is still fast asleep on the ground with the sun already well up in the sky","no text","dry_plain","asleep"),
("Right?","CARD","one large hand-drawn question mark alone on the page","no text","white","flat"),
("No.","CARD","one huge red X alone on the page","no text","white","flat"),
("All three woke before sunrise,","SCENE_A","he sits up on the cold ground in the dark before there is any light in the sky","no text","night_open","tired"),
("the Hadza about an hour before the sun came up.","SCENE_A","he is already sitting up in the grey dark while the sky is still black behind him","no text","night_open","tired"),
("Add it together and you get a number that ruins a story you have heard a hundred times.","CARD","two numbers on the page with a plus sign and a line drawn under them","no text","white","flat"),
("Between 5.7 and 7.1 hours a night.","CARD","nothing but the numbers","large hand-lettered text \"5.7 - 7.1 HOURS\"","white","flat"),
("Average, 6.4.","CARD","nothing but the number","large hand-lettered text \"6.4\"","white","flat"),
("The researchers put that at the low end of what people in industrialised countries get.","CARD","a simple bar chart of several bars, with one bar marked in red near the low end of the range","no text","white","flat"),
("So the people with no lights, no clocks and no alarms,","SCENE_A","he wakes on the bare ground in the dark with nothing around him to tell him the time","no text","night_open","tired"),
("and no mattress that costs more than a car,","CARD","a thick mattress with a price tag hanging off it and a red X through it","no text","white","flat"),
("were not sleeping any more than you are.","SCENE_M","he lies in bed looking sideways at the viewer, unimpressed","no text","modern","flat"),
("Every article you have ever read about how modern life stole your sleep.","CARD","a magazine page standing upright with a headline of squiggle lines on it","no text","white","flat"),
("That's the sound of it falling over.","CARD","that same magazine page tipped over and lying flat on the ground","no text","white","flat"),
("Somewhere a wellness brand is quietly deleting a slide.","SCENE_M","he stands beside a presentation board quietly wiping one panel blank, glancing sideways","no text","modern","dumb"),
("And it gets worse for the theory.","SCENE_M","he sits on the edge of his bed with his head in his hands","no text","modern","sad"),
("If modern life broke our sleep, who exactly is sleeping badly?","SCENE_M","he sits up in bed in the dark with a big question mark drawn in the air beside him","no text","modern","curious"),
("The researchers asked all three groups whether they had trouble sleeping.","GROUP","a figure with a clipboard asks a group of cavemen a question and they all shrug back at him","no text","dry_plain","dumb"),
("About two percent said yes.","CARD","a bar chart with one very short bar","a small label \"2%\"","white","flat"),
("In industrialised countries the figure runs between ten and thirty percent.","CARD","the same chart with a second bar many times taller beside the short one","a small label \"10-30%\"","white","flat"),
("And none of the three languages has a word for insomnia.","CARD","three speech bubbles side by side, each with an obvious blank gap in the middle of its squiggles","no text","white","flat"),
("They don't have the word because they don't have the problem.","GROUP","cavemen all sleeping soundly, none of them troubled","no text","camp_wide","asleep"),
("It is hard to complain about something your language has never needed a word for.","SCENE_A","he opens his mouth to complain and nothing comes out, an empty speech bubble above his head","no text","dry_plain","dumb"),
("And go back to the cold.","SCENE_A","he sits in the dark feeling the air change, pulling his hide tighter","no text","night_open","tired"),
("They did not wake because it got light.","CARD","a rising sun with a red X through it","no text","white","flat"),
("They woke because the night bottomed out.","SCENE_A","he wakes with a jolt in the coldest part of the night, breath showing in the air","no text","night_open","tired"),
("Your bedroom is the same temperature at three in the morning as it was at nine.","SCENE_M","he lies in bed while a small square thermostat on the wall shows the same reading all night","no text","modern","flat"),
("The drop never comes.","CARD","a perfectly flat horizontal line running all the way across the page with no dip in it","no text","white","flat"),
("Something in you is still waiting for it.","SCENE_M","he lies flat on his back in bed in the dark, eyes wide open, listening for something","no text","modern","tired"),
("So they went to bed late, they slept little,","SCENE_A","he lies down very late and gets up again far too soon, worn out","no text","night_open","sad"),
("and they woke in the cold.","SCENE_A","he sits hugging his knees in the cold dark before dawn, shivering","no text","night_open","sad"),

# ══ CHUONG 3 — khong ai duoc cat cu gac ══
("None of which explains the skull.","SCENE_N","the broken skull fragment lying alone in the dirt with its two holes showing","no text","cave_mouth","flat"),
("For all those hours, lying in the open, with no door.","SCENE_A","seen wide, he lies alone on the open ground with nothing around him for a long way","no text","night_open","asleep"),
("Who was watching?","SCENE_A","he lies asleep on the open ground while the dark presses in around him","no text","night_open","asleep"),
("Back to the obvious answer, the one everybody reaches for.","SCENE_A","he stands upright holding a spear, on watch, staring out into the dark","no text","night_fire","tired"),
("A rota.","CARD","a simple grid chart with names down one side and shaded blocks across it","no text","white","flat"),
("Somebody sits up, watches the dark, and hands it over.","GROUP","one caveman sits up watching the dark while the others sleep, reaching out to wake the next","no text","night_fire","tired"),
("Armies do it.","CARD","a stick figure with a simple helmet standing on watch","no text","white","flat"),
("Ships do it.","CARD","a simple boat outline with one tiny stick figure standing on deck","no text","white","flat"),
("Fire stations have done it since there were fire stations.","CARD","a simple building with a large door and one tiny stick figure awake inside","no text","white","flat"),
("But what does a night watch actually cost?","SCENE_A","he sits on watch with his eyes half closing, fighting to stay awake","no text","night_fire","tired"),
("It costs one person's sleep.","SCENE_A","he sits alone in the dark on watch, exhausted, everyone else asleep behind him","no text","night_fire","tired"),
("Every night.","SCENE_A","he sits alone on watch in the dark, the same as every other night","no text","night_fire","tired"),
("Forever.","SCENE_A","he sits on watch in the dark, seen small, the night stretching away around him","no text","night_open","tired"),
("And the danger that watch was paying for was not theoretical.","SCENE_N","a leopard stands still at the very edge of the firelight, side on, its head turned toward the camp, its eyes glowing yellow-green","no text","night_fire","flat"),
("Go back to that skull from Swartkrans.","SCENE_N","the broken skull fragment lying in the dirt on a cave floor","no text","cave_mouth","flat"),
("It was dug up in 1949.","SCENE_N","a small trowel and a brush lying in the dirt beside a half uncovered skull fragment","no text","cave_mouth","flat"),
("It has a catalogue number, SK 54.","CARD","the skull fragment with a small paper tag tied to it","a tag reading \"SK 54\"","white","flat"),
("The two holes in it are not somebody's reading of a myth or a cave painting.","CARD","a rolled scroll and a small cave painting side by side, both with red X through them","no text","white","flat"),
("They are a bite mark, left in bone,","CARD","a very close view of the two round holes in the bone","no text","white","flat"),
("on a relative of ours who did not make it through the night.","SCENE_A","he lies completely still and flat on the ground, not moving","no text","night_open","asleep"),
("So the stakes were exactly what you think they were.","SCENE_A","he lies down on the open ground and closes his eyes anyway","no text","night_open","scared"),
("Which makes what the trackers found much harder to explain.","GROUP","a camp of sleeping cavemen with a large question mark drawn in the air above them","no text","camp_wide","asleep"),
("In 2017 a team led by David Samson wired up an entire Hadza camp.","GROUP","every caveman in the camp lying down for the night, each with a small dark band around one wrist","no text","camp_wide","asleep"),
("Not a few volunteers.","GROUP","a small handful of cavemen standing apart with a big red X drawn over them","no text","camp_wide","flat"),
("Everybody.","GROUP","the entire camp lying down for the night, every single person, none left out","no text","camp_wide","asleep"),
("Every night.","SCENE_A","he sits alone on watch in the dark, the same as every other night","no text","night_fire","tired"),
("Twenty nights.","SCENE_N","a camp seen from a distance under a night sky, night after night, the same place","no text","camp_wide","flat"),
("If there was a watch rota, this would show it.","CARD","an empty chart grid waiting to be filled in","no text","white","flat"),
("Two-hour shifts would show up as a pattern.","CARD","a chart with a neat repeating staircase pattern drawn across it","no text","white","flat"),
("A designated guard would show up as one person awake all night.","CARD","a chart with one single unbroken line running all the way across the top","no text","white","flat"),
("They found neither.","GROUP","a camp of sleeping cavemen with nobody standing guard anywhere in the frame","no text","camp_wide","asleep"),
("No rota.","CARD","a rota grid with a red X through it","no text","white","flat"),
("No shifts.","CARD","a staircase pattern with a red X through it","no text","white","flat"),
("Nobody on duty.","SCENE_N","an empty stretch of ground at the edge of a sleeping camp where a guard should be","no text","camp_wide","flat"),
("Across all twenty nights,","CARD","a grid of twenty small night squares","no text","white","flat"),
("there were eighteen minutes when the whole camp was asleep at once.","CARD","one long horizontal bar filled almost completely, with a single tiny red sliver in it","no text","white","flat"),
("Eighteen minutes.","CARD","nothing but the words","large hand-lettered text \"18 MINUTES\"","white","flat"),
("Out of twenty nights.","SCENE_N","the same camp under the night sky, one night after another after another","no text","camp_wide","flat"),
("For 99.8 percent of the time they measured,","CARD","nothing but the number","large hand-lettered text \"99.8%\"","white","flat"),
("at least one person was awake.","GROUP","a camp of sleeping cavemen with exactly one figure sitting upright among them","no text","camp_wide","tired"),
("The median number of people awake during the night was eight.","GROUP","a camp at night with eight cavemen sitting upright while the rest lie asleep","no text","camp_wide","tired"),
("Eight people.","CARD","nothing but the number","large hand-lettered text \"8\"","white","flat"),
("Up.","GROUP","eight cavemen sitting upright in the dark camp while everyone else lies asleep around them","no text","camp_wide","tired"),
("In the dark.","SCENE_N","a quiet camp at night, a low fire burning down, everything still","no text","camp_wide","flat"),
("Doing nothing in particular.","GROUP","cavemen sitting up in the dark doing nothing at all, one scratching his head, one just staring","no text","camp_wide","dumb"),
("In a camp where not one of them had been told to stay awake.","GROUP","cavemen sitting up around a dark camp with no one giving any orders, everyone on their own","no text","camp_wide","dumb"),
("So how do you guard a camp with nobody on guard?","CARD","nothing but the words","large hand-lettered text \"HOW?\"","white","flat"),
("Age.","GROUP","cavemen of clearly different ages standing in a row: an old one, two young ones, a child","no text","dry_plain","happy"),
("The older people went to bed early and woke early.","GROUP","an old caveman with grey hair is already lying down asleep while younger ones are still sitting up by the fire","no text","night_fire","asleep"),
("The younger ones stayed up late and slept in.","GROUP","two young cavemen still wide awake and talking late by the fire while everyone else is asleep","no text","night_fire","happy"),
("The ones with small children were up in the middle,","GROUP","a caveman woman sits up in the middle of the night holding a small child while everyone else sleeps","no text","night_fire","tired"),
("for reasons every parent watching this already understands.","SCENE_W","she sits in the dark holding a small child, both of them awake, her eyes heavy","no text","night_fire","tired"),
("Nobody was covering a shift.","GROUP","cavemen lying and sitting at random around the camp, no order to it at all","no text","camp_wide","dumb"),
("Everybody was following their own clock.","GROUP","cavemen lying and sitting at all different stages of the night, each on his own schedule","no text","camp_wide","flat"),
("And because those clocks were spread out,","CARD","those same five clocks arranged along one long horizontal night line, evenly spread","no text","white","flat"),
("the camp was never all asleep at once.","GROUP","a night camp with most people asleep and two or three always sitting up","no text","camp_wide","tired"),
("The group was never unguarded,","GROUP","a sleeping camp with one caveman awake at the edge, watching outwards","no text","camp_wide","scared"),
("because the group was never all the same age.","GROUP","cavemen of clearly different ages standing together: an old one with grey hair, two young ones, a child","no text","dry_plain","happy"),
("Researchers call this the sentinel hypothesis.","CARD","nothing but the words","large hand-lettered text \"SENTINEL HYPOTHESIS\"","white","flat"),
("A guard rota that nobody wrote, nobody enforced,","CARD","a rota grid with every name line left blank and no signature at the bottom","no text","white","flat"),
("and nobody could get out of.","SCENE_A","he tries to walk away from the group into the dark and stops, finding nowhere to go","no text","night_open","sad"),
("Not one person lost a night's sleep to protect anybody.","SCENE_A","he sleeps soundly and completely relaxed on the ground","no text","night_fire","asleep"),
("Nobody had to be talked into it,","GROUP","two cavemen face each other arguing, and a big red X is drawn over them","no text","night_fire","flat"),
("and nobody had to be thanked for it.","GROUP","one caveman offers a hand to another in thanks, and a red X is drawn over it","no text","night_fire","flat"),
("It came free with being a group of people who were not all the same age.","GROUP","cavemen of clearly different ages sitting together around the fire: old, young and a child","no text","night_fire","happy"),

# ══ KHUC THANH THAT ══
("Now the honest part.","SCENE_A","he stands facing the viewer with both hands open, admitting something","no text","dry_plain","flat"),
("That study is one camp, twenty nights, in 2017.","SCENE_N","one small camp at night seen from a distance, alone in a wide dark landscape","no text","camp_wide","flat"),
("Nobody has measured a night from fifty thousand years ago,","CARD","a measuring tape stretching back across the page and snapping off short","no text","white","flat"),
("and nobody ever will.","CARD","the broken end of that measuring tape with a red X beside it","no text","white","flat"),
("It shows the mechanism works in living hunter-gatherers.","GROUP","a camp of cavemen sleeping at different times, some up, some down, working as it should","no text","camp_wide","flat"),
("It does not show your ancestors had it.","SCENE_A","he stands alone with a large question mark drawn in the air beside his head","no text","night_open","curious"),
("And even if they did, it was never the whole answer.","SCENE_A","he stands with one hand raised, only partly convinced","no text","night_open","curious"),
("Fire mattered.","SCENE_N","one small campfire burning alone on open ground at night","no text","night_fire","flat"),
("So did numbers, and a spear within reach.","GROUP","a tight cluster of cavemen sleeping close together with a wooden spear lying beside them","no text","camp_wide","asleep"),
("A sleeping camp is a harder thing to approach than one sleeping person.","SCENE_N","a leopard stands well back from a sleeping camp, hesitating, its head turned toward the group","no text","camp_wide","flat"),
("How much each of those was worth, nobody can put a figure on.","CARD","a weighing scale with question marks in both pans","no text","white","flat"),
("Somebody was awake almost all the time.","GROUP","a night camp with one caveman always sitting up somewhere in the frame","no text","camp_wide","flat"),
("Almost is not always.","CARD","the same bar with the one small unfilled gap circled in red","no text","white","flat"),
("SK 54 is what almost looks like.","SCENE_N","the broken skull fragment lying alone in the dirt with its two holes clearly visible","no text","cave_mouth","flat"),

# ══ KET ══
("So, how did ancient humans sleep in the open?","CARD","nothing but the words","large hand-lettered text \"SO HOW DID THEY SLEEP?\"","white","flat"),
("Badly, briefly, and in the cold.","SCENE_A","he lies curled up tight on the cold bare ground, not comfortable at all","no text","night_open","tired"),
("Three hours after dark, six hours a night, awake before the sun.","CARD","three small icons in a row: a clock pushed late, a short bar, a sun still below the horizon","no text","white","flat"),
("And never, as far as anyone can measure, all at once.","CARD","a long night bar with no gap anywhere in it","no text","white","flat"),
("Which brings this back to your house.","SCENE_M","a simple house seen from outside at night with one window still lit","no text","modern","flat"),
("How many people in it are awake right now?","SCENE_M","he lies awake in the dark while the rest of the house is silent","no text","modern","curious"),
("Your grandfather wakes at five and cannot get back to sleep.","SCENE_M","an older man sits on the edge of his bed in the half dark, awake, staring at nothing","no text","modern","tired"),
("Your teenage brother is awake at two and cannot be moved before noon.","SCENE_M","a younger man lies in bed wide awake in the middle of the night with a glowing screen beside him","no text","modern","dumb"),
("Somebody in your family gets up in the middle of the night,","SCENE_M","he pads across a dark room in the middle of the night","no text","modern","tired"),
("every night, and always has.","SCENE_M","he stands in a dark kitchen in the middle of the night, the same as always","no text","modern","tired"),
("You have called at least one of those things a problem.","CARD","nothing but the word","large hand-lettered text \"A PROBLEM\"","white","flat"),
("They are not a problem.","CARD","that same word with a big red X drawn through it","no text","white","flat"),
("They are a rota.","GROUP","cavemen of different ages awake at different points around a dark camp, covering the whole night between them","no text","camp_wide","flat"),
("Different bodies, set to different hours,","CARD","several clock faces in a row, each showing a different time","no text","white","flat"),
("covering a night nobody ever sat down and divided up.","CARD","one long night bar fully covered, with no dividing lines drawn on it at all","no text","white","flat"),
("The camp is gone.","SCENE_N","bare empty ground at night where a camp used to be, nothing left","no text","night_open","flat"),
("The fire is gone.","SCENE_N","a cold ring of grey stones on the ground with no fire in it","no text","night_open","flat"),
("The leopard is gone.","SCENE_N","an empty patch of dark ground at the edge of where the firelight used to reach","no text","night_open","flat"),
("Nobody needs anybody to be awake any more.","SCENE_M","he sleeps safely in a bed behind a closed door","no text","modern","asleep"),
("Tonight,","SCENE_M","a dark quiet bedroom at night with one closed door","no text","modern","flat"),
("someone in your house will wake at three in the morning for no reason they can name.","SCENE_M","close-up of his face as his eyes open in the dark for no reason","no text","modern","flat"),
("They will lie there in the dark and call it insomnia.","SCENE_M","he lies flat on his back in the dark, wide awake, arms straight at his sides","no text","modern","tired"),
("And they will still be listening,","SCENE_M","he lies still in the dark, head slightly turned, listening to the room","no text","modern","flat"),
("on the safe side of a locked door.","SCENE_M","he lies awake in bed, and behind him on the wall is one shut door with a lock on it","no text","modern","flat"),
]
