# -*- coding: utf-8 -*-
# Phần RIÊNG của từng shot V15. Thứ tự = thứ tự SHOTLINES_FULL.txt.
# (nhân vật, hành động+biểu cảm, góc máy, nền, chữ-trên-hình)
# nhân vật: modern | caveman | woman | child | none
# góc máy:  m medium · w wide · c close-up · hi high-angle · lo low-angle
# nền:      white | sky | dirt | cave | night | fire | indoor | body | green

SHOTS = [
# ---------- ĐỢT 1: HOOK + ALLERGY LÀ GÌ (001-100) ----------
("none", "one cute flat wall calendar page with a big spring blossom branch beside it, a single pink flower open on the branch", "m", "white", "APRIL"),
("modern", "mid-sneeze, head thrown forward into his own raised elbow, eyes squeezed shut, small motion lines bursting around his head", "m", "white", None),
("modern", "standing tired and deadpan beside a small chalk tally of nine marks, one hand holding a crumpled white tissue", "m", "white", "9"),
("modern", "in tight close-up with two big round watering eyes, a fat blue teardrop rolling from each eye, worried eyebrows", "c", "white", None),
("modern", "in close-up with a small red blocked nose and two little black X marks over the nostrils, mouth open to breathe", "c", "white", None),
("modern", "standing completely alone in empty space, arms slightly out, glancing around with a curious tilted head", "w", "white", None),
("none", "a cluster of five cute flat yellow round pollen grains with tiny simple faces, floating gently together", "c", "white", None),
("none", "a scatter of tiny cute yellow pollen grains drifting across open air on soft curved motion lines", "w", "sky", None),
("modern", "standing at a simple black signpost with two arrows pointing opposite ways, one arrow carrying a small yellow flower and the other a small brown peanut, curious tilted head", "w", "white", None),
("modern", "holding up one round flat brown cookie with both mitten hands, turning it over to look at the back", "m", "indoor", None),
("none", "one flat cream food packet held up close, with a small black rectangle of tiny unreadable print on the back", "c", "indoor", None),
("none", "one cute flat tan peanut in its shell with a little face, sitting alone under a bold hand-drawn warning line", "m", "white", "MAY CONTAIN"),
("modern", "standing frozen with wide round shocked eyes and a small open O mouth, a big red downward arrow drawn through his middle", "m", "white", None),
("none", "a cute flat grey six-wheeled Mars rover with a little face and a small antenna, parked on a flat rust-red planet surface", "w", "night", None),
("modern", "standing very small beside one enormous cute flat tan peanut that towers over him, looking up with wide round eyes", "lo", "white", None),
("none", "one cute flat white-and-red ambulance with a little face, a small red cross on its side and a tiny blue light on top", "m", "white", None),
("modern", "standing in a stiff soldier pose holding a tiny black flag, facing one cute flat pink daisy with a little smiling face, deadpan flat straight mouth", "m", "white", "WAR"),
("caveman", "standing calmly with a curious tilted head, one mitten hand raised in a small wave", "m", "white", None),
("none", "a long horizontal black timeline line with a single marker dot at the far left and one tiny plain white stickman standing on it", "w", "white", "50,000 BC"),
("caveman", "lying asleep on flat bare ground, eyes closed as two small curved lines, tiny z z z floating above his head", "hi", "dirt", None),
("caveman", "crouching down and scooping water from a small flat blue puddle with both mitten hands, drinking", "hi", "dirt", None),
("caveman", "crouched over a simple flat brown animal shape on the ground, both hands working at it, deadpan flat straight mouth, nothing graphic", "m", "dirt", None),
("caveman", "sitting beside a small flat orange campfire with grey curls of smoke drifting across his face, eyes half closed", "c", "fire", None),
("caveman", "standing calm and deadpan while five cute flat pink wiggly worms with little smiling faces float cheerfully around him", "m", "dirt", None),
("modern", "standing with a simple black outline of a coiled gut drawn on his belly, completely empty inside, one small green check mark beside it", "m", "white", None),
("caveman", "standing covered in small brown dirt smudges with little dust puffs around him, arms out, deadpan flat straight mouth", "m", "dirt", None),
("caveman", "standing calm and relaxed with half-lidded eyes, holding a small flat grey shield lowered and resting on the ground", "m", "dirt", None),
("none", "one simple black picture frame hanging on a wall, containing a small drawing of a caveman sitting beside a campfire", "m", "indoor", None),
("caveman", "standing beside one cute oversized white cotton swab with a big red X drawn over the swab, curious tilted head", "m", "white", None),
("none", "one flat yellow ruler laid across a small flat landscape of green ground with one tree and one blue puddle", "w", "white", None),
("none", "a simple black open doorway with three cute flat pink worms and two cute round green microbes with little faces walking out through it, small motion lines behind them", "w", "white", None),
("modern", "standing with an empty round white speech bubble floating beside his head, deadpan flat straight mouth", "m", "white", None),
("none", "one cute flat blue soap bar with a little face and three small sparkle marks, sitting on a spotless empty floor line", "c", "white", "TOO CLEAN"),
("none", "one large green check mark drawn big and centered", "m", "white", None),
("none", "a simple black cross-section line with a very shallow blue puddle on top and a much deeper dark shape hidden below it, a small black arrow pointing down", "m", "white", None),
("none", "one flat grey shield, whole and undamaged, with a small green check mark beside it", "m", "white", None),
("modern", "sitting slumped on a small black bench holding a tiny white sheet of paper, a flat grey shield propped unused beside him, deadpan flat straight mouth", "w", "white", None),
("none", "a stack of four flat coloured horizontal layers, the bottom layer marked with a small black arrow pointing at it", "m", "white", None),
("none", "a long horizontal black line with one small closed wooden box sitting at the far right end of it", "w", "white", None),
("none", "a big red X on the left with a black arrow pointing right toward a big green check mark", "m", "white", None),
("modern", "standing with a round thought bubble above his head containing a single bold question mark, curious tilted head", "m", "white", None),
("modern", "swinging a small fist toward one cute flat pink daisy with a little face, the flower leaning back with wide round surprised eyes", "m", "white", None),
("none", "one small white box with a big red X over it and three small black question marks floating above", "m", "white", None),
("none", "a tall stack of five flat coloured horizontal layers seen from the side, each a different flat colour", "m", "white", None),
("modern", "standing at the top of a deep black vertical shaft that runs off the bottom of the frame, peering down with wide round eyes", "hi", "white", None),
("none", "a stack of four flat coloured layers, each drawn slightly more oddly shaped than the one above, a small black question mark on the lowest", "m", "white", None),
("none", "one open white book with a single bold underlined heading line and three short scribbled text lines below it", "m", "white", "ALLERGY"),
("modern", "standing with sagging shoulders and drooping arms, a big red X drawn over him", "m", "white", None),
("modern", "holding a small black bow and arrow but aiming completely the wrong way, a small red target sitting unnoticed behind him, deadpan flat straight mouth", "w", "white", None),
("none", "one flat white clipboard with a black clip and four short scribbled lines on it", "m", "white", None),
("none", "one flat white list sheet showing three tiny drawings in a column, a round green microbe, a pink worm and a small grey spiky virus, each with a little face", "c", "white", None),
("none", "three cute flat characters standing in a row, a small purple spiky virus, a round green bacterium and a long pink worm, each with a simple little face", "m", "white", None),
("none", "a simple black outline of a house with one small red arrow pushing in through the front door", "m", "white", None),
("modern", "standing plainly with a small paper tag on a string hanging from his wrist, deadpan flat straight mouth", "m", "white", None),
("none", "one flat white clipboard list with three tiny threat drawings and, at the bottom, one cute flat pink daisy with a little smiling face clearly out of place", "m", "white", None),
("none", "one cute flat yellow round pollen grain with a simple little face, drawn big and alone", "c", "white", None),
("none", "one cute flat tan peanut in its shell with a simple little face, drawn big and alone", "c", "white", None),
("none", "one cute flat orange cat with a little face, three tiny white flakes floating off its back", "m", "white", None),
("none", "one flat white clipboard list with a small black tick being drawn beside the bottom entry", "c", "white", None),
("none", "one flat cream wanted poster pinned to a wall, showing a cute flat yellow pollen grain with a little face in the middle", "m", "white", "WANTED"),
("none", "one cute flat blue Y-shaped antibody with a simple little face, drawn big and centered, a small black arrow labelling it", "m", "white", "IgE"),
("none", "one cute flat blue Y-shaped antibody with a little face, its two arms cupping one cute flat yellow pollen grain that slots in perfectly like a puzzle piece", "c", "white", None),
("none", "one cute flat yellow pollen grain and one cute flat red apple slice standing side by side, both drawn with exactly the same simple little face, a small black equals sign between them", "m", "white", None),
("none", "one cute flat blue Y-shaped antibody with a little face handing a small cream poster to three cute round purple cells with little faces standing in a line", "m", "white", None),
("none", "one large cute round purple mast cell with a little face, its inside drawn full of small tightly packed orange dots", "c", "white", None),
("none", "a simple black outline of a house with one cute round purple cell with a little face parked at every door and every window", "w", "white", None),
("modern", "in tight close-up with a small black arrow pointing at his nose", "c", "white", None),
("modern", "in tight close-up with a small black arrow pointing at his throat", "c", "white", None),
("none", "one pair of cute flat pink lungs with simple little faces, drawn big and centered", "m", "white", None),
("modern", "with one arm held out and a small black arrow pointing at the surface of the arm", "c", "white", None),
("none", "one cute flat pink coiled gut with a simple little face, drawn big and centered", "m", "white", None),
("none", "three flat brown wooden crates stacked together, each sealed shut with black bands and marked with a small red warning triangle", "m", "white", None),
("none", "a simple black outline of a house with one flat brown sealed crate parked at every door and every window", "w", "white", None),
("none", "one flat brown wooden crate in close-up with a small cream label on the front showing one cute flat pink daisy with a little face", "c", "white", "FLOWER"),
("none", "one cute flat yellow pollen grain with a little face drifting down on a curved motion line and just touching the top of a flat brown sealed crate", "m", "white", None),
("none", "one flat brown wooden crate with its lid flung wide open, small black motion lines bursting upward from inside", "m", "white", None),
("none", "five flat brown wooden crates in a row, every single lid flung wide open at the same moment", "w", "white", None),
("none", "one large flat orange starburst shape drawn big and centered with sharp black motion lines radiating out", "m", "white", None),
("none", "a stream of cute flat orange round chemical blobs with little faces pouring out of an open flat brown crate", "m", "white", "HISTAMINE"),
("none", "a big heap of cute flat chemical blobs in orange, green and purple, each with a simple little face, piled up together", "m", "white", None),
("modern", "standing with one region of his chest circled in a black ring and a small black arrow pointing into it", "m", "white", None),
("none", "one cute flat pink worm with a little face running away fast from a red-marked zone, small motion lines behind it and a red no-entry circle above", "m", "white", None),
("none", "one cute flat red tube with a little face, three small red droplets escaping through tiny gaps in its side", "c", "white", None),
("none", "one flat pink rounded tissue shape puffed up big, with four small black arrows pointing outward around it", "w", "white", None),
("none", "a flat green wave of thick mucus flooding across the frame from one side with small curved motion lines", "w", "white", None),
("none", "one cute flat pink airway tube with a little face, squeezed narrow in the middle by two black arrows pressing in from each side", "c", "white", None),
("modern", "mid-sneeze with head thrown back, eyes squeezed shut and a burst of small motion lines from his nose", "m", "white", None),
("modern", "scratching hard at one arm with the other hand, small red squiggle marks on the skin, nervous wavy mouth", "m", "white", None),
("modern", "in close-up with both hands at his throat, a small red narrowing tube drawn at his neck, wide round frightened eyes", "c", "white", None),
("modern", "standing with both mitten hands turned up in a shrug and a big bold question mark floating above his head, dumb clueless expression", "m", "white", None),
("none", "one very small grey shield beside one very large grey shield, with a big red X drawn over the small one", "m", "white", None),
("none", "one large flat grey shield drawn big and centered with a small green check mark beside it", "m", "white", None),
("none", "a long black rack holding many simple flat weapons and shields lined up side by side", "w", "white", None),
("none", "a row of flat weapons all firing small motion lines toward one tiny cute flat yellow pollen grain with a little face", "w", "white", None),
("none", "one cute flat yellow pollen grain with a little smiling face holding up both tiny arms harmlessly, a small green check mark beside it", "c", "white", None),
("none", "two cute flat pink daisies with little smiling faces leaning toward each other, one tiny yellow pollen grain floating between them on a curved dotted line", "m", "green", None),
("modern", "in close-up with one cute flat yellow pollen grain with a little face sitting on the tip of his nose, eyes crossed looking down at it", "c", "white", None),
("none", "one large red warning triangle with a bold black upright warning stroke and dot inside it", "m", "white", None),
("none", "one cute flat pink airway tube with a little worried face, pinched completely shut in the middle and marked with a small red X", "m", "white", None),
("none", "one flat grey fork lying on a table line with a single tiny tan peanut crumb on its tip, a small black magnifying circle around the crumb", "c", "indoor", None),
# ---------- ĐỢT 2: SĂN GÌ · NỌC ĐỘC · DỌN SẠCH · SỐ LIỆU · STRACHAN (101-260) ----------
("none", "one cute flat tan peanut with a little smiling face holding up both tiny arms harmlessly, a small green check mark beside it", "m", "white", None),
("modern", "standing stiffly upright on guard duty holding a small black spear, wide awake with big round alert eyes, a red X over a tiny sleeping z z z beside him", "m", "white", None),
("modern", "in close-up on guard duty, staring hard at one tiny cute flat pink petal floating in front of his face, wide round eyes", "c", "white", None),
("modern", "slamming one mitten hand down on a huge round red button on a black console, deadpan flat straight mouth", "m", "white", None),
("none", "one enormous flat grey cannon aimed directly at one tiny cute flat pink daisy with a little face, the size difference absurd", "w", "white", None),
("none", "one large flat grey cannon with black motion lines bursting from its mouth, drawn big and centered", "m", "white", None),
("none", "one large flat grey cannon aimed at a big black question mark floating in front of it", "m", "white", None),
("modern", "holding a large round magnifying glass up and peering through it with a curious tilted head", "m", "white", None),
("none", "one cute flat pink worm with a simple little face, drawn big and alone", "m", "white", None),
("none", "three cute flat pink worms with simple little faces wriggling together", "m", "white", None),
("none", "one cute flat yellow-and-black bee with a little face and one cute flat sandy-brown scorpion with a little face, standing side by side", "m", "white", None),
("none", "a simple black flowchart of three boxes joined by arrows, the first box holding a tiny green microbe with a little face", "w", "white", None),
("none", "one very small cute round green microbe with a simple little face, drawn tiny in a large empty frame", "w", "white", None),
("none", "one cute round purple immune cell with a little face holding a magnifying glass over one tiny green microbe", "m", "white", None),
("none", "one cute round purple immune cell with a little face opening wide and swallowing one tiny green microbe whole", "m", "white", None),
("none", "one cute round purple immune cell with a little satisfied face and a small green microbe dissolving into dots inside it", "c", "white", None),
("none", "one cute round purple immune cell with a little face standing over one tiny green bacterium, a small green check mark beside them", "m", "white", None),
("none", "one tiny cute round purple immune cell beside one enormous long cute flat pink tapeworm with a little face that runs right across the frame, a big red X over the little cell", "w", "white", None),
("none", "a simple black signpost with two arrows, the first labelled with a tiny microbe and the second with a large worm, the second arrow circled in black", "w", "white", None),
("none", "one cute flat pink worm with a little face sitting comfortably in a small flat brown armchair inside a simple black room outline", "m", "white", None),
("none", "a simple black room outline being wrecked around one cute flat pink worm, small black motion lines and a tilted armchair", "m", "white", None),
("none", "a flat green wave of thick mucus flooding into a simple black room outline from both sides", "m", "white", None),
("none", "a simple black tube with two thick muscle walls squeezing inward, four black arrows pressing in", "w", "white", None),
("none", "a row of black arrows all pointing toward one small open black door at the end of a tube", "w", "white", None),
("none", "one cute flat pink coiled gut with a little face, one section of it circled in a black ring", "m", "white", None),
("none", "one cute flat pink worm with a little unhappy face holding a tiny suitcase, walking out of a flooded black room outline", "m", "white", None),
("none", "one cute flat blue Y-shaped antibody with a little face wearing a small white name badge on its front", "c", "white", "IgE"),
("none", "one large cute round purple mast cell with a little face, packed full of small orange dots and standing beside a small stack of crates", "m", "white", None),
("none", "one flat white clipboard list with four short scribbled lines and a small black arrow curling back to the top", "m", "white", None),
("none", "three cute flat icons in a row, a green mucus blob with a little face, a puffed pink swelling shape and a black cramping spiral", "m", "white", None),
("none", "two cute flat icons side by side, a pair of streaming blue eyes and a black arrow rushing out through a small open door", "m", "white", None),
("modern", "standing miserable with a red nose, watering eyes and slumped shoulders, nervous wavy mouth", "m", "white", None),
("modern", "sneezing hard beside one cute flat wall calendar page with a spring blossom branch on it", "m", "white", "APRIL"),
("none", "a very long horizontal black timeline line stretching right across the frame with tiny plain white stickmen dotted along it", "w", "white", None),
("none", "one cute flat blue globe with a simple little face and five small black location pins stuck around it", "m", "white", None),
("none", "one flat white medical chart with a big red X drawn over it", "m", "white", None),
("none", "one cute flat pink coiled gut with a little face containing three cute flat worms with little faces, a small green check mark beside it", "m", "white", None),
("caveman", "standing calm and relaxed with half-lidded eyes, a big red X drawn over a tiny sword and shield beside him", "m", "dirt", None),
("none", "a simple black house outline shaped like a coiled gut, with three cute flat pink worms with little faces looking out of its windows", "m", "white", None),
("none", "one flat white index card standing upright with a single large numeral drawn on it", "m", "white", "1"),
("none", "one flat white index card standing upright with a single large numeral drawn on it and a small green check mark beside it", "m", "white", "2"),
("none", "a plain white stick figure scientist with short dark hair, wearing a simple white lab coat, holding up a small white research paper with a curious tilted head", "m", "white", "1991"),
("none", "one cute flat pink worm with a little face with a big red X drawn over it", "m", "white", None),
("none", "one cute flat green poison bottle with a little face and a small skull-free warning label, drawn big and centered", "m", "white", None),
("none", "two plain white stick figure scientists with short dark hair, both wearing simple white lab coats, standing side by side", "m", "white", None),
("none", "two plain white stick figure scientists in simple white lab coats pushing a small white idea box forward along a black arrow", "m", "white", None),
("none", "one cute flat white stopwatch with a little face and a fast-moving hand, small black motion lines around it", "m", "white", None),
("none", "one flat white calendar grid with four weeks marked and one cute flat pink worm with a little face crawling slowly across it", "w", "white", None),
("none", "one cute flat white stopwatch with a little face, its hand a blur, small sharp black motion lines bursting out", "c", "white", None),
("none", "one cute flat pink worm with a little sleepy face crawling very slowly, a small trail of dots behind it", "m", "white", None),
("none", "one cute flat green snake with a little face striking fast, sharp black motion lines behind its head", "m", "white", None),
("none", "one cute flat green snake with a little face beside a small flat appointment book with a big red X over it", "m", "white", None),
("none", "one cute flat grey mouse with a little face standing beside one small cute flat yellow-and-black bee", "m", "white", None),
("none", "one cute flat grey mouse with a little calm face standing steady beside one very large cute flat yellow-and-black bee, a small green check mark beside the mouse", "m", "white", None),
("none", "a second cute flat grey mouse with a little shocked face and wide round eyes falling backward away from a large bee, a small red X beside it", "m", "white", None),
("none", "one cute flat grey mouse with a little face standing whole and unharmed, a big red X drawn over a small cracked-shape damage symbol", "m", "white", None),
("none", "one cute flat grey mouse with a little determined face holding up a tiny flat grey shield, a small green check mark beside it", "m", "white", None),
("none", "one large flat white card flipping over in mid-air with a curved black motion arrow around it", "m", "white", None),
("modern", "standing with one hand on his chin and a big bold question mark floating above his head, curious tilted head", "m", "white", None),
("none", "a simple black nose outline in profile with one cute flat yellow pollen grain being blown out of it on a black motion arrow", "c", "white", None),
("none", "a pair of simple black eye outlines with blue tear streams washing one tiny yellow pollen grain out and away", "c", "white", None),
("none", "one cute flat pink stomach with a little face tipping over, one black arrow pointing out through its top, nothing graphic", "m", "white", None),
("modern", "scratching one arm hard and flicking a tiny green droplet off his skin, small red squiggle marks, nervous wavy mouth", "m", "white", None),
("modern", "standing with four black arrows pointing outward from his body, each arrow carrying a tiny green droplet away", "w", "white", None),
("modern", "standing with small red pain marks around his head and a nervous wavy mouth", "c", "white", None),
("modern", "backing away fast from one cute flat pink daisy with a little face, both mitten hands raised, wide round eyes", "m", "white", None),
("none", "one flat grey gear wheel, whole and undamaged, with a big red X drawn over a small cracked-gear symbol beside it", "m", "white", None),
("none", "one flat brown toolbox standing open with three simple black tools inside and a small green check mark beside it", "m", "white", None),
("none", "one plain flat white card standing upright and completely blank", "m", "white", "HONEST"),
("none", "two plain white stick figure scientists in simple white lab coats facing each other with a big black question mark floating between them", "m", "white", None),
("none", "one plain white stick figure scientist in a simple white lab coat holding up a small sign showing a cute flat pink worm with a little face", "m", "white", None),
("none", "one plain white stick figure scientist in a simple white lab coat holding up a small sign showing a cute flat green snake with a little face", "m", "white", None),
("none", "two small signs side by side, one showing a cute pink worm and one showing a cute green snake, with a black plus sign between them", "m", "white", None),
("none", "one cute flat blue Y-shaped antibody with a simple little face, drawn big and centered with a small black label arrow", "m", "white", "IgE"),
("none", "one pair of cute flat pink lungs with little faces and one small pink skin patch, with a small black dotted circle around only part of them", "m", "white", None),
("none", "a row of five plain white stickmen all nodding in agreement with small green check marks above their heads", "w", "white", None),
("none", "one flat grey shield with a big red X drawn over a small crossed-out uselessness symbol beside it", "m", "white", None),
("modern", "standing in a stiff soldier pose fully loaded with a small black spear, a flat grey shield and a tiny helmet, deadpan flat straight mouth", "m", "white", None),
("modern", "standing alone holding up a small white resume sheet in front of an empty black hiring desk with nobody behind it", "w", "white", None),
("none", "one large flat white target board standing completely empty, with a big black question mark beside it", "m", "white", None),
("none", "one cute flat pink worm and one cute round green microbe with little faces, both with big red X marks drawn over them", "m", "white", None),
("modern", "standing with both mitten hands turned up in an innocent shrug, dumb clueless expression", "m", "white", None),
("none", "one cute flat blue soap bar with a little face in front, while three cute flat pink worms with sad little faces quietly slip away behind it unnoticed", "m", "white", None),
("none", "a short horizontal black timeline with three tiny plain white stickmen standing along it, one after another", "w", "white", None),
("none", "one plain white stickman holding a large flat brown mop and a small bucket, standing under a simple black banner line", "m", "indoor", "CLEAN"),
("none", "one cute flat blue water droplet with a simple little face, drawn big and alone", "m", "white", None),
("none", "one cute flat blue soap bar with a simple little face, drawn big and alone", "m", "white", None),
("none", "one flat grey sewer pipe with a simple little face, drawn big and alone", "m", "white", None),
("none", "one cute flat white-and-red capsule pill with a simple little face, drawn big and alone", "m", "white", None),
("none", "a small patch of flat pale-blue floor tiles in a neat grid, drawn big and centered", "w", "white", None),
("none", "one cute flat brown shoe with a simple little face, drawn big and alone", "m", "white", None),
("none", "one cute flat orange-and-white antibiotic capsule with a simple little face, drawn big and alone", "m", "white", None),
("none", "one flat white list sheet with seven short scribbled lines, each with a small green check mark beside it", "m", "white", None),
("modern", "holding a flat white list sheet close to his chest with both mitten hands, protective and deadpan", "m", "white", None),
("none", "one large round magnifying glass held over a flat white list sheet, one line glowing under it", "c", "white", None),
("none", "three cute flat pink worms with little faces being swept away by a large flat brown broom, small motion lines behind them", "m", "white", None),
("none", "four cute round green microbes with little faces being swept away by a large flat brown broom, small motion lines behind them", "m", "white", None),
("none", "one small plain white stickman child standing in front of a row of simple flat grey city buildings", "w", "sky", None),
("modern", "standing with both mitten hands held out to shake, but nobody there to meet him, empty space all around", "w", "white", None),
("none", "three faded pale-grey outlines of a worm, a microbe and a spiky virus, all drawn very light and ghostly", "m", "white", None),
("none", "a simple black factory outline with a conveyor belt pushing out a steady line of small flat grey shields", "w", "white", None),
("none", "one long empty black shooting range with target stands that are all completely bare", "w", "white", None),
("none", "one flat white chart with a black line climbing steeply upward from left to right", "m", "white", None),
("none", "one cute flat tan peanut with a little face beside two small plain white stickman children", "m", "white", None),
("none", "one flat white clipboard survey sheet with a black clip and three tick boxes", "m", "white", None),
("none", "one plain flat white card standing upright with a year written on it", "m", "white", "1997"),
("none", "one very short flat blue bar standing alone on a simple black baseline", "m", "white", "0.4%"),
("none", "one long black arrow pointing right across an empty frame with five small tick marks under it", "w", "white", None),
("none", "one slightly taller flat blue bar standing on a simple black baseline beside the first shorter one", "m", "white", "0.8%"),
("none", "one taller flat blue bar standing on a simple black baseline beside two shorter ones", "m", "white", "1.4%"),
("none", "three flat blue bars rising clearly in height from left to right on a black baseline", "m", "white", None),
("none", "a short horizontal black timeline with eleven small tick marks along it", "w", "white", None),
("none", "one flat cream survey map of a country shape with small black tick marks scattered over it", "m", "white", None),
("none", "one tallest flat blue bar standing at the end of a row of shorter bars on a black baseline", "w", "white", "2%"),
("none", "one simple flat green outline of England drawn big and centered", "m", "white", None),
("none", "one flat white chart with a black line just beginning to rise from the bottom left corner", "m", "white", None),
("none", "one flat white chart with a small black dot marked low on the left side of the line", "c", "white", "0.4%"),
("none", "one flat white chart with a small black dot marked clearly higher on the right side of the line", "c", "white", "1.1%"),
("none", "a short horizontal black timeline with a marker dot at each end and a black arrow running between them", "w", "white", "2008 - 2018"),
("none", "one flat white chart with a rising black line and a big black question mark floating over it", "m", "white", None),
("none", "one cute flat blue DNA double helix with a simple little face, moving very slowly with a small snail beside it", "m", "white", None),
("none", "one cute flat blue DNA double helix with a little face holding a tiny eraser, with a big red X drawn over the eraser", "m", "white", None),
("none", "a short horizontal black timeline with twenty small tick marks along it", "w", "white", None),
("none", "one cute flat blue DNA double helix with a little face beside a small white software update box with a big red X over it", "m", "white", None),
("none", "two identical cute flat blue DNA double helixes with little faces standing side by side, a black equals sign between them", "m", "white", None),
("none", "one cute flat brown snail with a little face carrying a tiny blue DNA helix on its shell, moving slowly", "m", "white", None),
("none", "one cute flat red rocket with a little face shooting upward fast with sharp black motion lines behind it", "m", "white", None),
("none", "one long bold black arrow pointing decisively to one side of an otherwise empty frame", "m", "white", None),
("modern", "standing with a black outline circle drawn over his chest and a big red X inside the circle", "m", "white", None),
("modern", "standing small inside a simple black room outline, with a small green check mark drawn on the room wall", "w", "indoor", None),
("modern", "holding a large round magnifying glass and sweeping it across an empty room, curious tilted head", "m", "indoor", None),
("none", "one small plain white stickman child sitting on a spotless floor beside a flat plastic toy and a small screen", "m", "indoor", None),
("child", "sitting on bare ground covered in small brown dirt smudges, playing with a stick and a stone", "m", "dirt", None),
("modern", "standing with both mitten hands held open and completely empty, curious tilted head", "m", "white", None),
("none", "one small white research paper sheet with a black staple corner, drawn big and centered", "m", "white", None),
("none", "one small white research paper sheet sliding into the frame sideways on a curved black motion line", "m", "white", "1989"),
("none", "a plain white stick figure scientist with short dark hair, wearing a simple white lab coat, holding up a small white paper with a deadpan flat straight mouth", "m", "white", None),
("none", "one flat cream medical journal lying open with two blank pages and a small black heading line", "m", "white", "BMJ"),
("none", "one small white paper sheet standing upright with a single bold underlined title line across the top", "c", "white", None),
("none", "a tall stack of flat white record folders piled up, with a small black number tag on the front", "m", "white", "11,765"),
("none", "one large round magnifying glass held over a tiny plain white stickman child standing alone", "m", "white", None),
("none", "one small plain white stickman child sneezing, with a small pink skin patch drawn on one arm", "m", "white", None),
("none", "a row of five small plain white stickman children standing side by side with a big black question mark above them", "w", "white", None),
("none", "one small plain white stickman child standing at the end of a row of four taller plain white stickman siblings", "w", "white", None),
("none", "one long black arrow curving steadily downward across the frame", "m", "white", None),
("none", "one small sneeze burst symbol and one small pink skin patch, both with big red X marks drawn over them", "m", "white", None),
("none", "one spotless empty flat house outline with three sparkle marks and a big red X drawn over it", "m", "white", None),
("none", "one flat house outline crowded with five small plain white stickmen inside it, a small green check mark beside it", "w", "indoor", None),
("none", "two small plain white stickman children lying asleep under one flat blue blanket, tiny z z z above them", "m", "indoor", None),
("none", "two small plain white stickman children sneezing toward each other, small motion lines between them", "m", "indoor", None),
("none", "three small plain white stickman siblings walking in through a black doorway trailing brown dirt clouds behind them", "w", "indoor", None),
("none", "one pair of small mitten hands held up close, covered in small brown dirt smudges and tiny green microbes with little faces", "c", "white", None),
("none", "one cute flat blue soap bar with a little face with a big red X drawn over it", "m", "white", None),
("none", "three small plain white stickman siblings covered in brown dirt smudges, with a small green check mark above them", "m", "white", None),
("none", "one small white research paper sheet with a long black arrow leading away from it to the right", "m", "white", None),
("none", "one small yellow lightbulb with a simple little face, drawn big and centered", "m", "white", None),
("none", "one small flat grey shield standing alone in a completely empty spotless room outline", "w", "indoor", None),
("none", "one large flat white target board that is completely blank with no rings or marks on it", "m", "white", None),
("none", "one flat grey shield turning to face one cute flat pink daisy with a little face, a small black aiming line between them", "m", "white", None),
("none", "one long black arrow curving back to the left, pointing to the start of a line", "m", "white", None),
# ---------- ĐỢT 3: OLD FRIENDS · AMISH · LEAP (261-420) ----------
("none", "one flat grey shield, whole and undamaged, with a small green check mark beside it", "m", "white", None),
("modern", "sitting slumped on a small black bench with a flat grey shield propped unused beside him, deadpan flat straight mouth", "m", "white", None),
("modern", "standing in a stiff soldier pose holding a small black spear, with a small wall calendar beside him showing many crossed-off pages", "m", "white", None),
("modern", "standing alone in the middle of a completely empty spotless room outline with three small sparkle marks around him", "w", "indoor", None),
("modern", "still gripping a small black spear tightly with both mitten hands, deadpan flat straight mouth", "c", "indoor", None),
("none", "a simple black window outline with one cute flat yellow pollen grain with a little face drifting in through it on a curved motion line", "m", "indoor", None),
("modern", "firing a small black arrow across an empty room with sharp black motion lines, deadpan flat straight mouth", "w", "indoor", None),
("none", "one cute flat pink daisy with a little face standing alone, with a small black arrow stuck in the ground beside it", "m", "white", None),
("none", "one cute flat blue soap bar with a little face and a big black question mark floating beside it", "m", "white", None),
("none", "one empty flat white target board with a small red X drawn beside it and three faded grey enemy outlines", "m", "white", None),
("none", "a neat tidy grid of small green check marks arranged in perfect rows", "w", "white", None),
("none", "a messy scattered grid of green check marks and red X marks mixed up out of order", "w", "white", None),
("caveman", "standing covered in brown dirt smudges with dust puffs around him, arms out, deadpan flat straight mouth", "m", "dirt", None),
("caveman", "sneezing hard with eyes squeezed shut and motion lines from his nose, one cute flat pink daisy floating nearby", "m", "green", None),
("modern", "standing in a completely spotless empty room with three small sparkle marks around him, deadpan flat straight mouth", "w", "indoor", None),
("modern", "standing calm and relaxed with half-lidded eyes while a cute flat pink daisy and a cute flat orange cat sit beside him, a small green check mark above", "m", "white", None),
("none", "one flat white jigsaw puzzle with a single piece-shaped hole missing from the middle", "m", "white", None),
("none", "one flat white measuring jug with a black amount scale on the side and a big red X drawn over it", "m", "white", None),
("none", "a large bold black question mark drawn big and centered, standing alone", "m", "white", "WHO"),
("none", "one flat white measuring jug with a black amount scale, drawn small and faded to one side", "m", "white", None),
("none", "one cute flat pink worm and one cute round green microbe with little faces standing together, drawn big and centered", "m", "white", "WHO"),
("none", "a plain white stick figure scientist with short dark hair, wearing a simple white lab coat, holding up a small white paper with a curious tilted head", "m", "white", "2003"),
("none", "one small white research paper being sharpened to a point, with a black arrow pointing at its sharp tip", "m", "white", None),
("none", "one cute flat pink worm and two cute round green microbes with little smiling faces standing arm in arm like old friends", "m", "white", "OLD FRIENDS"),
("none", "a large dense crowd of tiny grey microbe dots with a big red X drawn over the crowd", "w", "white", None),
("none", "three specific cute organisms standing together, a pink worm, a green soil bacterium and a brown gut microbe, each with a little smiling face, a small green check mark beside them", "m", "white", None),
("none", "a long horizontal black path with one cute flat pink worm and one cute round green microbe with little faces walking along it together", "w", "white", None),
("none", "a very long horizontal black timeline stretching off both edges of the frame, with tiny organism dots dotted along its whole length", "w", "white", None),
("none", "a small mound of flat brown soil with three cute round green bacteria with little faces peeking out of it", "m", "white", None),
("none", "a small flat blue puddle of untreated water with four cute round green bacteria with little faces swimming in it", "m", "white", None),
("none", "one cute flat pink coiled gut with a little face, its inside filled with many small friendly coloured dots", "m", "white", None),
("none", "three cute flat pink worms with little smiling faces waving cheerfully", "m", "white", None),
("modern", "standing as a small child-sized figure next to a cute flat pink worm and a cute round green microbe with little faces, all the same height", "m", "white", None),
("modern", "shaking hands warmly with one cute flat pink worm with a little smiling face, a small green check mark above them", "m", "white", None),
("none", "one cute round grey modern germ with a little face standing beside a big black question mark", "m", "white", None),
("none", "one cute round grey modern germ with a little face standing beside one cute pink worm, with a big red X drawn between them", "m", "white", None),
("none", "three small plain white stickman children in a row all sneezing at once with small motion lines", "w", "indoor", None),
("none", "one large flat glass petri dish with three small plain white stickman children sitting inside it and two little juice cartons", "m", "white", None),
("none", "one small plain white stickman child standing in a swirl of many tiny grey germ dots", "m", "indoor", None),
("none", "one small plain white stickman child sneezing hard with a small pink skin patch on one arm, a small red X beside", "m", "white", None),
("none", "three cute round grey germs with little blank unfriendly faces standing stiffly apart from each other", "m", "white", None),
("none", "one cute round grey germ with a little face standing at a small blackboard, holding a pointer, with a big red X drawn over the blackboard", "m", "white", None),
("none", "one cute round grey germ with a little worried face being chased away by a small flat grey shield with motion lines", "m", "white", None),
("none", "one cute flat pink worm with a little smiling face standing at a small blackboard holding a pointer, a small green check mark beside it", "m", "white", None),
("none", "one cute flat pink worm and one green microbe with little faces stacking small flat building blocks into a low wall together", "m", "white", None),
("none", "one small plain white stickman referee holding up both mitten hands in a clear stop signal, deadpan flat straight mouth", "m", "white", "STOP"),
("none", "three cute round blue cells with little calm faces standing in a neat row, each holding up a tiny stop sign", "m", "white", None),
("none", "one cute round blue cell with a little calm face holding up a tiny stop sign, drawn big and centered", "c", "white", "Treg"),
("none", "one cute round blue cell with a little firm face shaking its head and holding up one mitten hand, a small red no-entry circle beside it", "m", "white", None),
("none", "one small blackboard standing completely blank with a big red X drawn over it", "m", "white", None),
("modern", "firing a small black arrow with sharp motion lines, wide round eager eyes", "m", "white", None),
("modern", "still firing arrows with nobody to stop him, a small blue stop-sign cell lying unused on the ground beside him", "w", "white", None),
("modern", "standing as a fresh recruit in a tiny helmet holding a small black bow, wide round eager eyes", "m", "white", None),
("none", "one large flat white target board that is completely blank, with a big black question mark floating over it", "m", "white", None),
("none", "one small white research paper sheet lying flat and neat with a small green check mark beside it", "m", "white", None),
("modern", "standing with both mitten hands turned up in a shrug and a big bold question mark above his head, curious tilted head", "m", "white", None),
("none", "two separate groups of three small plain white stickman children standing apart, with a black dividing line between them", "w", "white", None),
("none", "one group of small plain white stickman children standing in a patch of flat brown dirt with a black arrow pointing at them", "w", "dirt", None),
("none", "a horizontal black timeline with twenty small tick marks and a tiny plain white stickman child at each end", "w", "white", None),
("none", "one flat white official stamp form with a big red X across it and a small black rubber stamp lying beside it", "m", "white", None),
("modern", "standing with one mitten hand raised and one finger up, curious tilted head", "m", "white", None),
("none", "two small flat farm outlines standing side by side, each with a little barn and a fence, a small green check mark above them", "w", "sky", None),
("none", "a simple flat map outline of the American Midwest with two small black location pins stuck in it", "m", "white", None),
("none", "two small plain white stickman farmers standing side by side, one in a plain flat blue shirt and one in a plain flat grey shirt", "m", "white", None),
("none", "a plain white stick figure scientist with short dark hair, wearing a simple white lab coat, holding up a small white research paper", "m", "white", "2016"),
("none", "one flat cream medical journal lying open with two blank pages and a small black heading line", "m", "white", "NEJM"),
("none", "two small flat farm outlines side by side with a black dotted comparison line running between them", "w", "sky", None),
("none", "one pair of open mitten hands holding up a small neat flat white box like an unexpected gift", "m", "white", None),
("none", "two identical small family trees drawn side by side in black lines, both with the same shape", "m", "white", None),
("none", "two rows of five small plain white stickmen each, the two rows matching exactly", "w", "white", None),
("none", "two identical flat white dinner plates side by side, each with the same simple food shapes on it", "m", "white", None),
("none", "one small flat cigarette shape with a big red X drawn over it, drawn small and alone", "m", "white", None),
("none", "two small flat farm outlines both sitting the same distance behind a long black boundary line", "w", "sky", None),
("none", "two matching columns of small green check marks standing side by side in neat rows", "w", "white", None),
("none", "two matching columns of green check marks with a big red X drawn over a small pair of arranging hands beside them", "m", "white", None),
("none", "a plain white stick figure scientist in a simple white lab coat sitting at a desk with a tall stack of papers, half-lidded tired eyes", "m", "indoor", None),
("none", "a plain white stick figure scientist in a simple white lab coat slumped asleep on a desk beside a very tall stack of papers, tiny z z z above", "m", "indoor", None),
("none", "two small flat farm outlines side by side with a single bold black line drawn between them", "w", "sky", None),
("none", "one small flat red barn with a little face and a small fence beside it, drawn big and centered", "m", "sky", None),
("none", "one small flat family farm with a little red barn and one cute flat brown horse with a little face standing outside it", "w", "sky", None),
("child", "standing right beside one cute flat brown horse with a little face, one small hand on the horse", "m", "sky", None),
("child", "toddling on unsteady legs beside one cute flat brown horse with a little face, wide round happy eyes", "m", "sky", None),
("none", "one very large flat grey industrial farm building with a long row of small windows and no animals outside", "w", "sky", None),
("none", "two small plain white stickman children standing far away from a large grey farm building, with a long black distance line between them", "w", "sky", None),
("none", "two identical small black family trees drawn side by side", "m", "white", None),
("none", "two matching rows of small green check marks side by side", "w", "white", None),
("none", "two small flat house outlines side by side, one with cheerful coloured dust motes floating inside and one with completely empty clear air", "w", "white", None),
("none", "one large bold black number outline standing alone and waiting to be filled in", "m", "white", None),
("none", "one flat white chart with two bars of very different heights and a small green check mark beside it", "m", "white", None),
("none", "one flat white chart showing one tall bar and one bar only a quarter as high, with a small pair of lungs beside the short bar", "m", "white", "1/4"),
("none", "one flat white chart showing one tall bar and one bar only a sixth as high, with a small pollen grain beside the short bar", "m", "white", "1/6"),
("none", "the inside of a small flat farmhouse room with many tiny coloured dust motes floating in the air", "w", "indoor", None),
("none", "a close-up cloud of tiny coloured dust motes with little faces floating thickly in the air", "c", "indoor", "6.8x"),
("none", "three cute round green bacteria with little faces leaving small coloured dots behind them as they float away", "m", "white", None),
("none", "a faint trail of small coloured dots hanging in the air, forming the soft outline of a worm and a microbe", "m", "indoor", None),
("none", "a quiet empty flat farmhouse room with tiny coloured dust motes hanging still in the light", "w", "indoor", None),
("none", "a flat white clipboard with an assignment list on it and a big red X drawn over the clipboard", "m", "white", None),
("none", "one small flat farm scene running by itself with no scientist anywhere in the frame, just a barn, a horse and two children", "w", "sky", None),
("none", "one empty flat white pen labelled as a control group standing completely empty with a big red X over it", "m", "white", None),
("none", "a small pile of coloured dust motes sitting still on a flat floor with a big black question mark above it", "m", "indoor", None),
("none", "a small pile of coloured dust motes sitting motionless and doing nothing, drawn plain and still", "c", "white", None),
("none", "a pair of mitten hands sweeping a small pile of coloured dust motes into a tiny glass jar", "m", "indoor", None),
("none", "one cute flat grey mouse with a little face having a tiny drop of dust mixture placed at its nose by a small dropper", "c", "white", None),
("none", "one cute flat grey mouse with a little calm face breathing easily, a small green check mark beside it and a red X over a tiny wheeze symbol", "m", "white", None),
("none", "a second cute flat grey mouse with a little face beside a small pile of different dust, with a flat straight deadpan expression and no change around it", "m", "white", None),
("none", "one cute flat grey mouse with a little face and one small black switch beside it flipped to the off position", "m", "white", "OFF"),
("none", "one small green check mark fading away into pale grey until it almost disappears", "m", "white", None),
("none", "two identical results drawn side by side with a big red X over a small pair of dice beside them", "m", "white", None),
("none", "a simple black gear-and-lever mechanism drawn under a horizontal line, with a small black arrow pointing down at it", "m", "white", None),
("none", "one small flat white pill bottle with a big red X drawn over it", "m", "white", None),
("none", "one small flat red barn with a little face, with five black arrows from all directions all pointing at it", "w", "sky", None),
("modern", "standing in a spotless empty room with a big red X drawn over a small sparkle mark beside him", "w", "indoor", None),
("modern", "standing alone in an empty room while three faded pale-grey outlines of a worm and two microbes drift away behind him", "w", "indoor", None),
("none", "one large bold black question mark standing upright and alone in an otherwise empty frame", "m", "white", None),
("none", "one flat white chart with many small dots forming a clear overall trend line", "w", "white", None),
("none", "one flat white chart with many small dots, and one single dot circled in red sitting far off the trend line", "w", "white", None),
("none", "two small plain white stickman children standing side by side, exactly the same size", "m", "white", None),
("none", "two small plain white stickman children standing in the same flat house outline with the same dirt patch and one cute flat brown dog with a little face", "w", "indoor", None),
("none", "one small plain white stickman child backing away from one cute flat tan peanut with a little face, wide round frightened eyes", "m", "white", None),
("none", "a second small plain white stickman child cheerfully eating a whole handful of cute flat tan peanuts, wide round happy eyes", "m", "white", None),
("none", "two small plain white stickman children standing side by side with a big black question mark hovering between them", "m", "white", None),
("none", "one flat cream official guidance leaflet with a black heading line, lying flat and centered", "m", "white", None),
("none", "one bold black arrow pointing firmly in one single direction across an empty frame", "m", "white", None),
("none", "two small plain white stickman parents standing protectively over one tiny plain white stickman baby", "m", "indoor", None),
("none", "a pair of mitten hands lifting a small flat jar of peanuts up and away out of a tiny baby's reach", "m", "indoor", None),
("none", "one small flat clock face with its hands being pushed backward by a black arrow", "m", "white", "WAIT"),
("none", "one cute flat tan peanut with a little face with a big red X drawn over it", "m", "white", None),
("none", "one pair of mitten hands held up flat in a careful blocking gesture, with a small red no-entry circle above them", "m", "white", None),
("none", "one flat cream guidance leaflet with a small green check mark beside it, looking perfectly reasonable", "m", "white", None),
("none", "the same flat cream guidance leaflet now turned completely upside down, with a black rotation arrow around it", "m", "white", None),
("none", "a plain white stick figure scientist with short dark hair in a simple white lab coat, standing in front of a small flat outline of a London skyline", "m", "white", "2015"),
("none", "one small white research paper sheet standing upright with a bold underlined title line", "m", "white", "LEAP"),
("none", "one flat cream medical journal lying open with two blank pages and a small black heading line", "m", "white", "NEJM"),
("none", "a large group of many tiny plain white stickman babies drawn small and packed together in a wide frame", "w", "white", "640"),
("none", "one tiny plain white stickman baby sitting beside a small clock face marked with a short early range", "m", "white", None),
("none", "one tiny plain white stickman baby with a small red warning triangle floating above it", "m", "white", None),
("none", "one tiny plain white stickman baby with a small pink skin patch on one arm and a small flat white egg with a little face beside it", "m", "white", None),
("none", "a group of tiny plain white stickman babies being separated into two groups by a black dotted line, with a small coin flipping above", "w", "white", None),
("none", "a small group of tiny plain white stickman babies each holding a tiny cute flat tan peanut with a little face", "m", "white", None),
("none", "a small flat kitchen scale holding a tiny pile of peanut pieces, with a small black weight label", "m", "indoor", "6g"),
("none", "a second small group of tiny plain white stickman babies with a big red X drawn over a peanut beside them", "m", "white", None),
("none", "one small flat clock face with a black arrow sweeping around it five times, and a tiny stickman child growing taller beneath", "m", "white", "5"),
("none", "two groups of tiny plain white stickman babies side by side with a big black question mark between them", "w", "white", None),
("none", "a small group of tiny plain white stickman children happily holding cute flat tan peanuts with little faces", "m", "white", None),
("none", "one flat white chart with two bars standing side by side ready to be compared", "m", "white", None),
("none", "one flat white chart with one tall bar and one very short bar beside it, a bold black downward arrow between them", "m", "white", "70-86%"),
("none", "one flat white chart with the tall bar clearly labelled by a small red X and the short bar by a small green check mark", "m", "white", None),
("none", "one tiny plain white stickman baby with a small pink dot marked on its forearm and a tiny magnifying circle around the dot", "c", "white", None),
("none", "one flat white chart with a group of three small figures, one of them marked in red", "w", "white", "1 in 3"),
("none", "one flat white chart with a group of ten small figures, only one of them marked in red", "w", "white", "1 in 10"),
("none", "a small group of tiny plain white stickman babies standing together with a small green check mark above them", "m", "white", None),
("none", "one cute flat tan peanut with a little smiling face wearing a tiny flat grey shield on its front", "m", "white", None),
("none", "one flat white signpost with a single arrow pointing forward toward a small green check mark", "m", "white", "BEFORE"),
("none", "one small flat white medicine bottle with a big red X drawn over it", "m", "white", None),
("none", "a pair of mitten hands holding a clipboard and turning away three tiny stickman babies marked with small red dots", "m", "white", None),
("none", "one tiny plain white stickman baby sitting at a small table with one peanut piece and a plain white stick figure doctor in a white coat watching closely", "m", "indoor", None),
("none", "one pair of mitten hands gently taking a small peanut piece back off a tiny table, with a small red no-entry circle above", "m", "indoor", None),
("modern", "standing in a home kitchen ignoring a small clipboard lying unread on the counter, deadpan flat straight mouth", "m", "indoor", None),
("none", "one small yellow lightbulb with a little face glowing brightly, with three small sharp black shine lines around it", "m", "white", None),
("none", "one cute flat pink coiled gut with a little face on one side and one cute flat tan peanut with a little face on the other, a small black balance scale between them", "m", "white", None),
# ---------- ĐỢT 4: DA vs RUỘT · FILAGGRIN · HOOKWORM · KẾT (421-563) ----------
("none", "one cute flat tan peanut with a little face standing between a small green check mark on one side and a small red X on the other", "m", "white", None),
("modern", "standing with one mitten hand on his chin and a big bold question mark above his head, curious tilted head", "m", "white", None),
("none", "a simple black signpost with two arrows, one pointing down toward a pink gut shape and one pointing at a pink skin patch", "w", "white", None),
("none", "one cute flat pink coiled gut with a little smiling face, with a small black arrow entering it from above", "m", "white", None),
("none", "one cute flat pink coiled gut with a little smiling face holding one cute flat tan peanut, a small green check mark beside them", "m", "white", None),
("none", "one flat white filing cabinet drawer sliding shut with a small peanut-labelled card filed neatly inside it", "m", "white", "FOOD"),
("none", "a small pink skin patch drawn cracked and split, with a black arrow entering through the crack", "c", "white", None),
("none", "a small pink skin patch with one cute flat tan peanut beside it and a small red X above them", "m", "white", None),
("none", "a small flat pink skin patch drawn with red inflamed edges, small cracks and a tiny leak, with a worried little face", "c", "white", None),
("none", "a simple flat brick wall with one obvious ragged hole broken through the middle of it", "c", "white", None),
("none", "one cute flat tan peanut with a little face climbing in through a ragged hole in a flat brick wall", "c", "white", None),
("none", "one cute flat tan peanut with a little face wearing a small black burglar mask, standing in front of a wall hole", "m", "white", None),
("none", "a simple black diagram of two arrows meeting at one central peanut, one arrow from a gut shape and one from a skin patch", "w", "white", None),
("none", "a plain white stick figure scientist with short dark hair in a simple white lab coat, holding up a small white research paper with a deadpan flat straight mouth", "m", "white", None),
("modern", "leaning forward with wide round alert eyes and one mitten hand raised, as if about to reveal something", "c", "white", None),
("none", "one small flat grey house with a cloud of tiny dust motes inside it, and three tiny tan peanut specks mixed among the motes", "w", "indoor", None),
("none", "a flat blue carpet in close-up with three tiny tan peanut specks resting in its fibres", "c", "indoor", None),
("none", "a flat green sofa in close-up with three tiny tan peanut specks resting on the cushion", "c", "indoor", None),
("none", "a pair of mitten hands lifting a tiny plain white stickman baby, with three tiny tan peanut specks on the fingers", "m", "indoor", None),
("none", "a small flat grey house drawn with a tiny waiter tray floating in each room, each tray holding a small tan peanut", "w", "indoor", None),
("none", "one flat wall calendar with several months of pages torn off and floating away", "m", "indoor", None),
("none", "one tiny plain white stickman baby crawling across a flat blue carpet, its skin drawn clean and unbroken", "m", "indoor", None),
("none", "one tiny plain white stickman baby crawling calmly with a small green check mark above it and a quiet still cloud of dust motes around", "m", "indoor", None),
("none", "one tiny plain white stickman baby crawling across a flat blue carpet with a small pink inflamed skin patch on one arm", "m", "indoor", None),
("none", "one tiny plain white stickman baby beside a small blackboard showing one cute tan peanut with a burglar mask, and a small red X on the board", "m", "indoor", None),
("none", "the same small blackboard lesson drawn three times receding into the distance, with a curved black repeat arrow around them", "w", "white", None),
("none", "one tiny plain white stickman baby with an arm drawn as a solid unbroken flat brick wall", "m", "white", None),
("none", "a second tiny plain white stickman baby with an arm drawn as a flat sieve full of small holes, a big black question mark above", "m", "white", None),
("none", "one cute flat blue DNA double helix with a little face, one of its rungs drawn broken and dangling loose", "c", "white", "filaggrin"),
("none", "a simple flat brick wall with several bricks missing so that small gaps run all the way through it", "m", "white", None),
("none", "one cute flat blue DNA double helix with a little face standing at the top of a small black ranking podium, holding a small pink skin patch", "m", "white", "No.1"),
("none", "one flat grey house interior with a very thick cloud of tiny tan peanut specks filling the air", "w", "indoor", None),
("none", "one tiny plain white stickman baby with a sieve-like arm sitting in a thick cloud of tan peanut specks, wide round eyes", "m", "indoor", None),
("none", "one flat white chart with a black line rising as a small cloud of specks beside it grows thicker", "w", "white", None),
("none", "one cute flat blue DNA double helix with a little face beside a small allergy symbol with a big red X drawn over the link between them", "m", "white", None),
("none", "one cute flat blue DNA double helix with a little face standing beside a simple black door left standing wide open", "m", "white", None),
("none", "two tiny plain white stickman babies standing together with a small black bracket drawn around just those two", "m", "white", None),
("none", "one flat cream guidance leaflet with a small green check mark on it, standing beside a big black backward-turning arrow", "m", "white", None),
("none", "a simple black doorway marked with a small green check mark, drawn firmly shut with a bolt across it", "m", "white", None),
("none", "a second simple black doorway marked with a small red X, standing wide open with nothing blocking it", "m", "white", None),
("none", "one tiny plain white stickman baby standing beside one cute flat tan peanut with a little face, a small black meeting line between them", "m", "white", None),
("none", "one cute flat tan peanut with a little face stepping through the wrong doorway, the one marked with a small red X", "m", "white", None),
("none", "one flat cream guidance leaflet being rewritten, with a small black pen crossing out the old line and writing a new one", "m", "white", None),
("none", "one flat cream guidance leaflet lying beside one small white research paper, a small green check mark between them", "m", "white", None),
("modern", "standing calm and composed with both mitten hands at his sides, deadpan flat straight mouth", "m", "white", None),
("none", "one flat grey gear wheel turning smoothly and correctly, with a big red X drawn over a small chaos scribble beside it", "m", "white", None),
("modern", "holding an old folded paper map upside down and squinting at it, curious tilted head", "m", "white", None),
("none", "a pair of mitten hands carrying three cute flat pink worms and green microbes with little faces back toward an open black doorway", "m", "white", None),
("none", "three cute flat pink worms and green microbes with little faces walking away out of a black doorway, small motion lines behind them", "m", "white", None),
("none", "one small flat house with a black welcome mat at the door and three cute organisms with little smiling faces standing on it", "m", "indoor", None),
("modern", "standing with one mitten hand raised and a small green check mark above his head, deadpan flat straight mouth", "m", "white", None),
("none", "a plain white stick figure scientist in a simple white lab coat holding a clipboard beside a small laboratory bench", "m", "indoor", None),
("none", "one cute flat pink hookworm with a simple little face resting inside a small clear glass sample jar", "m", "white", None),
("none", "a plain white stick figure doctor in a simple white lab coat standing watchfully beside a small glass sample jar, arms crossed", "m", "indoor", None),
("none", "one small flat clipboard with a formal trial protocol heading and three tick boxes, inside a black bordered frame", "m", "indoor", "TRIAL"),
("none", "one small flat kitchen counter with a home jar on it and a big red X drawn over the jar", "m", "indoor", None),
("none", "one small flat clipboard with a green check mark, beside a small black monitor screen and a clearly marked exit door", "m", "indoor", None),
("modern", "standing with both mitten hands turned up and a big bold question mark above his head, curious tilted head", "m", "white", None),
("none", "a group of thirty two tiny plain white stickmen drawn small and packed together, each with a tiny pair of pink lungs beside them", "w", "white", "32"),
("none", "a group of tiny plain white stickmen split into two even groups by a black dividing line", "w", "white", None),
("none", "one group of tiny plain white stickmen each standing beside a small cute flat pink hookworm with a little face", "m", "white", None),
("none", "a second group of tiny plain white stickmen each standing beside a small plain white sugar pill with no face", "m", "white", "PLACEBO"),
("none", "one flat wall calendar with sixteen weeks marked off in a neat grid", "w", "white", "16"),
("none", "two flat white bars side by side, both rising by exactly the same small amount, each with a small green check mark", "m", "white", None),
("none", "two flat white bars side by side, the worm-labelled one only a tiny bit taller than the other", "m", "white", None),
("none", "two flat white bars almost the same height with a very small black gap measurement drawn between their tops", "c", "white", None),
("none", "one small flat white document covered in tiny dense formal print with a stiff black seal stamped at the bottom", "c", "white", None),
("none", "two nearly identical flat white bars with a small pair of dice sitting between them", "m", "white", None),
("none", "a wide flat white chart with many pairs of nearly identical bars stretching across the frame", "w", "white", None),
("none", "one cute flat grey mouse with a little calm face standing beside a cute flat pink worm, a small green check mark above them", "m", "white", None),
("none", "one plain white stickman standing beside a cute flat pink worm with a big black question mark above them, no check mark and no X", "m", "white", None),
("none", "one cute flat pink worm with a little face and a small green check mark, beside a small white pill bottle with a big black question mark", "m", "white", None),
("none", "one small flat white pill bottle standing alone with a big black question mark above it", "m", "white", None),
("modern", "sitting still on a small black bench with one mitten hand on his chin, thinking, half-lidded eyes", "m", "white", None),
("modern", "standing alone holding a small glass jar with a worried nervous wavy mouth and a small red warning triangle above him", "m", "indoor", None),
("modern", "in close-up with a very red blocked nose, watering eyes and a deeply miserable nervous wavy mouth", "c", "white", None),
("modern", "reaching desperately toward a small glass jar with both mitten hands, wide round pleading eyes", "m", "indoor", None),
("none", "one small glass jar with a cute flat pink worm inside it and a big red X drawn firmly over the whole jar", "m", "white", None),
("none", "one small glass jar with a big red X over it, and a small flat white research paper beside it also marked with a red X", "m", "white", None),
("modern", "standing beside a small blackboard with one mitten hand raised as if asking a question, curious tilted head", "m", "indoor", None),
("none", "one small plain white stickman child sitting attentively at a tiny desk in front of a small blackboard covered in notes", "m", "indoor", None),
("none", "one small flat clock face with only a very narrow wedge of it shaded in, and a tiny stickman child inside that wedge", "m", "white", None),
("none", "one small plain white stickman child writing on a small blackboard while tiny worms and microbes with little faces watch", "m", "indoor", None),
("none", "one flat white filing cabinet drawer being pushed firmly shut with a small black label card on the front", "m", "white", None),
("modern", "standing fully grown beside a small glass jar holding one cute flat pink worm with a little face", "m", "white", None),
("none", "one small blackboard with a half-erased lesson on it and a big black question mark beside the blank part", "m", "white", None),
("none", "one flat wall calendar with thirty small year pages torn off and drifting away behind it", "w", "white", "30 YRS"),
("none", "one small flat lesson card with a clear date stamp printed in the corner of it", "c", "white", None),
("modern", "standing outside a closed classroom door with both mitten hands at his sides, deadpan flat straight mouth", "m", "indoor", None),
("none", "one closed classroom door with a small black clock beside it and a tiny green check mark drawn very faintly", "m", "indoor", None),
("modern", "standing with both mitten hands open holding a small odd-shaped package, curious tilted head", "m", "white", None),
("none", "one small flat white toolbox marked with a big black question mark, sitting closed", "m", "white", None),
("none", "one long horizontal black timeline with a small marker placed right at the very beginning of the line", "w", "white", None),
("none", "one small glass jar holding a cute flat pink worm with a little face, with a big red X drawn over it", "m", "white", None),
("none", "one small plain white stickman child playing in a flat brown dirt patch, drawn softly faded like a memory", "w", "dirt", None),
("none", "one long flat white list sheet with many crossed-out lines running down it", "m", "white", None),
("none", "one long flat white list sheet of crossed-out lines with a small red downward arrow beside it", "m", "white", None),
("none", "one flat grey gear wheel drawn cracked, with a small red X beside it", "m", "white", "DEFECT"),
("modern", "tilting his whole body sideways to look at something from a new angle, curious tilted head", "m", "white", None),
("none", "one large flat white card flipping right over in mid-air with a bold curved black rotation arrow around it", "m", "white", None),
("modern", "standing upright and turning to face the other way with a small green check mark above his head", "m", "white", None),
("none", "one flat grey gear wheel, completely whole and undamaged, with a small green check mark beside it", "m", "white", None),
("none", "one small flat cream envelope marked with an old wax seal, sitting beside a flat grey gear wheel", "m", "white", "ORDERS"),
("none", "one small flat cream order sheet lying under a thick layer of grey dust, never updated", "c", "white", None),
("none", "a pair of mitten hands sweeping away three cute flat pink worms and green microbes with little faces, small motion lines behind them", "m", "white", None),
("none", "one flat grey machine drawn whole and correct with a small green check mark beside it", "m", "white", None),
("none", "one simple black empty room outline with a small red X drawn on its wall", "w", "indoor", None),
("none", "one cute flat tan peanut with a little face beside a large orange starburst shape and sharp black motion lines", "m", "white", None),
("none", "one small white research paper sheet with a small black label arrow pointing at one line of it", "c", "white", None),
("none", "one cute flat green snake with a little face striking fast beside a large orange starburst shape, sharp black motion lines", "m", "white", None),
("none", "one flat grey cannon drawn twice at the same size side by side, with a black equals sign between them", "m", "white", None),
("none", "one cute flat white stopwatch with a little face drawn twice at the same reading, with a black equals sign between them", "m", "white", None),
("none", "one small orange starburst shape drawn twice identically with a black equals sign between them", "m", "white", None),
("none", "one flat grey cannon aimed first at a small green snake and then swinging round to aim at a small pink daisy, a curved black arrow showing the swing", "m", "white", None),
("none", "one flat grey cannon with a big red X drawn over a small green safety check mark beside it", "m", "white", None),
("none", "one small red warning triangle with a bold black upright warning stroke and dot inside it, drawn big and centered", "m", "white", None),
("modern", "leaning in close with one mitten hand cupped beside his mouth, wide round eyes, as if telling a secret", "c", "white", None),
("none", "one flat cream paper receipt printed with a small black victory laurel symbol at the top", "m", "white", "RECEIPT"),
("none", "three cute flat pink worms with little faces lying flat and beaten, with a small green check mark above them", "m", "white", None),
("none", "one small flat blue water drop with a little face beside a tiny plain white stickman child, a small green check mark above them", "m", "white", None),
("none", "one cute flat red rocket with a little face shooting upward extremely fast with sharp black motion lines", "m", "white", None),
("modern", "standing holding a small black spear, with an unopened cream envelope lying unnoticed at his feet", "m", "white", None),
("modern", "standing straight and steady with a small green check mark above his head, deadpan flat straight mouth", "m", "white", None),
("modern", "standing in a confident hunter pose holding a small black spear and a flat grey shield, both clearly ready", "m", "white", None),
("modern", "standing small in the middle of a very wide completely empty landscape, still holding his spear", "w", "sky", None),
("modern", "standing in a wide empty landscape while three faded pale-grey outlines of a worm and two microbes drift away over the horizon", "w", "sky", None),
("none", "one large bold black question mark with a small green check mark drawn beside it", "m", "white", None),
("caveman", "standing in a confident hunter pose facing three cute flat pink worms and green microbes with little faces", "w", "dirt", None),
("modern", "standing in the same confident hunter pose but facing a completely empty space with nothing in front of him", "w", "white", None),
("caveman", "holding a small black spear with three cute organisms with little faces standing in front of him", "m", "dirt", None),
("modern", "holding up a small flat gold trophy cup with a deadpan flat straight mouth", "m", "white", None),
("modern", "sneezing hard with a big red X drawn over a small weak drooping arm symbol beside him", "m", "white", None),
("none", "one small flat sound-echo symbol of three nested curved lines fading outward", "m", "white", None),
("none", "one long horizontal black timeline with a small black flag planted at the far end marking the finish", "w", "white", None),
("none", "one cute flat wall calendar page with a spring blossom branch beside it, a single pink flower open", "m", "white", "APRIL"),
("modern", "mid-sneeze, head thrown forward into his own raised elbow, eyes squeezed shut, small motion lines around his head", "m", "white", None),
("none", "one cute flat pink daisy with a little smiling face holding up both tiny arms harmlessly, a small green check mark beside it", "m", "white", None),
("modern", "looking down at a small flat card in his mitten hands and reading it carefully, curious tilted head", "c", "white", None),
("modern", "standing whole and upright with a big red X drawn over a small broken-gear symbol beside him", "m", "white", None),
("none", "one small flat grey cannon still fully loaded and ready, standing alone in an empty frame", "m", "white", None),
("none", "one simple black empty room outline drawn completely still and silent, with a small faded dust mote hanging in the air", "w", "indoor", None),
("modern", "standing alert and ready while a small cream envelope lies unopened on the ground behind him", "m", "white", None),
("modern", "standing in a hunter pose aiming his spear at empty air, while behind him a faded old target sign has been quietly taken down", "w", "white", None),
]
